/*=========================================================
*Copyright(c) 2016 CyberLogitec
*@FileName : OnsiteInspectionResultMgtDBDAOSearchHeader2RSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2016.05.31
*@LastModifier : 
*@LastVersion : 1.0
* 2016.05.31 
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.ees.mnr.generalmanage.onsiteinspectionresultmgt.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class OnsiteInspectionResultMgtDBDAOSearchHeader2RSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * Onsite Inspection Inquiry 화면을 직관적으로 수정하기 위하여 추가 SQL을 작성.
	  * </pre>
	  */
	public OnsiteInspectionResultMgtDBDAOSearchHeader2RSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("vndr_seq",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("insp_yr",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("insp_ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("rhq_ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.ees.mnr.generalmanage.onsiteinspectionresultmgt.integration").append("\n"); 
		query.append("FileName : OnsiteInspectionResultMgtDBDAOSearchHeader2RSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("WITH MASTER AS (SELECT DECODE(HDR_DTL.OFC_CD2, 'SELSC', HDR_DTL.OFC_CD1, HDR_DTL.OFC_CD2) OFC_CD," ).append("\n"); 
		query.append("               HDR_DTL.YD_CD ," ).append("\n"); 
		query.append("               WK2.PLN_YR," ).append("\n"); 
		query.append("               WK2.PLN_WK," ).append("\n"); 
		query.append("               WK2.PLN_MON," ).append("\n"); 
		query.append("               HDR_DTL.FLD_INSP_DT ," ).append("\n"); 
		query.append("               HDR_DTL.BBO_CHK_COUNT," ).append("\n"); 
		query.append("               HDR_DTL.BBG_CHK_COUNT" ).append("\n"); 
		query.append("          FROM EQR_WK_PRD WK2," ).append("\n"); 
		query.append("               (SELECT HDR.VNDR_SEQ ," ).append("\n"); 
		query.append("						(SELECT DISTINCT OFC_CD" ).append("\n"); 
		query.append("    		              FROM MDM_ORGANIZATION A" ).append("\n"); 
		query.append("            		     WHERE 1=1" ).append("\n"); 
		query.append("							AND A.OFC_KND_CD > 3" ).append("\n"); 
		query.append("					        AND A.DELT_FLG != 'Y' START WITH A.OFC_CD = HDR.INSP_OFC_CD CONNECT BY PRIOR A.PRNT_OFC_CD = A.OFC_CD ) OFC_CD1," ).append("\n"); 
		query.append("						(SELECT DISTINCT OFC_CD" ).append("\n"); 
		query.append("    		              FROM MDM_ORGANIZATION A" ).append("\n"); 
		query.append("            		     WHERE 1=1" ).append("\n"); 
		query.append("					        AND A.OFC_KND_CD = '3'" ).append("\n"); 
		query.append("					        AND A.DELT_FLG != 'Y' START WITH A.OFC_CD = HDR.INSP_OFC_CD CONNECT BY PRIOR A.PRNT_OFC_CD = A.OFC_CD ) OFC_CD2," ).append("\n"); 
		query.append("                       HDR.YD_CD ," ).append("\n"); 
		query.append("                       WK.PLN_YR," ).append("\n"); 
		query.append("                       WK.PLN_MON," ).append("\n"); 
		query.append("                       WK.PLN_WK," ).append("\n"); 
		query.append("                       HDR.FLD_INSP_DT ," ).append("\n"); 
		query.append("                       HDR.BRNC_INSP_FLG AS BBO_CHK_COUNT," ).append("\n"); 
		query.append("                       HDR.HDBRN_INSP_FLG AS BBG_CHK_COUNT" ).append("\n"); 
		query.append("                  FROM MNR_ONSITE_INSP_RSLT HDR," ).append("\n"); 
		query.append("                       EQR_WK_PRD WK" ).append("\n"); 
		query.append("                 WHERE (HDR.BRNC_INSP_FLG = 'Y'" ).append("\n"); 
		query.append("                            OR HDR.HDBRN_INSP_FLG = 'Y' )" ).append("\n"); 
		query.append("				   #if( ${vndr_seq} != '')" ).append("\n"); 
		query.append("				   AND HDR.VNDR_SEQ = @[vndr_seq]" ).append("\n"); 
		query.append("				   #end" ).append("\n"); 
		query.append("				   #if(${rhq_ofc_cd} != '')" ).append("\n"); 
		query.append("					   #if(${insp_ofc_cd} != '')" ).append("\n"); 
		query.append("					   AND HDR.INSP_OFC_CD IN" ).append("\n"); 
		query.append("						(SELECT DISTINCT OFC_CD" ).append("\n"); 
		query.append("    		              FROM MDM_ORGANIZATION A" ).append("\n"); 
		query.append("            		     WHERE A.DELT_FLG != 'Y' START WITH A.OFC_CD = @[insp_ofc_cd] CONNECT BY PRIOR A.OFC_CD = A.PRNT_OFC_CD )" ).append("\n"); 
		query.append("                       #else" ).append("\n"); 
		query.append("                          #if(${rhq_ofc_cd} == 'SELIB(SELSC)')" ).append("\n"); 
		query.append("                       AND HDR.INSP_OFC_CD IN (SELECT OFC_CD FROM MDM_ORGANIZATION WHERE AR_HD_QTR_OFC_CD IN 'SELIB' AND DELT_FLG != 'Y')" ).append("\n"); 
		query.append("                          #else" ).append("\n"); 
		query.append("					   AND HDR.INSP_OFC_CD IN (SELECT OFC_CD FROM MDM_ORGANIZATION WHERE AR_HD_QTR_OFC_CD IN @[rhq_ofc_cd] AND DELT_FLG != 'Y')" ).append("\n"); 
		query.append("                          #end" ).append("\n"); 
		query.append("		               #end" ).append("\n"); 
		query.append("                   #else" ).append("\n"); 
		query.append("                   #if(${insp_ofc_cd} != '')" ).append("\n"); 
		query.append("					   AND HDR.INSP_OFC_CD IN" ).append("\n"); 
		query.append("						(SELECT DISTINCT OFC_CD" ).append("\n"); 
		query.append("    		              FROM MDM_ORGANIZATION A" ).append("\n"); 
		query.append("            		     WHERE A.DELT_FLG != 'Y' START WITH A.OFC_CD = @[insp_ofc_cd] CONNECT BY PRIOR A.OFC_CD = A.PRNT_OFC_CD )" ).append("\n"); 
		query.append("				   #end" ).append("\n"); 
		query.append("				   #end" ).append("\n"); 
		query.append("				   #if(${insp_yr} != '')" ).append("\n"); 
		query.append("				   AND TO_CHAR(HDR.FLD_INSP_DT, 'YYYY') IN (@[insp_yr] )" ).append("\n"); 
		query.append("				   #end  " ).append("\n"); 
		query.append("                   AND TO_CHAR(HDR.FLD_INSP_DT, 'YYYYMMDD') BETWEEN WK.WK_ST_DT AND WK.WK_END_DT ) HDR_DTL" ).append("\n"); 
		query.append("         WHERE 1=1" ).append("\n"); 
		query.append("           #if(${insp_yr} != '')" ).append("\n"); 
		query.append("           AND WK2.PLN_YR IN (@[insp_yr] )" ).append("\n"); 
		query.append("		   #end" ).append("\n"); 
		query.append("           AND HDR_DTL.PLN_YR = WK2.PLN_YR" ).append("\n"); 
		query.append("           AND HDR_DTL.PLN_MON = WK2.PLN_MON" ).append("\n"); 
		query.append("           AND HDR_DTL.PLN_WK = WK2.PLN_WK" ).append("\n"); 
		query.append("         ORDER BY PLN_WK," ).append("\n"); 
		query.append("               PLN_MON," ).append("\n"); 
		query.append("               OFC_CD )" ).append("\n"); 
		query.append("SELECT RHQ_OFC_CD," ).append("\n"); 
		query.append("       OFC_CD INSP_OFC_CD," ).append("\n"); 
		query.append("       DUTY," ).append("\n"); 
		query.append("       DECODE(WK01, 1, 'O') WK01," ).append("\n"); 
		query.append("       DECODE(WK02, 1, 'O') WK02," ).append("\n"); 
		query.append("       DECODE(WK03, 1, 'O') WK03," ).append("\n"); 
		query.append("       DECODE(WK04, 1, 'O') WK04," ).append("\n"); 
		query.append("       DECODE(WK05, 1, 'O') WK05," ).append("\n"); 
		query.append("       DECODE(WK06, 1, 'O') WK06," ).append("\n"); 
		query.append("       DECODE(WK07, 1, 'O') WK07," ).append("\n"); 
		query.append("       DECODE(WK08, 1, 'O') WK08," ).append("\n"); 
		query.append("       DECODE(WK09, 1, 'O') WK09," ).append("\n"); 
		query.append("       DECODE(WK10, 1, 'O') WK10," ).append("\n"); 
		query.append("       DECODE(WK11, 1, 'O') WK11," ).append("\n"); 
		query.append("       DECODE(WK12, 1, 'O') WK12," ).append("\n"); 
		query.append("       DECODE(WK13, 1, 'O') WK13," ).append("\n"); 
		query.append("       DECODE(WK14, 1, 'O') WK14," ).append("\n"); 
		query.append("       DECODE(WK15, 1, 'O') WK15," ).append("\n"); 
		query.append("       DECODE(WK16, 1, 'O') WK16," ).append("\n"); 
		query.append("       DECODE(WK17, 1, 'O') WK17," ).append("\n"); 
		query.append("       DECODE(WK18, 1, 'O') WK18," ).append("\n"); 
		query.append("       DECODE(WK19, 1, 'O') WK19," ).append("\n"); 
		query.append("       DECODE(WK20, 1, 'O') WK20," ).append("\n"); 
		query.append("       DECODE(WK21, 1, 'O') WK21," ).append("\n"); 
		query.append("       DECODE(WK22, 1, 'O') WK22," ).append("\n"); 
		query.append("       DECODE(WK23, 1, 'O') WK23," ).append("\n"); 
		query.append("       DECODE(WK24, 1, 'O') WK24," ).append("\n"); 
		query.append("       DECODE(WK25, 1, 'O') WK25," ).append("\n"); 
		query.append("       DECODE(WK26, 1, 'O') WK26," ).append("\n"); 
		query.append("       DECODE(WK27, 1, 'O') WK27," ).append("\n"); 
		query.append("       DECODE(WK28, 1, 'O') WK28," ).append("\n"); 
		query.append("       DECODE(WK29, 1, 'O') WK29," ).append("\n"); 
		query.append("       DECODE(WK30, 1, 'O') WK30," ).append("\n"); 
		query.append("       DECODE(WK31, 1, 'O') WK31," ).append("\n"); 
		query.append("       DECODE(WK32, 1, 'O') WK32," ).append("\n"); 
		query.append("       DECODE(WK33, 1, 'O') WK33," ).append("\n"); 
		query.append("       DECODE(WK34, 1, 'O') WK34," ).append("\n"); 
		query.append("       DECODE(WK35, 1, 'O') WK35," ).append("\n"); 
		query.append("       DECODE(WK36, 1, 'O') WK36," ).append("\n"); 
		query.append("       DECODE(WK37, 1, 'O') WK37," ).append("\n"); 
		query.append("       DECODE(WK38, 1, 'O') WK38," ).append("\n"); 
		query.append("       DECODE(WK39, 1, 'O') WK39," ).append("\n"); 
		query.append("       DECODE(WK40, 1, 'O') WK40," ).append("\n"); 
		query.append("       DECODE(WK41, 1, 'O') WK41," ).append("\n"); 
		query.append("       DECODE(WK42, 1, 'O') WK42," ).append("\n"); 
		query.append("       DECODE(WK43, 1, 'O') WK43," ).append("\n"); 
		query.append("       DECODE(WK44, 1, 'O') WK44," ).append("\n"); 
		query.append("       DECODE(WK45, 1, 'O') WK45," ).append("\n"); 
		query.append("       DECODE(WK46, 1, 'O') WK46," ).append("\n"); 
		query.append("       DECODE(WK47, 1, 'O') WK47," ).append("\n"); 
		query.append("       DECODE(WK48, 1, 'O') WK48," ).append("\n"); 
		query.append("       DECODE(WK49, 1, 'O') WK49," ).append("\n"); 
		query.append("       DECODE(WK50, 1, 'O') WK50," ).append("\n"); 
		query.append("       DECODE(WK51, 1, 'O') WK51," ).append("\n"); 
		query.append("       DECODE(WK52, 1, 'O') WK52," ).append("\n"); 
		query.append("       DECODE(WK53, 1, 'O') WK53," ).append("\n"); 
		query.append("       NVL(WK01, 0)+NVL(WK02, 0) + NVL(WK03, 0) + NVL(WK04, 0) + NVL(WK05, 0) + NVL(WK06, 0) + NVL(WK07, 0) + NVL(WK08, 0) + NVL(WK09, 0) + NVL(WK10, 0) + NVL(WK11, 0) + NVL(WK12, 0) + NVL(WK13, 0) + NVL(WK14, 0) + NVL(WK15, 0) + NVL(WK16, 0) + NVL(WK17, 0) + NVL(WK18, 0) + NVL(WK19, 0) + NVL(WK20, 0) + NVL(WK21, 0) + NVL(WK22, 0) + NVL(WK23, 0) + NVL(WK24, 0) + NVL(WK25, 0) + NVL(WK26, 0) + NVL(WK27, 0) + NVL(WK28, 0) + NVL(WK29, 0) + NVL(WK30, 0) + NVL(WK31, 0) + NVL(WK32, 0) + NVL(WK33, 0) + NVL(WK34, 0) + NVL(WK35, 0) + NVL(WK36, 0) + NVL(WK37, 0) + NVL(WK38, 0) + NVL(WK39, 0) + NVL(WK40, 0) + NVL(WK41, 0) + NVL(WK42, 0) + NVL(WK43, 0) + NVL(WK44, 0) + NVL(WK45, 0) + NVL(WK46, 0) + NVL(WK47, 0) + NVL(WK48, 0) + NVL(WK49, 0) + NVL(WK50, 0) + NVL(WK51, 0) + NVL(WK52, 0) + NVL(WK53, 0) SUB_TOTAL" ).append("\n"); 
		query.append("  FROM (SELECT DISTINCT A.AR_HD_QTR_OFC_CD RHQ_OFC_CD," ).append("\n"); 
		query.append("               A.OFC_CD," ).append("\n"); 
		query.append("               'SCO' DUTY," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '01'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK01," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '02'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK02," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '03'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK03," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '04'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK04," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '05'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK05," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '06'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK06," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '07'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK07," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '08'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK08," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '09'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK09," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '10'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK10," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '11'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK11," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '12'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK12," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '13'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK13," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '14'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK14," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '15'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK15," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '16'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK16," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '17'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK17," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '18'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK18," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '19'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK19," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '20'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK20," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '21'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK21," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '22'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK22," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '23'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK23," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '24'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK24," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '25'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK25," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '26'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK26," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '27'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK27," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '28'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK28," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '29'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK29," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '30'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK30," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '31'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK31," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '32'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK32," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '33'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK33," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '34'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK34," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '35'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK35," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '36'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK36," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '37'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK37," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '38'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK38," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '39'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK39," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '40'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK40," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '41'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK41," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '42'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK42," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '43'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK43," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '44'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK44," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '45'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK45," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '46'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK46," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '47'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK47," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '48'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK48," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '49'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK49," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '50'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK50," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '51'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK51," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '52'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK52," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '53'" ).append("\n"); 
		query.append("                           AND BBO_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK53" ).append("\n"); 
		query.append("          FROM MDM_ORGANIZATION A," ).append("\n"); 
		query.append("               MASTER" ).append("\n"); 
		query.append("         WHERE A.OFC_CD = MASTER.OFC_CD(+)" ).append("\n"); 
		query.append("        #if(${rhq_ofc_cd} == 'SELIB(SELSC)')" ).append("\n"); 
		query.append("           AND A.OFC_KND_CD > 3" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("           AND (A.OFC_KND_CD = '3' OR A.OFC_CD IN ('PUSSC')) " ).append("\n"); 
		query.append("           AND A.OFC_CD NOT IN ('SELSC')" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("		#if(${rhq_ofc_cd} != '')" ).append("\n"); 
		query.append("		#if(${insp_ofc_cd} != '')" ).append("\n"); 
		query.append("			AND A.OFC_CD = @[insp_ofc_cd]" ).append("\n"); 
		query.append("		#else" ).append("\n"); 
		query.append("       		#if(${rhq_ofc_cd} == 'SELIB(SELSC)')" ).append("\n"); 
		query.append("			AND AR_HD_QTR_OFC_CD IN ('SELIB')" ).append("\n"); 
		query.append("            #else" ).append("\n"); 
		query.append("			AND AR_HD_QTR_OFC_CD IN (@[rhq_ofc_cd])" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("            #if(${insp_ofc_cd} != '')" ).append("\n"); 
		query.append("			AND A.OFC_CD = @[insp_ofc_cd]" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("           AND A.DELT_FLG != 'Y'" ).append("\n"); 
		query.append("         UNION ALL" ).append("\n"); 
		query.append("SELECT DISTINCT A.AR_HD_QTR_OFC_CD RHQ_OFC_CD," ).append("\n"); 
		query.append("               A.OFC_CD," ).append("\n"); 
		query.append("               'SSZ' DUTY," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '01'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK01," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '02'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK02," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '03'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK03," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '04'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK04," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '05'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK05," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '06'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK06," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '07'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK07," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '08'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK08," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '09'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK09," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '10'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK10," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '11'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK11," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '12'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK12," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '13'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK13," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '14'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK14," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '15'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK15," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '16'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK16," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '17'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK17," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '18'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK18," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '19'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK19," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '20'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK20," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '21'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK21," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '22'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK22," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '23'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK23," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '24'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK24," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '25'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK25," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '26'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK26," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '27'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK27," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '28'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK28," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '29'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK29," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '30'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK30," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '31'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK31," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '32'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK32," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '33'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK33," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '34'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK34," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '35'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK35," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '36'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK36," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '37'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK37," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '38'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK38," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '39'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK39," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '40'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK40," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '41'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK41," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '42'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK42," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '43'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK43," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '44'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK44," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '45'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK45," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '46'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK46," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '47'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK47," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '48'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK48," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '49'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK49," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '50'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK50," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '51'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK51," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '52'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK52," ).append("\n"); 
		query.append("               NVL((SELECT 1" ).append("\n"); 
		query.append("                          FROM MASTER" ).append("\n"); 
		query.append("                         WHERE PLN_WK = '53'" ).append("\n"); 
		query.append("                           AND BBG_CHK_COUNT = 'Y'" ).append("\n"); 
		query.append("                           AND ROWNUM = 1" ).append("\n"); 
		query.append("                           AND OFC_CD = A.OFC_CD), '') WK53" ).append("\n"); 
		query.append("          FROM MDM_ORGANIZATION A," ).append("\n"); 
		query.append("               MASTER" ).append("\n"); 
		query.append("         WHERE A.OFC_CD = MASTER.OFC_CD(+)" ).append("\n"); 
		query.append("        #if(${rhq_ofc_cd} == 'SELIB(SELSC)')" ).append("\n"); 
		query.append("           AND A.OFC_KND_CD > 3" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("		   AND (A.OFC_KND_CD = '3' OR A.OFC_CD IN ('PUSSC'))" ).append("\n"); 
		query.append("           AND A.OFC_CD NOT IN ('SELSC')" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("		#if(${rhq_ofc_cd} != '')" ).append("\n"); 
		query.append("		#if(${insp_ofc_cd} != '')" ).append("\n"); 
		query.append("			AND A.OFC_CD = @[insp_ofc_cd]" ).append("\n"); 
		query.append("		#else" ).append("\n"); 
		query.append("       		#if(${rhq_ofc_cd} == 'SELIB(SELSC)')" ).append("\n"); 
		query.append("			AND AR_HD_QTR_OFC_CD IN ('SELIB')" ).append("\n"); 
		query.append("            #else" ).append("\n"); 
		query.append("			AND AR_HD_QTR_OFC_CD IN (@[rhq_ofc_cd])" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("            #if(${insp_ofc_cd} != '')" ).append("\n"); 
		query.append("			AND A.OFC_CD = @[insp_ofc_cd]" ).append("\n"); 
		query.append("		    #end" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("           AND A.DELT_FLG != 'Y') A" ).append("\n"); 
		query.append(" ORDER BY RHQ_OFC_CD," ).append("\n"); 
		query.append("       OFC_CD," ).append("\n"); 
		query.append("       DECODE(DUTY, 'SCO', '1', 'SSZ', '2')" ).append("\n"); 

	}
}