/*=========================================================
*Copyright(c) 2015 CyberLogitec
*@FileName : SalesRPTDBDAOSearchInqByCondition060ListRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2015.05.22
*@LastModifier : 손진환
*@LastVersion : 1.0
* 2015.05.22 손진환
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.esm.coa.multidimensionrpt.salesrpt.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author jinhwan, Son
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class SalesRPTDBDAOSearchInqByCondition060ListRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * 2010.08.02  김기종 CSR No. CHM-201004764-01 
	  * [COA] COA Report 보완 요청  (Inquiry by Customized Condition) - bl_shpr_cd 예외로직 처리 추가
	  * 2010.09.01 김기종  CHM-201005370-01
	  * Inquiry by customized condition 기능 개선
	  * 2010.09.27 장영석 CHM-201005937 
	  * Inquiry by customized condition 기능추가
	  * 2011.06.22 김민아 [CHM-201111640-01] Reefer Core Account 조회조건 추가_Inquiry by customized condition
	  *                                                           Month 체크 시 COST_YRMON이 조회되도록 수정
	  * 2011.11.08 전윤주 [CHM-201114383-01] Inquiry by Customized Condition Tuning 요청
	  *                            From 절 순서 변경 후 힌트 사용
	  * 2011.11.28 전윤주 [CHM-201114789] 화면에서 surcharge 계정 code가 들어왔을 시 쿼리가 hint로 인해 잘못 풀리고 있음
	  *                기존 exists 문을 sub 쿼리로 변경하여 동일한 값이 나오도록 쿼리 변경
	  *                #if (${mdm_charge_cd} != '') 문을 sub 쿼리로 변경
	  * 2012.08.29 이석준[CHM-201219872] Inquiry by customized condition_MT Pick up Location 등 메뉴 추가
	  * 2013.01.22 성미영[CHM-201322531] [COA] Inquiry by Customized Condition 버튼 수정
	  * 2013.05.29 김수정[CHM-201324876] [COA] COA Report내 "IAS Region " / "Bound2" 추가
	  * 2014.01.20 김수정[CHM-201428552] [COA] Inquiry by Customized Condition Shipper / Contract Customer View 선택 추가
	  * 2014.06.03 최덕우[CHM-201430312] [COA] G.Customer Display 관련 일부 화면 로직 보완 수정
	  * 2015.05.14 손진환[CHM-201535771] [COA] CGO RCV DT를 부킹 모듈 상에서 OC Status 발생 date를 바로 바라볼 수 있도록 로직 수정
	  * 2015.05.14 손진환[CHM-201535424] [COA] COA 상 Fixed Rate 반영
	  * 2015.05.22 손진환[CHM-201536029] [COA] COA 상 Fixed Rate 반영 요청 CSR
	  * </pre>
	  */
	public SalesRPTDBDAOSearchInqByCondition060ListRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.esm.coa.multidimensionrpt.salesrpt.integration").append("\n"); 
		query.append("FileName : SalesRPTDBDAOSearchInqByCondition060ListRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("#foreach(${keys} IN ${keyList5})" ).append("\n"); 
		query.append("	 #if (${keys} == 'mty_pkup_yd_cd' || ${keys} == 'bkg_por_scc_cd'||${keys} == 'bkg_del_scc_cd')" ).append("\n"); 
		query.append("       #set($condition = true)" ).append("\n"); 
		query.append("     #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("       COST_YRMON                                                  AS COST_YRMON" ).append("\n"); 
		query.append("      ,SLS_YRMON                                                   AS SLS_YRMON" ).append("\n"); 
		query.append("      ,COST_WK                                                     AS COST_WK" ).append("\n"); 
		query.append("              " ).append("\n"); 
		query.append("#if(${f_include_ts} =='Y')" ).append("\n"); 
		query.append("       , ts_sts     " ).append("\n"); 
		query.append("#end      " ).append("\n"); 
		query.append("      " ).append("\n"); 
		query.append("#foreach(${keys} IN ${keyList1})" ).append("\n"); 
		query.append("    #if (${keys} == 'obrd_dt')" ).append("\n"); 
		query.append("      ,TO_CHAR($keys,'YYYY-MM-DD') AS $keys" ).append("\n"); 
		query.append("	#elseif(${keys} == 'cntr_rcv_dt')" ).append("\n"); 
		query.append("	  ,TO_CHAR(MAX($keys),'YYYY-MM-DD') AS $keys" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,1,3) N1ST_TRD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,29,3) N2ND_TRD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,57,3) N3RD_TRD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,85,3) N4TH_TRD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,113,3) N5TH_TRD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,5,5) N1ST_RLANE_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,33,5) N2ND_RLANE_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,61,5) N3RD_RLANE_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,89,5) N4TH_RLANE_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,117,5) N5TH_RLANE_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,10,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,10,9)) N1ST_FINC_VVD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,38,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,38,9)) N2ND_FINC_VVD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,66,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,66,9)) N3RD_FINC_VVD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,94,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,94,9)) N4TH_FINC_VVD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,122,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,122,9)) N5TH_FINC_VVD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,19,5) N1ST_POL_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,47,5) N2ND_POL_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,75,5) N3RD_POL_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,103,5) N4TH_POL_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,131,5) N5TH_POL_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,24,5) N1ST_POD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,52,5) N2ND_POD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,80,5) N3RD_POD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,108,5) N4TH_POD_CD" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,136,5) N5TH_POD_CD	" ).append("\n"); 
		query.append("	#elseif(${keys} == 'fixed_rate_flag')" ).append("\n"); 
		query.append("      #set($fixed_rate_flag = true)" ).append("\n"); 
		query.append("      , FX_RT_FLG AS FX_RT_FLG" ).append("\n"); 
		query.append("    #else" ).append("\n"); 
		query.append("      ,$keys AS $keys" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("      ,DIR_CD2                                                     AS DIR_CD2" ).append("\n"); 
		query.append("      ,TPSZ_CODE                                                   AS TPSZ_CODE" ).append("\n"); 
		query.append("      ,SUM(LOAD)                                                   AS LOAD" ).append("\n"); 
		query.append("#if (${mdm_charge_cd} != '')" ).append("\n"); 
		query.append("      ,SUM(CHARGE_REV)                                   AS REV" ).append("\n"); 
		query.append("      ,0     AS CMC" ).append("\n"); 
		query.append("      ,0      AS CM" ).append("\n"); 
		query.append("      ,0      AS OPC" ).append("\n"); 
		query.append("      ,0      AS OP" ).append("\n"); 
		query.append("      ,SUM(CHARGE_REV)/SUM(LOAD)                                    AS G_RPB" ).append("\n"); 
		query.append("      ,0      AS CM_COST" ).append("\n"); 
		query.append("      ,0      AS CMCOST" ).append("\n"); 
		query.append("      ,0      AS CMB" ).append("\n"); 
		query.append("      ,0      AS OP_COST" ).append("\n"); 
		query.append("      ,0      AS OPCOST" ).append("\n"); 
		query.append("      ,0    AS OPB" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("      ,SUM(BKG_REV)                                                AS REV" ).append("\n"); 
		query.append("      ,SUM(CM_COST)                                                AS CMC" ).append("\n"); 
		query.append("      ,SUM(BKG_REV+MISC_REV)-SUM(CM_COST)                          AS CM	" ).append("\n"); 
		query.append("#if(${pro_lvl} =='M') -- 2012.01.02 SHKIM CM2 ADD" ).append("\n"); 
		query.append("	  ,SUM(OWN_FDR_AMT) AS CM2C" ).append("\n"); 
		query.append("	  ,SUM(BKG_REV+MISC_REV)-SUM(CM_COST)- SUM(OWN_FDR_AMT)        AS CM2	  " ).append("\n"); 
		query.append("#else	  " ).append("\n"); 
		query.append("	  ,0 AS CM2C" ).append("\n"); 
		query.append("	  ,0 AS CM2" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("      ,SUM(OP_COST + DEM_DET)                                      AS OPC" ).append("\n"); 
		query.append("      ,SUM(BKG_REV+MISC_REV)-SUM(CM_COST)-SUM(OP_COST)             AS OP" ).append("\n"); 
		query.append("      ,SUM(BKG_REV)/SUM(LOAD)                                      AS G_RPB" ).append("\n"); 
		query.append("      ,SUM(CM_COST)                                                AS CM_COST" ).append("\n"); 
		query.append("      ,SUM(CM_COST)/SUM(LOAD)                                      AS CMCOST" ).append("\n"); 
		query.append("      ,(SUM(BKG_REV+MISC_REV)-SUM(CM_COST))/SUM(LOAD)              AS CMB" ).append("\n"); 
		query.append("      ,SUM(OP_COST+ DEM_DET)                                       AS OP_COST" ).append("\n"); 
		query.append("      ,SUM(OP_COST+ DEM_DET)/SUM(LOAD)                             AS OPCOST" ).append("\n"); 
		query.append("      ,(SUM(BKG_REV+MISC_REV)-SUM(CM_COST)-SUM(OP_COST))/SUM(LOAD) AS OPB" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("  FROM (" ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append("    SELECT " ).append("\n"); 
		query.append("          'dummy'  dummy_column" ).append("\n"); 
		query.append("          ,D.BKG_NO AS CHG_BKG_NO  " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${f_include_ts} =='Y' && ${rlane_cd} != 'RBCCO')" ).append("\n"); 
		query.append("          ,CASE WHEN d.trd_cd||d.rlane_cd||d.vsl_cd||d.skd_voy_no||d.dir_cd = v.trd_cd||v.rlane_cd||v.vsl_cd||v.skd_voy_no||v.dir_cd" ).append("\n"); 
		query.append("             THEN 'L/C'  ELSE 'T/S'  END TS_STS" ).append("\n"); 
		query.append("#elseif (${f_include_ts} =='Y' && ${rlane_cd} == 'RBCCO')" ).append("\n"); 
		query.append("          ,CASE WHEN d.trd_cd||d.rlane_cd = 'IASRBCCO'" ).append("\n"); 
		query.append("             THEN 'L/C'  ELSE 'T/S'  END TS_STS" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("          ,D.SPCL_CNTR_TPSZ_CD" ).append("\n"); 
		query.append("#set($sc_desc_flg   = 'FALSE')" ).append("\n"); 
		query.append("#set($cmdt_desc_flg = 'FALSE')" ).append("\n"); 
		query.append("#set($bl_shpr_flg   = 'FALSE')" ).append("\n"); 
		query.append("#set($grp_perp_flg   = 'FALSE')" ).append("\n"); 
		query.append("#set($vvd_flg   = 'FALSE')" ).append("\n"); 
		query.append("#foreach(${keys} IN ${keyList2})" ).append("\n"); 
		query.append("    #if (${keys} == 'sc_desc')" ).append("\n"); 
		query.append("          ,J.$keys AS $keys" ).append("\n"); 
		query.append("    #set($sc_desc_flg = 'TRUE')" ).append("\n"); 
		query.append("    #elseif (${keys} == 'rep_cmdt_desc')" ).append("\n"); 
		query.append("          ,F.$keys AS $keys" ).append("\n"); 
		query.append("    #set($cmdt_desc_flg = 'TRUE')" ).append("\n"); 
		query.append("    #elseif (${keys} == 'shpr_nm')" ).append("\n"); 
		query.append("          ,H.BL_SHPR_NM                                                                       AS SHPR_NM" ).append("\n"); 
		query.append("    #set($bl_shpr_flg = 'TRUE')" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_no')" ).append("\n"); 
		query.append("          ,D.BKG_NO                                                                           AS BKG_NO" ).append("\n"); 
		query.append("    #elseif (${keys} == 'rev_vvd')" ).append("\n"); 
		query.append("          ,D.VSL_CD||D.SKD_VOY_NO||D.DIR_CD                                                   AS REV_VVD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bl_no')" ).append("\n"); 
		query.append("          ,DECODE(SUBSTR(D.BL_NO, 1, 4), 'KOSA', 'K' || D.BKG_NO, D.BL_NO || D.BL_NO_TP || D.BL_NO_CHK) BL_NO" ).append("\n"); 
		query.append("    #elseif (${keys} == 'slan_cd')" ).append("\n"); 
		query.append("          ,D.SLAN_CD                                                                          AS SLAN_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'soc_flg' || ${keys} == 'spcl_dg_cgo_flg' || ${keys} == 'spcl_bb_cgo_flg' || ${keys} == 'spcl_awk_cgo_flg')" ).append("\n"); 
		query.append("          ,NVL(D.$keys, 'N') AS $keys" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_cgo_tp_cd_r')" ).append("\n"); 
		query.append("          ,DECODE(D.BKG_CGO_TP_CD, 'R', 'Y', 'N')                                             AS BKG_CGO_TP_CD_R" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_cgo_wgt')" ).append("\n"); 
		query.append("          ,D.BKG_CGO_WGT                                                                      AS BKG_CGO_WGT" ).append("\n"); 
		query.append("    #elseif (${keys} == 'sc_cust_cd')" ).append("\n"); 
		query.append("          ,D.AGMT_CNT_CD || TO_CHAR(lpad(DECODE(D.AGMT_CUST_SEQ,0,'',D.AGMT_CUST_SEQ),6,'0')) AS SC_CUST_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'cmdt_desc')" ).append("\n"); 
		query.append("          ,K.CMDT_NM                                                                          AS CMDT_DESC" ).append("\n"); 
		query.append("    #elseif (${keys} == 'sc_cust_nm')" ).append("\n"); 
		query.append("          ,(SELECT CUST_LGL_ENG_NM" ).append("\n"); 
		query.append("              FROM MDM_CUSTOMER B1" ).append("\n"); 
		query.append("             WHERE D.AGMT_CNT_CD   = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("               AND D.AGMT_CUST_SEQ = B1.CUST_SEQ(+)" ).append("\n"); 
		query.append("           )                                          AS SC_CUST_NM" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_shpr_cd')" ).append("\n"); 
		query.append("          ,D.SHPR_CNT_CD || TO_CHAR(LPAD(DECODE(D.SHPR_CUST_SEQ,0,'',D.SHPR_CUST_SEQ),6,'0')) AS BKG_SHPR_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'agmt_act_cust_cd')" ).append("\n"); 
		query.append("          ,D.AGMT_ACT_CNT_CD || TO_CHAR(lpad(DECODE(D.AGMT_ACT_CUST_SEQ,0,'',D.AGMT_ACT_CUST_SEQ),6,'0')) AS AGMT_ACT_CUST_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_shpr_nm')" ).append("\n"); 
		query.append("          ,(SELECT CUST_LGL_ENG_NM" ).append("\n"); 
		query.append("              FROM MDM_CUSTOMER B1" ).append("\n"); 
		query.append("             WHERE D.SHPR_CNT_CD   = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("               AND D.SHPR_CUST_SEQ = B1.CUST_SEQ(+)" ).append("\n"); 
		query.append("           )                                          AS BKG_SHPR_NM" ).append("\n"); 
		query.append("    #elseif (${keys} == 'cnee_cd')" ).append("\n"); 
		query.append("          ,D.CNEE_CNT_CD || TO_CHAR(LPAD(DECODE(D.CNEE_CUST_SEQ,0,'',D.CNEE_CUST_SEQ),6,'0')) AS CNEE_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'cnee_nm')" ).append("\n"); 
		query.append("          ,(SELECT CUST_LGL_ENG_NM" ).append("\n"); 
		query.append("              FROM MDM_CUSTOMER B1" ).append("\n"); 
		query.append("             WHERE D.CNEE_CNT_CD   = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("               AND D.CNEE_CUST_SEQ = B1.CUST_SEQ(+))                                          AS CNEE_NM" ).append("\n"); 
		query.append("    #elseif (${keys} == 'ntfy_cd')" ).append("\n"); 
		query.append("          ,D.NTFY_CNT_CD || TO_CHAR(LPAD(DECODE(D.NTFY_CUST_SEQ,0,'',D.NTFY_CUST_SEQ),6,'0')) AS NTFY_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'ntfy_nm')" ).append("\n"); 
		query.append("          ,(SELECT CUST_LGL_ENG_NM" ).append("\n"); 
		query.append("              FROM MDM_CUSTOMER B1" ).append("\n"); 
		query.append("             WHERE D.NTFY_CNT_CD   = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("               AND D.NTFY_CUST_SEQ = B1.CUST_SEQ(+))                                          AS NTFY_NM" ).append("\n"); 
		query.append("    #elseif (${keys} == 'shpr_cd')" ).append("\n"); 
		query.append("          ,D.SHPR_CNT_CD || TO_CHAR(LPAD(DECODE(D.SHPR_CUST_SEQ,0,'',D.SHPR_CUST_SEQ),6,'0')) AS SHPR_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bl_shpr_cd')" ).append("\n"); 
		query.append("          ,D.SHPR_CNT_CD || TO_CHAR(LPAD(DECODE(D.SHPR_CUST_SEQ,0,'',D.SHPR_CUST_SEQ),6,'0')) AS BL_SHPR_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'mty_pkup_yd_cd')" ).append("\n"); 
		query.append("         , B.MTY_PKUP_YD_CD MTY_PKUP_YD_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_scc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'SCC') BKG_POR_SCC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_scc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'SCC') BKG_DEL_SCC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_ecc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'ECC') BKG_POR_ECC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_ecc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'ECC') BKG_DEL_ECC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_lcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'LCC') BKG_POR_LCC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_lcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'LCC') BKG_DEL_LCC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_rcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'RCC') BKG_POR_RCC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_rcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'RCC') BKG_DEL_RCC_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'ias_rgn_cd')" ).append("\n"); 
		query.append("         , COA_GET_CD_NM_FNC('CD03218', R.IAS_RGN_CD) AS IAS_RGN_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'hul_bnd_cd')" ).append("\n"); 
		query.append("         , COA_GET_CD_NM_FNC('CD03217', R.HUL_BND_CD) AS HUL_BND_CD" ).append("\n"); 
		query.append("	#elseif (${keys} == 'rhq_cd_team')" ).append("\n"); 
		query.append("         , GRP.rhq_cd AS $keys" ).append("\n"); 
		query.append("	#set($grp_perp_flg = 'TRUE')" ).append("\n"); 
		query.append("	#elseif (${keys} == 'ofc_team_cd')" ).append("\n"); 
		query.append("         , GRP.$keys AS $keys" ).append("\n"); 
		query.append("	#set($grp_perp_flg = 'TRUE')" ).append("\n"); 
		query.append("	#elseif (${keys} == 'n1st_trd_cd' or ${keys} == 'n2nd_trd_cd' or ${keys} == 'n3rd_trd_cd' or ${keys} == 'n4th_trd_cd' or ${keys} == 'n5th_trd_cd' or" ).append("\n"); 
		query.append(" 			 ${keys} == 'n1st_rlane_cd' or ${keys} == 'n2nd_rlane_cd' or ${keys} == 'n3rd_rlane_cd' or ${keys} == 'n4th_rlane_cd' or ${keys} == 'n5th_rlane_cd' or" ).append("\n"); 
		query.append("			 ${keys} == 'n1st_finc_vvd_cd' or ${keys} == 'n2nd_finc_vvd_cd' or ${keys} == 'n3rd_finc_vvd_cd' or ${keys} == 'n4th_finc_vvd_cd' or ${keys} == 'n5th_finc_vvd_cd' or" ).append("\n"); 
		query.append("			 ${keys} == 'n1st_pol_cd' or ${keys} == 'n2nd_pol_cd' or ${keys} == 'n3rd_pol_cd' or ${keys} == 'n4th_pol_cd' or ${keys} == 'n5th_pol_cd' or" ).append("\n"); 
		query.append("			 ${keys} == 'n1st_pod_cd' or ${keys} == 'n2nd_pod_cd' or ${keys} == 'n3rd_pod_cd' or ${keys} == 'n4th_pod_cd' or ${keys} == 'n5th_pod_cd'" ).append("\n"); 
		query.append("			)" ).append("\n"); 
		query.append("	#set($vvd_flg = 'TRUE')" ).append("\n"); 
		query.append("	#elseif(${keys} == 'fixed_rate_flag')" ).append("\n"); 
		query.append("		 , NVL(CRB.FX_RT_FLG, 'N' ) AS FX_RT_FLG" ).append("\n"); 
		query.append("	#elseif (${keys} == 'rfa_ctrt_tp_cd')" ).append("\n"); 
		query.append("	     , MAX((SELECT COA_GET_CD_NM_FNC('CD03264', RFA_MN.$keys)" ).append("\n"); 
		query.append("        	      FROM PRI_RP_MN RFA_MN" ).append("\n"); 
		query.append("	                  ,PRI_RP_HDR RFA_HDR" ).append("\n"); 
		query.append("        	     WHERE RFA_HDR.PROP_NO = RFA_MN.PROP_NO" ).append("\n"); 
		query.append("                   AND RFA_MN.AMDT_SEQ = ( SELECT /*+ INDEX_DESC(A XPKPRI_RP_MN)*/ AMDT_SEQ FROM PRI_RP_MN A WHERE RFA_MN.PROP_NO = PROP_NO AND ROWNUM = 1)" ).append("\n"); 
		query.append("                   AND RFA_HDR.RFA_NO = D.RFA_NO)) AS $keys" ).append("\n"); 
		query.append("    #else" ).append("\n"); 
		query.append("        #if(${keys} == 'cust_grp_id')" ).append("\n"); 
		query.append("            #if(${f_cust_tp} != 'S')    " ).append("\n"); 
		query.append("                ,(SELECT NVL(B1.CUST_GRP_ID, D.AGMT_CNT_CD||D.AGMT_CUST_SEQ) FROM MDM_CUSTOMER B1    -- CONTRACT CUSTOMER" ).append("\n"); 
		query.append("                    WHERE 1=1 " ).append("\n"); 
		query.append("                        AND D.AGMT_CUST_SEQ = B1.CUST_SEQ(+) " ).append("\n"); 
		query.append("                        AND D.AGMT_CNT_CD = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("                ) AS $keys" ).append("\n"); 
		query.append("            #else                       " ).append("\n"); 
		query.append("                ,(SELECT NVL(B1.CUST_GRP_ID, D.SHPR_CNT_CD||D.SHPR_CUST_SEQ) FROM MDM_CUSTOMER B1    -- SHIPPER" ).append("\n"); 
		query.append("                    WHERE 1=1" ).append("\n"); 
		query.append("                        AND D.SHPR_CUST_SEQ = B1.CUST_SEQ(+)" ).append("\n"); 
		query.append("                        AND D.SHPR_CNT_CD = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("                ) AS $keys" ).append("\n"); 
		query.append("                " ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("        #elseif(${keys} == 'cust_grp_nm')" ).append("\n"); 
		query.append("            #if(${f_cust_tp} != 'S')    " ).append("\n"); 
		query.append("                ,(SELECT NVL(B2.CUST_GRP_NM, B1.CUST_LGL_ENG_NM) FROM MDM_CUSTOMER B1, MDM_CUST_PERF_GRP B2     -- CONTRACT CUSTOMER" ).append("\n"); 
		query.append("                    WHERE 1=1" ).append("\n"); 
		query.append("                        AND D.AGMT_CNT_CD = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("                        AND D.AGMT_CUST_SEQ = B1.CUST_SEQ(+) " ).append("\n"); 
		query.append("                        AND B1.CUST_GRP_ID = B2.CUST_GRP_ID(+)" ).append("\n"); 
		query.append("                ) AS $keys" ).append("\n"); 
		query.append("            #else                       " ).append("\n"); 
		query.append("                ,(SELECT NVL(B2.CUST_GRP_NM, B1.CUST_LGL_ENG_NM) FROM MDM_CUSTOMER B1, MDM_CUST_PERF_GRP B2   -- SHIPPER" ).append("\n"); 
		query.append("                    WHERE 1=1" ).append("\n"); 
		query.append("                        AND D.SHPR_CNT_CD = B1.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("                        AND D.SHPR_CUST_SEQ = B1.CUST_SEQ(+)" ).append("\n"); 
		query.append("                        AND B1.CUST_GRP_ID = B2.CUST_GRP_ID(+)" ).append("\n"); 
		query.append("                ) AS $keys" ).append("\n"); 
		query.append("                " ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("        #elseif(${keys} == 'cntr_rcv_dt')" ).append("\n"); 
		query.append("			#set($cntr_rcv_dt_condition = true)" ).append("\n"); 
		query.append("			,MAX(C.CGO_RCV_DT) AS cntr_rcv_dt" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("            ,D.$keys AS $keys            " ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("		#if(${vvd_flg} == 'TRUE')" ).append("\n"); 
		query.append("		 , COA_PSG_TS_ARRAY_FNC(D.n1st_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n1st_finc_vvd_cd,substr(D.N1ST_RLANE_CD,1,3),SUBSTR (D.n1st_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n1st_finc_vvd_cd,substr(D.N1ST_RLANE_CD,1,3),SUBSTR (D.n1st_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n1st_rlane_cd, SUBSTR (D.n1st_finc_vvd_cd, 1, 9), D.n1st_pol_cd, D.n1st_pod_cd, --1" ).append("\n"); 
		query.append("                              D.n2nd_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n2nd_finc_vvd_cd,substr(D.N2nd_RLANE_CD,1,3),SUBSTR (D.n2nd_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n2nd_finc_vvd_cd,substr(D.n2nd_RLANE_CD,1,3),SUBSTR (D.n2nd_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n2nd_rlane_cd, SUBSTR (D.n2nd_finc_vvd_cd, 1, 9), D.n2nd_pol_cd, D.n2nd_pod_cd, --2" ).append("\n"); 
		query.append("                              D.n3rd_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n3rd_finc_vvd_cd,substr(D.n3rd_RLANE_CD,1,3),SUBSTR (D.n3rd_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n3rd_finc_vvd_cd,substr(D.n3rd_RLANE_CD,1,3),SUBSTR (D.n3rd_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n3rd_rlane_cd, SUBSTR (D.n3rd_finc_vvd_cd, 1, 9), D.n3rd_pol_cd, D.n3rd_pod_cd, --3" ).append("\n"); 
		query.append("                              D.n4th_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n4th_finc_vvd_cd,substr(D.n4th_RLANE_CD,1,3),SUBSTR (D.n4th_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n4th_finc_vvd_cd,substr(D.n4th_RLANE_CD,1,3),SUBSTR (D.n4th_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n4th_rlane_cd, SUBSTR (D.n4th_finc_vvd_cd, 1, 9), D.n4th_pol_cd, D.n4th_pod_cd --4" ).append("\n"); 
		query.append("                             ) vvd_info" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("          ,DECODE('${wk_sts}',  'Y', D.COST_YRMON, '', DECODE('${period}', 'M', D.COST_YRMON, ''))                AS COST_YRMON" ).append("\n"); 
		query.append("          ,DECODE('${wk_sts}',  'Y', D.SLS_YRMON, '')                                                           AS SLS_YRMON" ).append("\n"); 
		query.append("          ,DECODE('${wk_sts}',  'Y', D.COST_WK, '')                                                             AS COST_WK" ).append("\n"); 
		query.append("          ,DECODE('${dir_sts}', 'Y', D.DIR_CD,  '')                                                             AS DIR_CD2" ).append("\n"); 
		query.append("          ,DECODE('${tpsz_sts}', 'BOX', D.SPCL_CNTR_TPSZ_CD, 'TEU','')                                          AS TPSZ_CODE" ).append("\n"); 
		query.append("          ,DECODE('${tpsz_sts}', 'BOX', SUM(NVL(D.BKG_QTY,0)), 'TEU',SUM(DECODE(SUBSTR(D.SPCL_CNTR_TPSZ_CD,-1,1),'2', D.BKG_QTY, '3', D.BKG_QTY, D.BKG_QTY*2))) AS LOAD" ).append("\n"); 
		query.append("          ,SUM(NVL(D.BKG_REV,0)+NVL(D.BKG_OFT_REV,0))                                                              AS BKG_REV" ).append("\n"); 
		query.append("          ,SUM(NVL(D.BKG_MISC_REV,0)+NVL(D.SCR_CHG_REV,0))                                                         AS MISC_REV" ).append("\n"); 
		query.append("          " ).append("\n"); 
		query.append("		  ,SUM(DECODE('${pro_vw}', 'P', NVL(D.PA_CM_COST_TTL_AMT, 0)   , 'R', NVL(D.RA_CM_COST_TTL_AMT, 0)))    AS CM_COST" ).append("\n"); 
		query.append("#if(${pro_lvl} =='M') -- 2012.01.02 SHKIM CM2 ADD" ).append("\n"); 
		query.append("		  ,SUM(D.OWN_FDR_AMT) AS OWN_FDR_AMT" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("          ,SUM(DECODE('${pro_vw}', 'P', 0, 'R', NVL(D.RA_OP_COST_TTL_AMT, 0)))                                  AS OP_COST" ).append("\n"); 
		query.append("          ,SUM(D.DMDT_COM_AMT)                                                                                     AS DEM_DET" ).append("\n"); 
		query.append("          ,SUM(NVL(D.BKG_QTY, 0)) AS CHARGE_LOAD" ).append("\n"); 
		query.append("#if (${mdm_charge_cd} != '')" ).append("\n"); 
		query.append("          ,COA_GET_REV_AMT_FNC (D.BKG_NO, D.SPCL_CNTR_TPSZ_CD,'${mdm_charge_cd}','${period}','${mdm_charge_type_cd}') AS CHARGE_REV" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("          FROM" ).append("\n"); 
		query.append("               COA_OFC_LVL L" ).append("\n"); 
		query.append("              ,COA_MON_VVD V " ).append("\n"); 
		query.append("              ,COA_LANE_RGST R" ).append("\n"); 
		query.append("#if(${period} =='M')" ).append("\n"); 
		query.append("              ,COA_BKG_EXPN_DTL D" ).append("\n"); 
		query.append("#elseif (${period} =='W')" ).append("\n"); 
		query.append("              ,COA_BKG_EXPN_DTL_WK D" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("              ,MDM_COMMODITY    K" ).append("\n"); 
		query.append("#if(${grp_perp_flg} =='TRUE' || (${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("			  ,MDM_CUST_PERF_GRP GRP" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${soc_sts} == 'Y')" ).append("\n"); 
		query.append("              ,COA_BKG_REV_DTL H" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cmdt_desc_flg} == 'TRUE')" ).append("\n"); 
		query.append("              ,(SELECT REP_CMDT_CD AS REP_CMDT_CD" ).append("\n"); 
		query.append("                      ,REP_CMDT_NM AS REP_CMDT_DESC" ).append("\n"); 
		query.append("                 FROM MDM_REP_CMDT" ).append("\n"); 
		query.append("                WHERE NVL(DELT_FLG,'N') = 'N'" ).append("\n"); 
		query.append("               ) F" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sc_desc_flg} == 'TRUE')" ).append("\n"); 
		query.append("              ,(SELECT CUST_CNT_CD     AS CUST_CNT_CD" ).append("\n"); 
		query.append("                      ,CUST_SEQ        AS CUST_SEQ" ).append("\n"); 
		query.append("                      ,CUST_LGL_ENG_NM AS SC_DESC" ).append("\n"); 
		query.append("                  FROM MDM_CUSTOMER" ).append("\n"); 
		query.append("                ) J" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_shpr_flg} == 'TRUE')" ).append("\n"); 
		query.append("              ,(SELECT CUST_CNT_CD     AS CUST_CNT_CD" ).append("\n"); 
		query.append("                      ,CUST_SEQ        AS CUST_SEQ" ).append("\n"); 
		query.append("                      ,CUST_LGL_ENG_NM AS BL_SHPR_NM" ).append("\n"); 
		query.append("                  FROM MDM_CUSTOMER" ).append("\n"); 
		query.append("                ) H" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (((${key_acct_group} != '' && ${key_acct_group} != 'All') || ${otr_key_acct} != '') || (${otr_regional_acct} == '' && ${local_acct} == '' && ${f_cust_tp} == 'C' && ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))))" ).append("\n"); 
		query.append("              ,MDM_CUSTOMER CO" ).append("\n"); 
		query.append("#if ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("              ,MDM_CUST_PERF_GRP CO_GRP" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if ((${f_ra_acct_group_cd} != '' && ${f_ra_acct_group_cd} != 'All') || ${otr_regional_acct} != '' || (${otr_regional_acct} != '' && ${f_cust_tp} == 'C' && ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))))" ).append("\n"); 
		query.append("              ,MDM_CUSTOMER RGN" ).append("\n"); 
		query.append("#if ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("              ,MDM_CUST_PERF_GRP RGN_GRP" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${local_acct} != '' || (${local_acct} != '' && ${f_cust_tp} == 'C' && ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))))" ).append("\n"); 
		query.append("              ,MDM_CUSTOMER LCL" ).append("\n"); 
		query.append("#if ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("              ,MDM_CUST_PERF_GRP LCL_GRP" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${mdm_charge_cd} != '')" ).append("\n"); 
		query.append("              ,(SELECT DISTINCT BKG_NO " ).append("\n"); 
		query.append("                  FROM BKG_CHG_RT " ).append("\n"); 
		query.append("                 WHERE CHG_CD = '${mdm_charge_cd}'" ).append("\n"); 
		query.append("                   AND FRT_INCL_XCLD_DIV_CD = DECODE('${mdm_charge_type_cd}','',FRT_INCL_XCLD_DIV_CD,'${mdm_charge_type_cd}')" ).append("\n"); 
		query.append("                )RT" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${mt_pu_cd} !='' || $condition )" ).append("\n"); 
		query.append("              ,BKG_BOOKING B" ).append("\n"); 
		query.append("#end " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${f_include_ts} =='Y' && ${rlane_cd} != 'RBCCO')" ).append("\n"); 
		query.append("              , BKG_VVD BV" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${f_fixed_rate} == 'Y' || $fixed_rate_flag )" ).append("\n"); 
		query.append("			, COA_RGST_BKG CRB" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if( $cntr_rcv_dt_condition )" ).append("\n"); 
		query.append("			, ( SELECT BKG_NO, MAX(CGO_RCV_DT) AS CGO_RCV_DT " ).append("\n"); 
		query.append("        		FROM BKG_CONTAINER " ).append("\n"); 
		query.append("		        GROUP BY BKG_NO ) C" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("          WHERE 1=1" ).append("\n"); 
		query.append("#if (${mt_pu_cd} !='' || $condition )" ).append("\n"); 
		query.append("            AND D.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${mt_pu_cd} !='')         " ).append("\n"); 
		query.append("            AND B.MTY_PKUP_YD_CD LIKE '${mt_pu_cd}'||DECODE('${mt_pu_yd_cd}','All','','${mt_pu_yd_cd}')||'%'  -- 화면에서 MT Pick up 5+2" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${mdm_charge_cd} != '')" ).append("\n"); 
		query.append("           AND D.BKG_NO = RT.BKG_NO" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${srep_cd} != '')" ).append("\n"); 
		query.append("#if(${ofc_vw} =='C')" ).append("\n"); 
		query.append("           AND D.CTRT_SREP_CD = '${srep_cd}'" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("           AND D.SREP_CD = '${srep_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${period} =='M')" ).append("\n"); 
		query.append("  #if(${f_include_ts} =='Y' && ${rlane_cd} != 'RBCCO')" ).append("\n"); 
		query.append("           AND V.COST_YRMON  BETWEEN '${year}'||'${fm_mon}' AND '${year}'||'${to_mon}'" ).append("\n"); 
		query.append("           AND V.VSL_CD              = BV.VSL_CD " ).append("\n"); 
		query.append("           AND V.SKD_VOY_NO          = BV.SKD_VOY_NO " ).append("\n"); 
		query.append("           AND V.DIR_CD              = BV.SKD_DIR_CD " ).append("\n"); 
		query.append("           AND BV.BKG_NO             = D.BKG_NO " ).append("\n"); 
		query.append("  #else" ).append("\n"); 
		query.append("           AND D.COST_YRMON  BETWEEN '${year}'||'${fm_mon}' AND '${year}'||'${to_mon}'             " ).append("\n"); 
		query.append("           AND V.TRD_CD              = D.TRD_CD " ).append("\n"); 
		query.append("           AND V.RLANE_CD            = D.RLANE_CD " ).append("\n"); 
		query.append("           AND V.IOC_CD              = D.IOC_CD " ).append("\n"); 
		query.append("           AND V.VSL_CD              = D.VSL_CD " ).append("\n"); 
		query.append("           AND V.SKD_VOY_NO          = D.SKD_VOY_NO " ).append("\n"); 
		query.append("           AND V.DIR_CD              = D.DIR_CD " ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("           AND D.COST_YRMON  BETWEEN L.OFC_APLY_FM_YRMON AND L.OFC_APLY_TO_YRMON" ).append("\n"); 
		query.append("#elseif (${period} =='W')" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  #if(${f_include_ts} =='Y' && ${rlane_cd} != 'RBCCO')" ).append("\n"); 
		query.append("           AND SUBSTR(V.SLS_YRMON, 1, 4)||V.COST_WK BETWEEN '${year}'||'${fm_wk}' AND '${year}'||'${to_wk}'" ).append("\n"); 
		query.append("           AND V.VSL_CD              = BV.VSL_CD " ).append("\n"); 
		query.append("           AND V.SKD_VOY_NO          = BV.SKD_VOY_NO " ).append("\n"); 
		query.append("           AND V.DIR_CD              = BV.SKD_DIR_CD " ).append("\n"); 
		query.append("           AND BV.BKG_NO             = D.BKG_NO " ).append("\n"); 
		query.append("           " ).append("\n"); 
		query.append("    #if ( ${sls_month} != '')" ).append("\n"); 
		query.append("           AND V.SLS_YRMON = '${year}'||'${fm_mon}'" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("  #else" ).append("\n"); 
		query.append("           AND SUBSTR(D.SLS_YRMON, 1, 4)||D.COST_WK BETWEEN '${year}'||'${fm_wk}' AND '${year}'||'${to_wk}'             " ).append("\n"); 
		query.append("           AND V.TRD_CD              = D.TRD_CD " ).append("\n"); 
		query.append("           AND V.RLANE_CD            = D.RLANE_CD " ).append("\n"); 
		query.append("           AND V.IOC_CD              = D.IOC_CD " ).append("\n"); 
		query.append("           AND V.VSL_CD              = D.VSL_CD " ).append("\n"); 
		query.append("           AND V.SKD_VOY_NO          = D.SKD_VOY_NO " ).append("\n"); 
		query.append("           AND V.DIR_CD              = D.DIR_CD " ).append("\n"); 
		query.append("    #if ( ${sls_month} != '')" ).append("\n"); 
		query.append("           AND D.SLS_YRMON = '${year}'||'${fm_mon}'" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("  #end  " ).append("\n"); 
		query.append("           AND D.SLS_YRMON  BETWEEN L.OFC_APLY_FM_YRMON AND L.OFC_APLY_TO_YRMON" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${f_fixed_rate} == 'Y' || $fixed_rate_flag )" ).append("\n"); 
		query.append("		   AND CRB.BKG_NO			 = D.BKG_NO" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${f_fixed_rate} == 'Y' )" ).append("\n"); 
		query.append("		   AND CRB.FX_RT_FLG		 = 'Y'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${ofc_vw} =='C')" ).append("\n"); 
		query.append("           AND D.AGMT_SGN_OFC_CD = L.OFC_CD" ).append("\n"); 
		query.append("#elseif (${ofc_vw} =='L')" ).append("\n"); 
		query.append("           AND D.SLS_OFC_CD = L.OFC_CD" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("           AND 1 = 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sc_desc_flg} == 'TRUE')" ).append("\n"); 
		query.append("           AND D.AGMT_CNT_CD   = J.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("           AND D.AGMT_CUST_SEQ = J.CUST_SEQ(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_shpr_flg} == 'TRUE')" ).append("\n"); 
		query.append("           AND D.SHPR_CNT_CD   = H.CUST_CNT_CD(+)" ).append("\n"); 
		query.append("           AND D.SHPR_CUST_SEQ = H.CUST_SEQ(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cmdt_desc_flg} == 'TRUE')" ).append("\n"); 
		query.append("           AND D.REP_CMDT_CD = F.REP_CMDT_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${grp_perp_flg} == 'TRUE' || ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All')))" ).append("\n"); 
		query.append("           AND D.CUST_GRP_ID = GRP.CUST_GRP_ID(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("           AND D.CMDT_CD             = K.CMDT_CD(+)" ).append("\n"); 
		query.append("           AND NVL(V.DELT_FLG,'N')   = 'N'" ).append("\n"); 
		query.append("       " ).append("\n"); 
		query.append("           " ).append("\n"); 
		query.append("           AND D.BL_NO_TP             IN ('M','0')" ).append("\n"); 
		query.append("           AND D.BKG_STS_CD           IN ('F','S',DECODE(NVL('${bkg_sts}','N'), 'Y', 'W'))" ).append("\n"); 
		query.append("           AND NVL(D.BKG_CGO_TP_CD,'*') <> 'P'" ).append("\n"); 
		query.append("           AND V.RLANE_CD            = R.RLANE_CD" ).append("\n"); 
		query.append("           AND V.DIR_CD              = R.DIR_CD" ).append("\n"); 
		query.append("           AND V.IOC_CD              = R.IOC_CD" ).append("\n"); 
		query.append("           AND V.TRD_CD              = R.TRD_CD" ).append("\n"); 
		query.append("           AND R.DELT_FLG            = 'N'" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${ias_rgn_cd} != '')" ).append("\n"); 
		query.append("           AND R.IAS_RGN_CD          = '${ias_rgn_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${hul_bnd_cd} != '')" ).append("\n"); 
		query.append("           AND R.HUL_BND_CD          = '${hul_bnd_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if ((${key_acct_group} != '' && ${key_acct_group} != 'All') || ${otr_key_acct} != '' || (${otr_regional_acct} == '' && ${local_acct} == '' && ${f_cust_tp} == 'C' && ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))))" ).append("\n"); 
		query.append("#if (${f_cust_tp} != 'S')" ).append("\n"); 
		query.append("           AND D.AGMT_CNT_CD   = CO.CUST_CNT_CD" ).append("\n"); 
		query.append("           AND D.AGMT_CUST_SEQ = CO.CUST_SEQ" ).append("\n"); 
		query.append("#if ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("           AND CO.CUST_GRP_ID   = CO_GRP.CUST_GRP_ID(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("           AND D.SHPR_CNT_CD   = CO.CUST_CNT_CD" ).append("\n"); 
		query.append("           AND D.SHPR_CUST_SEQ = CO.CUST_SEQ" ).append("\n"); 
		query.append("#if ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("           AND CO.CUST_GRP_ID   = CO_GRP.CUST_GRP_ID(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("           AND CO.NEW_KEY_ACCT_FLG  = 'Y'" ).append("\n"); 
		query.append("           AND CO.CNTR_DIV_FLG  = 'Y'" ).append("\n"); 
		query.append("           AND CO.DELT_FLG      = 'N'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if ((${f_ra_acct_group_cd} != '' && ${f_ra_acct_group_cd} != 'All') || ${otr_regional_acct} != ''|| (${otr_regional_acct} != '' && ${f_cust_tp} == 'C' && ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))))" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${f_cust_tp} != 'S')" ).append("\n"); 
		query.append("           AND D.AGMT_CNT_CD   = RGN.CUST_CNT_CD" ).append("\n"); 
		query.append("           AND D.AGMT_CUST_SEQ = RGN.CUST_SEQ" ).append("\n"); 
		query.append("#if ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("           AND RGN.CUST_GRP_ID   = RGN_GRP.CUST_GRP_ID(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("           AND D.SHPR_CNT_CD   = RGN.CUST_CNT_CD" ).append("\n"); 
		query.append("           AND D.SHPR_CUST_SEQ = RGN.CUST_SEQ" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("           AND RGN.RGN_ACCT_FLG  = 'Y'" ).append("\n"); 
		query.append("           AND RGN.CNTR_DIV_FLG  = 'Y'" ).append("\n"); 
		query.append("           AND RGN.DELT_FLG      = 'N'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${local_acct} != '' || (${local_acct} != '' && ${f_cust_tp} == 'C' && ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))))" ).append("\n"); 
		query.append("#if(${f_cust_tp} != 'S')" ).append("\n"); 
		query.append("           AND D.AGMT_CNT_CD   = LCL.CUST_CNT_CD" ).append("\n"); 
		query.append("           AND D.AGMT_CUST_SEQ = LCL.CUST_SEQ" ).append("\n"); 
		query.append("#if ((${ofc_team_cd} != '' && ${ofc_team_cd} !='All') || (${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All'))" ).append("\n"); 
		query.append("           AND LCL.CUST_GRP_ID   = LCL_GRP.CUST_GRP_ID(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("           AND D.SHPR_CNT_CD   = LCL.CUST_CNT_CD" ).append("\n"); 
		query.append("           AND D.SHPR_CUST_SEQ = LCL.CUST_SEQ" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("           AND LCL.RGN_ACCT_FLG  = 'Y'" ).append("\n"); 
		query.append("           AND LCL.CNTR_DIV_FLG  = 'Y'" ).append("\n"); 
		query.append("           AND LCL.DELT_FLG      = 'N'" ).append("\n"); 
		query.append("		   AND NVL(LCL.NEW_KEY_ACCT_FLG,'N') = 'N'" ).append("\n"); 
		query.append("		   AND NVL(LCL.RGN_ACCT_FLG, 'N') = 'N'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${f_include_ts} == 'Y' && ${rlane_cd} != 'RBCCO')" ).append("\n"); 
		query.append("  #if (${trd_cd} != '')" ).append("\n"); 
		query.append("             AND V.TRD_CD = '${trd_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${sub_trd_cd} != '')" ).append("\n"); 
		query.append("             AND V.SUB_TRD_CD = '${sub_trd_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${rlane_cd} != '')" ).append("\n"); 
		query.append("             AND V.RLANE_CD = '${rlane_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  #if (${dir_cd} != '')" ).append("\n"); 
		query.append("             AND V.DIR_CD = '${dir_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${vsl_cd} != '')" ).append("\n"); 
		query.append("             AND V.VSL_CD = '${vsl_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${skd_voy_no} != '')" ).append("\n"); 
		query.append("             AND V.SKD_VOY_NO = '${skd_voy_no}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${skd_dir_cd} != '')" ).append("\n"); 
		query.append("             AND V.DIR_CD = '${skd_dir_cd}'" ).append("\n"); 
		query.append("  #end  " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#elseif(${f_include_ts} == 'Y' && ${rlane_cd} == 'RBCCO')" ).append("\n"); 
		query.append("	#if(${trd_cd} !='' && ${rlane_cd} !='')" ).append("\n"); 
		query.append("             AND '${trd_cd}'||'${rlane_cd}' IN (D.N1ST_TRD_CD||D.N1ST_RLANE_CD, D.N2ND_TRD_CD||D.N2ND_RLANE_CD, D.N3RD_TRD_CD||D.N3RD_RLANE_CD, D.N4TH_TRD_CD||D.N4TH_RLANE_CD)" ).append("\n"); 
		query.append("  #end " ).append("\n"); 
		query.append("   " ).append("\n"); 
		query.append("#else " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  #if (${trd_cd} != '')" ).append("\n"); 
		query.append("             AND D.TRD_CD = '${trd_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${sub_trd_cd} != '')" ).append("\n"); 
		query.append("             AND D.SUB_TRD_CD = '${sub_trd_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${rlane_cd} != '')" ).append("\n"); 
		query.append("             AND D.RLANE_CD = '${rlane_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  #if (${dir_cd} != '')" ).append("\n"); 
		query.append("             AND D.DIR_CD = '${dir_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${vsl_cd} != '')" ).append("\n"); 
		query.append("             AND D.VSL_CD = '${vsl_cd}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${skd_voy_no} != '')" ).append("\n"); 
		query.append("             AND D.SKD_VOY_NO = '${skd_voy_no}'" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("  #if (${skd_dir_cd} != '')" ).append("\n"); 
		query.append("             AND D.DIR_CD = '${skd_dir_cd}'" ).append("\n"); 
		query.append("  #end " ).append("\n"); 
		query.append("#end   " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  " ).append("\n"); 
		query.append("#if (${taa_no} != '')" ).append("\n"); 
		query.append("           AND D.TAA_NO = '${taa_no}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_por_cd} != '')" ).append("\n"); 
		query.append("           AND D.BKG_POR_CD LIKE '${bkg_por_cd}' ||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${rev_pol_cd} != '')" ).append("\n"); 
		query.append("           AND D.REV_POL_CD LIKE '${rev_pol_cd}' ||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${rev_pod_cd} != '')" ).append("\n"); 
		query.append("           AND D.REV_POD_CD LIKE '${rev_pod_cd}' ||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_del_cd} != '')" ).append("\n"); 
		query.append("           AND D.BKG_DEL_CD LIKE '${bkg_del_cd}' ||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${ias_sub_grp_cd} != '')" ).append("\n"); 
		query.append("           AND SUBSTR(D.BKG_POL_CD,1,2) IN (SELECT IAS.POL_CNT_CD FROM COA_IAS_SUB IAS WHERE IAS.IAS_SUB_CD = '${ias_sub_grp_cd}')" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_pol_cd} != '')" ).append("\n"); 
		query.append("           AND D.BKG_POL_CD LIKE '${bkg_pol_cd}' ||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${ias_sub_grp_cd} != '')" ).append("\n"); 
		query.append("           AND (SUBSTR(D.BKG_POD_CD,1,2) IN (SELECT IAS.POD_CNT_CD" ).append("\n"); 
		query.append("                                               FROM COA_IAS_SUB IAS" ).append("\n"); 
		query.append("                                              WHERE IAS.IAS_SUB_CD = '${ias_sub_grp_cd}'" ).append("\n"); 
		query.append("#if (${ias_sub_grp_cd} == 'RSEA')" ).append("\n"); 
		query.append("                                                AND IAS.POD_CNT_CD NOT IN ('SA')" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                                             )" ).append("\n"); 
		query.append("#if (${ias_sub_grp_cd} == 'MEST')" ).append("\n"); 
		query.append("           AND  D.BKG_POD_CD != 'SAJED'" ).append("\n"); 
		query.append("#elseif (${ias_sub_grp_cd} == 'RSEA')" ).append("\n"); 
		query.append("           OR  (SUBSTR(D.BKG_POD_CD,1,2)='SA' AND D.BKG_POD_CD = 'SAJED')" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_pod_cd} != '')" ).append("\n"); 
		query.append("           AND D.BKG_POD_CD LIKE '${bkg_pod_cd}' ||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sc_no} != '')" ).append("\n"); 
		query.append("           AND D.SC_NO = '${sc_no}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${rfa_no} != '')" ).append("\n"); 
		query.append("           AND D.RFA_NO = '${rfa_no}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${shpr_cnt_cd} != '')" ).append("\n"); 
		query.append("           AND D.SHPR_CNT_CD || D.SHPR_CUST_SEQ = '${shpr_cnt_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cmdt_cd} != '')" ).append("\n"); 
		query.append("           AND D.REP_CMDT_CD = '${cmdt_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${usa_bkg_mod_cd} != '')" ).append("\n"); 
		query.append("           AND D.USA_BKG_MOD_CD = '${usa_bkg_mod_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_no} != '')" ).append("\n"); 
		query.append("           AND D.BKG_NO = '${bkg_no}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cntr_tpsz_cd} != '' )" ).append("\n"); 
		query.append("           AND (" ).append("\n"); 
		query.append("    #foreach($field_id in ${cntr_tpsz_cd})" ).append("\n"); 
		query.append("        #if($velocityCount > 1)" ).append("\n"); 
		query.append("               OR #end      D.SPCL_CNTR_TPSZ_CD = '$field_id'" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${key_acct_group} != '' && ${key_acct_group} != 'All')" ).append("\n"); 
		query.append("    #if (${key_acct_group1} != '')" ).append("\n"); 
		query.append("           AND CO.CUST_GRP_ID = '${key_acct_group1}'" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${f_ra_acct_group_cd} != '' && ${f_ra_acct_group_cd} != 'All')" ).append("\n"); 
		query.append("           AND RGN.CUST_GRP_ID = '${f_ra_acct_group_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${ofc_team_cd} != '' && ${ofc_team_cd} !='All')" ).append("\n"); 
		query.append("#if(${f_cust_tp} != 'C')" ).append("\n"); 
		query.append("		   AND GRP.OFC_TEAM_CD = '${ofc_team_cd}'" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${local_acct} != '')" ).append("\n"); 
		query.append("           AND LCL_GRP.OFC_TEAM_CD = '${ofc_team_cd}'" ).append("\n"); 
		query.append("#elseif(${otr_regional_acct} != '')" ).append("\n"); 
		query.append("           AND RGN_GRP.OFC_TEAM_CD = '${ofc_team_cd}'" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("           AND CO_GRP.OFC_TEAM_CD = '${ofc_team_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${cust_rhq_cd} != '' && ${cust_rhq_cd} !='All')" ).append("\n"); 
		query.append("#if(${f_cust_tp} != 'C')" ).append("\n"); 
		query.append("		   AND GRP.RHQ_CD = '${cust_rhq_cd}'" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("		   AND CO_GRP.RHQ_CD = '${cust_rhq_cd}'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${soc_sts} == 'Y')" ).append("\n"); 
		query.append("           AND D.BKG_NO       = H.BKG_NO" ).append("\n"); 
		query.append("           AND D.CNTR_TPSZ_CD = H.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("           AND D.COST_ROUT_NO = H.COST_ROUT_NO" ).append("\n"); 
		query.append("           AND NVL(H.SOC_FLG,'N') = 'N'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${sls_ofc_cd} !='')" ).append("\n"); 
		query.append("    #if(${excl_sts} =='')" ).append("\n"); 
		query.append("           AND DECODE('${ofc_lvl}','1',L.OFC_N1ST_LVL_CD,'2',L.OFC_N2ND_LVL_CD,'3',L.OFC_N3RD_LVL_CD,'4',L.OFC_N4TH_LVL_CD,'5',L.OFC_N5TH_LVL_CD" ).append("\n"); 
		query.append("              ,'6',L.OFC_N6TH_LVL_CD,'7',L.OFC_N7TH_LVL_CD) = '${ofc_cd}'" ).append("\n"); 
		query.append("    #else" ).append("\n"); 
		query.append("           AND L.OFC_CD = '${ofc_cd}'" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if( $cntr_rcv_dt_condition )" ).append("\n"); 
		query.append("			AND D.BKG_NO = C.BKG_NO(+)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${ofc_lvl}=='6' || ${ofc_lvl}=='7')" ).append("\n"); 
		query.append("           AND L.OFC_LVL = '${ofc_lvl}'" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("           AND L.OFC_LVL < '9'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("    GROUP BY 1" ).append("\n"); 
		query.append("            ,D.BKG_NO   " ).append("\n"); 
		query.append("#if(${f_include_ts} =='Y' && ${rlane_cd} != 'RBCCO')" ).append("\n"); 
		query.append("          ,CASE WHEN d.trd_cd||d.rlane_cd||d.vsl_cd||d.skd_voy_no||d.dir_cd = v.trd_cd||v.rlane_cd||v.vsl_cd||v.skd_voy_no||v.dir_cd" ).append("\n"); 
		query.append("             THEN 'L/C'  ELSE 'T/S'  END " ).append("\n"); 
		query.append("#elseif (${f_include_ts} =='Y' && ${rlane_cd} == 'RBCCO')" ).append("\n"); 
		query.append("          ,CASE WHEN d.trd_cd||d.rlane_cd = 'IASRBCCO'" ).append("\n"); 
		query.append("             THEN 'L/C'  ELSE 'T/S'  END " ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("            ,D.SPCL_CNTR_TPSZ_CD" ).append("\n"); 
		query.append("#set($vvd_flg = 'FALSE')" ).append("\n"); 
		query.append("#foreach(${keys} IN ${keyList3})" ).append("\n"); 
		query.append("    #if (${keys} == 'sc_desc')" ).append("\n"); 
		query.append("            ,J.$keys" ).append("\n"); 
		query.append("    #elseif (${keys} == 'rep_cmdt_desc')" ).append("\n"); 
		query.append("            ,F.$keys" ).append("\n"); 
		query.append("    #elseif (${keys} == 'shpr_nm')" ).append("\n"); 
		query.append("            ,H.BL_SHPR_NM" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_no')" ).append("\n"); 
		query.append("            ,D.BKG_NO" ).append("\n"); 
		query.append("    #elseif (${keys} == 'rev_vvd')" ).append("\n"); 
		query.append("            ,D.VSL_CD||D.SKD_VOY_NO||D.DIR_CD" ).append("\n"); 
		query.append("	#elseif (${keys} == 'fixed_rate_flag')" ).append("\n"); 
		query.append("			,CRB.FX_RT_FLG" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bl_no')" ).append("\n"); 
		query.append("            ,DECODE(SUBSTR(D.BL_NO, 1, 4), 'KOSA', 'K' || D.BKG_NO, D.BL_NO || D.BL_NO_TP || D.BL_NO_CHK)" ).append("\n"); 
		query.append("    #elseif (${keys} == 'slan_cd')" ).append("\n"); 
		query.append("            ,D.SLAN_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'soc_flg' || ${keys} == 'spcl_dg_cgo_flg' || ${keys} == 'spcl_bb_cgo_flg' || ${keys} == 'spcl_awk_cgo_flg')" ).append("\n"); 
		query.append("            ,NVL(D.$keys, 'N')" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_cgo_tp_cd_r')" ).append("\n"); 
		query.append("            ,DECODE(D.BKG_CGO_TP_CD, 'R', 'Y', 'N')" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_cgo_wgt')" ).append("\n"); 
		query.append("            ,D.BKG_CGO_WGT" ).append("\n"); 
		query.append("    #elseif (${keys} == 'sc_cust_cd')" ).append("\n"); 
		query.append("            ,D.AGMT_CNT_CD || TO_CHAR(LPAD(DECODE(D.AGMT_CUST_SEQ,0,'',D.AGMT_CUST_SEQ),6,'0'))" ).append("\n"); 
		query.append("    #elseif (${keys} == 'cmdt_desc')" ).append("\n"); 
		query.append("            ,K.CMDT_NM" ).append("\n"); 
		query.append("    #elseif (${keys} == 'sc_cust_nm')" ).append("\n"); 
		query.append("            ,D.AGMT_CNT_CD" ).append("\n"); 
		query.append("            ,D.AGMT_CUST_SEQ" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_shpr_cd')" ).append("\n"); 
		query.append("            ,D.SHPR_CNT_CD || TO_CHAR(LPAD(DECODE(D.SHPR_CUST_SEQ,0,'',D.SHPR_CUST_SEQ),6,'0'))" ).append("\n"); 
		query.append("    #elseif (${keys} == 'agmt_act_cust_cd')" ).append("\n"); 
		query.append("            ,D.AGMT_ACT_CNT_CD || TO_CHAR(LPAD(DECODE(D.AGMT_ACT_CUST_SEQ,0,'',D.AGMT_ACT_CUST_SEQ),6,'0'))" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_shpr_nm')" ).append("\n"); 
		query.append("            ,D.SHPR_CNT_CD" ).append("\n"); 
		query.append("            ,D.SHPR_CUST_SEQ" ).append("\n"); 
		query.append("    #elseif (${keys} == 'cnee_cd')" ).append("\n"); 
		query.append("            ,D.CNEE_CNT_CD || TO_CHAR(LPAD(DECODE(D.CNEE_CUST_SEQ,0,'',D.CNEE_CUST_SEQ),6,'0'))" ).append("\n"); 
		query.append("    #elseif (${keys} == 'cnee_nm')" ).append("\n"); 
		query.append("            ,D.CNEE_CNT_CD" ).append("\n"); 
		query.append("            ,D.CNEE_CUST_SEQ" ).append("\n"); 
		query.append("    #elseif (${keys} == 'ntfy_cd')" ).append("\n"); 
		query.append("            ,D.NTFY_CNT_CD || TO_CHAR(LPAD(DECODE(D.NTFY_CUST_SEQ,0,'',D.NTFY_CUST_SEQ),6,'0'))" ).append("\n"); 
		query.append("    #elseif (${keys} == 'ntfy_nm')" ).append("\n"); 
		query.append("            ,D.NTFY_CNT_CD" ).append("\n"); 
		query.append("            ,D.NTFY_CUST_SEQ" ).append("\n"); 
		query.append("    #elseif (${keys} == 'shpr_cd')" ).append("\n"); 
		query.append("            ,D.SHPR_CNT_CD || TO_CHAR(LPAD(DECODE(D.SHPR_CUST_SEQ,0,'',D.SHPR_CUST_SEQ),6,'0'))" ).append("\n"); 
		query.append("   #elseif (${keys} == 'bl_shpr_cd')" ).append("\n"); 
		query.append("            ,D.SHPR_CNT_CD || TO_CHAR(LPAD(DECODE(D.SHPR_CUST_SEQ,0,'',D.SHPR_CUST_SEQ),6,'0'))" ).append("\n"); 
		query.append("    #elseif (${keys} == 'mty_pkup_yd_cd')" ).append("\n"); 
		query.append("         , B.MTY_PKUP_YD_CD" ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_scc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'SCC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_scc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'SCC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_ecc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'ECC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_ecc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'ECC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_lcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'LCC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_lcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'LCC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_por_rcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_POR_CD,'RCC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'bkg_del_rcc_cd')" ).append("\n"); 
		query.append("         , COA_LOC_FNC(D.BKG_DEL_CD,'RCC') " ).append("\n"); 
		query.append("    #elseif (${keys} == 'ias_rgn_cd' || ${keys} == 'hul_bnd_cd')" ).append("\n"); 
		query.append("         , R.$keys" ).append("\n"); 
		query.append("	#elseif (${keys} == 'rhq_cd_team')" ).append("\n"); 
		query.append("         , GRP.RHQ_CD" ).append("\n"); 
		query.append("	#elseif  (${keys} == 'ofc_team_cd')" ).append("\n"); 
		query.append("		 , GRP.$keys" ).append("\n"); 
		query.append("	#elseif (${keys} == 'n1st_trd_cd' or ${keys} == 'n2nd_trd_cd' or ${keys} == 'n3rd_trd_cd' or ${keys} == 'n4th_trd_cd' or ${keys} == 'n5th_trd_cd' or" ).append("\n"); 
		query.append(" 			 ${keys} == 'n1st_rlane_cd' or ${keys} == 'n2nd_rlane_cd' or ${keys} == 'n3rd_rlane_cd' or ${keys} == 'n4th_rlane_cd' or ${keys} == 'n5th_rlane_cd' or" ).append("\n"); 
		query.append("			 ${keys} == 'n1st_finc_vvd_cd' or ${keys} == 'n2nd_finc_vvd_cd' or ${keys} == 'n3rd_finc_vvd_cd' or ${keys} == 'n4th_finc_vvd_cd' or ${keys} == 'n5th_finc_vvd_cd' or" ).append("\n"); 
		query.append("			 ${keys} == 'n1st_pol_cd' or ${keys} == 'n2nd_pol_cd' or ${keys} == 'n3rd_pol_cd' or ${keys} == 'n4th_pol_cd' or ${keys} == 'n5th_pol_cd' or" ).append("\n"); 
		query.append("			 ${keys} == 'n1st_pod_cd' or ${keys} == 'n2nd_pod_cd' or ${keys} == 'n3rd_pod_cd' or ${keys} == 'n4th_pod_cd' or ${keys} == 'n5th_pod_cd'" ).append("\n"); 
		query.append("			)" ).append("\n"); 
		query.append("	#set($vvd_flg = 'TRUE')" ).append("\n"); 
		query.append("	#elseif (${keys} == 'rfa_ctrt_tp_cd')" ).append("\n"); 
		query.append("   #else" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("        #if(${keys} == 'cust_grp_id')" ).append("\n"); 
		query.append("            #if(${f_cust_tp} != 'S')   " ).append("\n"); 
		query.append("                ,D.CUST_GRP_ID          -- CONTRACT CUSTOMER" ).append("\n"); 
		query.append("                ,D.AGMT_CUST_SEQ        " ).append("\n"); 
		query.append("                ,D.AGMT_CNT_CD" ).append("\n"); 
		query.append("            #else                 " ).append("\n"); 
		query.append("                ,D.CUST_GRP_ID          -- SHIPPER" ).append("\n"); 
		query.append("                ,D.SHPR_CUST_SEQ        " ).append("\n"); 
		query.append("                ,D.SHPR_CNT_CD" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("        #elseif(${keys} == 'cust_grp_nm')" ).append("\n"); 
		query.append("            #if(${f_cust_tp} != 'S')   " ).append("\n"); 
		query.append("                 ,D.CUST_GRP_ID         -- CONTRACT CUSTOMER" ).append("\n"); 
		query.append("                ,D.AGMT_CUST_SEQ" ).append("\n"); 
		query.append("                ,D.AGMT_CNT_CD" ).append("\n"); 
		query.append("            #else           " ).append("\n"); 
		query.append("                ,D.CUST_GRP_ID          -- SHIPPER" ).append("\n"); 
		query.append("                ,D.SHPR_NM" ).append("\n"); 
		query.append("                ,D.SHPR_CUST_SEQ" ).append("\n"); 
		query.append("                ,D.SHPR_CNT_CD" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("		#elseif(${keys} == 'cntr_rcv_dt')" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("            ,D.$keys       " ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("		#if(${vvd_flg} == 'TRUE')" ).append("\n"); 
		query.append("		 , COA_PSG_TS_ARRAY_FNC(D.n1st_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n1st_finc_vvd_cd,substr(D.N1ST_RLANE_CD,1,3),SUBSTR (D.n1st_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n1st_finc_vvd_cd,substr(D.N1ST_RLANE_CD,1,3),SUBSTR (D.n1st_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n1st_rlane_cd, SUBSTR (D.n1st_finc_vvd_cd, 1, 9), D.n1st_pol_cd, D.n1st_pod_cd, --1" ).append("\n"); 
		query.append("                              D.n2nd_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n2nd_finc_vvd_cd,substr(D.N2nd_RLANE_CD,1,3),SUBSTR (D.n2nd_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n2nd_finc_vvd_cd,substr(D.n2nd_RLANE_CD,1,3),SUBSTR (D.n2nd_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n2nd_rlane_cd, SUBSTR (D.n2nd_finc_vvd_cd, 1, 9), D.n2nd_pol_cd, D.n2nd_pod_cd, --2" ).append("\n"); 
		query.append("                              D.n3rd_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n3rd_finc_vvd_cd,substr(D.n3rd_RLANE_CD,1,3),SUBSTR (D.n3rd_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n3rd_finc_vvd_cd,substr(D.n3rd_RLANE_CD,1,3),SUBSTR (D.n3rd_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n3rd_rlane_cd, SUBSTR (D.n3rd_finc_vvd_cd, 1, 9), D.n3rd_pol_cd, D.n3rd_pod_cd, --3" ).append("\n"); 
		query.append("                              D.n4th_trd_cd," ).append("\n"); 
		query.append("                              DECODE (COA_SLAN_CONTI_CONV_FNC(D.n4th_finc_vvd_cd,substr(D.n4th_RLANE_CD,1,3),SUBSTR (D.n4th_ioc_conti_cd, 1, 1))" ).append("\n"); 
		query.append("                                     ,COA_SLAN_CONTI_CONV_FNC(D.n4th_finc_vvd_cd,substr(D.n4th_RLANE_CD,1,3),SUBSTR (D.n4th_ioc_conti_cd, 2, 1)), 'I' ,'O')," ).append("\n"); 
		query.append("                              D.n4th_rlane_cd, SUBSTR (D.n4th_finc_vvd_cd, 1, 9), D.n4th_pol_cd, D.n4th_pod_cd --4" ).append("\n"); 
		query.append("                             )" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("            ,DECODE('${wk_sts}', 'Y', D.COST_YRMON, '', DECODE('${period}', 'M', D.COST_YRMON, ''))" ).append("\n"); 
		query.append("            ,DECODE('${wk_sts}', 'Y', D.SLS_YRMON, '')" ).append("\n"); 
		query.append("            ,DECODE('${wk_sts}', 'Y', D.COST_WK, '')" ).append("\n"); 
		query.append("            ,DECODE('${dir_sts}', 'Y', D.DIR_CD, '')" ).append("\n"); 
		query.append("            ,DECODE('${tpsz_sts}', 'BOX', D.SPCL_CNTR_TPSZ_CD, 'TEU','')" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    )" ).append("\n"); 
		query.append("GROUP BY 1" ).append("\n"); 
		query.append("#if(${f_include_ts} =='Y')" ).append("\n"); 
		query.append("       , ts_sts     " ).append("\n"); 
		query.append("#end      " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#foreach(${keys} IN ${keyList4})" ).append("\n"); 
		query.append("    #if (${keys} == 'obrd_dt' )" ).append("\n"); 
		query.append("            ,TO_CHAR($keys,'YYYY-MM-DD')" ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,1,3) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,29,3) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,57,3) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,85,3) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_trd_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,113,3) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,5,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,33,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,61,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,89,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_rlane_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,117,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,10,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,10,9)) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,38,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,38,9)) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,66,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,66,9)) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,94,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,94,9)) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_finc_vvd_cd')" ).append("\n"); 
		query.append("      , DECODE(SUBSTR(VVD_INFO,122,9),'XXXXXXXXX','',SUBSTR(VVD_INFO,122,9)) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,19,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,47,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,75,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,103,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_pol_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,131,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n1st_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,24,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n2nd_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,52,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n3rd_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,80,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n4th_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,108,5) " ).append("\n"); 
		query.append("	#elseif(${keys} == 'n5th_pod_cd')" ).append("\n"); 
		query.append("      , SUBSTR(VVD_INFO,136,5) 	" ).append("\n"); 
		query.append("	#elseif(${keys} == 'fixed_rate_flag')" ).append("\n"); 
		query.append("	  , fx_rt_flg" ).append("\n"); 
		query.append("    #else" ).append("\n"); 
		query.append("            ,$keys" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("            ,COST_YRMON" ).append("\n"); 
		query.append("            ,SLS_YRMON" ).append("\n"); 
		query.append("            ,COST_WK" ).append("\n"); 
		query.append("            ,DIR_CD2" ).append("\n"); 
		query.append("            ,TPSZ_CODE" ).append("\n"); 

	}
}