/*=========================================================
*Copyright(c) 2010 CyberLogitec
*@FileName : BlRatingDBDAOSearchScInformListRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2010.04.07
*@LastModifier : 김태경
*@LastVersion : 1.0
* 2010.04.07 김태경
* 1.0 Creation
=========================================================*/
package com.clt.apps.opus.esm.bkg.outbounddocumentation.blrating.blrating.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;

import com.clt.framework.support.db.ISQLTemplate;

/**
 *
 * @author kim tae kyoung
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class BlRatingDBDAOSearchScInformListRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * SearchScInformList
	  * </pre>
	  */
	public BlRatingDBDAOSearchScInformListRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		query.append("/*").append("\n"); 
		query.append("Path : com.clt.apps.opus.esm.bkg.outbounddocumentation.blrating.blrating.integration").append("\n"); 
		query.append("FileName : BlRatingDBDAOSearchScInformListRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("/* 강제로 SearchScOftAutoratingListVO 만듬 */" ).append("\n"); 
		query.append("#if(${rate_type} =='SC')" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("   /* UI Basic */" ).append("\n"); 
		query.append("    '' RT_MTCH_PATT_CD," ).append("\n"); 
		query.append("    '' CMDT_NM," ).append("\n"); 
		query.append("    '' POR_CD," ).append("\n"); 
		query.append("    '' POL_CD," ).append("\n"); 
		query.append("    '' POD_CD," ).append("\n"); 
		query.append("    '' DEL_CD," ).append("\n"); 
		query.append("    '' DIR_CALL_FLG," ).append("\n"); 
		query.append("    '' RCV_DE_TERM_CD," ).append("\n"); 
		query.append("    '' DE_TERM_CD," ).append("\n"); 
		query.append("    '' RAT_UT_CD," ).append("\n"); 
		query.append("    '' PRC_CGO_TP_CD," ).append("\n"); 
		query.append("    '' CURR_CD," ).append("\n"); 
		query.append("    '' ORG_TRSP_MOD_CD," ).append("\n"); 
		query.append("    '' DEST_TRSP_MOD_CD," ).append("\n"); 
		query.append("    '' FNL_FRT_RT_AMT," ).append("\n"); 
		query.append("    '' TRNS_MOD_CD," ).append("\n"); 
		query.append("    '' OP_CNTR_QTY," ).append("\n"); 
		query.append("    '' NOTE_CTNT," ).append("\n"); 
		query.append("    '' DTL," ).append("\n"); 
		query.append("    '' NOTE," ).append("\n"); 
		query.append("    /* Ori IHC */" ).append("\n"); 
		query.append("    '' OI_ROUT_PNT_LOC_DEF_CD," ).append("\n"); 
		query.append("    '' OI_BSE_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' OI_VIA_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' OI_DIR_CALL_FLG," ).append("\n"); 
		query.append("    '' OI_RAT_UT_CD," ).append("\n"); 
		query.append("    '' OI_PRC_CGO_TP_CD," ).append("\n"); 
		query.append("    '' OI_PRC_TRSP_MOD_CD," ).append("\n"); 
		query.append("    '' OI_RCV_DE_TERM_CD," ).append("\n"); 
		query.append("    '' OI_PRC_CMDT_DEF_CD," ).append("\n"); 
		query.append("    '' OI_CURR_CD," ).append("\n"); 
		query.append("    '' OI_FNL_FRT_RT_AMT," ).append("\n"); 
		query.append("    /* Ori ARB */" ).append("\n"); 
		query.append("    '' OA_ROUT_PNT_LOC_DEF_CD," ).append("\n"); 
		query.append("    '' OA_BSE_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' OA_VIA_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' OA_DIR_CALL_FLG," ).append("\n"); 
		query.append("    '' OA_RAT_UT_CD," ).append("\n"); 
		query.append("    '' OA_PRC_CGO_TP_CD," ).append("\n"); 
		query.append("    '' OA_PRC_TRSP_MOD_CD," ).append("\n"); 
		query.append("    '' OA_RCV_DE_TERM_CD," ).append("\n"); 
		query.append("    '' OA_PRC_CMDT_DEF_CD," ).append("\n"); 
		query.append("    '' OA_CURR_CD," ).append("\n"); 
		query.append("    '' OA_FNL_FRT_RT_AMT," ).append("\n"); 
		query.append("    /* Dest ARB */" ).append("\n"); 
		query.append("    '' DA_ROUT_PNT_LOC_DEF_CD," ).append("\n"); 
		query.append("    '' DA_BSE_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' DA_VIA_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' DA_DIR_CALL_FLG," ).append("\n"); 
		query.append("    '' DA_RAT_UT_CD," ).append("\n"); 
		query.append("    '' DA_PRC_CGO_TP_CD," ).append("\n"); 
		query.append("    '' DA_PRC_TRSP_MOD_CD," ).append("\n"); 
		query.append("    '' DA_RCV_DE_TERM_CD," ).append("\n"); 
		query.append("    '' DA_PRC_CMDT_DEF_CD," ).append("\n"); 
		query.append("    '' DA_CURR_CD," ).append("\n"); 
		query.append("    '' DA_FNL_FRT_RT_AMT," ).append("\n"); 
		query.append("    /* Dest IHC */" ).append("\n"); 
		query.append("    '' DI_ROUT_PNT_LOC_DEF_CD," ).append("\n"); 
		query.append("    '' DI_BSE_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' DI_VIA_PORT_DEF_CD," ).append("\n"); 
		query.append("    '' DI_DIR_CALL_FLG," ).append("\n"); 
		query.append("    '' DI_RAT_UT_CD," ).append("\n"); 
		query.append("    '' DI_PRC_CGO_TP_CD," ).append("\n"); 
		query.append("    '' DI_PRC_TRSP_MOD_CD," ).append("\n"); 
		query.append("    '' DI_RCV_DE_TERM_CD," ).append("\n"); 
		query.append("    '' DI_PRC_CMDT_DEF_CD," ).append("\n"); 
		query.append("    '' DI_CURR_CD," ).append("\n"); 
		query.append("    '' DI_FNL_FRT_RT_AMT," ).append("\n"); 
		query.append("    /* SurCharge */" ).append("\n"); 
		query.append("    '' CHG_CD," ).append("\n"); 
		query.append("    '' CHG_UT_AMT," ).append("\n"); 
		query.append("    '' FRT_RT_AMT," ).append("\n"); 
		query.append("    '' RAT_AS_QTY," ).append("\n"); 
		query.append("    '' CHG_AMT," ).append("\n"); 
		query.append("    '' INCL_OFT_FLG," ).append("\n"); 
		query.append("    '' FRT_TERM_CD," ).append("\n"); 
		query.append("    '' CGO_TP_CD," ).append("\n"); 
		query.append("    '' PRC_HNGR_BAR_TP_CD," ).append("\n"); 
		query.append("    '' IN_GA_FLG," ).append("\n"); 
		query.append("    '' CNTR_WGT," ).append("\n"); 
		query.append("    /* Save SurCharge Column */" ).append("\n"); 
		query.append("    '' BKG_NO," ).append("\n"); 
		query.append("    '' USR_ID," ).append("\n"); 
		query.append("    '' CNTR_TPSZ_CD," ).append("\n"); 
		query.append("    '' CTRT_CNTR_TPSZ_CD," ).append("\n"); 
		query.append("    '' RCV_TERM_CD," ).append("\n"); 
		query.append("    '' DRY_CGO_FLG," ).append("\n"); 
		query.append("    '' AWK_CGO_FLG," ).append("\n"); 
		query.append("    '' DCGO_FLG," ).append("\n"); 
		query.append("    '' RC_FLG," ).append("\n"); 
		query.append("    '' BB_CGO_FLG," ).append("\n"); 
		query.append("    '' SOC_FLG," ).append("\n"); 
		query.append("    '' IMDG_CLSS_CD," ).append("\n"); 
		query.append("    '' PROP_NO," ).append("\n"); 
		query.append("    '' AMDT_SEQ," ).append("\n"); 
		query.append("    '' SVC_SCP_CD," ).append("\n"); 
		query.append("    '' PRC_GEN_SPCL_RT_TP_CD," ).append("\n"); 
		query.append("    '' PRC_CMDT_HDR_SEQ," ).append("\n"); 
		query.append("    '' PRC_ROUT_SEQ," ).append("\n"); 
		query.append("    '' PRC_RT_SEQ," ).append("\n"); 
		query.append("    /* Amout 로직 필요 Column */" ).append("\n"); 
		query.append("	'' RT_PRC_CGO_TP_CD," ).append("\n"); 
		query.append("    '' RT_FNL_FRT_RT_AMT ," ).append("\n"); 
		query.append("    '' RT_RAP_BKG_CONV_TP_CD      ,    " ).append("\n"); 
		query.append("    '' RT_RAP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_RAP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_RAP_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_RAP_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_RAP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' RT_RAR_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_RAR_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_RAR_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_RAR_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_RAR_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_RAR_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' RT_DOR_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_DOR_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_DOR_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_DOR_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_DOR_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_DOR_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' RT_TYP_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_TYP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_TYP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_TYP_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_TYP_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_TYP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' RT_APP_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_APP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_APP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_APP_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_APP_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_APP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' RT_RAS_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_RAS_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_RAS_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_RAS_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_RAS_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_RAS_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' RT_ARB_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_ARB_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_ARB_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_ARB_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_ARB_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_ARB_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' RT_ADD_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_ADD_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_ADD_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_ADD_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_ADD_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_ADD_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' OA_RAP_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' OA_RAP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' OA_RAP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' OA_RAP_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' OA_RAP_CURR_CD             ," ).append("\n"); 
		query.append("    '' OA_RAP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' OA_RAR_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' OA_RAR_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' OA_RAR_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' OA_RAR_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' OA_RAR_CURR_CD             ," ).append("\n"); 
		query.append("    '' OA_RAR_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' OA_DOR_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' OA_DOR_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' OA_DOR_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' OA_DOR_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' OA_DOR_CURR_CD             ," ).append("\n"); 
		query.append("    '' OA_DOR_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' OA_TYP_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' OA_TYP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' OA_TYP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' OA_TYP_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' OA_TYP_CURR_CD             ," ).append("\n"); 
		query.append("    '' OA_TYP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' DA_RAP_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' DA_RAP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' DA_RAP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' DA_RAP_DA_OP_CD            ," ).append("\n"); 
		query.append("    '' DA_RAP_CURR_CD             ," ).append("\n"); 
		query.append("    '' DA_RAP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' DA_RAR_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' DA_RAR_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' DA_RAR_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' DA_RAR_DA_OP_CD            ," ).append("\n"); 
		query.append("    '' DA_RAR_CURR_CD             ," ).append("\n"); 
		query.append("    '' DA_RAR_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' DA_DOR_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' DA_DOR_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' DA_DOR_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' DA_DOR_DA_OP_CD            ," ).append("\n"); 
		query.append("    '' DA_DOR_CURR_CD             ," ).append("\n"); 
		query.append("    '' DA_DOR_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' DA_TYP_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' DA_TYP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' DA_TYP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' DA_TYP_DA_OP_CD            ," ).append("\n"); 
		query.append("    '' DA_TYP_CURR_CD             ," ).append("\n"); 
		query.append("    '' DA_TYP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("    '' OA_RAC_BKG_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' OA_RAC_NOTE_CONV_SEQ      ," ).append("\n"); 
		query.append("    '' OA_RAC_NOTE_CONV_TP_CD    ," ).append("\n"); 
		query.append("    '' OA_RAC_RT_OP_CD           ," ).append("\n"); 
		query.append("    '' OA_RAC_CURR_CD            ," ).append("\n"); 
		query.append("    '' OA_RAC_FRT_RT_AMT         ," ).append("\n"); 
		query.append("    '' RT_RAC_BKG_CONV_TP_CD,     " ).append("\n"); 
		query.append("    '' RT_RAC_NOTE_CONV_SEQ      ," ).append("\n"); 
		query.append("    '' RT_RAC_NOTE_CONV_TP_CD    ," ).append("\n"); 
		query.append("    '' RT_RAC_RT_OP_CD           ," ).append("\n"); 
		query.append("    '' RT_RAC_CURR_CD            ," ).append("\n"); 
		query.append("    '' RT_RAC_FRT_RT_AMT         ," ).append("\n"); 
		query.append("    '' DA_RAC_BKG_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' DA_RAC_NOTE_CONV_SEQ      ," ).append("\n"); 
		query.append("    '' DA_RAC_NOTE_CONV_TP_CD    ," ).append("\n"); 
		query.append("    '' DA_RAC_DA_OP_CD           ," ).append("\n"); 
		query.append("    '' DA_RAC_CURR_CD            ," ).append("\n"); 
		query.append("    '' DA_RAC_FRT_RT_AMT		 ," ).append("\n"); 
		query.append("    '' RT_RAT_UT_CD				 ," ).append("\n"); 
		query.append("	'' OP_ROUT_PNT_LOC_DEF_CD	 ," ).append("\n"); 
		query.append("	'' OV_ROUT_VIA_PORT_DEF_CD	 ," ).append("\n"); 
		query.append("	'' DV_ROUT_VIA_PORT_DEF_CD	 ," ).append("\n"); 
		query.append("	'' DP_ROUT_PNT_LOC_DEF_CD    ," ).append("\n"); 
		query.append("	'' RT_APLY_DT				 ," ).append("\n"); 
		query.append("	'' PCT_BSE_CD				 ," ).append("\n"); 
		query.append("	'' CNT						 ," ).append("\n"); 
		query.append("	'' POR_MTCH_FLG 			 ," ).append("\n"); 
		query.append("	'' DEL_MTCH_FLG				 ," ).append("\n"); 
		query.append("	'' RT_CALC_FRT_RT_AMT		 ," ).append("\n"); 
		query.append("	'' OI_CALC_FRT_RT_AMT		 ," ).append("\n"); 
		query.append("	'' OA_CALC_FRT_RT_AMT		 ," ).append("\n"); 
		query.append("	'' DA_CALC_FRT_RT_AMT		 ," ).append("\n"); 
		query.append("	'' DI_CALC_FRT_RT_AMT		 ," ).append("\n"); 
		query.append("	'' OFT_CMB_SEQ				 ," ).append("\n"); 
		query.append("	'' RT_RAP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAR_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_DOR_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAC_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAS_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' OA_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' OA_RAC_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' DA_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' DA_RAC_CONV_CTNT	," ).append("\n"); 
		query.append("	'' FRT_INCL_XCLD_DIV_CD," ).append("\n"); 
		query.append("	'' DP_SEQ," ).append("\n"); 
		query.append("	'' POR_MTCH_FLG," ).append("\n"); 
		query.append("	'' DEL_MTCH_FLG," ).append("\n"); 
		query.append("	'' POR_CNT_CD," ).append("\n"); 
		query.append("	'' DEL_CNT_CD," ).append("\n"); 
		query.append("	'' CGO_CATE_CD," ).append("\n"); 
		query.append("	'' TRI_PROP_NO," ).append("\n"); 
		query.append("	'' EQ_SUBST_CNTR_TPSZ_CD" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='SURCHARG')" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("    '' CHG_CD," ).append("\n"); 
		query.append("    '' CHG_UT_AMT," ).append("\n"); 
		query.append("    '' FRT_RT_AMT," ).append("\n"); 
		query.append("    '' RAT_AS_QTY," ).append("\n"); 
		query.append("    '' RAT_UT_CD," ).append("\n"); 
		query.append("    '' CHG_AMT," ).append("\n"); 
		query.append("    '' INCL_OFT_FLG," ).append("\n"); 
		query.append("    '' FRT_TERM_CD," ).append("\n"); 
		query.append("    '' CGO_TP_CD," ).append("\n"); 
		query.append("    '' RCV_TERM_CD," ).append("\n"); 
		query.append("    '' DE_TERM_CD," ).append("\n"); 
		query.append("    '' IMDG_CLSS_CD," ).append("\n"); 
		query.append("    '' SOC_FLG," ).append("\n"); 
		query.append("    '' PRC_HNGR_BAR_TP_CD," ).append("\n"); 
		query.append("    '' IN_GA_FLG," ).append("\n"); 
		query.append("    '' CNTR_WGT" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("/* SearchSurchargePercentBaseChargeListVO */ " ).append("\n"); 
		query.append("#elseif(${rate_type} =='CODE')" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' PCT_BSE_CD," ).append("\n"); 
		query.append("	'' CHG_CD" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='AMT')" ).append("\n"); 
		query.append("/* SearchSurchargeOftFrightListVO */" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("	'' BKG_NO," ).append("\n"); 
		query.append("	'' OFT_CMB_SEQ," ).append("\n"); 
		query.append("	'' OFRT_SEQ," ).append("\n"); 
		query.append("	'' CHG_CD," ).append("\n"); 
		query.append("	'' CHG_UT_AMT," ).append("\n"); 
		query.append("	'' CURR_CD," ).append("\n"); 
		query.append("	'' CHG_AMT," ).append("\n"); 
		query.append("	'' RAT_AS_QTY," ).append("\n"); 
		query.append("	'' MAX_OFT_CMB_SEQ," ).append("\n"); 
		query.append("	'' MAX_OFRT_SEQ," ).append("\n"); 
		query.append("	'' SUM_AMOUNT" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='RFA')" ).append("\n"); 
		query.append("/* SearchRfaOftAutoratingListVO */" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' CTRT_NO				," ).append("\n"); 
		query.append("	'' PRC_RT_MTCH_PATT_CD	        ," ).append("\n"); 
		query.append("	'' PROP_NO			        ," ).append("\n"); 
		query.append("	'' AMDT_SEQ		        ," ).append("\n"); 
		query.append("	'' SVC_SCP_CD		        ," ).append("\n"); 
		query.append("	'' BQ_SEQ			        ," ).append("\n"); 
		query.append("	'' BKG_BQ_SEQ		        ," ).append("\n"); 
		query.append("	 	/* BKG_AUTO_RT_OCN_FRT_TMP 에 임시 저장할 칼럼 START */" ).append("\n"); 
		query.append("	'' CNTR_TPSZ_CD		        ," ).append("\n"); 
		query.append("	'' CTRT_CNTR_TPSZ_CD	        ," ).append("\n"); 
		query.append("	'' RCV_TERM_CD		        ," ).append("\n"); 
		query.append("	'' DE_TERM_CD		        ," ).append("\n"); 
		query.append("	'' DRY_CGO_FLG		        ," ).append("\n"); 
		query.append("	'' AWK_CGO_FLG		        ," ).append("\n"); 
		query.append("	'' DCGO_FLG		        ," ).append("\n"); 
		query.append("	'' RC_FLG		        ," ).append("\n"); 
		query.append("	'' BB_CGO_FLG		        ," ).append("\n"); 
		query.append("	'' SOC_FLG		        ," ).append("\n"); 
		query.append("	'' IMDG_CLSS_CD		        ," ).append("\n"); 
		query.append("	'' CMDT_HDR_SEQ		        ," ).append("\n"); 
		query.append("	'' ROUT_SEQ		        ," ).append("\n"); 
		query.append("	'' RT_SEQ		        ," ).append("\n"); 
		query.append("	 	/* BKG_AUTO_RT_OCN_FRT_TMP 에 임시 저장할 칼럼 END */" ).append("\n"); 
		query.append("	                                " ).append("\n"); 
		query.append("	 	/* UI GRID START */    " ).append("\n"); 
		query.append("	'' RT_MTCH_PATT_CD		," ).append("\n"); 
		query.append("	'' CMDT_NM				," ).append("\n"); 
		query.append("	'' POR_CD				," ).append("\n"); 
		query.append("	'' POL_CD				," ).append("\n"); 
		query.append("	'' POD_CD				," ).append("\n"); 
		query.append("	'' DEL_CD				," ).append("\n"); 
		query.append("	'' RCV_DE_TERM_CD	                ," ).append("\n"); 
		query.append("	'' RAT_UT_CD		        ," ).append("\n"); 
		query.append("	'' PRC_CGO_TP_CD			," ).append("\n"); 
		query.append("	'' CURR_CD				," ).append("\n"); 
		query.append("	'' ORG_TRSP_MOD_CD			," ).append("\n"); 
		query.append("	'' DEST_TRSP_MOD_CD		," ).append("\n"); 
		query.append("	'' FNL_FRT_RT_AMT			," ).append("\n"); 
		query.append("	'' TRNS_MOD_CD		        ," ).append("\n"); 
		query.append("	'' OP_CNTR_QTY			,				" ).append("\n"); 
		query.append("	'' NOTE_CTNT			,				" ).append("\n"); 
		query.append("	'' NOTE				,						" ).append("\n"); 
		query.append("	'' DTL				,						" ).append("\n"); 
		query.append("	 /* UI GRID END */              " ).append("\n"); 
		query.append("	 " ).append("\n"); 
		query.append("	 /* CHARGE UI 에 필요 속성 START */" ).append("\n"); 
		query.append("	'' CGO_CATE_CD			,					" ).append("\n"); 
		query.append("	 /* CHARGE UI 에 필요 속성 END */                        " ).append("\n"); 
		query.append("	'' BQ_POR_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_POL_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_POD_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_DEL_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_POR_RLY_PORT_APPL_FLG	," ).append("\n"); 
		query.append("	'' BQ_PST_RLY_PORT_APPL_FLG        ," ).append("\n"); 
		query.append("	'' OA_ADD_CHG_SEQ		        ," ).append("\n"); 
		query.append("	'' DA_ADD_CHG_SEQ		        ," ).append("\n"); 
		query.append("	'' CM_PRC_CMDT_TP_CD	        ," ).append("\n"); 
		query.append("	'' CM_PRC_CMDT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' RCV_TERM_CD		        ," ).append("\n"); 
		query.append("	'' DE_TERM_CD		        ," ).append("\n"); 
		query.append("	'' OP_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OV_ROUT_VIA_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DV_ROUT_VIA_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DP_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OP_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' DP_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' RT_RAT_UT_CD		        ," ).append("\n"); 
		query.append("	" ).append("\n"); 
		query.append("	'' RT_PRC_CGO_TP_CD	        ," ).append("\n"); 
		query.append("	'' RT_CURR_CD		        ," ).append("\n"); 
		query.append("	'' RT_FNL_FRT_RT_AMT	        ," ).append("\n"); 
		query.append("	'' OA_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OA_BSE_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OA_RAT_UT_CD		        ," ).append("\n"); 
		query.append("	'' OA_PRC_CGO_TP_CD	        ," ).append("\n"); 
		query.append("	'' OA_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' OA_RCV_DE_TERM_CD	        ," ).append("\n"); 
		query.append("	'' OA_CURR_CD		        ," ).append("\n"); 
		query.append("	'' OA_FNL_FRT_RT_AMT	        ," ).append("\n"); 
		query.append("	'' DA_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DA_BSE_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DA_RAT_UT_CD		        ," ).append("\n"); 
		query.append("	'' DA_PRC_CGO_TP_CD	        ," ).append("\n"); 
		query.append("	'' DA_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' DA_RCV_DE_TERM_CD	        ," ).append("\n"); 
		query.append("	'' DA_CURR_CD		        ," ).append("\n"); 
		query.append("	'' DA_FNL_FRT_RT_AMT	        ," ).append("\n"); 
		query.append("	'' RT_APP_BKG_CONV_TP_CD           ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_MAPG_ID        ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_SEQ            ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_RULE_CD        ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_TP_CD          ," ).append("\n"); 
		query.append("	'' RT_APP_RT_OP_CD                 ," ).append("\n"); 
		query.append("	'' RT_APP_CURR_CD                  ," ).append("\n"); 
		query.append("	'' RT_APP_FRT_RT_AMT               ," ).append("\n"); 
		query.append("	'' RT_RAS_BKG_CONV_TP_CD           ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_MAPG_ID        ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_SEQ            ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_RULE_CD        ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_TP_CD          ," ).append("\n"); 
		query.append("	'' RT_RAS_RT_OP_CD                 ," ).append("\n"); 
		query.append("	'' RT_RAS_CURR_CD                  ," ).append("\n"); 
		query.append("	'' RT_RAS_FRT_RT_AMT	           ," ).append("\n"); 
		query.append("	'' POR_MTCH_FLG		        	  ," ).append("\n"); 
		query.append("	'' DEL_MTCH_FLG		        ," ).append("\n"); 
		query.append("	'' OIH_FLG				," ).append("\n"); 
		query.append("	'' DIH_FLG         		," ).append("\n"); 
		query.append("    '' CHG_CD," ).append("\n"); 
		query.append("    '' CHG_UT_AMT," ).append("\n"); 
		query.append("    '' FRT_RT_AMT," ).append("\n"); 
		query.append("    '' RAT_AS_QTY," ).append("\n"); 
		query.append("    '' CHG_AMT," ).append("\n"); 
		query.append("    '' INCL_OFT_FLG," ).append("\n"); 
		query.append("    '' FRT_TERM_CD," ).append("\n"); 
		query.append("    '' CGO_TP_CD," ).append("\n"); 
		query.append("    '' PRC_HNGR_BAR_TP_CD," ).append("\n"); 
		query.append("    '' IN_GA_FLG," ).append("\n"); 
		query.append("    '' CNTR_WGT," ).append("\n"); 
		query.append("	'' BKG_NO," ).append("\n"); 
		query.append("	'' PRC_GEN_SPCL_RT_TP_CD," ).append("\n"); 
		query.append("	'' PRC_CMDT_HDR_SEQ," ).append("\n"); 
		query.append("	'' PRC_ROUT_SEQ," ).append("\n"); 
		query.append("	'' PRC_RT_SEQ," ).append("\n"); 
		query.append("	'' RT_CALC_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' OA_CALC_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' DA_CALC_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' BKG_BQ_OCCR_SEQ," ).append("\n"); 
		query.append("	'' OFT_CMB_SEQ," ).append("\n"); 
		query.append("	'' RT_RAP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAR_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_DOR_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAC_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAS_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' OA_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' OA_RAC_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' DA_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' DA_RAC_CONV_CTNT	," ).append("\n"); 
		query.append("	'' OA_MIN_CGO_WGT," ).append("\n"); 
		query.append("	'' OA_MAX_CGO_WGT," ).append("\n"); 
		query.append("	'' DA_MIN_CGO_WGT," ).append("\n"); 
		query.append("	'' DA_MAX_CGO_WGT," ).append("\n"); 
		query.append("	'' FRT_INCL_XCLD_DIV_CD," ).append("\n"); 
		query.append("	'' RT_RAS_CONV_CTNT," ).append("\n"); 
		query.append("	'' DP_SEQ," ).append("\n"); 
		query.append("	'' POR_CNT_CD," ).append("\n"); 
		query.append("	'' DEL_CNT_CD," ).append("\n"); 
		query.append("	'' CGO_CATE_CD," ).append("\n"); 
		query.append("	'' EQ_SUBST_CNTR_TPSZ_CD" ).append("\n"); 
		query.append("	FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='ETC')" ).append("\n"); 
		query.append("/* RateQtyVO */" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' IB_FLAG," ).append("\n"); 
		query.append("	'' CNTR_TPSZ_CD," ).append("\n"); 
		query.append("	'' QTY," ).append("\n"); 
		query.append("	'' CGO," ).append("\n"); 
		query.append("	'' PAGEROWS," ).append("\n"); 
		query.append("	'' EQ_SUB," ).append("\n"); 
		query.append("	'' EQ_SUB_QTY" ).append("\n"); 
		query.append("	FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='VO')" ).append("\n"); 
		query.append("/* ScOftAutoratingListVO */" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' BKG_NO," ).append("\n"); 
		query.append("	'' CA_FLG," ).append("\n"); 
		query.append("	'' SCPCD," ).append("\n"); 
		query.append("	'' CMDT_CD," ).append("\n"); 
		query.append("	'' CTRT_TP_CD," ).append("\n"); 
		query.append("	'' RT_APLY_DT," ).append("\n"); 
		query.append("	'' FNL_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' RT_AUD_TP_CD" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='SCNOTEOUT')" ).append("\n"); 
		query.append("/* ScNoteOutVO */" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' CONTENT," ).append("\n"); 
		query.append("	'' TITLE," ).append("\n"); 
		query.append("	'' FROMDATE," ).append("\n"); 
		query.append("	'' TODATE," ).append("\n"); 
		query.append("	'' SEQ," ).append("\n"); 
		query.append("	'' TODATE," ).append("\n"); 
		query.append("	'' TYPE," ).append("\n"); 
		query.append("	'' EFFECT_DT," ).append("\n"); 
		query.append("	'' EXPIRE_DT" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='SCNOTEIN')" ).append("\n"); 
		query.append("/* ScNoteInVO */" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' BKG_NO," ).append("\n"); 
		query.append("	'' SC_NO," ).append("\n"); 
		query.append("	'' SVC_SCP_CD," ).append("\n"); 
		query.append("	'' NOTE_RT_SEQ," ).append("\n"); 
		query.append("	'' PROP_NO," ).append("\n"); 
		query.append("	'' AMDT_SEQ," ).append("\n"); 
		query.append("	'' GEN_SPCL_RT_TP_CD," ).append("\n"); 
		query.append("	'' CMDT_HDR_SEQ," ).append("\n"); 
		query.append("	'' ROUT_SEQ," ).append("\n"); 
		query.append("	'' APPLICATION_DATE," ).append("\n"); 
		query.append("	'' START_APPLICATIONDATE," ).append("\n"); 
		query.append("	'' END_APPLICATIONDATE," ).append("\n"); 
		query.append("	'' NOTE_CHG_TP_CD	" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='TAA')" ).append("\n"); 
		query.append("/* SearchTaaOftAutoratingListVO */ " ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' CTRT_NO				," ).append("\n"); 
		query.append("	'' PRC_RT_MTCH_PATT_CD	        ," ).append("\n"); 
		query.append("	'' PROP_NO			        ," ).append("\n"); 
		query.append("	'' AMDT_SEQ		        ," ).append("\n"); 
		query.append("	'' SVC_SCP_CD		        ," ).append("\n"); 
		query.append("	'' BQ_SEQ			        ," ).append("\n"); 
		query.append("	'' BKG_BQ_SEQ		        ," ).append("\n"); 
		query.append("	 	/* BKG_AUTO_RT_OCN_FRT_TMP 에 임시 저장할 칼럼 START */" ).append("\n"); 
		query.append("	'' CNTR_TPSZ_CD		        ," ).append("\n"); 
		query.append("	'' CTRT_CNTR_TPSZ_CD	        ," ).append("\n"); 
		query.append("	'' RCV_TERM_CD		        ," ).append("\n"); 
		query.append("	'' DE_TERM_CD		        ," ).append("\n"); 
		query.append("	'' DRY_CGO_FLG		        ," ).append("\n"); 
		query.append("	'' AWK_CGO_FLG		        ," ).append("\n"); 
		query.append("	'' DCGO_FLG		        ," ).append("\n"); 
		query.append("	'' RC_FLG		        ," ).append("\n"); 
		query.append("	'' BB_CGO_FLG		        ," ).append("\n"); 
		query.append("	'' SOC_FLG		        ," ).append("\n"); 
		query.append("	'' IMDG_CLSS_CD		        ," ).append("\n"); 
		query.append("	'' CMDT_HDR_SEQ		        ," ).append("\n"); 
		query.append("	'' ROUT_SEQ		        ," ).append("\n"); 
		query.append("	'' RT_SEQ		        ," ).append("\n"); 
		query.append("	 	/* BKG_AUTO_RT_OCN_FRT_TMP 에 임시 저장할 칼럼 END */" ).append("\n"); 
		query.append("	                                " ).append("\n"); 
		query.append("	 	/* UI GRID START */    " ).append("\n"); 
		query.append("	'' RT_MTCH_PATT_CD		," ).append("\n"); 
		query.append("	'' CMDT_NM				," ).append("\n"); 
		query.append("	'' POR_CD				," ).append("\n"); 
		query.append("	'' POL_CD				," ).append("\n"); 
		query.append("	'' POD_CD				," ).append("\n"); 
		query.append("	'' DEL_CD				," ).append("\n"); 
		query.append("	'' RCV_DE_TERM_CD	                ," ).append("\n"); 
		query.append("	'' RAT_UT_CD		        ," ).append("\n"); 
		query.append("	'' PRC_CGO_TP_CD			," ).append("\n"); 
		query.append("	'' CURR_CD				," ).append("\n"); 
		query.append("	'' ORG_TRSP_MOD_CD			," ).append("\n"); 
		query.append("	'' DEST_TRSP_MOD_CD		," ).append("\n"); 
		query.append("	'' FNL_FRT_RT_AMT			," ).append("\n"); 
		query.append("	'' TRNS_MOD_CD		        ," ).append("\n"); 
		query.append("	'' OP_CNTR_QTY			,				" ).append("\n"); 
		query.append("	'' NOTE_CTNT			,				" ).append("\n"); 
		query.append("	'' NOTE				,						" ).append("\n"); 
		query.append("	'' DTL				,						" ).append("\n"); 
		query.append("	 /* UI GRID END */              " ).append("\n"); 
		query.append("	 " ).append("\n"); 
		query.append("	 /* CHARGE UI 에 필요 속성 START */" ).append("\n"); 
		query.append("	'' CGO_CATE_CD			,					" ).append("\n"); 
		query.append("	 /* CHARGE UI 에 필요 속성 END */                        " ).append("\n"); 
		query.append("	'' BQ_POR_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_POL_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_POD_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_DEL_APPL_FLG		        ,                                                " ).append("\n"); 
		query.append("	'' BQ_POR_RLY_PORT_APPL_FLG	," ).append("\n"); 
		query.append("	'' BQ_PST_RLY_PORT_APPL_FLG        ," ).append("\n"); 
		query.append("	'' OA_ADD_CHG_SEQ		        ," ).append("\n"); 
		query.append("	'' DA_ADD_CHG_SEQ		        ," ).append("\n"); 
		query.append("	'' CM_PRC_CMDT_TP_CD	        ," ).append("\n"); 
		query.append("	'' CM_PRC_CMDT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' RCV_TERM_CD		        ," ).append("\n"); 
		query.append("	'' DE_TERM_CD		        ," ).append("\n"); 
		query.append("	'' OP_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OV_ROUT_VIA_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DV_ROUT_VIA_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DP_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OP_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' DP_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' RT_RAT_UT_CD		        ," ).append("\n"); 
		query.append("	" ).append("\n"); 
		query.append("	'' RT_PRC_CGO_TP_CD	        ," ).append("\n"); 
		query.append("	'' RT_CURR_CD		        ," ).append("\n"); 
		query.append("	'' RT_FNL_FRT_RT_AMT	        ," ).append("\n"); 
		query.append("	'' OA_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OA_BSE_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' OA_RAT_UT_CD		        ," ).append("\n"); 
		query.append("	'' OA_PRC_CGO_TP_CD	        ," ).append("\n"); 
		query.append("	'' OA_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' OA_RCV_DE_TERM_CD	        ," ).append("\n"); 
		query.append("	'' OA_CURR_CD		        ," ).append("\n"); 
		query.append("	'' OA_FNL_FRT_RT_AMT	        ," ).append("\n"); 
		query.append("	'' DA_ROUT_PNT_LOC_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DA_BSE_PORT_DEF_CD	        ," ).append("\n"); 
		query.append("	'' DA_RAT_UT_CD		        ," ).append("\n"); 
		query.append("	'' DA_PRC_CGO_TP_CD	        ," ).append("\n"); 
		query.append("	'' DA_PRC_TRSP_MOD_CD	        ," ).append("\n"); 
		query.append("	'' DA_RCV_DE_TERM_CD	        ," ).append("\n"); 
		query.append("	'' DA_CURR_CD		        ," ).append("\n"); 
		query.append("	'' DA_FNL_FRT_RT_AMT	        ," ).append("\n"); 
		query.append("	'' RT_APP_BKG_CONV_TP_CD           ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_MAPG_ID        ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_SEQ            ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_RULE_CD        ," ).append("\n"); 
		query.append("	'' RT_APP_NOTE_CONV_TP_CD          ," ).append("\n"); 
		query.append("	'' RT_APP_RT_OP_CD                 ," ).append("\n"); 
		query.append("	'' RT_APP_CURR_CD                  ," ).append("\n"); 
		query.append("	'' RT_APP_FRT_RT_AMT               ," ).append("\n"); 
		query.append("	'' RT_RAS_BKG_CONV_TP_CD           ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_MAPG_ID        ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_SEQ            ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_RULE_CD        ," ).append("\n"); 
		query.append("	'' RT_RAS_NOTE_CONV_TP_CD          ," ).append("\n"); 
		query.append("	'' RT_RAS_RT_OP_CD                 ," ).append("\n"); 
		query.append("	'' RT_RAS_CURR_CD                  ," ).append("\n"); 
		query.append("	'' RT_RAS_FRT_RT_AMT	           ," ).append("\n"); 
		query.append("	'' POR_MTCH_FLG		        	  ," ).append("\n"); 
		query.append("	'' DEL_MTCH_FLG		        ," ).append("\n"); 
		query.append("	'' OIH_FLG				," ).append("\n"); 
		query.append("	'' DIH_FLG         		," ).append("\n"); 
		query.append("    '' CHG_CD," ).append("\n"); 
		query.append("    '' CHG_UT_AMT," ).append("\n"); 
		query.append("    '' FRT_RT_AMT," ).append("\n"); 
		query.append("    '' RAT_AS_QTY," ).append("\n"); 
		query.append("    '' CHG_AMT," ).append("\n"); 
		query.append("    '' INCL_OFT_FLG," ).append("\n"); 
		query.append("    '' FRT_TERM_CD," ).append("\n"); 
		query.append("    '' CGO_TP_CD," ).append("\n"); 
		query.append("    '' PRC_HNGR_BAR_TP_CD," ).append("\n"); 
		query.append("    '' IN_GA_FLG," ).append("\n"); 
		query.append("    '' CNTR_WGT," ).append("\n"); 
		query.append("	'' BKG_NO," ).append("\n"); 
		query.append("	'' PRC_GEN_SPCL_RT_TP_CD," ).append("\n"); 
		query.append("	'' PRC_CMDT_HDR_SEQ," ).append("\n"); 
		query.append("	'' PRC_ROUT_SEQ," ).append("\n"); 
		query.append("	'' PRC_RT_SEQ," ).append("\n"); 
		query.append("	'' RT_CALC_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' OA_CALC_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' DA_CALC_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' BKG_BQ_OCCR_SEQ," ).append("\n"); 
		query.append("	'' OFT_CMB_SEQ," ).append("\n"); 
		query.append("	'' RT_RAP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAR_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_DOR_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAC_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' RT_RAS_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' OA_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' OA_RAC_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' DA_TYP_CONV_CTNT	,		" ).append("\n"); 
		query.append("	'' DA_RAC_CONV_CTNT	," ).append("\n"); 
		query.append("	'' OA_MIN_CGO_WGT," ).append("\n"); 
		query.append("	'' OA_MAX_CGO_WGT," ).append("\n"); 
		query.append("	'' DA_MIN_CGO_WGT," ).append("\n"); 
		query.append("	'' DA_MAX_CGO_WGT," ).append("\n"); 
		query.append("	'' FRT_INCL_XCLD_DIV_CD," ).append("\n"); 
		query.append("	'' RT_RAS_CONV_CTNT," ).append("\n"); 
		query.append("	'' DP_SEQ," ).append("\n"); 
		query.append("	'' POR_CNT_CD," ).append("\n"); 
		query.append("	'' DEL_CNT_CD," ).append("\n"); 
		query.append("    '' RT_TYP_BKG_CONV_TP_CD      ," ).append("\n"); 
		query.append("    '' RT_TYP_NOTE_CONV_SEQ       ," ).append("\n"); 
		query.append("    '' RT_TYP_NOTE_CONV_TP_CD     ," ).append("\n"); 
		query.append("    '' RT_TYP_RT_OP_CD            ," ).append("\n"); 
		query.append("    '' RT_TYP_CURR_CD             ," ).append("\n"); 
		query.append("    '' RT_TYP_FRT_RT_AMT          ," ).append("\n"); 
		query.append("	'' RT_RAC_BKG_CONV_TP_CD	 ,     " ).append("\n"); 
		query.append("    '' RT_RAC_NOTE_CONV_TP_CD    ," ).append("\n"); 
		query.append("    '' RT_RAC_RT_OP_CD           ," ).append("\n"); 
		query.append("    '' RT_RAC_CURR_CD            ," ).append("\n"); 
		query.append("    '' RT_RAC_FRT_RT_AMT         ," ).append("\n"); 
		query.append("	'' TM_CMDT_CD," ).append("\n"); 
		query.append("	'' OP_ROUT_PNT_LOC_CD," ).append("\n"); 
		query.append("	'' OV_ROUT_VIA_PORT_CD," ).append("\n"); 
		query.append("	'' DV_ROUT_VIA_PORT_CD," ).append("\n"); 
		query.append("	'' DP_ROUT_PNT_LOC_CD," ).append("\n"); 
		query.append("	'' TRI_PROP_NO," ).append("\n"); 
		query.append("	'' RT_CALC_FRT_RT_AMT," ).append("\n"); 
		query.append("	'' EQ_SUBST_CNTR_TPSZ_CD" ).append("\n"); 
		query.append("	FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='SCPOP')" ).append("\n"); 
		query.append("/* ScCustInformVO */ " ).append("\n"); 
		query.append("/* RfaCustInformVO */" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' BKG_NO," ).append("\n"); 
		query.append("	'' S_CUST_CNT_CD," ).append("\n"); 
		query.append("	'' S_CUST_SEQ," ).append("\n"); 
		query.append("	'' S_CUST_NM," ).append("\n"); 
		query.append("	'' C_CUST_CNT_CD," ).append("\n"); 
		query.append("	'' C_CUST_SEQ," ).append("\n"); 
		query.append("	'' C_CUST_NM," ).append("\n"); 
		query.append("	'' N_CUST_CNT_CD," ).append("\n"); 
		query.append("	'' N_CUST_SEQ," ).append("\n"); 
		query.append("	'' N_CUST_NM," ).append("\n"); 
		query.append("	'' A_CUST_CNT_CD," ).append("\n"); 
		query.append("	'' A_CUST_SEQ," ).append("\n"); 
		query.append("	'' A_CUST_NM," ).append("\n"); 
		query.append("	'' P_CUST_CNT_CD," ).append("\n"); 
		query.append("	'' P_CUST_SEQ," ).append("\n"); 
		query.append("	'' P_CUST_NM" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#elseif(${rate_type} =='RATESEARCH')" ).append("\n"); 
		query.append("/* RateCntrInfo */" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("	'' BKG_NO," ).append("\n"); 
		query.append("	'' CNTR_NO," ).append("\n"); 
		query.append("	'' CNTR_TPSZ_CD," ).append("\n"); 
		query.append("	'' CNTR_DP_SEQ," ).append("\n"); 
		query.append("	'' RCV_TERM_CD," ).append("\n"); 
		query.append("	'' DE_TERM_CD," ).append("\n"); 
		query.append("	'' CNTR_PRT_FLG," ).append("\n"); 
		query.append("	'' CNTR_VOL_QTY," ).append("\n"); 
		query.append("	'' EQ_SUBST_TPSZ_CD," ).append("\n"); 
		query.append("	'' HNGR_FLG," ).append("\n"); 
		query.append("	'' DCGO_FLG," ).append("\n"); 
		query.append("	'' BB_CGO_FLG," ).append("\n"); 
		query.append("	'' AWK_CGO_FLG," ).append("\n"); 
		query.append("	'' RC_FLG," ).append("\n"); 
		query.append("	'' RD_CGO_FLG," ).append("\n"); 
		query.append("	'' SOC_FLG," ).append("\n"); 
		query.append("	'' DCGO_CNT," ).append("\n"); 
		query.append("	'' FLEX_HGT_FLG" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("'G3' PT" ).append("\n"); 
		query.append(",'GRP02(SEE TERM 3. GRO)' COMMODITY_DESCRIPTION" ).append("\n"); 
		query.append(",'OBSP' POR" ).append("\n"); 
		query.append(",'N/A' POL" ).append("\n"); 
		query.append(",'USLGB' POD" ).append("\n"); 
		query.append(",'USLGB' DEL" ).append("\n"); 
		query.append(",'Y' D_CALL" ).append("\n"); 
		query.append(",'Y/Y' RD" ).append("\n"); 
		query.append(",'D5' PER" ).append("\n"); 
		query.append(",'DR' CGO_TP" ).append("\n"); 
		query.append(",'USD' CUR" ).append("\n"); 
		query.append(",'1654' AMOUNT" ).append("\n"); 
		query.append(",'X/X' TRANS_MODE " ).append("\n"); 
		query.append(",'2' Q_TY" ).append("\n"); 
		query.append(",'DTL' DTL" ).append("\n"); 
		query.append(",'NT' NT_V" ).append("\n"); 
		query.append(",'' NT" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("UNION ALL " ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("'G4' PT" ).append("\n"); 
		query.append(",'BBBP02( TEST 3. TEST)' COMMODITY_DESCRIPTION" ).append("\n"); 
		query.append(",'ODSBSP' POR" ).append("\n"); 
		query.append(",'A/S' POL" ).append("\n"); 
		query.append(",'DDGB' POD" ).append("\n"); 
		query.append(",'FS' DEL" ).append("\n"); 
		query.append(",'Y' D_CALL" ).append("\n"); 
		query.append(",'N/N' RD" ).append("\n"); 
		query.append(",'D5' PER" ).append("\n"); 
		query.append(",'DR' CGO_TP" ).append("\n"); 
		query.append(",'USD' CUR" ).append("\n"); 
		query.append(",'1654' AMOUNT" ).append("\n"); 
		query.append(",'X/X' TRANS_MODE " ).append("\n"); 
		query.append(",'2' Q_TY" ).append("\n"); 
		query.append(",'DTL' DTL" ).append("\n"); 
		query.append(",'NT' NT_V" ).append("\n"); 
		query.append(",'EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE' NT" ).append("\n"); 
		query.append("FROM DUAL" ).append("\n"); 
		query.append("#end" ).append("\n"); 

	}
}