/*=========================================================
*Copyright(c) 2016 CyberLogitec
*@FileName : SurplusAreaDBDAOSearchYardSurplusAreaRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2016.02.19
*@LastModifier : 
*@LastVersion : 1.0
* 2016.02.19 
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.ees.eqr.cntrfcstsimul.surplusarea.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class SurplusAreaDBDAOSearchYardSurplusAreaRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * Surplus Area - Yard 데이터를 조회함
	  * 1. 2015.06.30, YongChan Shin
	  *    RCC (by ECC) - search condition added
	  * 2. - CHM-201537079, 2015-08-10, 신용찬, 표준코드 변환
	  * </pre>
	  */
	public SurplusAreaDBDAOSearchYardSurplusAreaRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("to_yrwk",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("loc_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("curr_yrwk",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("fm_yrwk",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.ees.eqr.cntrfcstsimul.surplusarea.integration").append("\n"); 
		query.append("FileName : SurplusAreaDBDAOSearchYardSurplusAreaRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("WITH  " ).append("\n"); 
		query.append("SIM_TP_CD_DATA AS (" ).append("\n"); 
		query.append("    SELECT 1 GRP_CD, TO_NUMBER('') SORT, 'INN' CODE, 'Initial Inventory' NAME             FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 1 GRP_CD, 1 SORT, 'IV' CODE, 'Inventory' NAME             FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 1 GRP_CD, 2 SORT, 'IM' CODE, 'Inventory Damage' NAME      FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 1 GRP_CD, 3 SORT, 'ID' CODE, 'Inventory Disposal' NAME    FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 1 GRP_CD, 4 SORT, 'IS' CODE, 'Inventory SOC' NAME         FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 2 GRP_CD, 0 SORT, 'INP' CODE, 'Inventory Plus (-)' NAME       	         FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 2 GRP_CD, 1 SORT, 'MG' CODE, 'MG' NAME       	         FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 2 GRP_CD, 2 SORT, 'RD' CODE, 'MT In via VD' NAME          FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 2 GRP_CD, 3 SORT, 'RI' CODE, 'MT In via EN/TN' NAME       FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 2 GRP_CD, 4 SORT, 'OH' CODE, 'On-hire' NAME               FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    #if (${rcc_cd} != 'DEHAM' && ${rcc_cd} != 'SGSIN') -- RCC_CD 가 DEHAM, SGSIN 인 경우 Domestic In 숨김" ).append("\n"); 
		query.append("    SELECT 2 GRP_CD, 5 SORT, 'DI' CODE, 'Domestic In' NAME           FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("    #if (${rcc_cd} != 'DEHAM' && ${rcc_cd} != 'USNYC') -- RCC_CD 가 DEHAM, USNYC 인 경우 Sublease In 숨김" ).append("\n"); 
		query.append("    SELECT 2 GRP_CD, 6 SORT, 'SI' CODE, 'Sublease In' NAME           FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 0 SORT, 'INM' CODE, 'Inventory Minus (-)' NAME       	         FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 1 SORT, 'OP' CODE, 'OP' NAME                    FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 2 SORT, 'RL' CODE, 'MT Out via VL' NAME          FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 3 SORT, 'RO' CODE, 'MT Out via EN/TN' NAME       FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 4 SORT, 'PL' CODE, 'MT Loading Plan' NAME       FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 5 SORT, 'OT' CODE, 'Off-hire / Disposal' NAME   FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 6 SORT, 'DO' CODE, 'Domestic Out' NAME          FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 3 GRP_CD, 7 SORT, 'SO' CODE, 'Sublease Out' NAME          FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 4 GRP_CD, 1 SORT, 'FBB' CODE, 'Final Balance' NAME         FROM DUAL" ).append("\n"); 
		query.append("    #if (${loc_type_code} == '5' || ${loc_type_code} == '6' || ${loc_type_code} == '7')" ).append("\n"); 
		query.append("    UNION ALL " ).append("\n"); 
		query.append("    SELECT 5 GRP_CD, 0 SORT, 'F1' CODE, 'Final Balance vs Target Volume' NAME    FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 5 GRP_CD, 1 SORT, 'F2' CODE, 'Target Vol (OP*Ratio)' NAME    FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 5 GRP_CD, 2 SORT, 'F3' CODE, 'Target Ratio vs OP' NAME    FROM DUAL UNION ALL" ).append("\n"); 
		query.append("    SELECT 5 GRP_CD, 3 SORT, 'F4' CODE, 'PFMC (Final Balance/Target Vol.)' NAME    FROM DUAL" ).append("\n"); 
		query.append("    #end " ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("," ).append("\n"); 
		query.append("SIM_SS_DATA AS (" ).append("\n"); 
		query.append("    SELECT " ).append("\n"); 
		query.append("        S.GRP_CD, S.SORT, S.CODE, S.NAME, Q.LOC_CD" ).append("\n"); 
		query.append("        , Q.CNTR_TPSZ_CD, Q.FCAST_YRWK" ).append("\n"); 
		query.append("        , SUM(NVL(DECODE(Q.INVT_SIM_TP_CD,S.CODE,Q.QTY,0),0)) QTY" ).append("\n"); 
		query.append("        , MAX(NVL(DECODE(Q.INVT_SIM_TP_CD,S.CODE,Q.MNL_INP,''),'')) MNL_INP" ).append("\n"); 
		query.append("    FROM SIM_TP_CD_DATA S, (" ).append("\n"); 
		query.append("        SELECT" ).append("\n"); 
		query.append("        #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("            SUBSTR(Q.YD_CD,1,2)" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '3') --RCC (by LCC)" ).append("\n"); 
		query.append("            B.LCC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("            B.ECC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("            B.SCC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("            B.SCC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("            Q.YD_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '8') --RCC (by ECC)" ).append("\n"); 
		query.append("            B.ECC_CD" ).append("\n"); 
		query.append("        #end    " ).append("\n"); 
		query.append("            LOC_CD" ).append("\n"); 
		query.append("            , Q.INVT_SIM_TP_CD" ).append("\n"); 
		query.append("            , Q.CNTR_TPSZ_CD, Q.FCAST_YRWK" ).append("\n"); 
		query.append("            , SUM(NVL(Q.CNTR_QTY,0)) QTY" ).append("\n"); 
		query.append("            , MAX(Q.MNL_INP) MNL_INP" ).append("\n"); 
		query.append("        FROM (" ).append("\n"); 
		query.append("            SELECT" ).append("\n"); 
		query.append("            Q.YD_CD, " ).append("\n"); 
		query.append("			CASE" ).append("\n"); 
		query.append("			WHEN Q.FCAST_YRWK >= @[curr_yrwk] --(SELECT MAX(W.PLN_YR||W.PLN_WK) FROM EQR_WK_PRD W WHERE TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN W.WK_ST_DT AND W.WK_END_DT) " ).append("\n"); 
		query.append("			THEN " ).append("\n"); 
		query.append("		    	CASE" ).append("\n"); 
		query.append("			    WHEN SQ.FCAST_YRWK IS NOT NULL " ).append("\n"); 
		query.append("			    THEN Q.INVT_SIM_TP_CD" ).append("\n"); 
		query.append("			    ELSE DECODE(Q.INVT_SIM_TP_CD,'OF','OP','OP','XX','MF','MG','MG','XX',Q.INVT_SIM_TP_CD) --Q.INVT_SIM_TP_CD DECODE(Q.INVT_SIM_TP_CD,'OF','OP','OP','XX','MF','MG','MG','XX',Q.INVT_SIM_TP_CD)" ).append("\n"); 
		query.append("			    END" ).append("\n"); 
		query.append("			ELSE Q.INVT_SIM_TP_CD" ).append("\n"); 
		query.append("			END INVT_SIM_TP_CD ,  " ).append("\n"); 
		query.append("			Q.CNTR_TPSZ_CD, Q.FCAST_YRWK, NVL(SQ.CNTR_QTY,Q.CNTR_QTY) CNTR_QTY" ).append("\n"); 
		query.append("            , CASE WHEN SQ.FCAST_YRWK IS NOT NULL THEN 'Y' ELSE '' END MNL_INP" ).append("\n"); 
		query.append("            FROM EQR_CTRL_INVT_SIM_DTL D, EQR_CTRL_INVT_SIM_DTL_QTY Q" ).append("\n"); 
		query.append("               , ( SELECT Q.FCAST_YRWK, Q.YD_CD, Q.INVT_SIM_TP_CD, Q.CNTR_TPSZ_CD, Q.CNTR_QTY, Q.TMP_SAV_FLG, Q.CRE_DT, Q.UPD_DT  " ).append("\n"); 
		query.append("                   FROM EQR_CTRL_INVT_SIM S, EQR_CTRL_INVT_SIM_QTY Q" ).append("\n"); 
		query.append("                   WHERE 1=1" ).append("\n"); 
		query.append("                   AND S.FCAST_YRWK = Q.FCAST_YRWK" ).append("\n"); 
		query.append("                   AND S.YD_CD = Q.YD_CD" ).append("\n"); 
		query.append("                   AND S.INVT_SIM_TP_CD = Q.INVT_SIM_TP_CD " ).append("\n"); 
		query.append("                   AND Q.FCAST_YRWK >= @[curr_yrwk] --(SELECT MAX(W.PLN_YR||W.PLN_WK) FROM EQR_WK_PRD W WHERE TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN W.WK_ST_DT AND W.WK_END_DT)" ).append("\n"); 
		query.append("                   AND Q.UPD_DT >= (SELECT TO_DATE(W.WK_ST_DT,'YYYYMMDD')+(1+5/24) BAT_MND FROM EQR_WK_PRD W WHERE W.PLN_YR = SUBSTR(@[curr_yrwk],1,4) AND W.PLN_WK = SUBSTR(@[curr_yrwk],5))" ).append("\n"); 
		query.append("                 ) SQ" ).append("\n"); 
		query.append("            WHERE 1=1" ).append("\n"); 
		query.append("            AND D.FCAST_YRWK = Q.FCAST_YRWK" ).append("\n"); 
		query.append("            AND D.YD_CD = Q.YD_CD" ).append("\n"); 
		query.append("            AND D.INVT_SIM_TP_CD = Q.INVT_SIM_TP_CD" ).append("\n"); 
		query.append("            AND D.FCAST_YRWK = Q.FCAST_YRWK" ).append("\n"); 
		query.append("            AND Q.FCAST_YRWK BETWEEN @[fm_yrwk] AND @[to_yrwk]" ).append("\n"); 
		query.append("            AND Q.FCAST_YRWK = SQ.FCAST_YRWK(+)" ).append("\n"); 
		query.append("            AND Q.YD_CD = SQ.YD_CD(+)" ).append("\n"); 
		query.append("            AND Q.INVT_SIM_TP_CD = SQ.INVT_SIM_TP_CD(+)" ).append("\n"); 
		query.append("            AND Q.CNTR_TPSZ_CD = SQ.CNTR_TPSZ_CD(+)" ).append("\n"); 
		query.append("            GROUP BY Q.YD_CD, Q.INVT_SIM_TP_CD, Q.CNTR_TPSZ_CD, Q.FCAST_YRWK, NVL(SQ.CNTR_QTY,Q.CNTR_QTY), SQ.FCAST_YRWK" ).append("\n"); 
		query.append("            UNION ALL" ).append("\n"); 
		query.append("            SELECT " ).append("\n"); 
		query.append("            Q.YD_CD, " ).append("\n"); 
		query.append("			Q.INVT_SIM_TP_CD INVT_SIM_TP_CD , " ).append("\n"); 
		query.append("			Q.CNTR_TPSZ_CD, Q.FCAST_YRWK, Q.CNTR_QTY" ).append("\n"); 
		query.append("            , 'Y' MNL_INP" ).append("\n"); 
		query.append("            FROM EQR_CTRL_INVT_SIM S, EQR_CTRL_INVT_SIM_QTY Q" ).append("\n"); 
		query.append("            WHERE 1=1" ).append("\n"); 
		query.append("            AND S.FCAST_YRWK = Q.FCAST_YRWK" ).append("\n"); 
		query.append("            AND S.YD_CD = Q.YD_CD" ).append("\n"); 
		query.append("            AND S.INVT_SIM_TP_CD = Q.INVT_SIM_TP_CD " ).append("\n"); 
		query.append("            AND S.FCAST_YRWK = Q.FCAST_YRWK" ).append("\n"); 
		query.append("            AND Q.FCAST_YRWK >= @[curr_yrwk] --(SELECT MAX(W.PLN_YR||W.PLN_WK) FROM EQR_WK_PRD W WHERE TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN W.WK_ST_DT AND W.WK_END_DT)" ).append("\n"); 
		query.append("            AND Q.UPD_DT >= (SELECT TO_DATE(W.WK_ST_DT,'YYYYMMDD')+(1+5/24) BAT_MND FROM EQR_WK_PRD W WHERE TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN W.WK_ST_DT AND W.WK_END_DT)" ).append("\n"); 
		query.append("            AND NOT EXISTS (" ).append("\n"); 
		query.append("                SELECT 'X' " ).append("\n"); 
		query.append("                FROM EQR_CTRL_INVT_SIM_DTL_QTY X" ).append("\n"); 
		query.append("                WHERE 1=1" ).append("\n"); 
		query.append("                AND X.FCAST_YRWK = Q.FCAST_YRWK" ).append("\n"); 
		query.append("                AND X.YD_CD = Q.YD_CD" ).append("\n"); 
		query.append("                AND X.INVT_SIM_TP_CD = Q.INVT_SIM_TP_CD" ).append("\n"); 
		query.append("                AND X.CNTR_TPSZ_CD = Q.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("            )" ).append("\n"); 
		query.append("            GROUP BY Q.YD_CD, Q.INVT_SIM_TP_CD, Q.CNTR_TPSZ_CD, Q.FCAST_YRWK, Q.CNTR_QTY" ).append("\n"); 
		query.append("        ) Q, MDM_LOCATION A, MDM_EQ_ORZ_CHT B" ).append("\n"); 
		query.append("        WHERE 1=1" ).append("\n"); 
		query.append("            AND A.LOC_CD = SUBSTR(Q.YD_CD,1,5)" ).append("\n"); 
		query.append("            AND A.SCC_CD = B.SCC_CD" ).append("\n"); 
		query.append("            AND NVL(A.DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("            AND NVL(B.DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("        #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("            AND B.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '3') --RCC (by LCC)          " ).append("\n"); 
		query.append("            AND B.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("            AND B.LCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("            AND B.LCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("            AND B.ECC_CD =@[loc_cd]" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("            AND B.SCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '8') --RCC (by ECC)          " ).append("\n"); 
		query.append("            AND B.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("        #end         " ).append("\n"); 
		query.append("	    #if( ${level_cd} == '2' ) --LEVEL_CD 2 RHQ" ).append("\n"); 
		query.append("    		AND B.LCC_CD IN (" ).append("\n"); 
		query.append("		        SELECT LCC_CD" ).append("\n"); 
		query.append("        		FROM MDM_EQ_ORZ_CHT                         " ).append("\n"); 
		query.append("		        WHERE SCC_CD IN (" ).append("\n"); 
		query.append("        		    SELECT SCC_CD" ).append("\n"); 
		query.append("		            FROM MDM_LOCATION" ).append("\n"); 
		query.append("        		    WHERE LOC_CD IN (SELECT DISTINCT LOC_CD" ).append("\n"); 
		query.append("                		             FROM MDM_ORGANIZATION" ).append("\n"); 
		query.append("                        		     WHERE NVL(DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("		                             CONNECT BY NOCYCLE PRIOR OFC_CD = PRNT_OFC_CD" ).append("\n"); 
		query.append("        		                     START WITH OFC_CD = (SELECT DISTINCT AR_HD_QTR_OFC_CD FROM MDM_ORGANIZATION WHERE OFC_CD = @[ofc_cd]))" ).append("\n"); 
		query.append("		        )" ).append("\n"); 
		query.append("		    )" ).append("\n"); 
		query.append("	    #elseif( ${level_cd} == '5' ) --LEVEL_CD 5 ATLSC-->ATLSA, PHXSC-->PHXSA" ).append("\n"); 
		query.append("		    AND B.LCC_CD IN (" ).append("\n"); 
		query.append("        		SELECT LCC_CD" ).append("\n"); 
		query.append("		        FROM MDM_EQ_ORZ_CHT                         " ).append("\n"); 
		query.append("		        WHERE SCC_CD IN (" ).append("\n"); 
		query.append("        		    SELECT SCC_CD" ).append("\n"); 
		query.append("		            FROM MDM_LOCATION" ).append("\n"); 
		query.append("        		    WHERE LOC_CD IN (SELECT DISTINCT LOC_CD" ).append("\n"); 
		query.append("                		             FROM MDM_ORGANIZATION" ).append("\n"); 
		query.append("                        		     WHERE NVL(DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("		                             CONNECT BY NOCYCLE PRIOR OFC_CD = PRNT_OFC_CD" ).append("\n"); 
		query.append("        		                     START WITH OFC_CD = (SELECT DISTINCT AR_HD_QTR_OFC_CD FROM MDM_ORGANIZATION WHERE OFC_CD = @[ofc_cd] AND OFC_CD IN ('ATLSA','PHXSA'))) -- ATLSC-->ATLSA, PHXSC-->PHXSA " ).append("\n"); 
		query.append("		        )" ).append("\n"); 
		query.append("		    )" ).append("\n"); 
		query.append("	    #elseif( ${level_cd} == '6' ) --LEVEL_CD 6 Office" ).append("\n"); 
		query.append("    		AND B.LCC_CD IN (" ).append("\n"); 
		query.append("		        SELECT LCC_CD" ).append("\n"); 
		query.append("        		FROM MDM_EQ_ORZ_CHT                         " ).append("\n"); 
		query.append("		        WHERE SCC_CD IN (" ).append("\n"); 
		query.append("        		    SELECT SCC_CD" ).append("\n"); 
		query.append("		            FROM MDM_LOCATION" ).append("\n"); 
		query.append("        		    WHERE LOC_CD IN (SELECT LOC_CD FROM MDM_ORGANIZATION WHERE NVL(DELT_FLG,'N') <> 'Y' AND OFC_CD = @[ofc_cd])" ).append("\n"); 
		query.append("		        )" ).append("\n"); 
		query.append("		    )" ).append("\n"); 
		query.append("	    #elseif( ${level_cd} == '3' || ${level_cd} == '4' ) --LEVEL_CD 3,4 Office" ).append("\n"); 
		query.append("			AND 1=2 --조회안되야함" ).append("\n"); 
		query.append("	    #end" ).append("\n"); 
		query.append("    	GROUP BY " ).append("\n"); 
		query.append("        #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("            SUBSTR(Q.YD_CD,1,2)" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '3') --RCC (by LCC)          " ).append("\n"); 
		query.append("            B.LCC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("            B.ECC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("            B.SCC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("            B.SCC_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("            Q.YD_CD" ).append("\n"); 
		query.append("        #elseif (${loc_type_code} == '8') --RCC (by ECC)          " ).append("\n"); 
		query.append("            B.ECC_CD" ).append("\n"); 
		query.append("        #end      " ).append("\n"); 
		query.append("            , Q.INVT_SIM_TP_CD, Q.CNTR_TPSZ_CD, Q.FCAST_YRWK " ).append("\n"); 
		query.append("    ) Q         " ).append("\n"); 
		query.append("    GROUP BY S.GRP_CD, S.SORT, S.CODE, S.NAME, Q.LOC_CD, Q.CNTR_TPSZ_CD, Q.FCAST_YRWK" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.LOC_CD, A.CODE, A.NAME, A.GRP_CD, A.SORT" ).append("\n"); 
		query.append("#foreach( $key in ${arrweek1}) -- 과거 3주" ).append("\n"); 
		query.append(", DECODE(NVL(A.D2_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.D2_$key,0) D2_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.D4_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.D4_$key,0) D4_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.D5_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.D5_$key,0) D5_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.D7_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.D7_$key,0) D7_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.R2_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.R2_$key,0) R2_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.R5_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.R5_$key,0) R5_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.R9_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.R9_$key,0) R9_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.O2_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.O2_$key,0) O2_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.O4_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.O4_$key,0) O4_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.S2_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.S2_$key,0) S2_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.S4_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.S4_$key,0) S4_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.F2_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.F2_$key,0) F2_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.F4_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.F4_$key,0) F4_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.F5_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.F5_$key,0) F5_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.A2_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.A2_$key,0) A2_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.A4_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.A4_$key,0) A4_$key" ).append("\n"); 
		query.append(", DECODE(NVL(A.A5_MINUS_YN_$key,1),'Y',-1,1) * NVL(A.A5_$key,0) A5_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#foreach( $key in ${arrweek2}) -- 현재,미래3주 " ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.D2_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB') " ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.D2_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.D2_$key,0,TO_NUMBER(NULL),A.D2_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.D2_$key END,0) D2_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.D4_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.D4_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3) " ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.D4_$key,0,TO_NUMBER(NULL),A.D4_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.D4_$key END,0) D4_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.D5_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.D5_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.D5_$key,0,TO_NUMBER(NULL),A.D5_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.D5_$key END,0) D5_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.D7_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.D7_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.D7_$key,0,TO_NUMBER(NULL),A.D7_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.D7_$key END,0) D7_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.R2_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.R2_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.R2_$key,0,TO_NUMBER(NULL),A.R2_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.R2_$key END,0) R2_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.R5_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.R5_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.R5_$key,0,TO_NUMBER(NULL),A.R5_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.R5_$key END,0) R5_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.R9_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.R9_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.R9_$key,0,TO_NUMBER(NULL),A.R9_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.R9_$key END,0) R9_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.O2_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.O2_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.O2_$key,0,TO_NUMBER(NULL),A.O2_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.O2_$key END,0) O2_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.O4_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.O4_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.O4_$key,0,TO_NUMBER(NULL),A.O4_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.O4_$key END,0) O4_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.S2_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.S2_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.S2_$key,0,TO_NUMBER(NULL),A.S2_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.S2_$key END,0) S2_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.S4_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.S4_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.S4_$key,0,TO_NUMBER(NULL),A.S4_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.S4_$key END,0) S4_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.F2_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.F2_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.F2_$key,0,TO_NUMBER(NULL),A.F2_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.F2_$key END,0) F2_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.F4_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.F4_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.F4_$key,0,TO_NUMBER(NULL),A.F4_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.F4_$key END,0) F4_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.F5_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.F5_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.F5_$key,0,TO_NUMBER(NULL),A.F5_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.F5_$key END,0) F5_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.A2_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.A2_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.A2_$key,0,TO_NUMBER(NULL),A.A2_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.A2_$key END,0) A2_$key" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.A4_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.A4_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.A4_$key,0,TO_NUMBER(NULL),A.A4_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.A4_$key END,0) A4_$key" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(", NVL(CASE WHEN NVL(A.A5_B_$key,'N')<>'Y' AND A.CODE IN ('INP','RD','RI','OH','DI','SI','INM','OP','RL','RO','OT','DO','SO','FBB')" ).append("\n"); 
		query.append("       THEN CEIL((" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek1})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         +" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     A.A5_$key" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("                                 )/3)" ).append("\n"); 
		query.append("       WHEN A.CODE = 'F3' " ).append("\n"); 
		query.append("       THEN NVL(COALESCE(" ).append("\n"); 
		query.append("    #foreach( $key in ${arrweek3})" ).append("\n"); 
		query.append("        #if($velocityCount > 1 )" ).append("\n"); 
		query.append("                         ," ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("                     DECODE(A.A5_$key,0,TO_NUMBER(NULL),A.A5_$key)" ).append("\n"); 
		query.append("    #end    " ).append("\n"); 
		query.append("			),0)" ).append("\n"); 
		query.append("       ELSE A.A5_$key END,0) A5_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#foreach( $key in ${arrweek2}) -- 현재,미래3주 " ).append("\n"); 
		query.append(", A.D2_B_$key, A.D4_B_$key, A.D5_B_$key, A.D7_B_$key, A.R2_B_$key" ).append("\n"); 
		query.append(", A.R5_B_$key, A.R9_B_$key, A.O2_B_$key, A.O4_B_$key, A.S2_B_$key" ).append("\n"); 
		query.append(", A.S4_B_$key, A.F2_B_$key, A.F4_B_$key, A.F5_B_$key, A.A2_B_$key" ).append("\n"); 
		query.append(", A.A4_B_$key, A.A5_B_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("FROM (" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.LOC_CD, A.CODE, A.NAME, A.GRP_CD, A.SORT" ).append("\n"); 
		query.append("#foreach( $key in ${arrweek}) " ).append("\n"); 
		query.append(", MAX(ABS(A.D2_$key)) D2_$key, MAX(ABS(A.D4_$key)) D4_$key, MAX(ABS(A.D5_$key)) D5_$key, MAX(ABS(A.D7_$key)) D7_$key, MAX(ABS(A.R2_$key)) R2_$key, MAX(ABS(A.R5_$key)) R5_$key, MAX(ABS(A.R9_$key)) R9_$key" ).append("\n"); 
		query.append(", MAX(ABS(A.O2_$key)) O2_$key, MAX(ABS(A.O4_$key)) O4_$key, MAX(ABS(A.S2_$key)) S2_$key, MAX(ABS(A.S4_$key)) S4_$key, MAX(ABS(A.F2_$key)) F2_$key, MAX(ABS(A.F4_$key)) F4_$key, MAX(ABS(A.F5_$key)) F5_$key" ).append("\n"); 
		query.append(", MAX(ABS(A.A2_$key)) A2_$key, MAX(ABS(A.A4_$key)) A4_$key, MAX(ABS(A.A5_$key)) A5_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.D2_$key)) <> MAX(A.D2_$key) THEN 'Y' ELSE '' END D2_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.D4_$key)) <> MAX(A.D4_$key) THEN 'Y' ELSE '' END D4_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.D5_$key)) <> MAX(A.D5_$key) THEN 'Y' ELSE '' END D5_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.D7_$key)) <> MAX(A.D7_$key) THEN 'Y' ELSE '' END D7_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.R2_$key)) <> MAX(A.R2_$key) THEN 'Y' ELSE '' END R2_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.R5_$key)) <> MAX(A.R5_$key) THEN 'Y' ELSE '' END R5_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.R9_$key)) <> MAX(A.R9_$key) THEN 'Y' ELSE '' END R9_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.O2_$key)) <> MAX(A.O2_$key) THEN 'Y' ELSE '' END O2_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.O4_$key)) <> MAX(A.O4_$key) THEN 'Y' ELSE '' END O4_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.S2_$key)) <> MAX(A.S2_$key) THEN 'Y' ELSE '' END S2_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.S4_$key)) <> MAX(A.S4_$key) THEN 'Y' ELSE '' END S4_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.F2_$key)) <> MAX(A.F2_$key) THEN 'Y' ELSE '' END F2_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.F4_$key)) <> MAX(A.F4_$key) THEN 'Y' ELSE '' END F4_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.F5_$key)) <> MAX(A.F5_$key) THEN 'Y' ELSE '' END F5_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.A2_$key)) <> MAX(A.A2_$key) THEN 'Y' ELSE '' END A2_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.A4_$key)) <> MAX(A.A4_$key) THEN 'Y' ELSE '' END A4_MINUS_YN_$key" ).append("\n"); 
		query.append(", CASE WHEN A.CODE='FBB' AND MAX(ABS(A.A5_$key)) <> MAX(A.A5_$key) THEN 'Y' ELSE '' END A5_MINUS_YN_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#foreach( $key in ${arrweek2}) -- 현재,미래3주 " ).append("\n"); 
		query.append(", MAX(A.D2_B_$key) D2_B_$key, MAX(A.D4_B_$key) D4_B_$key, MAX(A.D5_B_$key) D5_B_$key, MAX(A.D7_B_$key) D7_B_$key, MAX(A.R2_B_$key) R2_B_$key" ).append("\n"); 
		query.append(", MAX(A.R5_B_$key) R5_B_$key, MAX(A.R9_B_$key) R9_B_$key, MAX(A.O2_B_$key) O2_B_$key, MAX(A.O4_B_$key) O4_B_$key, MAX(A.S2_B_$key) S2_B_$key" ).append("\n"); 
		query.append(", MAX(A.S4_B_$key) S4_B_$key, MAX(A.F2_B_$key) F2_B_$key, MAX(A.F4_B_$key) F4_B_$key, MAX(A.F5_B_$key) F5_B_$key, MAX(A.A2_B_$key) A2_B_$key" ).append("\n"); 
		query.append(", MAX(A.A4_B_$key) A4_B_$key, MAX(A.A5_B_$key) A5_B_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("FROM (" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append(" CASE WHEN GROUPING(R.LOC_CD)='1' THEN 'TTL' ELSE R.LOC_CD END LOC_CD" ).append("\n"); 
		query.append(", R.CODE, R.NAME, R.GRP_CD, R.SORT" ).append("\n"); 
		query.append("#foreach( $key in ${arrweek2}) -- 현재,미래3주" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D2$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END D2_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D4$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END D4_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D5$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END D5_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D7$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END D7_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='R2$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END R2_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='R5$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END R5_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='R9$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END R9_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='O2$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END O2_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='O4$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END O4_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='S2$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END S2_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='S4$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END S4_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='F2$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END F2_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='F4$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END F4_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='F5$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END F5_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='A2$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END A2_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='A4$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END A4_B_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='A5$key' THEN DECODE(GROUPING(R.LOC_CD),'1','',MAX(NVL(R.MNL_INP,''))) ELSE '' END A5_B_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#foreach( $key in ${arrweek})" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D2$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END D2_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D4$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END D4_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D5$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END D5_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='D7$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END D7_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='R2$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END R2_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='R5$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END R5_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='R9$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END R9_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='O2$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END O2_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='O4$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END O4_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='S2$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END S2_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='S4$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END S4_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='F2$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END F2_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='F4$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END F4_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='F5$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END F5_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='A2$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END A2_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='A4$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END A4_$key" ).append("\n"); 
		query.append(",CASE WHEN R.CNTR_TPSZ_CD||R.FCAST_YRWK='A5$key' THEN DECODE(R.GRP_CD,'5',DECODE(GROUPING(R.LOC_CD),'1',TO_NUMBER(''),MAX(NVL((R.QTY),0))),SUM(NVL(R.QTY,0))) ELSE 0 END A5_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("FROM (" ).append("\n"); 
		query.append("    SELECT " ).append("\n"); 
		query.append("        X.LOC_CD" ).append("\n"); 
		query.append("        , X.CODE, X.NAME, X.GRP_CD, X.SORT" ).append("\n"); 
		query.append("        , X.FCAST_YRWK, X.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("        ,X.QTY" ).append("\n"); 
		query.append("        ,X.MNL_INP" ).append("\n"); 
		query.append("    FROM (" ).append("\n"); 
		query.append("            SELECT" ).append("\n"); 
		query.append("                A.LOC_CD, " ).append("\n"); 
		query.append("                'INN' CODE, 'Initial Inventory' NAME, A.GRP_CD, TO_NUMBER('') SORT" ).append("\n"); 
		query.append("                , A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                , A.FCAST_YRWK" ).append("\n"); 
		query.append("                , CASE " ).append("\n"); 
		query.append("                  WHEN A.FCAST_YRWK <= (SELECT MAX(W.PLN_YR||W.PLN_WK) CURR_WK FROM EQR_WK_PRD W WHERE TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN W.WK_ST_DT AND W.WK_END_DT) " ).append("\n"); 
		query.append("			      --THEN SUM(NVL(DECODE(A.CODE,'IV',A.QTY,0),0)-(NVL(DECODE(A.CODE,'IS',A.QTY,0),0)+NVL(DECODE(A.CODE,'ID',A.QTY,0),0)))" ).append("\n"); 
		query.append("				  THEN SUM(NVL(DECODE(A.CODE,'IV',A.QTY,0),0)-(NVL(DECODE(A.CODE,'IS',A.QTY,0),0)))" ).append("\n"); 
		query.append("                  ELSE TO_NUMBER('')" ).append("\n"); 
		query.append("                  END QTY" ).append("\n"); 
		query.append("                , '' MNL_INP" ).append("\n"); 
		query.append("            FROM SIM_SS_DATA A" ).append("\n"); 
		query.append("            WHERE 1=1" ).append("\n"); 
		query.append("            AND A.GRP_CD IN ('1')" ).append("\n"); 
		query.append("            GROUP BY A.LOC_CD, A.GRP_CD, A.CNTR_TPSZ_CD, A.FCAST_YRWK" ).append("\n"); 
		query.append("            UNION ALL" ).append("\n"); 
		query.append("            SELECT" ).append("\n"); 
		query.append("                A.LOC_CD, " ).append("\n"); 
		query.append("                CASE" ).append("\n"); 
		query.append("                WHEN A.GRP_CD = '2' AND GROUPING(A.GRP_CD)='0' AND GROUPING(A.CODE)='1'" ).append("\n"); 
		query.append("                THEN 'INP'" ).append("\n"); 
		query.append("                WHEN A.GRP_CD = '3' AND GROUPING(A.GRP_CD)='0' AND GROUPING(A.CODE)='1'" ).append("\n"); 
		query.append("                THEN 'INM'" ).append("\n"); 
		query.append("                ELSE A.CODE" ).append("\n"); 
		query.append("                END CODE,        " ).append("\n"); 
		query.append("                CASE" ).append("\n"); 
		query.append("                WHEN A.GRP_CD = '2' AND GROUPING(A.GRP_CD)='0' AND GROUPING(A.CODE)='1'" ).append("\n"); 
		query.append("                THEN 'Inventory Plus (-)'" ).append("\n"); 
		query.append("                WHEN A.GRP_CD = '3' AND GROUPING(A.GRP_CD)='0' AND GROUPING(A.CODE)='1'" ).append("\n"); 
		query.append("                THEN 'Inventory Minus (-)'" ).append("\n"); 
		query.append("                ELSE A.NAME" ).append("\n"); 
		query.append("                END NAME," ).append("\n"); 
		query.append("                A.GRP_CD," ).append("\n"); 
		query.append("                CASE" ).append("\n"); 
		query.append("                WHEN A.GRP_CD = '2' AND GROUPING(A.GRP_CD)='0' AND GROUPING(A.CODE)='1'" ).append("\n"); 
		query.append("                THEN 0" ).append("\n"); 
		query.append("                WHEN A.GRP_CD = '3' AND GROUPING(A.GRP_CD)='0' AND GROUPING(A.CODE)='1'" ).append("\n"); 
		query.append("                THEN 0" ).append("\n"); 
		query.append("                ELSE A.SORT" ).append("\n"); 
		query.append("                END SORT" ).append("\n"); 
		query.append("                , A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                , A.FCAST_YRWK" ).append("\n"); 
		query.append("                , SUM(NVL(A.QTY,0)) QTY" ).append("\n"); 
		query.append("                , CASE" ).append("\n"); 
		query.append("                WHEN A.GRP_CD IN ('2','3') AND A.SORT >= '0' AND A.CODE NOT IN ('PL')" ).append("\n"); 
		query.append("                THEN MAX(A.MNL_INP)" ).append("\n"); 
		query.append("                ELSE ''" ).append("\n"); 
		query.append("                END MNL_INP" ).append("\n"); 
		query.append("            FROM SIM_SS_DATA A" ).append("\n"); 
		query.append("            WHERE 1=1" ).append("\n"); 
		query.append("            AND A.GRP_CD IN ('2','3')" ).append("\n"); 
		query.append("            AND A.CODE NOT IN ('PL')" ).append("\n"); 
		query.append("            GROUP BY GROUPING SETS ((A.LOC_CD, A.GRP_CD, A.SORT, A.CODE, A.NAME, A.CNTR_TPSZ_CD, A.FCAST_YRWK),(A.LOC_CD, A.GRP_CD, A.CNTR_TPSZ_CD, A.FCAST_YRWK))" ).append("\n"); 
		query.append("            UNION ALL" ).append("\n"); 
		query.append("            SELECT" ).append("\n"); 
		query.append("                A.LOC_CD," ).append("\n"); 
		query.append("                'FBB' CODE, 'Final Balance' NAME, 4 GRP_CD, TO_NUMBER('') SORT" ).append("\n"); 
		query.append("                , A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                , A.FCAST_YRWK" ).append("\n"); 
		query.append("                , CASE " ).append("\n"); 
		query.append("                  WHEN A.FCAST_YRWK <= (SELECT MAX(W.PLN_YR||W.PLN_WK) CURR_WK FROM EQR_WK_PRD W WHERE TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN W.WK_ST_DT AND W.WK_END_DT) " ).append("\n"); 
		query.append("                  THEN SUM(NVL(DECODE(A.CODE,'IV',A.QTY,0),0)-(NVL(DECODE(A.CODE,'IS',A.QTY,0),0)))" ).append("\n"); 
		query.append("				  --THEN SUM(NVL(DECODE(A.CODE,'IV',A.QTY,0),0)-(NVL(DECODE(A.CODE,'IS',A.QTY,0),0)+NVL(DECODE(A.CODE,'ID',A.QTY,0),0)))" ).append("\n"); 
		query.append("                  ELSE 0" ).append("\n"); 
		query.append("                  END +" ).append("\n"); 
		query.append("				  SUM(NVL(DECODE(A.GRP_CD,'2',A.QTY,0),0)) - SUM(NVL(DECODE(A.GRP_CD,'3',A.QTY,0),0)) QTY" ).append("\n"); 
		query.append("                , '' MNL_INP" ).append("\n"); 
		query.append("            FROM SIM_SS_DATA A" ).append("\n"); 
		query.append("            WHERE 1=1" ).append("\n"); 
		query.append("            AND A.GRP_CD IN ('1','2','3')" ).append("\n"); 
		query.append("            AND A.CODE NOT IN ('PL')" ).append("\n"); 
		query.append("            GROUP BY A.LOC_CD, A.CNTR_TPSZ_CD, A.FCAST_YRWK" ).append("\n"); 
		query.append("            UNION ALL" ).append("\n"); 
		query.append("            SELECT" ).append("\n"); 
		query.append("                A.LOC_CD, 'PL' CODE, 'MT Loading Plan' NAME, 3 GRP_CD, 4 SORT" ).append("\n"); 
		query.append("                , A.CNTR_TPSZ_CD, A.FCAST_YRWK" ).append("\n"); 
		query.append("                , SUM(B.QTY) QTY" ).append("\n"); 
		query.append("                , '' MNL_INP" ).append("\n"); 
		query.append("            FROM (SELECT DISTINCT A.LOC_CD, A.CNTR_TPSZ_CD, A.FCAST_YRWK FROM SIM_SS_DATA A WHERE A.GRP_CD IN ('3')) A, " ).append("\n"); 
		query.append("            (" ).append("\n"); 
		query.append("                SELECT" ).append("\n"); 
		query.append("                #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("                    SUBSTR(PLN.POL_YD_CD,1,2)" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '3') --RCC (by LCC)" ).append("\n"); 
		query.append("                    B.LCC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("                    B.ECC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("                    B.SCC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("                    B.SCC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("                    PLN.POL_YD_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '8') --RCC (by ECC)" ).append("\n"); 
		query.append("                    B.ECC_CD" ).append("\n"); 
		query.append("                #end    " ).append("\n"); 
		query.append("                    LOC_CD" ).append("\n"); 
		query.append("                    , PLN.CNTR_TPSZ_CD, PLN.WK" ).append("\n"); 
		query.append("                    , SUM(NVL(PLN.CNTR_QTY,0)) QTY" ).append("\n"); 
		query.append("                FROM (" ).append("\n"); 
		query.append("                    SELECT " ).append("\n"); 
		query.append("                        LODG.POL_YD_CD" ).append("\n"); 
		query.append("                        ,LODG.VSL_CD" ).append("\n"); 
		query.append("                        ,LODG.SKD_VOY_NO" ).append("\n"); 
		query.append("                        ,LODG.SKD_DIR_CD" ).append("\n"); 
		query.append("                        ,W.PLN_YR||W.PLN_WK WK" ).append("\n"); 
		query.append("                        ,QTY.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                        ,QTY.CNTR_QTY" ).append("\n"); 
		query.append("                    FROM EQR_CTRL_MTY_LODG_PLN LODG, VSK_VSL_PORT_SKD V, EQR_WK_PRD W, EQR_CTRL_MTY_DCHG_PLN DCHG, EQR_CTRL_MTY_DCHG_PLN_QTY QTY" ).append("\n"); 
		query.append("                    WHERE 1=1" ).append("\n"); 
		query.append("                        AND LODG.VSL_CD = DCHG.VSL_CD" ).append("\n"); 
		query.append("                        AND LODG.SKD_VOY_NO = DCHG.SKD_VOY_NO" ).append("\n"); 
		query.append("                        AND LODG.SKD_DIR_CD = DCHG.SKD_DIR_CD" ).append("\n"); 
		query.append("                        AND LODG.POL_YD_CD = DCHG.POL_YD_CD" ).append("\n"); 
		query.append("                        AND LODG.VSL_CD = V.VSL_CD" ).append("\n"); 
		query.append("                        AND LODG.SKD_VOY_NO = V.SKD_VOY_NO" ).append("\n"); 
		query.append("                        AND LODG.SKD_DIR_CD = V.SKD_DIR_CD" ).append("\n"); 
		query.append("                        AND LODG.POL_YD_CD = V.YD_CD" ).append("\n"); 
		query.append("                        AND W.PLN_YR = TO_CHAR(V.VPS_ETA_DT,'YYYY')" ).append("\n"); 
		query.append("                        AND V.VPS_ETA_DT BETWEEN TO_DATE(W.WK_ST_DT,'YYYYMMDD') AND TO_DATE(W.WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("                        AND DCHG.VSL_CD = QTY.VSL_CD" ).append("\n"); 
		query.append("                        AND DCHG.SKD_VOY_NO = QTY.SKD_VOY_NO" ).append("\n"); 
		query.append("                        AND DCHG.SKD_DIR_CD = QTY.SKD_DIR_CD" ).append("\n"); 
		query.append("                        AND DCHG.POL_YD_CD = QTY.POL_YD_CD" ).append("\n"); 
		query.append("                        AND DCHG.POD_YD_CD = QTY.POD_YD_CD" ).append("\n"); 
		query.append("                ) PLN, MDM_YARD Y, MDM_LOCATION A, MDM_EQ_ORZ_CHT B" ).append("\n"); 
		query.append("                WHERE 1=1" ).append("\n"); 
		query.append("                    AND PLN.POL_YD_CD = Y.YD_CD" ).append("\n"); 
		query.append("                    AND Y.LOC_CD = A.LOC_CD" ).append("\n"); 
		query.append("                    AND A.SCC_CD = B.SCC_CD" ).append("\n"); 
		query.append("                    AND NVL(Y.DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("                    AND NVL(A.DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("                    AND NVL(B.DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("                #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("                    AND B.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '3') --RCC (by LCC)          " ).append("\n"); 
		query.append("                    AND B.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("                    AND B.LCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("                    AND B.LCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("                    AND B.ECC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("                    AND B.SCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '8') --RCC (by ECC)          " ).append("\n"); 
		query.append("                    AND B.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #end         " ).append("\n"); 
		query.append("                    GROUP BY " ).append("\n"); 
		query.append("                    #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("                        SUBSTR(PLN.POL_YD_CD,1,2)" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '3') --RCC (by LCC)          " ).append("\n"); 
		query.append("                        B.LCC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("                        B.ECC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("                        B.SCC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("                        B.SCC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("                        PLN.POL_YD_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '8') --RCC (by ECC)          " ).append("\n"); 
		query.append("                        B.ECC_CD" ).append("\n"); 
		query.append("                    #end         " ).append("\n"); 
		query.append("                        , PLN.CNTR_TPSZ_CD, PLN.WK" ).append("\n"); 
		query.append("            ) B" ).append("\n"); 
		query.append("            WHERE 1=1" ).append("\n"); 
		query.append("                AND A.LOC_CD = B.LOC_CD(+)" ).append("\n"); 
		query.append("                AND A.CNTR_TPSZ_CD = B.CNTR_TPSZ_CD(+)" ).append("\n"); 
		query.append("                AND A.FCAST_YRWK = B.WK(+)" ).append("\n"); 
		query.append("                GROUP BY A.LOC_CD, A.CNTR_TPSZ_CD, A.FCAST_YRWK" ).append("\n"); 
		query.append("            #if (${loc_type_code} == '5' || ${loc_type_code} == '6' || ${loc_type_code} == '7')                " ).append("\n"); 
		query.append("            UNION ALL" ).append("\n"); 
		query.append("            SELECT" ).append("\n"); 
		query.append("                A.LOC_CD, A.CODE, A.NAME, A.GRP_CD, A.SORT" ).append("\n"); 
		query.append("                , A.CNTR_TPSZ_CD, A.FCAST_YRWK" ).append("\n"); 
		query.append("                , " ).append("\n"); 
		query.append("                CASE" ).append("\n"); 
		query.append("                WHEN A.CODE = 'F3'" ).append("\n"); 
		query.append("                THEN " ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN NVL(MAX(MB.MB),TO_NUMBER('')) BETWEEN 0 AND 50 THEN 0.5" ).append("\n"); 
		query.append("                    WHEN NVL(MAX(MB.MB),TO_NUMBER('')) BETWEEN 51 AND 80 THEN 0.7" ).append("\n"); 
		query.append("                    WHEN NVL(MAX(MB.MB),TO_NUMBER('')) BETWEEN 81 AND 100 THEN 0.9" ).append("\n"); 
		query.append("                    WHEN NVL(MAX(MB.MB),TO_NUMBER('')) BETWEEN -100 AND -50 THEN 1.2" ).append("\n"); 
		query.append("                    WHEN NVL(MAX(MB.MB),TO_NUMBER('')) BETWEEN -49 AND -1 THEN 1.5" ).append("\n"); 
		query.append("                    ELSE TO_NUMBER('')" ).append("\n"); 
		query.append("                    END " ).append("\n"); 
		query.append("                ELSE TO_NUMBER('')" ).append("\n"); 
		query.append("                END QTY" ).append("\n"); 
		query.append("                , '' MNL_INP" ).append("\n"); 
		query.append("            FROM (SELECT DISTINCT A.LOC_CD, A.CODE, A.NAME, A.GRP_CD, A.SORT, A.CNTR_TPSZ_CD, A.FCAST_YRWK FROM SIM_SS_DATA A WHERE A.GRP_CD='5') A," ).append("\n"); 
		query.append("            (" ).append("\n"); 
		query.append("                SELECT /*+ ORDERED USE_NL(O L T S) INDEX( L XAK1MDM_LOCATION ) */" ).append("\n"); 
		query.append("                #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("                    L.LOC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '3') --RCC (by LCC)" ).append("\n"); 
		query.append("                    O.LCC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("                    O.ECC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("                    O.SCC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("                    O.SCC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("                    L.LOC_CD" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '8') --RCC (by ECC)" ).append("\n"); 
		query.append("                    O.ECC_CD" ).append("\n"); 
		query.append("                #end    " ).append("\n"); 
		query.append("                    LOC_CD," ).append("\n"); 
		query.append("                    S.CNTR_TPSZ_CD," ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN SUM(T.IB_QTY) >= SUM(T.OB_QTY) THEN ROUND(SUM(T.OB_QTY) / SUM(T.IB_QTY) * 100)" ).append("\n"); 
		query.append("                    WHEN SUM(T.OB_QTY) >0 THEN ROUND( SUM (T.IB_QTY) / SUM (T.OB_QTY) * -1 * 100)" ).append("\n"); 
		query.append("                    ELSE 0" ).append("\n"); 
		query.append("                    END AS MB" ).append("\n"); 
		query.append("                    ,(SELECT MAX(W.PLN_YR||W.PLN_WK) WK FROM EQR_WK_PRD W WHERE T.TGT_MVMT_DT BETWEEN W.WK_ST_DT AND W.WK_END_DT) FCAST_YRWK" ).append("\n"); 
		query.append("                FROM MDM_EQ_ORZ_CHT O, MDM_LOCATION L, CIM_LOC_MTCH_BAK_SMRY T, CIM_TP_SZ_DP_SEQ S--, EQR_WK_PRD W" ).append("\n"); 
		query.append("                WHERE 1=1" ).append("\n"); 
		query.append("                    AND T.TGT_MVMT_DT BETWEEN (SELECT MIN(W.WK_ST_DT) WK_ST_DT FROM EQR_WK_PRD W WHERE W.PLN_YR||W.PLN_WK BETWEEN @[fm_yrwk] AND @[to_yrwk])" ).append("\n"); 
		query.append("                                      AND     (SELECT MAX(W.WK_END_DT) WK_END_DT FROM EQR_WK_PRD W WHERE W.PLN_YR||W.PLN_WK BETWEEN @[fm_yrwk] AND @[to_yrwk])" ).append("\n"); 
		query.append("                    AND T.CNTR_TPSZ_CD = S.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                    AND T.LOC_CD = L.LOC_CD" ).append("\n"); 
		query.append("                    AND L.SCC_CD = O.SCC_CD" ).append("\n"); 
		query.append("                    AND NVL(O.DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("                    AND NVL(L.DELT_FLG,'N') <> 'Y'" ).append("\n"); 
		query.append("                    AND T.FULL_MTY_CD = 'F'" ).append("\n"); 
		query.append("                    AND T.MVMT_CO_CD IN ('H','S')" ).append("\n"); 
		query.append("                    AND S.CNTR_TPSZ_DIV_CD = DECODE('A', 'A', S.CNTR_TPSZ_DIV_CD, 'A')" ).append("\n"); 
		query.append("                    AND T.ENR_FLG = 'N'" ).append("\n"); 
		query.append("                    AND T.TN_ROUT_FLG = 'N'" ).append("\n"); 
		query.append("                    AND T.SOC_FLG = 'N'" ).append("\n"); 
		query.append("                    AND S.CNTR_TPSZ_CD IN ('D2','D4','D5','D7','R2','R5','R9','O2','O4','S2','S4','F2','F4','F5','A2','A4','A5')" ).append("\n"); 
		query.append("                #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("                    AND O.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '3') --RCC (by LCC)          " ).append("\n"); 
		query.append("                    AND O.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("                    AND O.LCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("                    AND O.LCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("                    AND O.ECC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("                    AND O.SCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #elseif (${loc_type_code} == '8') --RCC (by ECC)          " ).append("\n"); 
		query.append("                    AND O.RCC_CD =@[loc_cd]" ).append("\n"); 
		query.append("                #end                       " ).append("\n"); 
		query.append("                    GROUP BY " ).append("\n"); 
		query.append("                    #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("                        L.LOC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '3') --RCC (by LCC)          " ).append("\n"); 
		query.append("                        O.LCC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '4') --LCC (by ECC)" ).append("\n"); 
		query.append("                        O.ECC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '5') --LCC (by SCC)" ).append("\n"); 
		query.append("                        O.SCC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '6') --ECC (by SCC)" ).append("\n"); 
		query.append("                        O.SCC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("                        L.LOC_CD" ).append("\n"); 
		query.append("                    #elseif (${loc_type_code} == '8') --RCC (by ECC)          " ).append("\n"); 
		query.append("                        O.ECC_CD" ).append("\n"); 
		query.append("                    #end         " ).append("\n"); 
		query.append("                        , S.CNTR_TPSZ_CD, T.TGT_MVMT_DT" ).append("\n"); 
		query.append("            ) MB" ).append("\n"); 
		query.append("            WHERE 1=1" ).append("\n"); 
		query.append("            #if (${loc_type_code} == '2') --RCC (by Country)" ).append("\n"); 
		query.append("                AND SUBSTR(A.LOC_CD,1,2) = MB.LOC_CD(+)" ).append("\n"); 
		query.append("            #elseif (${loc_type_code} == '7') --SCC (by Yard)" ).append("\n"); 
		query.append("                AND SUBSTR(A.LOC_CD,1,5) = MB.LOC_CD(+)" ).append("\n"); 
		query.append("            #else" ).append("\n"); 
		query.append("                AND A.LOC_CD = MB.LOC_CD(+)" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("            AND A.CNTR_TPSZ_CD = MB.CNTR_TPSZ_CD(+)" ).append("\n"); 
		query.append("            AND A.FCAST_YRWK = MB.FCAST_YRWK(+)" ).append("\n"); 
		query.append("            GROUP BY A.LOC_CD, A.CODE, A.NAME, A.GRP_CD, A.SORT, A.CNTR_TPSZ_CD, A.FCAST_YRWK" ).append("\n"); 
		query.append("            #end " ).append("\n"); 
		query.append("        ) X" ).append("\n"); 
		query.append("    WHERE 1=1" ).append("\n"); 
		query.append(") R" ).append("\n"); 
		query.append("GROUP BY GROUPING SETS ((R.GRP_CD, R.SORT, R.CODE, R.NAME, R.CNTR_TPSZ_CD, R.FCAST_YRWK),(R.LOC_CD, R.GRP_CD, R.SORT, R.CODE, R.NAME, R.CNTR_TPSZ_CD, R.FCAST_YRWK))" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("GROUP BY A.LOC_CD, A.CODE, A.NAME, A.GRP_CD, A.SORT" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("ORDER BY CASE WHEN A.LOC_CD ='TTL' THEN 'AAAAA' ELSE A.LOC_CD END, A.GRP_CD, A.SORT" ).append("\n"); 

	}
}