/*=========================================================
*Copyright(c) 2012 CyberLogitec
*@FileName : DemandNoteSendDBDAOSearchDemandNoteIssueMstPreviewRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2012.07.12
*@LastModifier : KIM HYUN HWA
*@LastVersion : 1.0
* 2012.07.12 KIM HYUN HWA
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.ees.dmt.dmtinvoicemgt.demandnotesend.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author ISD1
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class DemandNoteSendDBDAOSearchDemandNoteIssueMstPreviewRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * SearchDemandNoteIssueMstPreview
	  * </pre>
	  */
	public DemandNoteSendDBDAOSearchDemandNoteIssueMstPreviewRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("payer_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("dmdt_trf_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("session_usr_id",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("session_ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.ees.dmt.dmtinvoicemgt.demandnotesend.integration").append("\n"); 
		query.append("FileName : DemandNoteSendDBDAOSearchDemandNoteIssueMstPreviewRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("#if (${call_to_rd_tp} == 'group') " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("SELECT MAX (CUST_VAT) AS CUST_VAT" ).append("\n"); 
		query.append("      ,MAX (ADDRESS01) AS ADDRESS01" ).append("\n"); 
		query.append("      ,MAX (OFC_ADD01) AS OFC_ADD01" ).append("\n"); 
		query.append("      ,MAX (OFC_ADD02) AS OFC_ADD02" ).append("\n"); 
		query.append("      ,MAX (OFC_ADD03) AS OFC_ADD03" ).append("\n"); 
		query.append("      ,MAX (HEADER01) AS HEADER01" ).append("\n"); 
		query.append("      ,MAX (HEADER02) AS HEADER02" ).append("\n"); 
		query.append("      ,MAX (HEADER03) AS HEADER03" ).append("\n"); 
		query.append("      ,MAX (HEADER04) AS HEADER04" ).append("\n"); 
		query.append("      ,MAX (HEADER05) AS HEADER05" ).append("\n"); 
		query.append("      ,MAX (HEADER06) AS HEADER06" ).append("\n"); 
		query.append("      ,MAX (HEADER07) AS HEADER07" ).append("\n"); 
		query.append("      ,MAX (HEADER08) AS HEADER08" ).append("\n"); 
		query.append("      ,MAX (HEADER09) AS HEADER09" ).append("\n"); 
		query.append("      ,MAX (HEADER10) AS HEADER10" ).append("\n"); 
		query.append("      ,MAX (SH_NUM) AS SH_NUM" ).append("\n"); 
		query.append("      ,MAX (HJS_REF) AS HJS_REF" ).append("\n"); 
		query.append("      ,MAX (PRINT_DATE) AS PRINT_DATE" ).append("\n"); 
		query.append("      ,MAX (DMDT_TRF_NM) AS DMDT_TRF_NM" ).append("\n"); 
		query.append("      ,MAX (TITLE) AS TITLE" ).append("\n"); 
		query.append("	  ,MAX (TAX_NM) AS TAX_NM" ).append("\n"); 
		query.append("  FROM (SELECT CUST.CUST_RGST_NO AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS HEADER06" ).append("\n"); 
		query.append("              ,'' AS HEADER07" ).append("\n"); 
		query.append("              ,'' AS HEADER08" ).append("\n"); 
		query.append("              ,'' AS HEADER09" ).append("\n"); 
		query.append("              ,'' AS HEADER10" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("              ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("              ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM MDM_CUSTOMER CUST" ).append("\n"); 
		query.append("         WHERE CUST.CUST_CNT_CD = SUBSTR (@[payer_cd]" ).append("\n"); 
		query.append("                                         ,1" ).append("\n"); 
		query.append("                                         ,2" ).append("\n"); 
		query.append("                                         )" ).append("\n"); 
		query.append("           AND CUST.CUST_SEQ = SUBSTR (@[payer_cd]" ).append("\n"); 
		query.append("                                      ,3" ).append("\n"); 
		query.append("                                      ,6" ).append("\n"); 
		query.append("                                      )" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("			  , (" ).append("\n"); 
		query.append("                SELECT CUST_NM || '|' || ADDRESS01 " ).append("\n"); 
		query.append("                FROM (" ).append("\n"); 
		query.append("                    SELECT DMDT_PAYR_NM AS CUST_NM" ).append("\n"); 
		query.append("                          ,REPLACE (DMDT_PAYR_ADDR" ).append("\n"); 
		query.append("                                   ,'@*'" ).append("\n"); 
		query.append("                                   , CHR (13)" ).append("\n"); 
		query.append("                                     || CHR (10)" ).append("\n"); 
		query.append("                                   ) AS ADDRESS01" ).append("\n"); 
		query.append("                          , 1 AS SORT         " ).append("\n"); 
		query.append("                      FROM DMT_PAYR_INFO" ).append("\n"); 
		query.append("                     WHERE SYS_AREA_GRP_ID =" ).append("\n"); 
		query.append("                                 (SELECT SYS_AREA_GRP_ID" ).append("\n"); 
		query.append("                                    FROM COM_SYS_AREA_GRP_ID" ).append("\n"); 
		query.append("                                   WHERE CNT_CD = (SELECT SUBSTR (LOC_CD" ).append("\n"); 
		query.append("                                                                 ,1" ).append("\n"); 
		query.append("                                                                 ,2" ).append("\n"); 
		query.append("                                                                 )" ).append("\n"); 
		query.append("                                                     FROM MDM_ORGANIZATION" ).append("\n"); 
		query.append("                                                    WHERE OFC_CD = @[session_ofc_cd])" ).append("\n"); 
		query.append("                                     AND CO_IND_CD = 'H')" ).append("\n"); 
		query.append("                       AND CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                       AND CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                    UNION ALL" ).append("\n"); 
		query.append("                    SELECT LOCL_NM AS CUST_NM" ).append("\n"); 
		query.append("                            ,TRIM (LOCL_ADDR1)" ).append("\n"); 
		query.append("                           || CHR (13)" ).append("\n"); 
		query.append("                           || CHR (10)" ).append("\n"); 
		query.append("                           || TRIM (LOCL_ADDR2)" ).append("\n"); 
		query.append("                           || CHR (13)" ).append("\n"); 
		query.append("                           || CHR (10)" ).append("\n"); 
		query.append("                           || TRIM (LOCL_ADDR3)" ).append("\n"); 
		query.append("                           || CHR (13)" ).append("\n"); 
		query.append("                           || CHR (10)" ).append("\n"); 
		query.append("                           || TRIM (LOCL_ADDR4)" ).append("\n"); 
		query.append("                           || ' '" ).append("\n"); 
		query.append("                           || LOCL_ZIP_CD AS ADDRESS01" ).append("\n"); 
		query.append("                           , 2 AS SORT " ).append("\n"); 
		query.append("                      FROM MDM_CR_CUST" ).append("\n"); 
		query.append("                     WHERE CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                       AND CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                       AND LOCL_NM IS NOT NULL" ).append("\n"); 
		query.append("                    UNION ALL   " ).append("\n"); 
		query.append("                    SELECT CASE" ).append("\n"); 
		query.append("                              WHEN SUBSTR (@[payer_cd] ,1 ,2) = '00'" ).append("\n"); 
		query.append("                                 THEN (SELECT VNDR_LGL_ENG_NM" ).append("\n"); 
		query.append("                                         FROM MDM_VENDOR" ).append("\n"); 
		query.append("                                        WHERE VNDR_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                                          AND VNDR_LGL_ENG_NM IS NOT NULL)" ).append("\n"); 
		query.append("                              ELSE (SELECT CUST_LGL_ENG_NM" ).append("\n"); 
		query.append("                                      FROM MDM_CUSTOMER" ).append("\n"); 
		query.append("                                     WHERE CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                                       AND CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                                       AND CUST_LGL_ENG_NM IS NOT NULL)" ).append("\n"); 
		query.append("                           END AS CUST_NM" ).append("\n"); 
		query.append("                          ,CASE" ).append("\n"); 
		query.append("                              WHEN SUBSTR (@[payer_cd] ,1 ,2) = '00'" ).append("\n"); 
		query.append("                                 THEN (SELECT ZIP_CD" ).append("\n"); 
		query.append("                                              || ','" ).append("\n"); 
		query.append("                                              || REPLACE (ENG_ADDR" ).append("\n"); 
		query.append("                                                         ,'@*'" ).append("\n"); 
		query.append("                                                         , CHR (13)" ).append("\n"); 
		query.append("                                                           || CHR (10)" ).append("\n"); 
		query.append("                                                         )" ).append("\n"); 
		query.append("                                         FROM MDM_VENDOR" ).append("\n"); 
		query.append("                                        WHERE VNDR_SEQ = SUBSTR (@[payer_cd] ,3 ,6))" ).append("\n"); 
		query.append("                              ELSE (SELECT CASE" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 1" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 2" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 3" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 4" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.STE_CD" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 5" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 6" ).append("\n"); 
		query.append("                                                 THEN ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                                 ,'@*'" ).append("\n"); 
		query.append("                                                                 , CHR (13)" ).append("\n"); 
		query.append("                                                                   || CHR (10)" ).append("\n"); 
		query.append("                                                                 )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              ELSE REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                                 ,'@*'" ).append("\n"); 
		query.append("                                                                 , CHR (13)" ).append("\n"); 
		query.append("                                                                   || CHR (10)" ).append("\n"); 
		query.append("                                                                 ) " ).append("\n"); 
		query.append("                                                   || ' '" ).append("\n"); 
		query.append("                                                   || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                   || ' '" ).append("\n"); 
		query.append("                                                   || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                           END" ).append("\n"); 
		query.append("                                      FROM MDM_CUST_ADDR ADDR" ).append("\n"); 
		query.append("                                          ,MDM_COUNTRY CN" ).append("\n"); 
		query.append("                                     WHERE ADDR.CUST_CNT_CD = CN.CNT_CD(+)" ).append("\n"); 
		query.append("									   AND ADDR.PRMRY_CHK_FLG = 'Y'" ).append("\n"); 
		query.append("                                       AND ADDR.CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                                       AND ADDR.CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("									   AND ROWNUM = 1 )" ).append("\n"); 
		query.append("                           END AS ADDRESS01" ).append("\n"); 
		query.append("                           , 3 AS SORT " ).append("\n"); 
		query.append("                      FROM DUAL" ).append("\n"); 
		query.append("                      ORDER BY SORT   " ).append("\n"); 
		query.append("                    ) " ).append("\n"); 
		query.append("                    WHERE ROWNUM < 2" ).append("\n"); 
		query.append("                )  AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS HEADER06" ).append("\n"); 
		query.append("              ,'' AS HEADER07" ).append("\n"); 
		query.append("              ,'' AS HEADER08" ).append("\n"); 
		query.append("              ,'' AS HEADER09" ).append("\n"); 
		query.append("              ,'' AS HEADER10" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("              ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DUAL" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT      " ).append("\n"); 
		query.append("			  ,'' AS ADDRESS01        " ).append("\n"); 
		query.append("              ,REPLACE(B.SH_ADDR1,'@*',CHR(13)||CHR(10)) AS OFC_ADD01" ).append("\n"); 
		query.append("              ,REPLACE(B.SH_ADDR2,'@*',CHR(13)||CHR(10)) AS OFC_ADD02" ).append("\n"); 
		query.append("              ,REPLACE(B.SH_ADDR3,'@*',CHR(13)||CHR(10)) AS OFC_ADD03" ).append("\n"); 
		query.append("              ,B.SH_HD_N1ST_MSG AS HEADER01" ).append("\n"); 
		query.append("              ,B.SH_HD_N2ND_MSG AS HEADER02" ).append("\n"); 
		query.append("              ,B.SH_HD_N3RD_MSG AS HEADER03" ).append("\n"); 
		query.append("              ,B.SH_HD_N4TH_MSG AS HEADER04" ).append("\n"); 
		query.append("              ,B.SH_HD_N5TH_MSG AS HEADER05" ).append("\n"); 
		query.append("              ,B.SH_HD_N6TH_MSG AS HEADER06" ).append("\n"); 
		query.append("              ,B.SH_HD_N7TH_MSG AS HEADER07" ).append("\n"); 
		query.append("              ,B.SH_HD_N8TH_MSG AS HEADER08" ).append("\n"); 
		query.append("              ,B.SH_HD_N9TH_MSG AS HEADER09" ).append("\n"); 
		query.append("              ,B.SH_HD_N10TH_MSG AS HEADER10" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("              ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DMT_SH_SET B" ).append("\n"); 
		query.append("         WHERE B.OFC_CD = @[session_ofc_cd]" ).append("\n"); 
		query.append("           AND B.DMDT_TRF_CD = @[dmdt_trf_cd]" ).append("\n"); 
		query.append("           AND B.DMDT_SH_TP_CD = 'G'" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS HEADER06" ).append("\n"); 
		query.append("              ,'' AS HEADER07" ).append("\n"); 
		query.append("              ,'' AS HEADER08" ).append("\n"); 
		query.append("              ,'' AS HEADER09" ).append("\n"); 
		query.append("              ,'' AS HEADER10" ).append("\n"); 
		query.append("              ,SH.BIL_TO_LOC_DIV_CD||'|'||SH.CUST_REF_PRN_FLG||'|'||SH.PHN_FAX_PRN_FLG||'|'||SH.CUST_VAT_PRN_FLG||'|'||SH.TAX_AMT_PRN_FLG||'|'||SH.DC_AMT_FLG AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("              ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DMT_OFC_SH_OPT SH" ).append("\n"); 
		query.append("         WHERE SH.OFC_CD = @[session_ofc_cd]" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS HEADER06" ).append("\n"); 
		query.append("              ,'' AS HEADER07" ).append("\n"); 
		query.append("              ,'' AS HEADER08" ).append("\n"); 
		query.append("              ,'' AS HEADER09" ).append("\n"); 
		query.append("              ,'' AS HEADER10" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,USR_NM AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("              ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM COM_USER" ).append("\n"); 
		query.append("         WHERE USR_ID = @[session_usr_id]" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS HEADER06" ).append("\n"); 
		query.append("              ,'' AS HEADER07" ).append("\n"); 
		query.append("              ,'' AS HEADER08" ).append("\n"); 
		query.append("              ,'' AS HEADER09" ).append("\n"); 
		query.append("              ,'' AS HEADER10" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,TO_CHAR (NVL (GLOBALDATE_PKG.TIME_LOCAL_OFC_FNC (@[session_ofc_cd])" ).append("\n"); 
		query.append("                            ,SYSDATE)" ).append("\n"); 
		query.append("                       ,'DDMonYY', 'NLS_DATE_LANGUAGE = American') AS PRINT_DATE" ).append("\n"); 
		query.append("              ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DUAL" ).append("\n"); 
		query.append("          UNION ALL" ).append("\n"); 
		query.append("          SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS HEADER06" ).append("\n"); 
		query.append("              ,'' AS HEADER07" ).append("\n"); 
		query.append("              ,'' AS HEADER08" ).append("\n"); 
		query.append("              ,'' AS HEADER09" ).append("\n"); 
		query.append("              ,'' AS HEADER10" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("              ,DMDT_TRF_NM AS DMDT_TRF_NM " ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("           FROM DMT_TRF_TP" ).append("\n"); 
		query.append("          WHERE DMDT_TRF_CD = @[dmdt_trf_cd]" ).append("\n"); 
		query.append("		  UNION ALL" ).append("\n"); 
		query.append("		SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("		      ,'' AS ADDRESS01" ).append("\n"); 
		query.append("		      ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("		      ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("		      ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("		      ,'' AS HEADER01" ).append("\n"); 
		query.append("		      ,'' AS HEADER02" ).append("\n"); 
		query.append("		      ,'' AS HEADER03" ).append("\n"); 
		query.append("		      ,'' AS HEADER04" ).append("\n"); 
		query.append("		      ,'' AS HEADER05" ).append("\n"); 
		query.append("		      ,'' AS HEADER06" ).append("\n"); 
		query.append("		      ,'' AS HEADER07" ).append("\n"); 
		query.append("		      ,'' AS HEADER08" ).append("\n"); 
		query.append("		      ,'' AS HEADER09" ).append("\n"); 
		query.append("		      ,'' AS HEADER10" ).append("\n"); 
		query.append("		      ,'' AS SH_NUM" ).append("\n"); 
		query.append("		      ,'' AS HJS_REF" ).append("\n"); 
		query.append("		      ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("		      ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("		      ,NVL ((SELECT AA.CSTMZ_TIT_DESC" ).append("\n"); 
		query.append("		               FROM DMT_CSTMZ_TIT_OPT AA" ).append("\n"); 
		query.append("		                   ,DMT_CSTMZ_TIT_TRF_OPT BB" ).append("\n"); 
		query.append("		              WHERE AA.OFC_CD = BB.OFC_CD(+)" ).append("\n"); 
		query.append("		                AND AA.CR_TERM_SEQ = BB.CR_TERM_SEQ(+)" ).append("\n"); 
		query.append("		                AND AA.OFC_CD = @[session_ofc_cd]" ).append("\n"); 
		query.append("		                AND BB.DMDT_TRF_CD = @[dmdt_trf_cd]" ).append("\n"); 
		query.append("		                AND AA.DMDT_SH_TP_CD = 'G')" ).append("\n"); 
		query.append("		           ,'DEMAND') AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("		  FROM DUAL " ).append("\n"); 
		query.append("		 UNION ALL" ).append("\n"); 
		query.append("		SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("		      ,'' AS ADDRESS01" ).append("\n"); 
		query.append("		      ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("		      ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("		      ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("		      ,'' AS HEADER01" ).append("\n"); 
		query.append("		      ,'' AS HEADER02" ).append("\n"); 
		query.append("		      ,'' AS HEADER03" ).append("\n"); 
		query.append("		      ,'' AS HEADER04" ).append("\n"); 
		query.append("		      ,'' AS HEADER05" ).append("\n"); 
		query.append("		      ,'' AS HEADER06" ).append("\n"); 
		query.append("		      ,'' AS HEADER07" ).append("\n"); 
		query.append("		      ,'' AS HEADER08" ).append("\n"); 
		query.append("		      ,'' AS HEADER09" ).append("\n"); 
		query.append("		      ,'' AS HEADER10" ).append("\n"); 
		query.append("		      ,'' AS SH_NUM" ).append("\n"); 
		query.append("		      ,'' AS HJS_REF" ).append("\n"); 
		query.append("		      ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("		      ,'' AS DMDT_TRF_NM" ).append("\n"); 
		query.append("		      ,'' TITLE			  " ).append("\n"); 
		query.append("              ,( SELECT DECODE(SUBSTR(LOC_CD,1,2), 'AU' , 'GST' ,'IN' ,'TAX', 'VAT') AS TAX_NM" ).append("\n"); 
		query.append("                  FROM MDM_ORGANIZATION" ).append("\n"); 
		query.append("                 WHERE OFC_CD = @[session_ofc_cd] ) AS TAX_NM" ).append("\n"); 
		query.append("		  FROM DUAL " ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("SELECT MAX (CUST_VAT) AS CUST_VAT" ).append("\n"); 
		query.append("      ,MAX (ADDRESS01) AS ADDRESS01" ).append("\n"); 
		query.append("      ,MAX (OFC_ADD01) AS OFC_ADD01" ).append("\n"); 
		query.append("      ,MAX (OFC_ADD02) AS OFC_ADD02" ).append("\n"); 
		query.append("      ,MAX (OFC_ADD03) AS OFC_ADD03" ).append("\n"); 
		query.append("      ,MAX (HEADER01) AS HEADER01" ).append("\n"); 
		query.append("      ,MAX (HEADER02) AS HEADER02" ).append("\n"); 
		query.append("      ,MAX (HEADER03) AS HEADER03" ).append("\n"); 
		query.append("      ,MAX (HEADER04) AS HEADER04" ).append("\n"); 
		query.append("      ,MAX (HEADER05) AS HEADER05" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK01) AS SHEET_REMARK01" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK02) AS SHEET_REMARK02" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK03) AS SHEET_REMARK03" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK04) AS SHEET_REMARK04" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK05) AS SHEET_REMARK05" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK06) AS SHEET_REMARK06" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK07) AS SHEET_REMARK07" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK08) AS SHEET_REMARK08" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK09) AS SHEET_REMARK09" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK10) AS SHEET_REMARK10" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK11) AS SHEET_REMARK11" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK12) AS SHEET_REMARK12" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK13) AS SHEET_REMARK13" ).append("\n"); 
		query.append("      ,MAX (SHEET_REMARK14) AS SHEET_REMARK14" ).append("\n"); 
		query.append("      ,MAX (SH_NUM) AS SH_NUM" ).append("\n"); 
		query.append("      ,MAX (HJS_REF) AS HJS_REF" ).append("\n"); 
		query.append("      ,MAX (PRINT_DATE) AS PRINT_DATE  " ).append("\n"); 
		query.append("      ,MAX (TITLE) AS TITLE    " ).append("\n"); 
		query.append("	  ,MAX (TAX_NM) AS TAX_NM" ).append("\n"); 
		query.append("  FROM (SELECT CUST.CUST_RGST_NO AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM MDM_CUSTOMER CUST" ).append("\n"); 
		query.append("         WHERE CUST.CUST_CNT_CD = SUBSTR (@[payer_cd]" ).append("\n"); 
		query.append("                                         ,1" ).append("\n"); 
		query.append("                                         ,2" ).append("\n"); 
		query.append("                                         )" ).append("\n"); 
		query.append("           AND CUST.CUST_SEQ = SUBSTR (@[payer_cd]" ).append("\n"); 
		query.append("                                      ,3" ).append("\n"); 
		query.append("                                      ,6" ).append("\n"); 
		query.append("                                      )" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              , (" ).append("\n"); 
		query.append("                SELECT CUST_NM || '|' || ADDRESS01 " ).append("\n"); 
		query.append("                FROM (" ).append("\n"); 
		query.append("                    SELECT DMDT_PAYR_NM AS CUST_NM" ).append("\n"); 
		query.append("                          ,REPLACE (DMDT_PAYR_ADDR" ).append("\n"); 
		query.append("                                   ,'@*'" ).append("\n"); 
		query.append("                                   , CHR (13)" ).append("\n"); 
		query.append("                                     || CHR (10)" ).append("\n"); 
		query.append("                                   ) AS ADDRESS01" ).append("\n"); 
		query.append("                          , 1 AS SORT         " ).append("\n"); 
		query.append("                      FROM DMT_PAYR_INFO" ).append("\n"); 
		query.append("                     WHERE SYS_AREA_GRP_ID =" ).append("\n"); 
		query.append("                                 (SELECT SYS_AREA_GRP_ID" ).append("\n"); 
		query.append("                                    FROM COM_SYS_AREA_GRP_ID" ).append("\n"); 
		query.append("                                   WHERE CNT_CD = (SELECT SUBSTR (LOC_CD" ).append("\n"); 
		query.append("                                                                 ,1" ).append("\n"); 
		query.append("                                                                 ,2" ).append("\n"); 
		query.append("                                                                 )" ).append("\n"); 
		query.append("                                                     FROM MDM_ORGANIZATION" ).append("\n"); 
		query.append("                                                    WHERE OFC_CD = @[session_ofc_cd])" ).append("\n"); 
		query.append("                                     AND CO_IND_CD = 'H')" ).append("\n"); 
		query.append("                       AND CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                       AND CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                    UNION ALL" ).append("\n"); 
		query.append("                    SELECT LOCL_NM AS CUST_NM" ).append("\n"); 
		query.append("                            ,TRIM (LOCL_ADDR1)" ).append("\n"); 
		query.append("                           || CHR (13)" ).append("\n"); 
		query.append("                           || CHR (10)" ).append("\n"); 
		query.append("                           || TRIM (LOCL_ADDR2)" ).append("\n"); 
		query.append("                           || CHR (13)" ).append("\n"); 
		query.append("                           || CHR (10)" ).append("\n"); 
		query.append("                           || TRIM (LOCL_ADDR3)" ).append("\n"); 
		query.append("                           || CHR (13)" ).append("\n"); 
		query.append("                           || CHR (10)" ).append("\n"); 
		query.append("                           || TRIM (LOCL_ADDR4)" ).append("\n"); 
		query.append("                           || ' '" ).append("\n"); 
		query.append("                           || LOCL_ZIP_CD AS ADDRESS01" ).append("\n"); 
		query.append("                           , 2 AS SORT " ).append("\n"); 
		query.append("                      FROM MDM_CR_CUST" ).append("\n"); 
		query.append("                     WHERE CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                       AND CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                       AND LOCL_NM IS NOT NULL" ).append("\n"); 
		query.append("                    UNION ALL   " ).append("\n"); 
		query.append("                    SELECT CASE" ).append("\n"); 
		query.append("                              WHEN SUBSTR (@[payer_cd] ,1 ,2) = '00'" ).append("\n"); 
		query.append("                                 THEN (SELECT VNDR_LGL_ENG_NM" ).append("\n"); 
		query.append("                                         FROM MDM_VENDOR" ).append("\n"); 
		query.append("                                        WHERE VNDR_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                                          AND VNDR_LGL_ENG_NM IS NOT NULL)" ).append("\n"); 
		query.append("                              ELSE (SELECT CUST_LGL_ENG_NM" ).append("\n"); 
		query.append("                                      FROM MDM_CUSTOMER" ).append("\n"); 
		query.append("                                     WHERE CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                                       AND CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("                                       AND CUST_LGL_ENG_NM IS NOT NULL)" ).append("\n"); 
		query.append("                           END AS CUST_NM" ).append("\n"); 
		query.append("                          ,CASE" ).append("\n"); 
		query.append("                              WHEN SUBSTR (@[payer_cd] ,1 ,2) = '00'" ).append("\n"); 
		query.append("                                 THEN (SELECT ZIP_CD" ).append("\n"); 
		query.append("                                              || ','" ).append("\n"); 
		query.append("                                              || REPLACE (ENG_ADDR" ).append("\n"); 
		query.append("                                                         ,'@*'" ).append("\n"); 
		query.append("                                                         , CHR (13)" ).append("\n"); 
		query.append("                                                           || CHR (10)" ).append("\n"); 
		query.append("                                                         )" ).append("\n"); 
		query.append("                                         FROM MDM_VENDOR" ).append("\n"); 
		query.append("                                        WHERE VNDR_SEQ = SUBSTR (@[payer_cd] ,3 ,6))" ).append("\n"); 
		query.append("                              ELSE (SELECT CASE" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 1" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 2" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 3" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 4" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.STE_CD" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 5" ).append("\n"); 
		query.append("                                                 THEN REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                              ,'@*'" ).append("\n"); 
		query.append("                                                              , CHR (13)" ).append("\n"); 
		query.append("                                                                || CHR (10)" ).append("\n"); 
		query.append("                                                              )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              WHEN CN.BKG_ADDR_ORD_CD = 6" ).append("\n"); 
		query.append("                                                 THEN ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                                 ,'@*'" ).append("\n"); 
		query.append("                                                                 , CHR (13)" ).append("\n"); 
		query.append("                                                                   || CHR (10)" ).append("\n"); 
		query.append("                                                                 )" ).append("\n"); 
		query.append("                                                      || ' '" ).append("\n"); 
		query.append("                                                      || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                              ELSE REPLACE (ADDR.BZET_ADDR" ).append("\n"); 
		query.append("                                                                 ,'@*'" ).append("\n"); 
		query.append("                                                                 , CHR (13)" ).append("\n"); 
		query.append("                                                                   || CHR (10)" ).append("\n"); 
		query.append("                                                                 )" ).append("\n"); 
		query.append("                                                   || ' '" ).append("\n"); 
		query.append("                                                   || ADDR.CTY_NM" ).append("\n"); 
		query.append("                                                   || ' '" ).append("\n"); 
		query.append("                                                   || ADDR.ZIP_CD" ).append("\n"); 
		query.append("                                           END" ).append("\n"); 
		query.append("                                      FROM MDM_CUST_ADDR ADDR" ).append("\n"); 
		query.append("                                          ,MDM_COUNTRY CN" ).append("\n"); 
		query.append("                                     WHERE ADDR.CUST_CNT_CD = CN.CNT_CD(+)" ).append("\n"); 
		query.append("									   AND ADDR.PRMRY_CHK_FLG = 'Y'" ).append("\n"); 
		query.append("                                       AND ADDR.CUST_CNT_CD = SUBSTR (@[payer_cd] ,1 ,2)" ).append("\n"); 
		query.append("                                       AND ADDR.CUST_SEQ = SUBSTR (@[payer_cd] ,3 ,6)" ).append("\n"); 
		query.append("									   AND ROWNUM = 1)" ).append("\n"); 
		query.append("                           END AS ADDRESS01" ).append("\n"); 
		query.append("                           , 3 AS SORT " ).append("\n"); 
		query.append("                      FROM DUAL" ).append("\n"); 
		query.append("                      ORDER BY SORT   " ).append("\n"); 
		query.append("                    ) " ).append("\n"); 
		query.append("                    WHERE ROWNUM < 2" ).append("\n"); 
		query.append("                )  AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DUAL" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,REPLACE(B.SH_ADDR1,'@*',CHR(13)||CHR(10)) AS OFC_ADD01" ).append("\n"); 
		query.append("              ,REPLACE(B.SH_ADDR2,'@*',CHR(13)||CHR(10)) AS OFC_ADD02" ).append("\n"); 
		query.append("              ,REPLACE(B.SH_ADDR3,'@*',CHR(13)||CHR(10)) AS OFC_ADD03" ).append("\n"); 
		query.append("              ,B.SH_HD_N1ST_MSG AS HEADER01" ).append("\n"); 
		query.append("              ,B.SH_HD_N2ND_MSG AS HEADER02" ).append("\n"); 
		query.append("              ,B.SH_HD_N3RD_MSG AS HEADER03" ).append("\n"); 
		query.append("              ,B.SH_HD_N4TH_MSG AS HEADER04" ).append("\n"); 
		query.append("              ,B.SH_HD_N5TH_MSG AS HEADER05" ).append("\n"); 
		query.append("              ,B.SH_RMK1 AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,B.SH_RMK2 AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,B.SH_RMK3 AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,B.SH_RMK4 AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,B.SH_RMK5 AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,B.SH_RMK6 AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,B.SH_RMK7 AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,B.SH_RMK8 AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,B.SH_RMK9 AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,B.SH_RMK10 AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,B.SH_RMK11 AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,B.SH_RMK12 AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,B.SH_RMK13 AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,B.SH_RMK14 AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DMT_SH_SET B" ).append("\n"); 
		query.append("         WHERE B.OFC_CD = @[session_ofc_cd]" ).append("\n"); 
		query.append("           AND B.DMDT_TRF_CD = @[dmdt_trf_cd]" ).append("\n"); 
		query.append("           AND B.DMDT_SH_TP_CD = 'D'" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,SH.BIL_TO_LOC_DIV_CD||'|'||SH.CUST_REF_PRN_FLG||'|'||SH.PHN_FAX_PRN_FLG||'|'||SH.CUST_VAT_PRN_FLG||'|'||SH.TAX_AMT_PRN_FLG||'|'||SH.DC_AMT_FLG AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DMT_OFC_SH_OPT SH" ).append("\n"); 
		query.append("         WHERE SH.OFC_CD = @[session_ofc_cd]" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,USR_NM AS HJS_REF" ).append("\n"); 
		query.append("              ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM COM_USER" ).append("\n"); 
		query.append("         WHERE USR_ID = @[session_usr_id]" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("              ,TO_CHAR (NVL (GLOBALDATE_PKG.TIME_LOCAL_OFC_FNC (@[session_ofc_cd])" ).append("\n"); 
		query.append("                            ,SYSDATE)" ).append("\n"); 
		query.append("                       ,'DDMonYY', 'NLS_DATE_LANGUAGE = American') AS PRINT_DATE" ).append("\n"); 
		query.append("			  ,'' AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("          FROM DUAL" ).append("\n"); 
		query.append("		  UNION ALL" ).append("\n"); 
		query.append("		SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("			  ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("		      ,NVL ((SELECT AA.CSTMZ_TIT_DESC" ).append("\n"); 
		query.append("		               FROM DMT_CSTMZ_TIT_OPT AA" ).append("\n"); 
		query.append("		                   ,DMT_CSTMZ_TIT_TRF_OPT BB" ).append("\n"); 
		query.append("		              WHERE AA.OFC_CD = BB.OFC_CD(+)" ).append("\n"); 
		query.append("		                AND AA.CR_TERM_SEQ = BB.CR_TERM_SEQ(+)" ).append("\n"); 
		query.append("		                AND AA.OFC_CD = @[session_ofc_cd]" ).append("\n"); 
		query.append("		                AND BB.DMDT_TRF_CD = @[dmdt_trf_cd]" ).append("\n"); 
		query.append("		                AND AA.DMDT_SH_TP_CD = 'D')" ).append("\n"); 
		query.append("		           ,'DEMAND') AS TITLE" ).append("\n"); 
		query.append("			  ,'' AS TAX_NM" ).append("\n"); 
		query.append("		  FROM DUAL " ).append("\n"); 
		query.append("		  UNION ALL" ).append("\n"); 
		query.append("		SELECT '' AS CUST_VAT" ).append("\n"); 
		query.append("              ,'' AS ADDRESS01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD01" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD02" ).append("\n"); 
		query.append("              ,'' AS OFC_ADD03" ).append("\n"); 
		query.append("              ,'' AS HEADER01" ).append("\n"); 
		query.append("              ,'' AS HEADER02" ).append("\n"); 
		query.append("              ,'' AS HEADER03" ).append("\n"); 
		query.append("              ,'' AS HEADER04" ).append("\n"); 
		query.append("              ,'' AS HEADER05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK01" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK02" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK03" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK04" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK05" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK06" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK07" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK08" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK09" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK10" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK11" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK12" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK13" ).append("\n"); 
		query.append("              ,'' AS SHEET_REMARK14" ).append("\n"); 
		query.append("              ,'' AS SH_NUM" ).append("\n"); 
		query.append("              ,'' AS HJS_REF" ).append("\n"); 
		query.append("			  ,'' AS PRINT_DATE" ).append("\n"); 
		query.append("		      ,'' AS TITLE" ).append("\n"); 
		query.append("              ,( SELECT DECODE(SUBSTR(LOC_CD,1,2), 'AU' , 'GST' ,'IN' ,'TAX', 'VAT') AS TAX_NM" ).append("\n"); 
		query.append("                  FROM MDM_ORGANIZATION" ).append("\n"); 
		query.append("                 WHERE OFC_CD = @[session_ofc_cd] ) AS TAX_NM" ).append("\n"); 
		query.append("		  FROM DUAL" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("## finish" ).append("\n"); 

	}
}