/*=========================================================
*Copyright(c) 2016 CyberLogitec
*@FileName : SCReportDBDAOcreatePriMotFileLogDataCSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2016.04.19
*@LastModifier : CHLOE MIJIN SEO
*@LastVersion : 1.0
* 2016.04.19 CHLOE MIJIN SEO
* 1.0 Creation
=========================================================*/
package com.clt.apps.opus.esm.pri.screport.screport.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.clt.framework.support.db.ISQLTemplate;

/**
 *
 * @author CHLOE MIJIN SEO
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class SCReportDBDAOcreatePriMotFileLogDataCSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * 일자별 대상 BKG 을 가져와 해당 일자의 데이터를 생성한다.
	  * -  중복 제거 이전 
	  * 
	  * PRI_MOT_FILE_RT_LOG
	  * PRI_MOT_FILE_RT_LOG_DTL
	  * </pre>
	  */
	public SCReportDBDAOcreatePriMotFileLogDataCSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("test_exec_dt",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.clt.apps.opus.esm.pri.screport.screport.integration").append("\n"); 
		query.append("FileName : SCReportDBDAOcreatePriMotFileLogDataCSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("INSERT ALL" ).append("\n"); 
		query.append("WHEN    SCG_SEQ = 1 THEN" ).append("\n"); 
		query.append("INTO PRI_MOT_FILE_RT_LOG (BAT_EXE_DT, MOT_FILE_RT_LOG_SEQ, BKG_NO, BKG_SRC_TP_CD, CTRT_NO, CTRT_HLD_NM, ACT_CUST_NM, MOT_FILE_LANE_CD, MOT_FILE_ORG_CD, MOT_FILE_DEST_CD, MOT_FILE_CNTR_TP_CD, MOT_FILE_CMDT_TP_CD, MOT_FILE_CNTR_SZ_CD, MOT_FILE_RT_AMT, CTRT_EFF_DT, CTRT_EXP_DT, MOT_FILE_RMK, CRE_USR_ID, CRE_DT, UPD_USR_ID, UPD_DT, SHPR_CNT_CD, SHPR_SEQ, CNEE_NM, OP_AGN_NM, COMM_AMT, FWRD_CNT_CD, FWRD_CUST_SEQ) " ).append("\n"); 
		query.append("VALUES ( BAT_EXE_DT, MOT_FILE_RT_SEQ, BKG_NO, BKG_SRC_TP_CD, CTRT_NO, CTRT_HLDR, ACT_CUST_NM, MOT_FILE_LANE_CD, MOT_FILE_OLOC_CD, MOT_FILE_DLOC_CD, MOT_FILE_CNTR_TP_CD, " ).append("\n"); 
		query.append("MOT_FILE_CMDT_TP_CD, MOT_FILE_CNTR_SZ_CD, MOT_FILE_RT_AMT, CTRT_EFF_DT, CTRT_EXP_DT, NULL , 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, SHPR_CNT_CD, SHPR_SEQ, CNEE_NM, OP_AGN_NM, COMM_AMT, FWRD_CNT_CD, FWRD_CUST_SEQ)" ).append("\n"); 
		query.append("WHEN    SCG_SEQ > 1 THEN" ).append("\n"); 
		query.append("INTO PRI_MOT_FILE_RT_LOG_DTL (BAT_EXE_DT, MOT_FILE_RT_LOG_SEQ, SCG_SEQ, CHG_CD, RAT_UT_CD, MOT_FILE_CHG_AMT, CRE_USR_ID, CRE_DT, UPD_USR_ID, UPD_DT, CURR_CD)" ).append("\n"); 
		query.append("VALUES ( BAT_EXE_DT, MOT_FILE_RT_SEQ, SCG_SEQ - 1, CHG_CD, RAT_UT_CD, MOT_FILE_CHG_AMT, 'SYSTEM', SYSDATE, 'SYSTEM', SYSDATE, CURR_CD )" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("WITH BKG_NO_LIST AS (" ).append("\n"); 
		query.append(" SELECT  /*+ ORDERED USE_NL */" ).append("\n"); 
		query.append("         'V' AS IND, B.BKG_NO, 'POL' AS O_LOC_GB" ).append("\n"); 
		query.append("   FROM  VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("      ,  BKG_BOOKING B" ).append("\n"); 
		query.append("      ,  BKG_VVD     C" ).append("\n"); 
		query.append("      ,  PRI_MOT_FILE_LOC_PPT OL" ).append("\n"); 
		query.append("      ,  PRI_MOT_FILE_LOC_PPT DL" ).append("\n"); 
		query.append("  WHERE  A.VPS_ETD_DT " ).append("\n"); 
		query.append("         BETWEEN TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) + 1 " ).append("\n"); 
		query.append("         AND TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) + 2" ).append("\n"); 
		query.append("    AND  A.VSL_CD = C.VSL_CD" ).append("\n"); 
		query.append("    AND  A.SKD_VOY_NO = C.SKD_VOY_NO" ).append("\n"); 
		query.append("    AND  A.SKD_DIR_CD = C.SKD_DIR_CD" ).append("\n"); 
		query.append("    AND  A.VPS_PORT_CD = C.POL_CD " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    AND  A.CLPT_IND_SEQ = C.POL_CLPT_IND_SEQ" ).append("\n"); 
		query.append("    AND  B.BKG_NO = C.BKG_NO" ).append("\n"); 
		query.append("    AND  B.POL_CD = C.POL_CD" ).append("\n"); 
		query.append("    AND  C.VSL_PRE_PST_CD||C.VSL_SEQ = ( SELECT MIN(VSL_PRE_PST_CD||VSL_SEQ) FROM BKG_VVD VVD2 WHERE VVD2.BKG_NO = B.BKG_NO)" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  B.RCV_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    AND  B.DE_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  OL.ORG_DEST_TP_CD = 'O'" ).append("\n"); 
		query.append("    AND  OL.LOC_CD = B.POL_CD" ).append("\n"); 
		query.append("    AND  DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("    AND  DL.LOC_CD = B.POD_CD" ).append("\n"); 
		query.append("    AND  B.BKG_STS_CD <> 'X'" ).append("\n"); 
		query.append("    AND  B.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  UNION ALL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(" SELECT  /*+ ORDERED USE_NL */" ).append("\n"); 
		query.append("         'V' AS IND, B.BKG_NO, 'POR' AS O_LOC_GB" ).append("\n"); 
		query.append("   FROM  VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("      ,  BKG_BOOKING B" ).append("\n"); 
		query.append("      ,  BKG_VVD     C" ).append("\n"); 
		query.append("      ,  PRI_MOT_FILE_LOC_PPT DL" ).append("\n"); 
		query.append("  WHERE  A.VPS_ETD_DT " ).append("\n"); 
		query.append("         BETWEEN TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) + 1 " ).append("\n"); 
		query.append("         AND TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) + 2" ).append("\n"); 
		query.append("    AND  A.VSL_CD = C.VSL_CD" ).append("\n"); 
		query.append("    AND  A.SKD_VOY_NO = C.SKD_VOY_NO" ).append("\n"); 
		query.append("    AND  A.SKD_DIR_CD = C.SKD_DIR_CD" ).append("\n"); 
		query.append("    AND  A.VPS_PORT_CD = C.POL_CD " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    AND  A.CLPT_IND_SEQ = C.POL_CLPT_IND_SEQ" ).append("\n"); 
		query.append("    AND  B.BKG_NO = C.BKG_NO" ).append("\n"); 
		query.append("    AND  B.POL_CD = C.POL_CD" ).append("\n"); 
		query.append("    AND  C.VSL_PRE_PST_CD||C.VSL_SEQ = ( SELECT MIN(VSL_PRE_PST_CD||VSL_SEQ) FROM BKG_VVD VVD2 WHERE VVD2.BKG_NO = B.BKG_NO)" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  B.RCV_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    AND  B.DE_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  B.POR_CD IN ('CNNKG', 'CNLYG')" ).append("\n"); 
		query.append("    AND  DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("    AND  DL.LOC_CD = B.POD_CD" ).append("\n"); 
		query.append("    AND  B.BKG_STS_CD <> 'X'" ).append("\n"); 
		query.append("    AND  B.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  UNION ALL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--  C/A : C/A booking after BDR " ).append("\n"); 
		query.append(" SELECT  /*+ ORDERED USE_NL */" ).append("\n"); 
		query.append("        'C' AS IND, A.BKG_NO, 'POL' AS O_LOC_GB" ).append("\n"); 
		query.append("   FROM BKG_CORRECTION A" ).append("\n"); 
		query.append("      , BKG_BOOKING B" ).append("\n"); 
		query.append("      , PRI_MOT_FILE_LOC_PPT OL" ).append("\n"); 
		query.append("      , PRI_MOT_FILE_LOC_PPT DL        " ).append("\n"); 
		query.append("  WHERE A.CORR_NO NOT   IN ( '0000000001', 'TMP0000001' )" ).append("\n"); 
		query.append("    AND A.CORR_CXL_FLG  = 'N'" ).append("\n"); 
		query.append("    AND A.CORR_GDT      " ).append("\n"); 
		query.append("        BETWEEN TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) - 1 " ).append("\n"); 
		query.append("        AND TO_DATE (@[test_exec_dt],'YYYY-MM-DD' )        " ).append("\n"); 
		query.append("    AND A.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND B.RCV_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    AND B.DE_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND OL.ORG_DEST_TP_CD = 'O'" ).append("\n"); 
		query.append("    AND OL.LOC_CD = B.POL_CD" ).append("\n"); 
		query.append("    AND DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("    AND DL.LOC_CD = B.POD_CD" ).append("\n"); 
		query.append("    AND B.BKG_STS_CD <> 'X'" ).append("\n"); 
		query.append("    AND B.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append(" " ).append("\n"); 
		query.append("  UNION ALL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(" SELECT  /*+ ORDERED USE_NL */" ).append("\n"); 
		query.append("        'C' AS IND, A.BKG_NO, 'POR' AS O_LOC_GB" ).append("\n"); 
		query.append("   FROM BKG_CORRECTION A" ).append("\n"); 
		query.append("      , BKG_BOOKING B" ).append("\n"); 
		query.append("      , PRI_MOT_FILE_LOC_PPT DL        " ).append("\n"); 
		query.append("  WHERE A.CORR_NO NOT   IN ( '0000000001', 'TMP0000001' )" ).append("\n"); 
		query.append("    AND A.CORR_CXL_FLG  = 'N'" ).append("\n"); 
		query.append("    AND A.CORR_GDT      " ).append("\n"); 
		query.append("        BETWEEN TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) - 1 " ).append("\n"); 
		query.append("        AND TO_DATE (@[test_exec_dt],'YYYY-MM-DD' )        " ).append("\n"); 
		query.append("    AND A.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND B.RCV_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    AND B.DE_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND B.POR_CD IN ('CNNKG', 'CNLYG')   " ).append("\n"); 
		query.append("    AND DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("    AND DL.LOC_CD = B.POD_CD" ).append("\n"); 
		query.append("    AND B.BKG_STS_CD <> 'X'" ).append("\n"); 
		query.append("    AND B.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append(" " ).append("\n"); 
		query.append("  UNION ALL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--  BDR : Changed booking during after vessel sailing until BDR	" ).append("\n"); 
		query.append(" SELECT  'B' AS IND, B.BKG_NO, 'POL' AS O_LOC_GB" ).append("\n"); 
		query.append("   FROM  VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("      ,  BKG_BOOKING B" ).append("\n"); 
		query.append("      ,  BKG_VVD     C" ).append("\n"); 
		query.append("      ,  BKG_BL_DOC  D" ).append("\n"); 
		query.append("      ,  (SELECT BKG_NO" ).append("\n"); 
		query.append("            FROM BKG_CHG_RT" ).append("\n"); 
		query.append("           WHERE 1=1" ).append("\n"); 
		query.append("             AND UPD_DT BETWEEN TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) - 1 AND TO_DATE (@[test_exec_dt],'YYYY-MM-DD' )" ).append("\n"); 
		query.append("           GROUP BY BKG_NO" ).append("\n"); 
		query.append("         ) E " ).append("\n"); 
		query.append("      ,  PRI_MOT_FILE_LOC_PPT OL" ).append("\n"); 
		query.append("      ,  PRI_MOT_FILE_LOC_PPT DL" ).append("\n"); 
		query.append("  WHERE  A.VPS_ETD_DT <= TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) + 1 " ).append("\n"); 
		query.append("    AND  A.VSL_CD = C.VSL_CD" ).append("\n"); 
		query.append("    AND  A.SKD_VOY_NO = C.SKD_VOY_NO" ).append("\n"); 
		query.append("    AND  A.SKD_DIR_CD = C.SKD_DIR_CD" ).append("\n"); 
		query.append("    AND  A.VPS_PORT_CD = C.POL_CD " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    AND  A.CLPT_IND_SEQ = C.POL_CLPT_IND_SEQ" ).append("\n"); 
		query.append("    AND  B.BKG_NO = C.BKG_NO" ).append("\n"); 
		query.append("    AND  B.POL_CD = C.POL_CD" ).append("\n"); 
		query.append("    AND  C.VSL_PRE_PST_CD||C.VSL_SEQ = ( SELECT MIN(VSL_PRE_PST_CD||VSL_SEQ) FROM BKG_VVD VVD2 WHERE VVD2.BKG_NO = B.BKG_NO)" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    AND  B.RCV_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    AND  B.DE_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  OL.ORG_DEST_TP_CD = 'O'" ).append("\n"); 
		query.append("    AND  OL.LOC_CD = B.POL_CD" ).append("\n"); 
		query.append("    AND  DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("    AND  DL.LOC_CD = B.POD_CD" ).append("\n"); 
		query.append("    AND  B.BKG_STS_CD <> 'X'" ).append("\n"); 
		query.append("    AND  B.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    AND  B.BKG_NO = D.BKG_NO " ).append("\n"); 
		query.append("    AND  D.BDR_FLG = 'N'" ).append("\n"); 
		query.append("    AND  B.BKG_NO = E.BKG_NO  " ).append("\n"); 
		query.append(" " ).append("\n"); 
		query.append(" UNION ALL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(" SELECT  'B' AS IND, B.BKG_NO, 'POR' AS O_LOC_GB" ).append("\n"); 
		query.append("      FROM  VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("      ,  BKG_BOOKING B" ).append("\n"); 
		query.append("      ,  BKG_VVD     C" ).append("\n"); 
		query.append("      ,  BKG_BL_DOC  D" ).append("\n"); 
		query.append("      ,  (SELECT BKG_NO" ).append("\n"); 
		query.append("            FROM BKG_CHG_RT" ).append("\n"); 
		query.append("           WHERE 1=1" ).append("\n"); 
		query.append("             AND UPD_DT BETWEEN TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) - 1 AND TO_DATE (@[test_exec_dt],'YYYY-MM-DD' )" ).append("\n"); 
		query.append("           GROUP BY BKG_NO" ).append("\n"); 
		query.append("         ) E " ).append("\n"); 
		query.append("      ,  PRI_MOT_FILE_LOC_PPT DL" ).append("\n"); 
		query.append("  WHERE  A.VPS_ETD_DT <= TO_DATE (@[test_exec_dt],'YYYY-MM-DD' ) + 1 " ).append("\n"); 
		query.append("    AND  A.VSL_CD = C.VSL_CD" ).append("\n"); 
		query.append("    AND  A.SKD_VOY_NO = C.SKD_VOY_NO" ).append("\n"); 
		query.append("    AND  A.SKD_DIR_CD = C.SKD_DIR_CD" ).append("\n"); 
		query.append("    AND  A.VPS_PORT_CD = C.POL_CD " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    AND  A.CLPT_IND_SEQ = C.POL_CLPT_IND_SEQ" ).append("\n"); 
		query.append("    AND  B.BKG_NO = C.BKG_NO" ).append("\n"); 
		query.append("    AND  B.POL_CD = C.POL_CD" ).append("\n"); 
		query.append("    AND  C.VSL_PRE_PST_CD||C.VSL_SEQ = ( SELECT MIN(VSL_PRE_PST_CD||VSL_SEQ) FROM BKG_VVD VVD2 WHERE VVD2.BKG_NO = B.BKG_NO)" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  B.RCV_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    AND  B.DE_TERM_CD = 'Y'" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  B.POR_CD IN ('CNNKG', 'CNLYG')" ).append("\n"); 
		query.append("    AND  DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("    AND  DL.LOC_CD = B.POD_CD" ).append("\n"); 
		query.append("    AND  B.BKG_STS_CD <> 'X'" ).append("\n"); 
		query.append("    AND  B.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    AND  B.BKG_NO = D.BKG_NO " ).append("\n"); 
		query.append("    AND  D.BDR_FLG = 'N'" ).append("\n"); 
		query.append("    AND  B.BKG_NO = E.BKG_NO " ).append("\n"); 
		query.append(") " ).append("\n"); 
		query.append(", BKG_INFO_LIST AS (" ).append("\n"); 
		query.append("SELECT  BKG_INFO.IND" ).append("\n"); 
		query.append("      , BKG_INFO.BKG_NO" ).append("\n"); 
		query.append("      , BKG_INFO.CTRT_NO" ).append("\n"); 
		query.append("      , BKG_INFO.RT_APLY_DT" ).append("\n"); 
		query.append("      , BKG_INFO.O_LOC_GB" ).append("\n"); 
		query.append("      , BKG_INFO.POR_CD" ).append("\n"); 
		query.append("      , BKG_INFO.POL_CD" ).append("\n"); 
		query.append("      , BKG_INFO.POD_CD" ).append("\n"); 
		query.append("      , BKG_INFO.BKG_SVC_SCP_CD" ).append("\n"); 
		query.append("      , BKG_INFO.BKG_CGO_CATE" ).append("\n"); 
		query.append("      , BKG_INFO.BKG_SHPR_CNT_CD" ).append("\n"); 
		query.append("      , BKG_INFO.BKG_SHPR_SEQ" ).append("\n"); 
		query.append("      , BKG_INFO.FWRD_CNT_CD" ).append("\n"); 
		query.append("      , BKG_INFO.FWRD_CUST_SEQ" ).append("\n"); 
		query.append("      , BKG_INFO.BKG_CGO_CATE_TPSZ" ).append("\n"); 
		query.append("   FROM (SELECT " ).append("\n"); 
		query.append("                BL.IND" ).append("\n"); 
		query.append("              , BL.BKG_NO" ).append("\n"); 
		query.append("              , DECODE (BR.BKG_CTRT_TP_CD, 'R', BK.RFA_NO, 'S', BK.SC_NO, 'T', BK.TAA_NO ) " ).append("\n"); 
		query.append("                AS CTRT_NO" ).append("\n"); 
		query.append("              , BR.RT_APLY_DT" ).append("\n"); 
		query.append("              , BL.O_LOC_GB" ).append("\n"); 
		query.append("              , BK.POR_CD" ).append("\n"); 
		query.append("              , BK.POL_CD" ).append("\n"); 
		query.append("              , BK.POD_CD" ).append("\n"); 
		query.append("              , BK.SVC_SCP_CD AS BKG_SVC_SCP_CD" ).append("\n"); 
		query.append("              , BC.CUST_CNT_CD AS BKG_SHPR_CNT_CD" ).append("\n"); 
		query.append("              , BC.CUST_SEQ AS BKG_SHPR_SEQ" ).append("\n"); 
		query.append("              , BC1.CUST_CNT_CD AS FWRD_CNT_CD" ).append("\n"); 
		query.append("              , BC1.CUST_SEQ AS FWRD_CUST_SEQ" ).append("\n"); 
		query.append("              , CM.CMDT_CD AS BKG_CGO_CATE" ).append("\n"); 
		query.append("              , CM.CNTR_TPSZ_CD AS BKG_CGO_CATE_TPSZ  " ).append("\n"); 
		query.append("           FROM BKG_NO_LIST BL" ).append("\n"); 
		query.append("              , BKG_BOOKING BK" ).append("\n"); 
		query.append("              , BKG_RATE BR" ).append("\n"); 
		query.append("              , BKG_CUSTOMER BC" ).append("\n"); 
		query.append("              , BKG_CUSTOMER BC1" ).append("\n"); 
		query.append("              , ( SELECT DISTINCT B.BKG_NO, C.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                       , COALESCE( B.HAMO_TRF_CD, B.CMDT_HS_CD , B.NCM_NO ) AS CMDT_CD" ).append("\n"); 
		query.append("                    FROM BKG_CNTR_MF_DESC B, BKG_CONTAINER C " ).append("\n"); 
		query.append("                   WHERE B.BKG_NO = C.BKG_NO AND B.CNTR_NO = C.CNTR_NO) CM" ).append("\n"); 
		query.append("          WHERE BL.BKG_NO = BK.BKG_NO" ).append("\n"); 
		query.append("            AND BL.BKG_NO = BR.BKG_NO(+)" ).append("\n"); 
		query.append("            AND BR.BKG_CTRT_TP_CD(+) IS NOT NULL" ).append("\n"); 
		query.append("            AND BL.BKG_NO = BC.BKG_NO(+)" ).append("\n"); 
		query.append("            AND BL.BKG_NO = BC1.BKG_NO(+)" ).append("\n"); 
		query.append("            AND BC.BKG_CUST_TP_CD(+)  = 'S'" ).append("\n"); 
		query.append("            AND BC1.BKG_CUST_TP_CD(+) = 'F' " ).append("\n"); 
		query.append("            AND BL.BKG_NO = CM.BKG_NO" ).append("\n"); 
		query.append("            AND ( (BR.BKG_CTRT_TP_CD = 'R' AND EXISTS (SELECT " ).append("\n"); 
		query.append("                                                              1 " ).append("\n"); 
		query.append("                                                         FROM PRI_RP_HDR  X " ).append("\n"); 
		query.append("                                                        WHERE X.RFA_NO = BK.RFA_NO AND ROWNUM = 1 ) ) OR " ).append("\n"); 
		query.append("                  (BR.BKG_CTRT_TP_CD = 'S' AND EXISTS (SELECT " ).append("\n"); 
		query.append("                                                              1 " ).append("\n"); 
		query.append("                                                         FROM PRI_SP_HDR  X " ).append("\n"); 
		query.append("                                                        WHERE X.SC_NO  = BK.SC_NO  AND ROWNUM = 1 ) ) OR  " ).append("\n"); 
		query.append("                  (BR.BKG_CTRT_TP_CD = 'T' AND EXISTS (SELECT " ).append("\n"); 
		query.append("                                                              1 " ).append("\n"); 
		query.append("                                                         FROM PRI_TAA_HDR X " ).append("\n"); 
		query.append("                                                        WHERE X.TAA_NO = BK.TAA_NO AND ROWNUM = 1 ) ) ) ) BKG_INFO" ).append("\n"); 
		query.append("     " ).append("\n"); 
		query.append("),  CTRT_INFO_LIST AS (" ).append("\n"); 
		query.append("SELECT  " ).append("\n"); 
		query.append("        DISTINCT SS.CTRT_NO, SS.RT_APLY_DT, SS.PROP_NO, SS.AMDT_SEQ" ).append("\n"); 
		query.append("      , SS.SVC_SCP_CD" ).append("\n"); 
		query.append("      , SD.CTRT_EFF_DT" ).append("\n"); 
		query.append("      , SD.CTRT_EXP_DT                      " ).append("\n"); 
		query.append("      , SS.CCP_NM" ).append("\n"); 
		query.append("      , SS.CUST_CNT_CD" ).append("\n"); 
		query.append("      , SS.CUST_SEQ" ).append("\n"); 
		query.append("   FROM (SELECT" ).append("\n"); 
		query.append("                SCIF.CTRT_NO" ).append("\n"); 
		query.append("              , SCIF.RT_APLY_DT" ).append("\n"); 
		query.append("              , SCIF.PROP_NO" ).append("\n"); 
		query.append("              , SCIF.AMDT_SEQ" ).append("\n"); 
		query.append("              , SCIF.SVC_SCP_CD" ).append("\n"); 
		query.append("              , SCIF.CUST_CNT_CD" ).append("\n"); 
		query.append("              , SCIF.CUST_SEQ" ).append("\n"); 
		query.append("              , SCIF.CCP_NM" ).append("\n"); 
		query.append("           FROM (SELECT  " ).append("\n"); 
		query.append("                        DISTINCT" ).append("\n"); 
		query.append("                        A.CTRT_NO" ).append("\n"); 
		query.append("                      , A.RT_APLY_DT" ).append("\n"); 
		query.append("                      , C.PROP_NO" ).append("\n"); 
		query.append("                      , C.AMDT_SEQ" ).append("\n"); 
		query.append("                      , A.BKG_SVC_SCP_CD AS SVC_SCP_CD" ).append("\n"); 
		query.append("                      , D.CUST_CNT_CD" ).append("\n"); 
		query.append("                      , D.CUST_SEQ" ).append("\n"); 
		query.append("                      , D.CTRT_PTY_NM AS CCP_NM" ).append("\n"); 
		query.append("                   FROM BKG_INFO_LIST A" ).append("\n"); 
		query.append("                      , PRI_SP_HDR B" ).append("\n"); 
		query.append("                      , PRI_SP_MN C" ).append("\n"); 
		query.append("                      , PRI_SP_CTRT_PTY D" ).append("\n"); 
		query.append("                  WHERE 1=1" ).append("\n"); 
		query.append("                    AND A.CTRT_NO != 'DUM000001' " ).append("\n"); 
		query.append("                    AND A.CTRT_NO  = B.SC_NO" ).append("\n"); 
		query.append("                    AND B.PROP_NO  = C.PROP_NO" ).append("\n"); 
		query.append("                    AND C.AMDT_SEQ = (SELECT " ).append("\n"); 
		query.append("                                             MAX ( M.AMDT_SEQ ) " ).append("\n"); 
		query.append("                                        FROM PRI_SP_MN M " ).append("\n"); 
		query.append("                                       WHERE M.PROP_NO = C.PROP_NO " ).append("\n"); 
		query.append("                                         AND TO_DATE ( @[test_exec_dt],'YYYY-MM-DD' ) " ).append("\n"); 
		query.append("                                             BETWEEN M.EFF_DT AND M.EXP_DT AND M.PROP_STS_CD = 'F')" ).append("\n"); 
		query.append("                   AND C.PROP_NO   = D.PROP_NO" ).append("\n"); 
		query.append("                   AND C.AMDT_SEQ  = D.AMDT_SEQ" ).append("\n"); 
		query.append("                   AND D.PRC_CTRT_PTY_TP_CD = 'C'" ).append("\n"); 
		query.append("                   ) SCIF" ).append("\n"); 
		query.append("          ) SS                       " ).append("\n"); 
		query.append("     , PRI_SP_DUR SD" ).append("\n"); 
		query.append("     , MDM_CUSTOMER MC" ).append("\n"); 
		query.append(" WHERE SS.PROP_NO     = SD.PROP_NO" ).append("\n"); 
		query.append("   AND SS.AMDT_SEQ    = SD.AMDT_SEQ" ).append("\n"); 
		query.append("   AND SS.CUST_CNT_CD = MC.CUST_CNT_CD" ).append("\n"); 
		query.append("   AND SS.CUST_SEQ    = MC.CUST_SEQ" ).append("\n"); 
		query.append("                 " ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append(" " ).append("\n"); 
		query.append("SELECT  " ).append("\n"); 
		query.append("       DISTINCT RS.CTRT_NO, RS.RT_APLY_DT, RS.PROP_NO, RS.AMDT_SEQ" ).append("\n"); 
		query.append("     , RS.SVC_SCP_CD" ).append("\n"); 
		query.append("     , SD.CTRT_EFF_DT" ).append("\n"); 
		query.append("     , SD.CTRT_EXP_DT" ).append("\n"); 
		query.append("     , RS.CCP_NM" ).append("\n"); 
		query.append("     , RS.CUST_CNT_CD" ).append("\n"); 
		query.append("     , RS.CUST_SEQ" ).append("\n"); 
		query.append("  FROM (SELECT" ).append("\n"); 
		query.append("               RFAIF.CTRT_NO" ).append("\n"); 
		query.append("             , RFAIF.RT_APLY_DT" ).append("\n"); 
		query.append("             , RFAIF.PROP_NO" ).append("\n"); 
		query.append("             , RFAIF.AMDT_SEQ" ).append("\n"); 
		query.append("             , RFAIF.SVC_SCP_CD" ).append("\n"); 
		query.append("             , RFAIF.CCP_NM" ).append("\n"); 
		query.append("             , RFAIF.CTRT_CUST_CNT_CD AS CUST_CNT_CD" ).append("\n"); 
		query.append("             , RFAIF.CTRT_CUST_SEQ AS CUST_SEQ" ).append("\n"); 
		query.append("          FROM (SELECT DISTINCT" ).append("\n"); 
		query.append("                       A.CTRT_NO" ).append("\n"); 
		query.append("                     , A.RT_APLY_DT" ).append("\n"); 
		query.append("                     , C.PROP_NO" ).append("\n"); 
		query.append("                     , C.AMDT_SEQ" ).append("\n"); 
		query.append("                     , A.BKG_SVC_SCP_CD AS SVC_SCP_CD" ).append("\n"); 
		query.append("                     , MC.CUST_LGL_ENG_NM AS CCP_NM" ).append("\n"); 
		query.append("                     , C.CTRT_CUST_CNT_CD" ).append("\n"); 
		query.append("                     , C.CTRT_CUST_SEQ" ).append("\n"); 
		query.append("                  FROM BKG_INFO_LIST A" ).append("\n"); 
		query.append("                     , PRI_RP_HDR B" ).append("\n"); 
		query.append("                     , PRI_RP_MN C" ).append("\n"); 
		query.append("                     , MDM_CUSTOMER MC" ).append("\n"); 
		query.append("                 WHERE 1=1" ).append("\n"); 
		query.append("                   AND A.CTRT_NO != 'DUM0000001'" ).append("\n"); 
		query.append("                   AND A.CTRT_NO          = B.RFA_NO" ).append("\n"); 
		query.append("                   AND B.PROP_NO          = C.PROP_NO" ).append("\n"); 
		query.append("                   AND C.AMDT_SEQ         = ( SELECT " ).append("\n"); 
		query.append("                                                     MAX ( M.AMDT_SEQ ) " ).append("\n"); 
		query.append("                                                FROM PRI_RP_MN M " ).append("\n"); 
		query.append("                                               WHERE M.PROP_NO = C.PROP_NO " ).append("\n"); 
		query.append("                                                 AND TO_DATE ( @[test_exec_dt],'YYYY-MM-DD' ) " ).append("\n"); 
		query.append("                                                     BETWEEN M.EFF_DT AND M.EXP_DT AND M.PROP_STS_CD = 'A' )" ).append("\n"); 
		query.append("                   AND C.CTRT_CUST_CNT_CD = MC.CUST_CNT_CD" ).append("\n"); 
		query.append("                   AND C.CTRT_CUST_SEQ    = MC.CUST_SEQ " ).append("\n"); 
		query.append("                   ) RFAIF" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("         ) RS                       " ).append("\n"); 
		query.append("     , PRI_RP_MN  RM" ).append("\n"); 
		query.append("     , PRI_RP_DUR SD" ).append("\n"); 
		query.append(" WHERE RS.PROP_NO  = RM.PROP_NO" ).append("\n"); 
		query.append("   AND RS.AMDT_SEQ = RM.AMDT_SEQ" ).append("\n"); 
		query.append("   AND RS.PROP_NO  = SD.PROP_NO" ).append("\n"); 
		query.append("   AND RS.AMDT_SEQ = SD.AMDT_SEQ" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(" UNION ALL" ).append("\n"); 
		query.append(" " ).append("\n"); 
		query.append("SELECT  " ).append("\n"); 
		query.append("       DISTINCT TS.CTRT_NO, TS.RT_APLY_DT, TS.TAA_PROP_NO, TS.AMDT_SEQ" ).append("\n"); 
		query.append("     , TS.SVC_SCP_CD" ).append("\n"); 
		query.append("     , TM.EFF_DT AS CTRT_EFF_DT" ).append("\n"); 
		query.append("     , TM.EXP_DT AS CTRT_EXP_DT" ).append("\n"); 
		query.append("     , TS.CCP_NM" ).append("\n"); 
		query.append("     , TS.CUST_CNT_CD" ).append("\n"); 
		query.append("     , TS.CUST_SEQ" ).append("\n"); 
		query.append("  FROM PRI_TAA_MN TM" ).append("\n"); 
		query.append("     , (SELECT" ).append("\n"); 
		query.append("               TAAIF.CTRT_NO" ).append("\n"); 
		query.append("             , TAAIF.RT_APLY_DT " ).append("\n"); 
		query.append("             , TAAIF.TAA_PROP_NO " ).append("\n"); 
		query.append("             , TAAIF.AMDT_SEQ " ).append("\n"); 
		query.append("             , TAAIF.SVC_SCP_CD " ).append("\n"); 
		query.append("             , TAAIF.CCP_NM" ).append("\n"); 
		query.append("             , TAAIF.CTRT_CUST_CNT_CD AS CUST_CNT_CD" ).append("\n"); 
		query.append("             , TAAIF.CTRT_CUST_SEQ AS CUST_SEQ" ).append("\n"); 
		query.append("         FROM (SELECT " ).append("\n"); 
		query.append("                      DISTINCT A.CTRT_NO" ).append("\n"); 
		query.append("                    , A.RT_APLY_DT" ).append("\n"); 
		query.append("                    , C.TAA_PROP_NO" ).append("\n"); 
		query.append("                    , C.AMDT_SEQ" ).append("\n"); 
		query.append("                    , C.SVC_SCP_CD" ).append("\n"); 
		query.append("                    , MC.CUST_LGL_ENG_NM AS CCP_NM" ).append("\n"); 
		query.append("                    , C.CTRT_CUST_CNT_CD" ).append("\n"); 
		query.append("                    , C.CTRT_CUST_SEQ" ).append("\n"); 
		query.append("                 FROM BKG_INFO_LIST A" ).append("\n"); 
		query.append("                    , PRI_TAA_HDR B" ).append("\n"); 
		query.append("                    , PRI_TAA_MN C" ).append("\n"); 
		query.append("                    , MDM_CUSTOMER MC" ).append("\n"); 
		query.append("                    , BKG_CUSTOMER BC" ).append("\n"); 
		query.append("                WHERE 1=1" ).append("\n"); 
		query.append("                  AND A.CTRT_NO != 'DUM0000001'" ).append("\n"); 
		query.append("                  AND A.CTRT_NO          = B.TAA_NO" ).append("\n"); 
		query.append("                  AND B.TAA_PROP_NO      = C.TAA_PROP_NO" ).append("\n"); 
		query.append("                  AND C.AMDT_SEQ         = (SELECT " ).append("\n"); 
		query.append("                                                   MAX ( M.AMDT_SEQ ) " ).append("\n"); 
		query.append("                                              FROM PRI_TAA_MN M " ).append("\n"); 
		query.append("                                             WHERE M.TAA_PROP_NO = C.TAA_PROP_NO " ).append("\n"); 
		query.append("                                               AND TO_DATE ( @[test_exec_dt],'YYYY-MM-DD' ) " ).append("\n"); 
		query.append("                                                   BETWEEN M.EFF_DT AND M.EXP_DT AND M.CFM_FLG = 'Y' )" ).append("\n"); 
		query.append("                  AND C.SVC_SCP_CD       = A.BKG_SVC_SCP_CD" ).append("\n"); 
		query.append("                  AND C.CTRT_CUST_CNT_CD = MC.CUST_CNT_CD" ).append("\n"); 
		query.append("                  AND C.CTRT_CUST_SEQ    = MC.CUST_SEQ " ).append("\n"); 
		query.append("                  ) TAAIF" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       ) TS" ).append("\n"); 
		query.append(" WHERE TS.TAA_PROP_NO = TM.TAA_PROP_NO" ).append("\n"); 
		query.append("   AND TS.AMDT_SEQ    = TM.AMDT_SEQ" ).append("\n"); 
		query.append("   AND TS.SVC_SCP_CD  = TM.SVC_SCP_CD" ).append("\n"); 
		query.append(") " ).append("\n"); 
		query.append(", BKG_TPSZ  AS (" ).append("\n"); 
		query.append("SELECT  " ).append("\n"); 
		query.append("        T1.BKG_NO" ).append("\n"); 
		query.append("      , T1.CNTR_TPSZ_KNT" ).append("\n"); 
		query.append("      , T1.TTL_CNTR_QTY" ).append("\n"); 
		query.append("      , T1.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("      , T1.CGO_TP_CD" ).append("\n"); 
		query.append("      , T1.CNTR_QTY" ).append("\n"); 
		query.append("      , (SELECT " ).append("\n"); 
		query.append("                A.CNTR_SZ_CD " ).append("\n"); 
		query.append("           FROM PRI_RAT_UT A " ).append("\n"); 
		query.append("          WHERE A.RAT_UT_CD = T1.CNTR_TPSZ_CD ) AS CNTR_SZ_CD" ).append("\n"); 
		query.append("   FROM (SELECT  " ).append("\n"); 
		query.append("                QD.BKG_NO" ).append("\n"); 
		query.append("              , COUNT(1) OVER () CNTR_TPSZ_KNT" ).append("\n"); 
		query.append("              , (SELECT " ).append("\n"); 
		query.append("                        SUM(OP_CNTR_QTY) " ).append("\n"); 
		query.append("                   FROM BKG_QUANTITY A " ).append("\n"); 
		query.append("                  WHERE A.BKG_NO = QD.BKG_NO ) TTL_CNTR_QTY" ).append("\n"); 
		query.append("              , CASE WHEN QD.CNTR_TPSZ_CD LIKE 'R%' AND" ).append("\n"); 
		query.append("                          QD.DRY_CGO_FLG = 'Y' -- RD 인 경우만 예외처리" ).append("\n"); 
		query.append("                     THEN QD.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                     ELSE NVL(QD.EQ_SUBST_CNTR_TPSZ_CD, QD.CNTR_TPSZ_CD)" ).append("\n"); 
		query.append("                 END CNTR_TPSZ_CD" ).append("\n"); 
		query.append("              , CASE WHEN QD.DCGO_FLG    = 'Y' THEN 'DG'" ).append("\n"); 
		query.append("                     WHEN QD.AWK_CGO_FLG = 'Y' THEN 'AK'" ).append("\n"); 
		query.append("                     WHEN QD.RC_FLG      = 'Y' THEN 'RF'" ).append("\n"); 
		query.append("                     WHEN QD.BB_CGO_FLG  = 'Y' THEN 'BB'" ).append("\n"); 
		query.append("                     ELSE 'DR'" ).append("\n"); 
		query.append("                 END CGO_TP_CD" ).append("\n"); 
		query.append("              , SUM(QD.OP_CNTR_QTY) CNTR_QTY" ).append("\n"); 
		query.append("           FROM BKG_QTY_DTL QD" ).append("\n"); 
		query.append("              , ( SELECT" ).append("\n"); 
		query.append("                         BKG_NO " ).append("\n"); 
		query.append("                    FROM BKG_NO_LIST" ).append("\n"); 
		query.append("                   GROUP BY BKG_NO) BL" ).append("\n"); 
		query.append("          WHERE QD.BKG_NO       = BL.BKG_NO" ).append("\n"); 
		query.append("            AND QD.CNTR_TPSZ_CD NOT LIKE 'Q%'" ).append("\n"); 
		query.append("          GROUP BY QD.BKG_NO" ).append("\n"); 
		query.append("                 , CASE WHEN QD.CNTR_TPSZ_CD LIKE 'R%' AND" ).append("\n"); 
		query.append("                             QD.DRY_CGO_FLG = 'Y'" ).append("\n"); 
		query.append("                        THEN QD.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                        ELSE NVL(QD.EQ_SUBST_CNTR_TPSZ_CD, QD.CNTR_TPSZ_CD)" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("                 , CASE WHEN  QD.DCGO_FLG    = 'Y' THEN 'DG'" ).append("\n"); 
		query.append("                        WHEN  QD.AWK_CGO_FLG = 'Y' THEN 'AK'" ).append("\n"); 
		query.append("                        WHEN  QD.RC_FLG      = 'Y' THEN 'RF'" ).append("\n"); 
		query.append("                        WHEN  QD.BB_CGO_FLG  = 'Y' THEN 'BB'" ).append("\n"); 
		query.append("                        ELSE  'DR'" ).append("\n"); 
		query.append("                    END ) T1" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(", BKG_RT  AS (    " ).append("\n"); 
		query.append("    SELECT  " ).append("\n"); 
		query.append("           RT.BKG_NO" ).append("\n"); 
		query.append("         , RT.RT_SEQ" ).append("\n"); 
		query.append("         , RT.CGO_CATE_CD" ).append("\n"); 
		query.append("         , RT.CHG_CD" ).append("\n"); 
		query.append("         , RT.RAT_UT_CD" ).append("\n"); 
		query.append("         , RT.RAT_AS_QTY" ).append("\n"); 
		query.append("         , RT.CHG_UT_AMT" ).append("\n"); 
		query.append("         , RT.CHG_AMT" ).append("\n"); 
		query.append("         , (SELECT A.CNTR_SZ_CD FROM PRI_RAT_UT A WHERE A.RAT_UT_CD = RT.RAT_UT_CD ) AS RAT_SZ_CD" ).append("\n"); 
		query.append("         , RT.CURR_CD" ).append("\n"); 
		query.append("         , RT.FRT_TERM_CD" ).append("\n"); 
		query.append("      FROM BKG_CHG_RT  RT" ).append("\n"); 
		query.append("         , (SELECT BKG_NO FROM BKG_NO_LIST GROUP BY BKG_NO) BL" ).append("\n"); 
		query.append("     WHERE RT.BKG_NO = BL.BKG_NO " ).append("\n"); 
		query.append("       AND RT.FRT_INCL_XCLD_DIV_CD <> 'I'" ).append("\n"); 
		query.append("       AND RT.CHG_CD IN ( SELECT CHG_CD FROM PRI_MOT_CHG )" ).append("\n"); 
		query.append("       AND RT.RAT_UT_CD <> 'PC'" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(", BKG_RT_PC  AS (    " ).append("\n"); 
		query.append("    SELECT RT.BKG_NO" ).append("\n"); 
		query.append("         , RT.RT_SEQ" ).append("\n"); 
		query.append("         , RT.CGO_CATE_CD" ).append("\n"); 
		query.append("         , RT.CHG_CD" ).append("\n"); 
		query.append("         , RT.RAT_UT_CD" ).append("\n"); 
		query.append("         , RT.RAT_AS_QTY" ).append("\n"); 
		query.append("         , RT.CHG_UT_AMT" ).append("\n"); 
		query.append("         , RT.CHG_AMT" ).append("\n"); 
		query.append("         , (SELECT " ).append("\n"); 
		query.append("                   A.CNTR_SZ_CD " ).append("\n"); 
		query.append("              FROM PRI_RAT_UT A " ).append("\n"); 
		query.append("             WHERE A.RAT_UT_CD = RT.RAT_UT_CD )  " ).append("\n"); 
		query.append("           AS RAT_SZ_CD" ).append("\n"); 
		query.append("         , RT.CURR_CD" ).append("\n"); 
		query.append("         , RT.FRT_TERM_CD" ).append("\n"); 
		query.append("      FROM BKG_CHG_RT  RT" ).append("\n"); 
		query.append("         , (SELECT " ).append("\n"); 
		query.append("                   BKG_NO " ).append("\n"); 
		query.append("              FROM BKG_NO_LIST" ).append("\n"); 
		query.append("             GROUP BY BKG_NO) BL" ).append("\n"); 
		query.append("     WHERE RT.BKG_NO = BL.BKG_NO " ).append("\n"); 
		query.append("       AND RT.FRT_INCL_XCLD_DIV_CD <> 'I'" ).append("\n"); 
		query.append("       AND RT.CHG_CD IN ( SELECT CHG_CD FROM PRI_MOT_CHG )" ).append("\n"); 
		query.append("       AND RT.RAT_UT_CD = 'PC'" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(", RT_TPSZ_MTCH  AS (" ).append("\n"); 
		query.append("    SELECT  T2.BKG_NO  ," ).append("\n"); 
		query.append("            T2.CNTR_TPSZ_CD, " ).append("\n"); 
		query.append("            T2.CNTR_QTY, -- 필요한 칼럼 추가해야 함" ).append("\n"); 
		query.append("            T2.CNTR_TPSZ_KNT," ).append("\n"); 
		query.append("            T2.TTL_CNTR_QTY," ).append("\n"); 
		query.append("            T2.CGO_TP_CD," ).append("\n"); 
		query.append("            T2.CNTR_SZ_CD," ).append("\n"); 
		query.append("            T1.BKG_NO       AS RT_BKG_NO," ).append("\n"); 
		query.append("            T1.RT_SEQ       ," ).append("\n"); 
		query.append("            T1.CGO_CATE_CD  ," ).append("\n"); 
		query.append("            T1.CHG_CD       ," ).append("\n"); 
		query.append("            T1.RAT_UT_CD    ," ).append("\n"); 
		query.append("            T1.RAT_AS_QTY   ," ).append("\n"); 
		query.append("            T1.CHG_UT_AMT   ," ).append("\n"); 
		query.append("            T1.CHG_AMT      ," ).append("\n"); 
		query.append("            T1.RAT_SZ_CD    ," ).append("\n"); 
		query.append("            T1.CURR_CD      ," ).append("\n"); 
		query.append("            T1.FRT_TERM_CD  ," ).append("\n"); 
		query.append("        CASE" ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = T2.CNTR_TPSZ_CD  THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  95" ).append("\n"); 
		query.append("                    ELSE  90" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_SZ_CD  = T2.CNTR_SZ_CD AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT      A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   = T2.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  85" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  80" ).append("\n"); 
		query.append("                    ELSE  75" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_SZ_CD  = T2.CNTR_SZ_CD THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  70" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  65" ).append("\n"); 
		query.append("                    ELSE  60" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BX' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   = T2.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_SZ_CD   = T2.CNTR_SZ_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   IN ( '20', '40', '45', '53' )" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  55" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  50" ).append("\n"); 
		query.append("                    ELSE  45" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BX' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  40" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  35" ).append("\n"); 
		query.append("                    ELSE  30" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BL' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   = T2.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_SZ_CD   = T2.CNTR_SZ_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   IN ( '20', '40', '45', '53' )" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.CHG_CD       <> 'OFT'            THEN  100" ).append("\n"); 
		query.append("                    WHEN  T2.CGO_TP_CD    IN ( 'AK', 'BB' )   THEN  25" ).append("\n"); 
		query.append("                    ELSE  20" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BL' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.CHG_CD       <> 'OFT'            THEN  100" ).append("\n"); 
		query.append("                    WHEN  T2.CGO_TP_CD    IN ( 'AK', 'BB' )   THEN  15" ).append("\n"); 
		query.append("                    ELSE  10" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'PC' THEN  100" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            ELSE  1" ).append("\n"); 
		query.append("            END MTCH_IND" ).append("\n"); 
		query.append("    FROM    BKG_RT    T1  ," ).append("\n"); 
		query.append("            BKG_TPSZ  T2" ).append("\n"); 
		query.append("    WHERE   T1.BKG_NO(+) = T2.BKG_NO   " ).append("\n"); 
		query.append("      AND   T1.CGO_CATE_CD(+) = T2.CGO_TP_CD" ).append("\n"); 
		query.append("    UNION ALL" ).append("\n"); 
		query.append("    SELECT  T2.BKG_NO  ," ).append("\n"); 
		query.append("            T2.CNTR_TPSZ_CD, " ).append("\n"); 
		query.append("            T2.CNTR_QTY, -- 필요한 칼럼 추가해야 함" ).append("\n"); 
		query.append("            T2.CNTR_TPSZ_KNT," ).append("\n"); 
		query.append("            T2.TTL_CNTR_QTY," ).append("\n"); 
		query.append("            T2.CGO_TP_CD," ).append("\n"); 
		query.append("            T2.CNTR_SZ_CD," ).append("\n"); 
		query.append("            T1.BKG_NO       AS RT_BKG_NO," ).append("\n"); 
		query.append("            T1.RT_SEQ       ," ).append("\n"); 
		query.append("            T1.CGO_CATE_CD  ," ).append("\n"); 
		query.append("            T1.CHG_CD       ," ).append("\n"); 
		query.append("            T1.RAT_UT_CD    ," ).append("\n"); 
		query.append("            T1.RAT_AS_QTY   ," ).append("\n"); 
		query.append("            T1.CHG_UT_AMT   ," ).append("\n"); 
		query.append("            T1.CHG_AMT      ," ).append("\n"); 
		query.append("            T1.RAT_SZ_CD    ," ).append("\n"); 
		query.append("            T1.CURR_CD      ," ).append("\n"); 
		query.append("            T1.FRT_TERM_CD  ," ).append("\n"); 
		query.append("        CASE" ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = T2.CNTR_TPSZ_CD  THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  95" ).append("\n"); 
		query.append("                    ELSE  90" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_SZ_CD  = T2.CNTR_SZ_CD AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT      A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   = T2.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  85" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  80" ).append("\n"); 
		query.append("                    ELSE  75" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_SZ_CD  = T2.CNTR_SZ_CD THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  70" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  65" ).append("\n"); 
		query.append("                    ELSE  60" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BX' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   = T2.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_SZ_CD   = T2.CNTR_SZ_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   IN ( '20', '40', '45', '53' )" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  55" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  50" ).append("\n"); 
		query.append("                    ELSE  45" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BX' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.CNTR_TPSZ_KNT AND T1.CGO_CATE_CD = T2.CGO_TP_CD  THEN  40" ).append("\n"); 
		query.append("                    WHEN  T1.CGO_CATE_CD  = T2.CGO_TP_CD      THEN  35" ).append("\n"); 
		query.append("                    ELSE  30" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BL' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   = T2.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' AND" ).append("\n"); 
		query.append("                    NVL(" ).append("\n"); 
		query.append("                      (" ).append("\n"); 
		query.append("                      SELECT  'Y'" ).append("\n"); 
		query.append("                      FROM    BKG_RT  A" ).append("\n"); 
		query.append("                      WHERE   A.BKG_NO      = T1.BKG_NO" ).append("\n"); 
		query.append("                      AND     A.CHG_CD      = T1.CHG_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_SZ_CD   = T2.CNTR_SZ_CD" ).append("\n"); 
		query.append("                      AND     A.RAT_UT_CD   IN ( '20', '40', '45', '53' )" ).append("\n"); 
		query.append("                      AND     ROWNUM        = 1" ).append("\n"); 
		query.append("                      ), 'N') = 'N' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.CHG_CD       <> 'OFT'            THEN  100" ).append("\n"); 
		query.append("                    WHEN  T2.CGO_TP_CD    IN ( 'AK', 'BB' )   THEN  25" ).append("\n"); 
		query.append("                    ELSE  20" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'BL' THEN" ).append("\n"); 
		query.append("                    CASE" ).append("\n"); 
		query.append("                    WHEN  T1.RAT_AS_QTY   = T2.TTL_CNTR_QTY   THEN  100" ).append("\n"); 
		query.append("                    WHEN  T1.CHG_CD       <> 'OFT'            THEN  100" ).append("\n"); 
		query.append("                    WHEN  T2.CGO_TP_CD    IN ( 'AK', 'BB' )   THEN  15" ).append("\n"); 
		query.append("                    ELSE  10" ).append("\n"); 
		query.append("                    END" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            WHEN  T1.RAT_UT_CD = 'PC' THEN  100" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("            ELSE  1" ).append("\n"); 
		query.append("            END MTCH_IND" ).append("\n"); 
		query.append("      FROM (SELECT" ).append("\n"); 
		query.append("                   ROW_NUMBER() OVER (PARTITION BY BKG_NO, CGO_CATE_CD, CHG_CD ORDER BY BKG_NO, CGO_CATE_CD, CHG_CD, CHG_AMT DESC) AS BKEY," ).append("\n"); 
		query.append("                   BKG_NO, RT_SEQ, CGO_CATE_CD, CHG_CD, RAT_UT_CD, RAT_AS_QTY, CHG_UT_AMT, CHG_AMT, RAT_SZ_CD, CURR_CD, FRT_TERM_CD        " ).append("\n"); 
		query.append("              FROM BKG_RT_PC) T1" ).append("\n"); 
		query.append("         , (SELECT ROW_NUMBER() OVER (PARTITION BY BKG_NO, CGO_TP_CD ORDER BY BKG_NO, CGO_TP_CD, CNTR_TPSZ_CD DESC) AS BKEY, " ).append("\n"); 
		query.append("                   BKG_NO, CNTR_TPSZ_KNT, TTL_CNTR_QTY, CNTR_TPSZ_CD, CGO_TP_CD, CNTR_QTY, CNTR_SZ_CD" ).append("\n"); 
		query.append("              FROM BKG_TPSZ)  T2" ).append("\n"); 
		query.append("     WHERE T1.BKG_NO = T2.BKG_NO   " ).append("\n"); 
		query.append("       AND T1.CGO_CATE_CD = T2.CGO_TP_CD" ).append("\n"); 
		query.append("       AND T1.BKEY = T2.BKEY" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("), BKG_CHG_LIST AS (" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    SELECT  T1.BKG_NO" ).append("\n"); 
		query.append("        ,   T1.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("		,   ( SELECT RM.MOT_FILE_CNTR_TP_CD FROM PRI_MOT_FILE_RAT_UT_MAPG RM WHERE T1.CNTR_TPSZ_CD = RM.RAT_UT_CD ) AS MOT_CNTR_TP_CD " ).append("\n"); 
		query.append("        ,   T1.CGO_TP_CD" ).append("\n"); 
		query.append("        ,   T1.CHG_CD" ).append("\n"); 
		query.append("        ,   MAX ( T1.RAT_UT_CD ) AS RAT_UT_CD" ).append("\n"); 
		query.append("        ,   CASE WHEN T1.RAT_UT_CD = 'PC' THEN SUM ( T1.CHG_AMT ) ELSE MAX ( T1.CHG_UT_AMT ) END RT_AMT" ).append("\n"); 
		query.append("        ,   MAX(T1.CURR_CD) AS CURR_CD" ).append("\n"); 
		query.append("        ,   T1.FRT_TERM_CD" ).append("\n"); 
		query.append("    FROM    RT_TPSZ_MTCH  T1" ).append("\n"); 
		query.append("    WHERE   NOT EXISTS  (" ).append("\n"); 
		query.append("                        SELECT  'X'" ).append("\n"); 
		query.append("                        FROM    RT_TPSZ_MTCH  T2" ).append("\n"); 
		query.append("                        WHERE   T2.BKG_NO   = T1.BKG_NO" ).append("\n"); 
		query.append("                        AND     T2.RT_SEQ   = T1.RT_SEQ" ).append("\n"); 
		query.append("                        AND     T2.MTCH_IND > T1.MTCH_IND" ).append("\n"); 
		query.append("                        )" ).append("\n"); 
		query.append("    GROUP   BY  " ).append("\n"); 
		query.append("            T1.BKG_NO" ).append("\n"); 
		query.append("        ,   T1.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("        ,   T1.CGO_TP_CD" ).append("\n"); 
		query.append("        ,   T1.CHG_CD" ).append("\n"); 
		query.append("        ,   T1.FRT_TERM_CD" ).append("\n"); 
		query.append("        ,   T1.RAT_UT_CD" ).append("\n"); 
		query.append("    ORDER   BY         " ).append("\n"); 
		query.append("            T1.BKG_NO" ).append("\n"); 
		query.append("        ,   T1.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("        ,   T1.CGO_TP_CD" ).append("\n"); 
		query.append("        ,   T1.CHG_CD" ).append("\n"); 
		query.append("        ,   T1.FRT_TERM_CD" ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("SELECT A.* FROM (" ).append("\n"); 
		query.append("	SELECT DISTINCT BF.BAT_EXE_DT" ).append("\n"); 
		query.append("             --, BF.MOT_FILE_RT_SEQ" ).append("\n"); 
		query.append("             --, BF.SCG_SEQ" ).append("\n"); 
		query.append("             , DENSE_RANK () OVER ( ORDER BY BF.IND, BF.BKG_NO, BF.CNTR_TPSZ_CD, BF.CGO_TP_CD, BF.BKG_CGO_CATE ) AS MOT_FILE_RT_SEQ" ).append("\n"); 
		query.append("             , ROW_NUMBER () OVER ( PARTITION BY BF.IND, BF.BKG_NO, BF.CNTR_TPSZ_CD, BF.CGO_TP_CD, BF.BKG_CGO_CATE  ORDER BY  DECODE ( BF.CHG_CD, 'OFT', '000', '111' ), BF.CHG_CD, BF.BASE_CUST_NM ) AS SCG_SEQ" ).append("\n"); 
		query.append("             , BF.BKG_NO" ).append("\n"); 
		query.append("             , BF.IND AS BKG_SRC_TP_CD" ).append("\n"); 
		query.append("             , BF.SHPR_CNT_CD" ).append("\n"); 
		query.append("             , BF.SHPR_SEQ" ).append("\n"); 
		query.append("             , BF.CTRT_NO" ).append("\n"); 
		query.append("             , BF.BASE_CUST_NM" ).append("\n"); 
		query.append("             , BF.CTRT_HLDR" ).append("\n"); 
		query.append("             , BF.ACT_CUST AS ACT_CUST_NM" ).append("\n"); 
		query.append("             , BF.CNEE_NM" ).append("\n"); 
		query.append("             , BF.OP_AGN_NM" ).append("\n"); 
		query.append("             , INSTR(NVL(BF.CTRT_HLDR,' '),'*') AS CTRT_HLDR_1" ).append("\n"); 
		query.append("             , INSTR(NVL(BF.ACT_CUST,' '),'*') AS ACT_CUST_NM_1" ).append("\n"); 
		query.append("             , INSTR(NVL(BF.CNEE_NM,' '),'*') AS CNEE_NM_1" ).append("\n"); 
		query.append("             , BF.MOT_FILE_LANE_CD" ).append("\n"); 
		query.append("             , BF.MOT_FILE_OLOC_CD" ).append("\n"); 
		query.append("             , BF.MOT_FILE_DLOC_CD" ).append("\n"); 
		query.append("             , BF.MF_RAT_UT_CD AS MOT_FILE_CNTR_TP_CD" ).append("\n"); 
		query.append("             , BF.BKG_CGO_CATE AS MOT_FILE_CMDT_TP_CD" ).append("\n"); 
		query.append("             , BF.SZ AS MOT_FILE_CNTR_SZ_CD" ).append("\n"); 
		query.append("             , BF.CTRT_EFF_DT" ).append("\n"); 
		query.append("             , BF.CTRT_EXP_DT" ).append("\n"); 
		query.append("             , BF.CHG_CD" ).append("\n"); 
		query.append("             , BF.RAT_UT_CD" ).append("\n"); 
		query.append("             , BF.RT_AMT AS MOT_FILE_CHG_AMT" ).append("\n"); 
		query.append("             , BF.OFT_AMT AS MOT_FILE_RT_AMT" ).append("\n"); 
		query.append("             , BF.CURR_CD" ).append("\n"); 
		query.append("             , NULL AS COMM_AMT --NO USE " ).append("\n"); 
		query.append("             , BF.FWRD_CNT_CD" ).append("\n"); 
		query.append("             , BF.FWRD_CUST_SEQ " ).append("\n"); 
		query.append("          FROM (" ).append("\n"); 
		query.append("                --BL.O_LOC_GB = 'POL' 인 경우" ).append("\n"); 
		query.append("                SELECT DISTINCT" ).append("\n"); 
		query.append("                       TO_DATE (@[test_exec_dt], 'YYYY-MM-DD' ) AS BAT_EXE_DT" ).append("\n"); 
		query.append("                     --, DENSE_RANK () OVER ( ORDER BY BL.IND, BL.BKG_NO, T1.CNTR_TPSZ_CD, T1.CGO_TP_CD ) AS MOT_FILE_RT_SEQ" ).append("\n"); 
		query.append("                     --, RANK () OVER ( PARTITION BY BL.IND, BL.BKG_NO, T1.CNTR_TPSZ_CD, T1.CGO_TP_CD  ORDER BY  DECODE ( T1.CHG_CD, 'OFT', '000', '111' ), T1.CHG_CD, CL.CCP_NM  ) AS SCG_SEQ" ).append("\n"); 
		query.append("                     , BL.BKG_NO" ).append("\n"); 
		query.append("                     , BL.IND" ).append("\n"); 
		query.append("                     , CL.CUST_CNT_CD  AS SHPR_CNT_CD  --Customer Code" ).append("\n"); 
		query.append("                     , CL.CUST_SEQ     AS SHPR_SEQ     --Customer Seq" ).append("\n"); 
		query.append("                     , BL.CTRT_NO                              --SCRA No." ).append("\n"); 
		query.append("                     , CL.CCP_NM               AS BASE_CUST_NM --VERIFY FIELD(NOT USE)" ).append("\n"); 
		query.append("                     , INSTR(NVL(CL.CCP_NM,' '),'*') AS CTRT_HLDR_1" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN BC_CNEE.CUST_NM" ).append("\n"); 
		query.append("                                   ELSE CL.CCP_NM" ).append("\n"); 
		query.append("                       END CTRT_HLDR                           --Contractor" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN ''" ).append("\n"); 
		query.append("                            ELSE BC_SHIP.CUST_NM" ).append("\n"); 
		query.append("                        END  ACT_CUST                          --Shipper" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN ''" ).append("\n"); 
		query.append("                            WHEN INSTR(NVL(CL.CCP_NM,' '),'TO ORDER') >= 1  THEN ''" ).append("\n"); 
		query.append("                            ELSE BC_CNEE.CUST_NM" ).append("\n"); 
		query.append("                        END  CNEE_NM                           --Consignee" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN CL.CCP_NM" ).append("\n"); 
		query.append("                            ELSE ''" ).append("\n"); 
		query.append("                        END  OP_AGN_NM                         --Operation Agent  " ).append("\n"); 
		query.append("                     , NVL(DL.MOT_FILE_LANE_CD,'1') AS MOT_FILE_LANE_CD --Lane                     " ).append("\n"); 
		query.append("                     , CASE WHEN BL.POR_CD IN ('CNNKG', 'CNLYG') THEN BL.POR_CD" ).append("\n"); 
		query.append("                            ELSE OL.MOT_FILE_LOC_CD END MOT_FILE_OLOC_CD  --POL" ).append("\n"); 
		query.append("                     , DL.MOT_FILE_LOC_CD AS MOT_FILE_DLOC_CD  --POD" ).append("\n"); 
		query.append("                     , BL.O_LOC_GB" ).append("\n"); 
		query.append("                     , BL.POR_CD" ).append("\n"); 
		query.append("                     , BL.BKG_CGO_CATE" ).append("\n"); 
		query.append("                     , RM.MOT_FILE_CNTR_TP_CD AS MF_RAT_UT_CD  --Container Type" ).append("\n"); 
		query.append("                     , SUBSTR ( CS.CNTR_SZ_DESC, 1, 2 ) AS SZ  --Container Size" ).append("\n"); 
		query.append("                     , CL.CTRT_EFF_DT" ).append("\n"); 
		query.append("                     , CL.CTRT_EXP_DT" ).append("\n"); 
		query.append("                     , T1.CHG_CD" ).append("\n"); 
		query.append("                     , T1.RAT_UT_CD" ).append("\n"); 
		query.append("                     , T1.RT_AMT" ).append("\n"); 
		query.append("                     , MAX ( DECODE ( T1.CHG_CD, 'OFT', T1.RT_AMT, NULL ) ) OVER ( PARTITION BY BL.IND, BL.BKG_NO, T1.CNTR_TPSZ_CD, T1.CGO_TP_CD ) AS OFT_AMT " ).append("\n"); 
		query.append("                     , T1.CURR_CD" ).append("\n"); 
		query.append("                     , T1.FRT_TERM_CD --PAY_TERM_CD" ).append("\n"); 
		query.append("                     , BQ.SOC_FLG" ).append("\n"); 
		query.append("                     , T1.CGO_TP_CD" ).append("\n"); 
		query.append("                     , T1.MOT_CNTR_TP_CD" ).append("\n"); 
		query.append("                     , BL.FWRD_CNT_CD" ).append("\n"); 
		query.append("                     , BL.FWRD_CUST_SEQ " ).append("\n"); 
		query.append("                     , T1.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                 FROM  BKG_CHG_LIST  T1" ).append("\n"); 
		query.append("                     , BKG_INFO_LIST BL" ).append("\n"); 
		query.append("                     , CTRT_INFO_LIST CL" ).append("\n"); 
		query.append("                     , PRI_MOT_FILE_LOC_PPT OL" ).append("\n"); 
		query.append("                     , PRI_MOT_FILE_LOC_PPT DL" ).append("\n"); 
		query.append("                     , PRI_MOT_FILE_RAT_UT_MAPG RM" ).append("\n"); 
		query.append("                     , MDM_CNTR_TP_SZ  TS" ).append("\n"); 
		query.append("                     , MDM_CNTR_SZ  CS" ).append("\n"); 
		query.append("                     , BKG_CUSTOMER BC_SHIP" ).append("\n"); 
		query.append("                     , BKG_CUSTOMER BC_CNEE" ).append("\n"); 
		query.append("                     , BKG_QTY_DTL BQ" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                 WHERE BL.BKG_NO = T1.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND BL.CTRT_NO = CL.CTRT_NO(+)" ).append("\n"); 
		query.append("                   AND NVL ( BL.RT_APLY_DT, SYSDATE ) = NVL ( CL.RT_APLY_DT, SYSDATE ) " ).append("\n"); 
		query.append("                   AND BL.O_LOC_GB = 'POL' AND BL.POL_CD = OL.LOC_CD AND OL.ORG_DEST_TP_CD = 'O'" ).append("\n"); 
		query.append("                   AND BL.POR_CD NOT IN ('CNNKG', 'CNLYG')" ).append("\n"); 
		query.append("				   AND BL.BKG_CGO_CATE_TPSZ = BQ.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                   AND BL.POD_CD = DL.LOC_CD" ).append("\n"); 
		query.append("                   AND DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("                 " ).append("\n"); 
		query.append("                   AND BL.BKG_NO = BC_SHIP.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND BC_SHIP.BKG_CUST_TP_CD (+)= 'S'" ).append("\n"); 
		query.append("                   AND BL.BKG_NO = BC_CNEE.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND BC_CNEE.BKG_CUST_TP_CD (+)= 'C'" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                   AND T1.CNTR_TPSZ_CD = RM.RAT_UT_CD(+)" ).append("\n"); 
		query.append("                   AND T1.CNTR_TPSZ_CD = TS.CNTR_TPSZ_CD(+)" ).append("\n"); 
		query.append("                   AND TS.CNTR_SZ_CD   = CS.CNTR_SZ_CD(+) " ).append("\n"); 
		query.append("                   " ).append("\n"); 
		query.append("                   AND T1.BKG_NO = BQ.BKG_NO(+) " ).append("\n"); 
		query.append("                   AND T1.CNTR_TPSZ_CD = BQ.CNTR_TPSZ_CD(+)                    " ).append("\n"); 
		query.append("                   AND T1.CHG_CD IS NOT NULL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                 UNION ALL" ).append("\n"); 
		query.append("                --BL.O_LOC_GB = 'POR' 인 경우" ).append("\n"); 
		query.append("                SELECT DISTINCT" ).append("\n"); 
		query.append("                       TO_DATE (@[test_exec_dt], 'YYYY-MM-DD' ) AS BAT_EXE_DT" ).append("\n"); 
		query.append("                     --, DENSE_RANK () OVER ( ORDER BY BL.IND, BL.BKG_NO, T1.CNTR_TPSZ_CD, T1.CGO_TP_CD ) AS MOT_FILE_RT_SEQ" ).append("\n"); 
		query.append("                     --, RANK () OVER ( PARTITION BY BL.IND, BL.BKG_NO, T1.CNTR_TPSZ_CD, T1.CGO_TP_CD  ORDER BY  DECODE ( T1.CHG_CD, 'OFT', '000', '111' ), T1.CHG_CD, CL.CCP_NM  ) AS SCG_SEQ" ).append("\n"); 
		query.append("                     , BL.BKG_NO" ).append("\n"); 
		query.append("                     , BL.IND" ).append("\n"); 
		query.append("                     , CL.CUST_CNT_CD  AS SHPR_CNT_CD  --Customer Code" ).append("\n"); 
		query.append("                     , CL.CUST_SEQ     AS SHPR_SEQ     --Customer Seq" ).append("\n"); 
		query.append("                     , BL.CTRT_NO                              --SCRA No." ).append("\n"); 
		query.append("                     , CL.CCP_NM               AS BASE_CUST_NM --VERIFY FIELD(NOT USE)" ).append("\n"); 
		query.append("                     , INSTR(NVL(CL.CCP_NM,' '),'*') AS CTRT_HLDR_1" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN BC_CNEE.CUST_NM" ).append("\n"); 
		query.append("                                   ELSE CL.CCP_NM" ).append("\n"); 
		query.append("                       END CTRT_HLDR                           --Contractor" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN ''" ).append("\n"); 
		query.append("                            ELSE BC_SHIP.CUST_NM" ).append("\n"); 
		query.append("                        END  ACT_CUST                          --Shipper" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN ''" ).append("\n"); 
		query.append("                            WHEN INSTR(NVL(CL.CCP_NM,' '),'TO ORDER') >= 1  THEN ''" ).append("\n"); 
		query.append("                            ELSE BC_CNEE.CUST_NM" ).append("\n"); 
		query.append("                        END  CNEE_NM                           --Consignee" ).append("\n"); 
		query.append("                     , CASE WHEN INSTR(NVL(CL.CCP_NM,' '),'SHIPPERS ASSO') >= 1  THEN CL.CCP_NM" ).append("\n"); 
		query.append("                            ELSE ''" ).append("\n"); 
		query.append("                        END  OP_AGN_NM                         --Operation Agent  " ).append("\n"); 
		query.append("                     , NVL(DL.MOT_FILE_LANE_CD,'1') AS MOT_FILE_LANE_CD --Lane" ).append("\n"); 
		query.append("                     " ).append("\n"); 
		query.append("                     , BL.POR_CD AS MOT_FILE_OLOC_CD  --POL" ).append("\n"); 
		query.append("                     , DL.MOT_FILE_LOC_CD AS MOT_FILE_DLOC_CD  --POD" ).append("\n"); 
		query.append("                     , BL.O_LOC_GB" ).append("\n"); 
		query.append("                     , BL.POR_CD" ).append("\n"); 
		query.append("                     , BL.BKG_CGO_CATE" ).append("\n"); 
		query.append("                     , RM.MOT_FILE_CNTR_TP_CD AS MF_RAT_UT_CD  --Container Type" ).append("\n"); 
		query.append("                     , SUBSTR ( CS.CNTR_SZ_DESC, 1, 2 ) AS SZ  --Container Size" ).append("\n"); 
		query.append("                     , CL.CTRT_EFF_DT" ).append("\n"); 
		query.append("                     , CL.CTRT_EXP_DT" ).append("\n"); 
		query.append("                     , T1.CHG_CD" ).append("\n"); 
		query.append("                     , T1.RAT_UT_CD" ).append("\n"); 
		query.append("                     , T1.RT_AMT" ).append("\n"); 
		query.append("                     , MAX ( DECODE ( T1.CHG_CD, 'OFT', T1.RT_AMT, NULL ) ) OVER ( PARTITION BY BL.IND, BL.BKG_NO, T1.CNTR_TPSZ_CD, T1.CGO_TP_CD) AS OFT_AMT " ).append("\n"); 
		query.append("                     , T1.CURR_CD" ).append("\n"); 
		query.append("                     " ).append("\n"); 
		query.append("                     , T1.FRT_TERM_CD --PAY_TERM_CD" ).append("\n"); 
		query.append("                     , BQ.SOC_FLG" ).append("\n"); 
		query.append("                     , T1.CGO_TP_CD" ).append("\n"); 
		query.append("                     , T1.MOT_CNTR_TP_CD" ).append("\n"); 
		query.append("                     , BL.FWRD_CNT_CD" ).append("\n"); 
		query.append("                     , BL.FWRD_CUST_SEQ " ).append("\n"); 
		query.append("                     , T1.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                 FROM  BKG_CHG_LIST  T1" ).append("\n"); 
		query.append("                     , BKG_INFO_LIST BL" ).append("\n"); 
		query.append("                     , CTRT_INFO_LIST CL" ).append("\n"); 
		query.append("                     , PRI_MOT_FILE_LOC_PPT DL" ).append("\n"); 
		query.append("                     , PRI_MOT_FILE_RAT_UT_MAPG RM" ).append("\n"); 
		query.append("                     , MDM_CNTR_TP_SZ  TS" ).append("\n"); 
		query.append("                     , MDM_CNTR_SZ  CS" ).append("\n"); 
		query.append("                     , BKG_CUSTOMER BC_SHIP" ).append("\n"); 
		query.append("                     , BKG_CUSTOMER BC_CNEE" ).append("\n"); 
		query.append("                     , BKG_QTY_DTL BQ" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                 WHERE BL.BKG_NO = T1.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND BL.CTRT_NO = CL.CTRT_NO(+)" ).append("\n"); 
		query.append("                   AND NVL ( BL.RT_APLY_DT, SYSDATE ) = NVL ( CL.RT_APLY_DT, SYSDATE ) " ).append("\n"); 
		query.append("                   AND BL.O_LOC_GB = 'POR' AND BL.POR_CD IN ('CNNKG', 'CNLYG')" ).append("\n"); 
		query.append("	               AND BL.BKG_CGO_CATE_TPSZ = BQ.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                   " ).append("\n"); 
		query.append("                   AND BL.POD_CD = DL.LOC_CD" ).append("\n"); 
		query.append("                   AND DL.ORG_DEST_TP_CD = 'D'" ).append("\n"); 
		query.append("                 " ).append("\n"); 
		query.append("                   AND BL.BKG_NO = BC_SHIP.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND BC_SHIP.BKG_CUST_TP_CD (+)= 'S'" ).append("\n"); 
		query.append("                   AND BL.BKG_NO = BC_CNEE.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND BC_CNEE.BKG_CUST_TP_CD (+)= 'C'" ).append("\n"); 
		query.append("                 " ).append("\n"); 
		query.append("                   AND T1.CNTR_TPSZ_CD = RM.RAT_UT_CD(+)" ).append("\n"); 
		query.append("                   AND T1.CNTR_TPSZ_CD = TS.CNTR_TPSZ_CD(+)" ).append("\n"); 
		query.append("                   AND TS.CNTR_SZ_CD   = CS.CNTR_SZ_CD(+) " ).append("\n"); 
		query.append("                   " ).append("\n"); 
		query.append("                   AND T1.BKG_NO = BQ.BKG_NO(+) " ).append("\n"); 
		query.append("                   AND T1.CNTR_TPSZ_CD = BQ.CNTR_TPSZ_CD(+) " ).append("\n"); 
		query.append("                   AND T1.CHG_CD IS NOT NULL" ).append("\n"); 
		query.append("	) BF" ).append("\n"); 
		query.append(" ) A" ).append("\n"); 
		query.append(" WHERE ( A.CTRT_HLDR_1 < 1 AND A.ACT_CUST_NM_1 < 1 AND A.CNEE_NM_1 < 1 )" ).append("\n"); 
		query.append("   AND ( A.MOT_FILE_RT_AMT  IS NOT NULL)" ).append("\n"); 
		query.append(" ORDER BY 2, 3, 4, 5, 6, 7, 8, 9" ).append("\n"); 

	}
}