/*=========================================================
*Copyright(c) 2009 CyberLogitec
*@FileName : InputDataRLAExamineDBDAOSearchInputDataRLAListRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2009.10.07
*@LastModifier : 정은호
*@LastVersion : 1.0
* 2009.10.07 정은호
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.ees.eqr.scenariomanage.inputdatarlaexamine.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author ChungEunHo
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class InputDataRLAExamineDBDAOSearchInputDataRLAListRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * Input Data Red Light Alert (EES_EQR_003) 조회
	  * </pre>
	  */
	public InputDataRLAExamineDBDAOSearchInputDataRLAListRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("toWeek",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("scnrPlanID",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("fromWeek",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.ees.eqr.scenariomanage.inputdatarlaexamine.integration").append("\n"); 
		query.append("FileName : InputDataRLAExamineDBDAOSearchInputDataRLAListRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("#if (${datatype} == 'LNK' || ${datatype} == '')" ).append("\n"); 
		query.append("-- LINK INFO START" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.WEEK" ).append("\n"); 
		query.append(",A.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.VOL_TOTAL" ).append("\n"); 
		query.append(",A.AMT_TOTAL" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",NVL(A.VOL_$key, 0)" ).append("\n"); 
		query.append(",NVL(A.AMT_$key, 0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,A.CHECKBOX" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",'F' VOL_FLAG$key" ).append("\n"); 
		query.append(",'F' AMT_FLAG$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append(",@[scnrPlanID] SCNR_ID" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--      ,A.FM_ECC_CD" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("#if(${fmTypeBy} != '')" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,A.TO_ECC_CD" ).append("\n"); 
		query.append("#if(${toTypeBy} != '')" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${atTypeBy} != '')" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("VOL_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("AMT_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",SUM(A.VOL_$key)     VOL_$key" ).append("\n"); 
		query.append(",SUM(A.AMT_$key)     AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,'' CHECKBOX" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("SUBSTR(A.SCNR_ID, 5, 6) WEEK" ).append("\n"); 
		query.append(",'LNK' DATACODE" ).append("\n"); 
		query.append(",B.ITEMNAME ALERTITEM" ).append("\n"); 
		query.append(",C.DIVNAME DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",'' VVD" ).append("\n"); 
		query.append(",null VOL_TOTAL" ).append("\n"); 
		query.append(",SUM(A.LINKAMT) AMT_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",null VOL_$key" ).append("\n"); 
		query.append(",SUM(DECODE(SUBSTR('$key' , 2 , 1), 2, DECODE(A.TPSIZE, 20, LINKAMT), 4, DECODE(A.TPSIZE, 40, LINKAMT), DECODE(A.TPSIZE, 45, LINKAMT))) AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",'1' SORTNUM" ).append("\n"); 
		query.append(",A.TRSP_MOD_CD DIVNUM" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- BELOW" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.SCNR_ID" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.ITEM" ).append("\n"); 
		query.append(",B.ALT_BSE_CD DIV" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",A.AMT LINKAMT" ).append("\n"); 
		query.append(",B.AMT ALERTAMT" ).append("\n"); 
		query.append(",A.TRSP_MOD_CD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- LINK INFO" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("DISTINCT A.SCNR_ID" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",DECODE(A.TRSP_MOD_CD, 'W','WAT','T','TRK','R','RAL')  ITEM" ).append("\n"); 
		query.append(",C.TPSIZE TPSIZE" ).append("\n"); 
		query.append(",DECODE(C.TPSIZE, 20, A.TZ_20FT_COST_AMT, 40, A.TZ_40FT_COST_AMT, 45, A.TZ_45FT_COST_AMT) AMT" ).append("\n"); 
		query.append(",B.RCC_CD" ).append("\n"); 
		query.append(",A.TRSP_MOD_CD" ).append("\n"); 
		query.append("FROM EQR_SCNR_ECC_LNK A," ).append("\n"); 
		query.append("MDM_EQ_ORZ_CHT B," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT 20 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 40 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 45 TPSIZE FROM DUAL" ).append("\n"); 
		query.append(") C" ).append("\n"); 
		query.append("WHERE A.FM_ECC_CD = B.ECC_CD(+)" ).append("\n"); 
		query.append("AND   A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- RED LIGHT ALERT" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("RCC_CD" ).append("\n"); 
		query.append(",ALT_ITM_DIV_CD ITEM" ).append("\n"); 
		query.append(",ALT_BSE_CD" ).append("\n"); 
		query.append(",CNTR_SZ_CD TPSIZE" ).append("\n"); 
		query.append(",NVL(ALT_COST_AMT,0) AMT" ).append("\n"); 
		query.append("FROM EQR_INP_DAT_RED_LGT_ALT" ).append("\n"); 
		query.append("WHERE" ).append("\n"); 
		query.append("TO_CHAR(CNTR_SZ_CD) <> 'NA'" ).append("\n"); 
		query.append("AND    ALT_ITM_DIV_CD IN ('WAT','TRK','RAL')" ).append("\n"); 
		query.append("AND    ALT_BSE_CD = 'B' -- BELOW" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE" ).append("\n"); 
		query.append("A.RCC_CD = B.RCC_CD" ).append("\n"); 
		query.append("AND   A.ITEM   = B.ITEM" ).append("\n"); 
		query.append("AND   A.TPSIZE = B.TPSIZE" ).append("\n"); 
		query.append("AND   A.AMT < B.AMT -- BELOW" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- OVER" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.SCNR_ID" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.ITEM" ).append("\n"); 
		query.append(",B.ALT_BSE_CD DIV" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",A.AMT" ).append("\n"); 
		query.append(",B.AMT" ).append("\n"); 
		query.append(",A.TRSP_MOD_CD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- LINK INFO" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("DISTINCT A.SCNR_ID" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",DECODE(A.TRSP_MOD_CD, 'W','WAT','T','TRK','R','RAL')  ITEM" ).append("\n"); 
		query.append(",C.TPSIZE TPSIZE" ).append("\n"); 
		query.append(",DECODE(C.TPSIZE, 20, A.TZ_20FT_COST_AMT, 40, A.TZ_40FT_COST_AMT, 45, A.TZ_45FT_COST_AMT) AMT" ).append("\n"); 
		query.append(",B.RCC_CD" ).append("\n"); 
		query.append(",A.TRSP_MOD_CD" ).append("\n"); 
		query.append("FROM EQR_SCNR_ECC_LNK A," ).append("\n"); 
		query.append("MDM_EQ_ORZ_CHT B," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT 20 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 40 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 45 TPSIZE FROM DUAL" ).append("\n"); 
		query.append(") C" ).append("\n"); 
		query.append("WHERE A.FM_ECC_CD = B.ECC_CD(+)" ).append("\n"); 
		query.append("AND   A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- RED LIGHT ALERT" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("RCC_CD" ).append("\n"); 
		query.append(",ALT_ITM_DIV_CD ITEM" ).append("\n"); 
		query.append(",ALT_BSE_CD" ).append("\n"); 
		query.append(",CNTR_SZ_CD TPSIZE" ).append("\n"); 
		query.append(",NVL(ALT_COST_AMT,0) AMT" ).append("\n"); 
		query.append("FROM EQR_INP_DAT_RED_LGT_ALT" ).append("\n"); 
		query.append("WHERE" ).append("\n"); 
		query.append("TO_CHAR(CNTR_SZ_CD) <> 'NA'" ).append("\n"); 
		query.append("AND    ALT_ITM_DIV_CD IN ('WAT','TRK','RAL')" ).append("\n"); 
		query.append("AND    ALT_BSE_CD = 'O' -- BELOW" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE" ).append("\n"); 
		query.append("A.RCC_CD = B.RCC_CD" ).append("\n"); 
		query.append("AND   A.ITEM   = B.ITEM" ).append("\n"); 
		query.append("AND   A.TPSIZE = B.TPSIZE" ).append("\n"); 
		query.append("AND   A.AMT > B.AMT -- OVER" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("INTG_CD_VAL_CTNT ITEMCODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC ITEMNAME" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00873'" ).append("\n"); 
		query.append(") B," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("INTG_CD_VAL_CTNT DIVCODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DP_DESC DIVNAME" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00876'" ).append("\n"); 
		query.append(") C" ).append("\n"); 
		query.append("WHERE A.ITEM     = B.ITEMCODE" ).append("\n"); 
		query.append("AND   A.DIV      = C.DIVCODE" ).append("\n"); 
		query.append("-- FROM TO" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("#if(${fromStatus} != '')" ).append("\n"); 
		query.append("AND   A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toStatus} != '')" ).append("\n"); 
		query.append("AND   A.TO_ECC_CD IN (" ).append("\n"); 
		query.append("#if(${fmtoat}== '1' && ${toStatus} != '')" ).append("\n"); 
		query.append("#foreach($key IN ${toeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $toeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("-- AT" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${atStatus} != '')" ).append("\n"); 
		query.append("AND" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(") OR A.TO_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("GROUP BY SUBSTR(A.SCNR_ID, 5, 6)" ).append("\n"); 
		query.append(",B.ITEMNAME" ).append("\n"); 
		query.append(",C.DIVNAME" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.TRSP_MOD_CD" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- INPUT DATA TYPE" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT DATACODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC DATATYPE" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00248'" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.DATACODE = B.DATACODE" ).append("\n"); 
		query.append("GROUP BY A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append("ORDER BY 1,2,3,4" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("-- LINK INFO END" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- ECC INFO" ).append("\n"); 
		query.append("#if(${datatype} == '')" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${datatype} == 'ECC' || ${datatype} == '')" ).append("\n"); 
		query.append("--ECC INFO START" ).append("\n"); 
		query.append("SELECT A.WEEK" ).append("\n"); 
		query.append(",A.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.VOL_TOTAL" ).append("\n"); 
		query.append(",A.AMT_TOTAL" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",NVL(A.VOL_$key, 0)" ).append("\n"); 
		query.append(",NVL(A.AMT_$key, 0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--      ,A.CHECKBOX" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",'F' VOL_FLAG$key" ).append("\n"); 
		query.append(",'F' AMT_FLAG$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.SORTNUM  -- HIDDEN VALUE" ).append("\n"); 
		query.append(",A.ITEMCODE   -- HIDDEN VALUE" ).append("\n"); 
		query.append(",@[scnrPlanID] SCNR_ID" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--      ,A.FM_ECC_CD" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("#if(${fmTypeBy} != '')" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,A.TO_ECC_CD" ).append("\n"); 
		query.append("#if(${toTypeBy} != '')" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${atTypeBy} != '')" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("VOL_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("AMT_TOTAL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",SUM(A.VOL_$key)     VOL_$key" ).append("\n"); 
		query.append(",SUM(A.AMT_$key)     AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--          ,'' CHECKBOX" ).append("\n"); 
		query.append(",A.SORTNUM     -- HIDDEN VALUE" ).append("\n"); 
		query.append(",A.ITEMCODE      -- HIDDEN VALUE" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT SUBSTR(A.SCNR_ID, 5, 6) WEEK" ).append("\n"); 
		query.append(",'ECC' DATATYPE" ).append("\n"); 
		query.append(",B.ITEMNAME ALERTITEM" ).append("\n"); 
		query.append(",C.DIVNAME DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",'' VVD" ).append("\n"); 
		query.append(",null VOL_TOTAL" ).append("\n"); 
		query.append(",SUM(A.LINKAMT) AMT_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",null VOL_$key" ).append("\n"); 
		query.append(",SUM(DECODE(SUBSTR('$key' , 2 , 1), 2, DECODE(A.TPSIZE, 20, LINKAMT), 4, DECODE(A.TPSIZE, 40, LINKAMT), DECODE(A.TPSIZE, 45, LINKAMT))) AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",'2' SORTNUM" ).append("\n"); 
		query.append(",B.ITEMCODE" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("------- BELOW ---------------------------------------" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.SCNR_ID" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append(",A.ECC_CD FM_ECC_CD" ).append("\n"); 
		query.append(",''       TO_ECC_CD" ).append("\n"); 
		query.append(",A.ITEMCODE" ).append("\n"); 
		query.append(",B.ALT_BSE_CD DIV" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",A.AMT LINKAMT" ).append("\n"); 
		query.append(",B.AMT ALERTAMT" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- Storage Cost, Steve Dorage, Handling Cost, Shuttling Cost -----" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",B.ITEMCODE" ).append("\n"); 
		query.append(",B.ITEMNAME" ).append("\n"); 
		query.append(",A.TPSIZE" ).append("\n"); 
		query.append(",DECODE(A.TPSIZE, 20, DECODE(B.ITEMCODE, 'STD', A.STV_20FT_COST_AMT," ).append("\n"); 
		query.append("'STR', A.STO_20FT_COST_AMT," ).append("\n"); 
		query.append("'HND', A.HNDL_20FT_COST_AMT," ).append("\n"); 
		query.append("'SHT', A.STTL_20FT_COST_AMT" ).append("\n"); 
		query.append(")," ).append("\n"); 
		query.append("40, DECODE(B.ITEMCODE, 'STD', A.STV_40FT_COST_AMT," ).append("\n"); 
		query.append("'STR', A.STO_40FT_COST_AMT," ).append("\n"); 
		query.append("'HND', A.HNDL_40FT_COST_AMT," ).append("\n"); 
		query.append("'SHT', A.STTL_40FT_COST_AMT" ).append("\n"); 
		query.append(")," ).append("\n"); 
		query.append("45, DECODE(B.ITEMCODE, 'STD', A.STV_45FT_COST_AMT," ).append("\n"); 
		query.append("'STR', A.STO_45FT_COST_AMT," ).append("\n"); 
		query.append("'HND', A.HNDL_45FT_COST_AMT," ).append("\n"); 
		query.append("'SHT', A.STTL_45FT_COST_AMT" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(") AMT" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",A.STV_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.STV_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.STV_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.STO_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.STO_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.STO_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.HNDL_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.HNDL_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.HNDL_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.STTL_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.STTL_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.STTL_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append("FROM EQR_SCNR_ECC A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT 20 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 40 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 45 TPSIZE FROM DUAL" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("INTG_CD_VAL_CTNT ITEMCODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC ITEMNAME" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE" ).append("\n"); 
		query.append("INTG_CD_ID = 'CD00873'" ).append("\n"); 
		query.append("AND INTG_CD_VAL_CTNT IN ('STD', 'STR', 'HND', 'SHT')" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("-- TRANSHIPMENT COST -------------------" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",'TRS'  ITEMCODE" ).append("\n"); 
		query.append(",'Transhipment Cost' ITEMNAME" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",ROUND(AVG(DECODE(B.TPSIZE, 20, A.TS_20FT_UC_AMT, 40, A.TS_40FT_UC_AMT, 45, A.TS_45FT_UC_AMT)),2) AMT" ).append("\n"); 
		query.append(",C.RCC_CD" ).append("\n"); 
		query.append("FROM EQR_SCNR_TS_TML A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT 20 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 40 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 45 TPSIZE FROM DUAL" ).append("\n"); 
		query.append(") B," ).append("\n"); 
		query.append("MDM_EQ_ORZ_CHT C" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("AND   A.ECC_CD = C.ECC_CD" ).append("\n"); 
		query.append("GROUP BY A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",C.RCC_CD" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- RED LIGHT ALERT" ).append("\n"); 
		query.append("SELECT RCC_CD" ).append("\n"); 
		query.append(",ALT_ITM_DIV_CD ITEMCODE" ).append("\n"); 
		query.append(",ALT_BSE_CD" ).append("\n"); 
		query.append(",CNTR_SZ_CD TPSIZE" ).append("\n"); 
		query.append(",NVL(ALT_COST_AMT,0) AMT" ).append("\n"); 
		query.append("FROM EQR_INP_DAT_RED_LGT_ALT" ).append("\n"); 
		query.append("WHERE  TO_CHAR(CNTR_SZ_CD) <> 'NA'" ).append("\n"); 
		query.append("AND    ALT_ITM_DIV_CD IN ('TRS','STD','STR','HND','SHT')" ).append("\n"); 
		query.append("AND    ALT_BSE_CD = 'B' -- BELOW" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.RCC_CD  = B.RCC_CD" ).append("\n"); 
		query.append("AND   A.ITEMCODE= B.ITEMCODE" ).append("\n"); 
		query.append("AND   A.TPSIZE  = B.TPSIZE" ).append("\n"); 
		query.append("AND   A.AMT < B.AMT -- BELOW" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- OVER" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append(",A.ECC_CD FM_ECC_CD" ).append("\n"); 
		query.append(",''       TO_ECC_CD" ).append("\n"); 
		query.append(",A.ITEMCODE" ).append("\n"); 
		query.append(",B.ALT_BSE_CD DIV" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",A.AMT LINKAMT" ).append("\n"); 
		query.append(",B.AMT ALERTAMT" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- Storage Cost, Steve Dorage, Handling Cost, Shuttling Cost" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",B.ITEMCODE" ).append("\n"); 
		query.append(",B.ITEMNAME" ).append("\n"); 
		query.append(",A.TPSIZE" ).append("\n"); 
		query.append(",DECODE(A.TPSIZE, 20, DECODE(B.ITEMCODE, 'STD', A.STV_20FT_COST_AMT," ).append("\n"); 
		query.append("'STR', A.STO_20FT_COST_AMT," ).append("\n"); 
		query.append("'HND', A.HNDL_20FT_COST_AMT," ).append("\n"); 
		query.append("'SHT', A.STTL_20FT_COST_AMT" ).append("\n"); 
		query.append(")," ).append("\n"); 
		query.append("40, DECODE(B.ITEMCODE, 'STD', A.STV_40FT_COST_AMT," ).append("\n"); 
		query.append("'STR', A.STO_40FT_COST_AMT," ).append("\n"); 
		query.append("'HND', A.HNDL_40FT_COST_AMT," ).append("\n"); 
		query.append("'SHT', A.STTL_40FT_COST_AMT" ).append("\n"); 
		query.append(")," ).append("\n"); 
		query.append("45, DECODE(B.ITEMCODE, 'STD', A.STV_45FT_COST_AMT," ).append("\n"); 
		query.append("'STR', A.STO_45FT_COST_AMT," ).append("\n"); 
		query.append("'HND', A.HNDL_45FT_COST_AMT," ).append("\n"); 
		query.append("'SHT', A.STTL_45FT_COST_AMT" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(") AMT" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",A.STV_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.STV_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.STV_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.STO_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.STO_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.STO_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.HNDL_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.HNDL_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.HNDL_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.STTL_20FT_COST_AMT" ).append("\n"); 
		query.append(",A.STTL_40FT_COST_AMT" ).append("\n"); 
		query.append(",A.STTL_45FT_COST_AMT" ).append("\n"); 
		query.append(",A.RCC_CD" ).append("\n"); 
		query.append("FROM EQR_SCNR_ECC A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT 20 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 40 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 45 TPSIZE FROM DUAL" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT ITEMCODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC ITEMNAME" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00873'" ).append("\n"); 
		query.append("AND INTG_CD_VAL_CTNT IN ('STD', 'STR', 'HND', 'SHT')" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("-- TRANSHIPMENT COST" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",'TRS'  ITEMCODE" ).append("\n"); 
		query.append(",'Transhipment Cost' ITEMNAME" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",ROUND(AVG(DECODE(B.TPSIZE, 20, A.TS_20FT_UC_AMT, 40, A.TS_40FT_UC_AMT, 45, A.TS_45FT_UC_AMT)),2) AMT" ).append("\n"); 
		query.append(",C.RCC_CD" ).append("\n"); 
		query.append("FROM EQR_SCNR_TS_TML A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT 20 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 40 TPSIZE FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT 45 TPSIZE FROM DUAL" ).append("\n"); 
		query.append(") B," ).append("\n"); 
		query.append("MDM_EQ_ORZ_CHT C" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("AND   A.ECC_CD = C.ECC_CD" ).append("\n"); 
		query.append("GROUP BY A.SCNR_ID" ).append("\n"); 
		query.append(",A.ECC_CD" ).append("\n"); 
		query.append(",B.TPSIZE" ).append("\n"); 
		query.append(",C.RCC_CD" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- RED LIGHT ALERT" ).append("\n"); 
		query.append("SELECT RCC_CD" ).append("\n"); 
		query.append(",ALT_ITM_DIV_CD ITEMCODE" ).append("\n"); 
		query.append(",ALT_BSE_CD" ).append("\n"); 
		query.append(",CNTR_SZ_CD TPSIZE" ).append("\n"); 
		query.append(",NVL(ALT_COST_AMT,0) AMT" ).append("\n"); 
		query.append("FROM EQR_INP_DAT_RED_LGT_ALT" ).append("\n"); 
		query.append("WHERE  TO_CHAR(CNTR_SZ_CD) <> 'NA'" ).append("\n"); 
		query.append("AND    ALT_ITM_DIV_CD IN ('TRS','STD','STR','HND','SHT')" ).append("\n"); 
		query.append("AND    ALT_BSE_CD = 'O' -- BELOW" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.RCC_CD  = B.RCC_CD" ).append("\n"); 
		query.append("AND   A.ITEMCODE= B.ITEMCODE" ).append("\n"); 
		query.append("AND   A.TPSIZE  = B.TPSIZE" ).append("\n"); 
		query.append("AND   A.AMT > B.AMT -- OVER" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT ITEMCODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC ITEMNAME" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00873'" ).append("\n"); 
		query.append(") B," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT DIVCODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DP_DESC DIVNAME" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00876'" ).append("\n"); 
		query.append(") C" ).append("\n"); 
		query.append("WHERE A.ITEMCODE = B.ITEMCODE" ).append("\n"); 
		query.append("AND   A.DIV      = C.DIVCODE" ).append("\n"); 
		query.append("-- FROM TO" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("#if(${fromStatus} != '')" ).append("\n"); 
		query.append("AND   A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toStatus} != '')" ).append("\n"); 
		query.append("AND   A.TO_ECC_CD IN (" ).append("\n"); 
		query.append("#if(${fmtoat}== '1' && ${toStatus} != '')" ).append("\n"); 
		query.append("#foreach($key IN ${toeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $toeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("-- AT" ).append("\n"); 
		query.append("#if(${atStatus} != '')" ).append("\n"); 
		query.append("AND" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(") OR A.TO_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("GROUP BY SUBSTR(A.SCNR_ID, 5, 6)" ).append("\n"); 
		query.append(",B.ITEMNAME" ).append("\n"); 
		query.append(",C.DIVNAME" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",B.ITEMCODE" ).append("\n"); 
		query.append("--ORDER BY 3,4,5,6" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- INPUT DATA TYPE" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT DATACODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC DATATYPE" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00248'" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.DATATYPE = B.DATACODE" ).append("\n"); 
		query.append("GROUP BY A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.ITEMCODE" ).append("\n"); 
		query.append("ORDER BY 1,2,3,4" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("--------------- ECC INFO END ------------------------------" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- ----------- VESSEL SKD ---------------------------------------------------------" ).append("\n"); 
		query.append("#if(${datatype} == '')" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${datatype} == 'VSK' || ${datatype} == '')" ).append("\n"); 
		query.append("---------------- VESSEL SKD START ------------------------------" ).append("\n"); 
		query.append("SELECT A.WEEK" ).append("\n"); 
		query.append(",A.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.VOL_TOTAL" ).append("\n"); 
		query.append(",A.AMT_TOTAL" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",A.VOL_$key" ).append("\n"); 
		query.append(",A.AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--      ,A.CHECKBOX" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",'F' VOL_FLAG$key" ).append("\n"); 
		query.append(",'F' AMT_FLAG$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append(",@[scnrPlanID] SCNR_ID" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--      ,A.FM_ECC_CD" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("#if(${fmTypeBy} != '')" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,A.TO_ECC_CD" ).append("\n"); 
		query.append("#if(${toTypeBy} != '')" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${atTypeBy} != '')" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("VOL_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("AMT_TOTAL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",SUM(A.VOL_$key)     VOL_$key" ).append("\n"); 
		query.append(",SUM(A.AMT_$key)     AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,'' CHECKBOX" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.WEEK" ).append("\n"); 
		query.append(",A.DATACODE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",null VOL_TOTAL" ).append("\n"); 
		query.append(",null AMT_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",null VOL_$key" ).append("\n"); 
		query.append(",null AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",'3' SORTNUM" ).append("\n"); 
		query.append(",'' DIVNUM" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("------------  LANE NEW (B-A) -------------------------" ).append("\n"); 
		query.append("SELECT DISTINCT SUBSTR(@[scnrPlanID],5 , 6) WEEK" ).append("\n"); 
		query.append(",'VSK'    DATACODE" ).append("\n"); 
		query.append(",'Lane'   ALERTITEM" ).append("\n"); 
		query.append(",'new'    DIV" ).append("\n"); 
		query.append(",''       FM_ECC_CD" ).append("\n"); 
		query.append(",''       TO_ECC_CD" ).append("\n"); 
		query.append(",VSL      VVD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT DISTINCT VSL_CD||SKD_VOY_NO||SKD_DIR_CD VSL" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--					  	  WHERE  VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("WHERE  VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append("MINUS" ).append("\n"); 
		query.append("SELECT DISTINCT VSL_CD||SKD_VOY_NO||SKD_DIR_CD VSL" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD" ).append("\n"); 
		query.append("WHERE SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND   VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--					  	  AND   VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND   VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("------------  LANE SKIP (A-B) -----------------------" ).append("\n"); 
		query.append("SELECT DISTINCT SUBSTR(@[scnrPlanID],5 , 6) WEEK" ).append("\n"); 
		query.append(",'VSK'    DATACODE" ).append("\n"); 
		query.append(",'Lane'   ALERTITEM" ).append("\n"); 
		query.append(",'new'    DIV" ).append("\n"); 
		query.append(",''       FM_ECC_CD" ).append("\n"); 
		query.append(",''       TO_ECC_CD" ).append("\n"); 
		query.append(",VSL      VVD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT DISTINCT VSL_CD||SKD_VOY_NO||SKD_DIR_CD VSL" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD" ).append("\n"); 
		query.append("WHERE SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND   VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--					  	  AND   VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND   VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("MINUS" ).append("\n"); 
		query.append("SELECT DISTINCT VSL_CD||SKD_VOY_NO||SKD_DIR_CD VSL" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--					  	  WHERE  VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("WHERE  VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("------------  PORT ADD(B-A) -------------------------" ).append("\n"); 
		query.append("SELECT DISTINCT SUBSTR(@[scnrPlanID],5 , 6) WEEK" ).append("\n"); 
		query.append(",'VSK'    DATACODE" ).append("\n"); 
		query.append(",'Port'   ALERTITEM" ).append("\n"); 
		query.append(",'add'    DIV" ).append("\n"); 
		query.append(",PORT     FM_ECC_CD" ).append("\n"); 
		query.append(",''       TO_ECC_CD" ).append("\n"); 
		query.append(",VVD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT VS.VSL_CD||VS.SKD_VOY_NO||VS.SKD_DIR_CD  VVD" ).append("\n"); 
		query.append(",VS.VPS_PORT_CD  PORT" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD VS" ).append("\n"); 
		query.append("WHERE (VSL_CD, SKD_VOY_NO, SKD_DIR_CD) IN" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT /*+ XAK1VSK_VSL_PORT_SKD */" ).append("\n"); 
		query.append("DISTINCT A.VSL_CD,A.SKD_VOY_NO,A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                            WHERE  A.VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("WHERE  A.VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND       (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND A.CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append("AND NVL(SKD_CNG_STS_CD,'N') <> 'S'" ).append("\n"); 
		query.append("INTERSECT" ).append("\n"); 
		query.append("SELECT DISTINCT A.VSL_CD" ).append("\n"); 
		query.append(",A.SKD_VOY_NO" ).append("\n"); 
		query.append(",A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD A" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND   A.VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                            AND  A.VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  A.VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                        AND  VS.VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  VS.VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND VS.CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append("AND NVL(VS.SKD_CNG_STS_CD,'N') <> 'S'  -- port skip" ).append("\n"); 
		query.append("MINUS" ).append("\n"); 
		query.append("SELECT ES.VSL_CD||ES.SKD_VOY_NO||ES.SKD_DIR_CD VVD" ).append("\n"); 
		query.append(", ES.VSL_LOC_CD PORT" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD ES" ).append("\n"); 
		query.append("WHERE (VSL_CD, SKD_VOY_NO, SKD_DIR_CD) IN" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT /*+ XAK1VSK_VSL_PORT_SKD */" ).append("\n"); 
		query.append("DISTINCT A.VSL_CD" ).append("\n"); 
		query.append(",A.SKD_VOY_NO" ).append("\n"); 
		query.append(",A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                             WHERE  A.VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("WHERE  A.VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND A.CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append("AND NVL(SKD_CNG_STS_CD,'N') <> 'S'" ).append("\n"); 
		query.append("INTERSECT" ).append("\n"); 
		query.append("SELECT DISTINCT A.VSL_CD,A.SKD_VOY_NO" ).append("\n"); 
		query.append(",A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD A" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND   A.VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                             AND  A.VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  A.VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND ES.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND ES.VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                        AND  ES.VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  ES.VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("------------  PORT SKIP(A-B) ----------------------" ).append("\n"); 
		query.append("SELECT DISTINCT SUBSTR(@[scnrPlanID],5 , 6) WEEK" ).append("\n"); 
		query.append(",'VSK'    DATACODE" ).append("\n"); 
		query.append(",'Port'   ALERTITEM" ).append("\n"); 
		query.append(",'skip'   DIV" ).append("\n"); 
		query.append(",PORT     FM_ECC_CD" ).append("\n"); 
		query.append(",''       TO_ECC_CD" ).append("\n"); 
		query.append(",VVD" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT ES.VSL_CD||ES.SKD_VOY_NO||ES.SKD_DIR_CD VVD" ).append("\n"); 
		query.append(", ES.VSL_LOC_CD PORT" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD ES" ).append("\n"); 
		query.append("WHERE (VSL_CD, SKD_VOY_NO, SKD_DIR_CD) IN" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT /*+ XAK1VSK_VSL_PORT_SKD */" ).append("\n"); 
		query.append("DISTINCT A.VSL_CD" ).append("\n"); 
		query.append(",A.SKD_VOY_NO" ).append("\n"); 
		query.append(",A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                             WHERE  A.VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("WHERE  A.VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND A.CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append("AND NVL(SKD_CNG_STS_CD,'N') <> 'S'" ).append("\n"); 
		query.append("INTERSECT" ).append("\n"); 
		query.append("SELECT DISTINCT A.VSL_CD,A.SKD_VOY_NO" ).append("\n"); 
		query.append(",A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD A" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND   A.VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                             AND  A.VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  A.VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND ES.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND ES.VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                        AND  ES.VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  ES.VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("MINUS" ).append("\n"); 
		query.append("SELECT VS.VSL_CD||VS.SKD_VOY_NO||VS.SKD_DIR_CD  VVD" ).append("\n"); 
		query.append(",VS.VPS_PORT_CD  PORT" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD VS" ).append("\n"); 
		query.append("WHERE (VSL_CD, SKD_VOY_NO, SKD_DIR_CD) IN" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT /*+ XAK1VSK_VSL_PORT_SKD */" ).append("\n"); 
		query.append("DISTINCT A.VSL_CD,A.SKD_VOY_NO,A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM VSK_VSL_PORT_SKD A" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                            WHERE  A.VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("WHERE  A.VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND       (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND A.CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append("AND NVL(SKD_CNG_STS_CD,'N') <> 'S'" ).append("\n"); 
		query.append("INTERSECT" ).append("\n"); 
		query.append("SELECT DISTINCT A.VSL_CD" ).append("\n"); 
		query.append(",A.SKD_VOY_NO" ).append("\n"); 
		query.append(",A.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("FROM EQR_SCNR_VSL_SKD A" ).append("\n"); 
		query.append("WHERE A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("--AND   A.VSL_CALL_IND_CD = '1'" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                                            AND  A.VSL_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  A.VSL_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("-- CSR NO. N200903060123 Split 01-EQR sked 기준 변경" ).append("\n"); 
		query.append("--                        AND  VS.VPS_ETA_DT BETWEEN (" ).append("\n"); 
		query.append("AND  VS.VPS_ETB_DT BETWEEN (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_ST_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[fromWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND     (" ).append("\n"); 
		query.append("SELECT TO_DATE(WK_END_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("FROM EQR_WK_PRD" ).append("\n"); 
		query.append("WHERE PLN_YR||PLN_WK = @[toWeek]" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("--AND VS.CLPT_IND_SEQ ='1'" ).append("\n"); 
		query.append("AND NVL(VS.SKD_CNG_STS_CD,'N') <> 'S'  -- port skip" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("-- FROM TO" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("WHERE   1=1" ).append("\n"); 
		query.append("#if(${fromStatus} != '')" ).append("\n"); 
		query.append("AND   A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toStatus} != '')" ).append("\n"); 
		query.append("AND   A.TO_ECC_CD IN (" ).append("\n"); 
		query.append("#if(${fmtoat}== '1' && ${toStatus} != '')" ).append("\n"); 
		query.append("#foreach($key IN ${toeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $toeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("-- AT" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${atStatus} != '')" ).append("\n"); 
		query.append("WHERE (" ).append("\n"); 
		query.append("A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(") OR  A.TO_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- INPUT DATA TYPE" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT DATACODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC DATATYPE" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00248'" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.DATACODE = B.DATACODE" ).append("\n"); 
		query.append("GROUP BY A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append("ORDER BY 1,2,3,4" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("---------------- VESSEL SKD END   ------------------------------" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- ----------- OB FORECAST ---------------------------------------------------------" ).append("\n"); 
		query.append("#if(${datatype} == '' )" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if(${datatype} =='OBF' || ${datatype} == '')" ).append("\n"); 
		query.append("---------------- OB FORECAST START   --------------------------" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("A.WEEK" ).append("\n"); 
		query.append(",A.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.VOL_TOTAL" ).append("\n"); 
		query.append(",A.AMT_TOTAL" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",A.VOL_$key" ).append("\n"); 
		query.append(",A.AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--      ,A.CHECKBOX" ).append("\n"); 
		query.append("#foreach( ${key} in ${tpszArr})" ).append("\n"); 
		query.append(",'F' VOL_FLAG$key" ).append("\n"); 
		query.append(",'F' AMT_FLAG$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append(",@[scnrPlanID] SCNR_ID" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--      ,A.FM_ECC_CD" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("#if(${fmTypeBy} != '')" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${fmTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,A.TO_ECC_CD" ).append("\n"); 
		query.append("#if(${toTypeBy} != '')" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${atTypeBy} != '')" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'C')" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT CNT_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'E')" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT ECC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'L')" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT LCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${atTypeBy} == 'R')" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.FM_ECC_CD)  FM_ECC_CD" ).append("\n"); 
		query.append(",(SELECT RCC_CD FROM EQR_ECC_MST WHERE ECC_CD = A.TO_ECC_CD)  TO_ECC_CD" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.VOL_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("VOL_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append("#if($velocityCount == 1)" ).append("\n"); 
		query.append(",NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("+NVL(SUM(A.AMT_$key),0)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("AMT_TOTAL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",SUM(A.VOL_$key)     VOL_$key" ).append("\n"); 
		query.append(",SUM(A.AMT_$key)     AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("--      ,'' CHECKBOX" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("SUBSTR(A.SCNR_ID, 5, 6) WEEK" ).append("\n"); 
		query.append(",'OBF' DATACODE" ).append("\n"); 
		query.append(",C.CO_NAME ALERTITEM" ).append("\n"); 
		query.append(",B.NAME DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",'' VVD" ).append("\n"); 
		query.append(",SUM(DECODE(B.CODE, 1, A.QTY1, 2, A.QTY2) ) VOL_TOTAL" ).append("\n"); 
		query.append(",null AMT_TOTAL" ).append("\n"); 
		query.append("#foreach($key IN ${tpszArr})" ).append("\n"); 
		query.append(",SUM(DECODE(A.CNTR_TPSZ_CD, '$key', DECODE(B.CODE, 1, A.QTY1, 2, A.QTY2)) ) VOL_$key" ).append("\n"); 
		query.append(",null AMT_$key" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(",'4' SORTNUM" ).append("\n"); 
		query.append(",B.CODE DIVNUM" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- DEMAND VOL ----------------------------------------" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append(",SUM(A.CNTR_VOL_QTY) QTY1" ).append("\n"); 
		query.append(",0 QTY2" ).append("\n"); 
		query.append(",1 SORTNUM" ).append("\n"); 
		query.append("FROM EQR_OB_FCAST A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("---- AVG VOL (A >= B) -----------------------" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.TPSIZE" ).append("\n"); 
		query.append(",A.AVG_QTY" ).append("\n"); 
		query.append(",B.RLA_QTY" ).append("\n"); 
		query.append(",2 SORTNUM" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- AVG VOL ----------------.----------" ).append("\n"); 
		query.append("SELECT" ).append("\n"); 
		query.append("@[scnrPlanID] SCNR_ID" ).append("\n"); 
		query.append(", SUBSTR(@[scnrPlanID],5,6) FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.CNTR_TPSZ_CD TPSIZE" ).append("\n"); 
		query.append(",B.RCC_CD" ).append("\n"); 
		query.append(",NVL(SUM(A.CNTR_VOL_QTY)/4, 0) AVG_QTY" ).append("\n"); 
		query.append("FROM EQR_OB_FCAST A," ).append("\n"); 
		query.append("MDM_EQ_ORZ_CHT B" ).append("\n"); 
		query.append("WHERE A.FM_ECC_CD = B.ECC_CD" ).append("\n"); 
		query.append("AND   A.SCNR_ID IN (" ).append("\n"); 
		query.append("SELECT SCNR_ID" ).append("\n"); 
		query.append("FROM EQR_SCNR_MST" ).append("\n"); 
		query.append("WHERE SUBSTR(SCNR_ID, 12, 3) = '000'" ).append("\n"); 
		query.append("AND SUBSTR(SCNR_ID, 5, 6) < SUBSTR(@[scnrPlanID],5,6)" ).append("\n"); 
		query.append("AND ROWNUM < 5" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND   A.FCAST_YRWK IN (" ).append("\n"); 
		query.append("SELECT SUBSTR(SCNR_ID, 5, 6)" ).append("\n"); 
		query.append("FROM EQR_SCNR_MST" ).append("\n"); 
		query.append("WHERE SUBSTR(SCNR_ID, 12, 3) = '000'" ).append("\n"); 
		query.append("AND SUBSTR(SCNR_ID, 5, 6) < SUBSTR(@[scnrPlanID],5,6)" ).append("\n"); 
		query.append("AND ROWNUM < 5" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("GROUP BY A.FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append(",B.RCC_CD" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- RLA" ).append("\n"); 
		query.append("SELECT RCC_CD" ).append("\n"); 
		query.append(",CNTR_TPSZ_CD TPSIZE" ).append("\n"); 
		query.append(",RLA_QTY" ).append("\n"); 
		query.append("FROM EQR_OB_FCAST_RED_LGT_ALT" ).append("\n"); 
		query.append("WHERE RLA_TP_CD = 'V'" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.RCC_CD = B.RCC_CD" ).append("\n"); 
		query.append("AND   A.TPSIZE = B.TPSIZE" ).append("\n"); 
		query.append("AND   A.AVG_QTY >= B.RLA_QTY" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE B.CO_CD = A.CO_CD" ).append("\n"); 
		query.append("AND   B.FM_ECC_CD = A.FM_ECC_CD" ).append("\n"); 
		query.append("AND   B.TO_ECC_CD = A.TO_ECC_CD" ).append("\n"); 
		query.append("AND   B.TPSIZE    = A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("AND   A.SCNR_ID = @[scnrPlanID]" ).append("\n"); 
		query.append("AND   A.FCAST_YRWK = SUBSTR(@[scnrPlanID],5,6)" ).append("\n"); 
		query.append("GROUP BY A.SCNR_ID" ).append("\n"); 
		query.append(",A.FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("-- AVG VOL (A >= B)" ).append("\n"); 
		query.append("SELECT A.SCNR_ID" ).append("\n"); 
		query.append(",A.FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.TPSIZE" ).append("\n"); 
		query.append(",0 QTY1" ).append("\n"); 
		query.append(",A.AVG_QTY QTY2" ).append("\n"); 
		query.append(",2 SORTNUM" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- AVG VOL" ).append("\n"); 
		query.append("SELECT @[scnrPlanID] SCNR_ID" ).append("\n"); 
		query.append(",SUBSTR(@[scnrPlanID],5,6) FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.CNTR_TPSZ_CD TPSIZE" ).append("\n"); 
		query.append(",B.RCC_CD" ).append("\n"); 
		query.append(",NVL(SUM(A.CNTR_VOL_QTY)/4, 0) AVG_QTY" ).append("\n"); 
		query.append("FROM EQR_OB_FCAST A," ).append("\n"); 
		query.append("MDM_EQ_ORZ_CHT B" ).append("\n"); 
		query.append("WHERE A.FM_ECC_CD = B.ECC_CD" ).append("\n"); 
		query.append("AND   A.SCNR_ID IN (SELECT SCNR_ID" ).append("\n"); 
		query.append("FROM EQR_SCNR_MST" ).append("\n"); 
		query.append("WHERE SUBSTR(SCNR_ID, 12, 3) = '000'" ).append("\n"); 
		query.append("AND SUBSTR(SCNR_ID, 5, 6) < SUBSTR(@[scnrPlanID],5,6)" ).append("\n"); 
		query.append("AND ROWNUM < 5" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND   A.FCAST_YRWK IN (SELECT SUBSTR(SCNR_ID, 5, 6)" ).append("\n"); 
		query.append("FROM EQR_SCNR_MST" ).append("\n"); 
		query.append("WHERE SUBSTR(SCNR_ID, 12, 3) = '000'" ).append("\n"); 
		query.append("AND SUBSTR(SCNR_ID, 5, 6) < SUBSTR(@[scnrPlanID],5,6)" ).append("\n"); 
		query.append("AND ROWNUM < 5" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("GROUP BY A.FCAST_YRWK" ).append("\n"); 
		query.append(",A.CO_CD" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.CNTR_TPSZ_CD" ).append("\n"); 
		query.append(",B.RCC_CD" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- RLA -------------------------------" ).append("\n"); 
		query.append("SELECT RCC_CD" ).append("\n"); 
		query.append(",CNTR_TPSZ_CD TPSIZE" ).append("\n"); 
		query.append(",RLA_QTY" ).append("\n"); 
		query.append("FROM EQR_OB_FCAST_RED_LGT_ALT" ).append("\n"); 
		query.append("WHERE RLA_TP_CD = 'V'" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.RCC_CD = B.RCC_CD" ).append("\n"); 
		query.append("AND   A.TPSIZE = B.TPSIZE" ).append("\n"); 
		query.append("AND   A.AVG_QTY >= B.RLA_QTY" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT '1' CODE, 'Demand Vol' NAME FROM DUAL" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT '2' CODE, 'Avg Vol Diff' NAME FROM DUAL" ).append("\n"); 
		query.append(") B," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT    CO_CD" ).append("\n"); 
		query.append(",INTG_CD_VAL_DP_DESC CO_NAME" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00264'" ).append("\n"); 
		query.append(") C" ).append("\n"); 
		query.append("WHERE A.CO_CD = C.CO_CD" ).append("\n"); 
		query.append("-- FROM TO" ).append("\n"); 
		query.append("#if(${fmtoat} == '1')" ).append("\n"); 
		query.append("#if(${fromStatus} != '')" ).append("\n"); 
		query.append("AND     A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${toStatus} != '')" ).append("\n"); 
		query.append("AND     A.TO_ECC_CD IN  (" ).append("\n"); 
		query.append("#if(${fmtoat}== '1' && ${toStatus} != '')" ).append("\n"); 
		query.append("#foreach($key IN ${toeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $toeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("-- AT" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("#if(${atStatus} != '')" ).append("\n"); 
		query.append("AND" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("A.FM_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(") OR  A.TO_ECC_CD IN (" ).append("\n"); 
		query.append("#if((${fmtoat}== '1' || ${fmtoat}== '2') && (${fromStatus} != '' || ${atStatus} != ''))" ).append("\n"); 
		query.append("#foreach($key IN ${fromeccArr})" ).append("\n"); 
		query.append("#if($velocityCount < $fromeccArr.size())" ).append("\n"); 
		query.append("'$key'," ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("'$key'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("GROUP BY SUBSTR(A.SCNR_ID, 5, 6)" ).append("\n"); 
		query.append(",C.CO_NAME" ).append("\n"); 
		query.append(",B.NAME" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",B.CODE" ).append("\n"); 
		query.append("--ORDER BY 1,2,3,5,6,B.CODE" ).append("\n"); 
		query.append(") A," ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("-- INPUT DATA TYPE" ).append("\n"); 
		query.append("SELECT INTG_CD_VAL_CTNT DATACODE" ).append("\n"); 
		query.append(",INTG_CD_VAL_DESC DATATYPE" ).append("\n"); 
		query.append("FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("WHERE INTG_CD_ID = 'CD00248'" ).append("\n"); 
		query.append(") B" ).append("\n"); 
		query.append("WHERE A.DATACODE = B.DATACODE" ).append("\n"); 
		query.append("GROUP BY A.WEEK" ).append("\n"); 
		query.append(",B.DATATYPE" ).append("\n"); 
		query.append(",A.ALERTITEM" ).append("\n"); 
		query.append(",A.DIV" ).append("\n"); 
		query.append(",A.FM_ECC_CD" ).append("\n"); 
		query.append(",A.TO_ECC_CD" ).append("\n"); 
		query.append(",A.VVD" ).append("\n"); 
		query.append(",A.SORTNUM" ).append("\n"); 
		query.append(",A.DIVNUM" ).append("\n"); 
		query.append("ORDER BY 1, A.SORTNUM, 3, 5, 6, A.DIVNUM" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- 20070603 정선희 과장님 요청사항으로 O/B Forecast 는 당분간 조회되면 안됨.	START" ).append("\n"); 
		query.append("WHERE 1=0" ).append("\n"); 
		query.append("-- 20070603 정선희 과장님 요청사항으로 O/B Forecast 는 당분간 조회되면 안됨.	END" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("---------------- OB FORECAST END   ----------------------------" ).append("\n"); 
		query.append("#end" ).append("\n"); 

	}
}