/*=========================================================
*Copyright(c) 2018 CyberLogitec
*@FileName : GeneralBookingListSearchDBDAOsearchBkgListFor301310EdiRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2018.01.31
*@LastModifier : 
*@LastVersion : 1.0
* 2018.01.31 
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.esm.bkg.bookingconduct.generalbookingconduct.generalbookinglistsearch.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class GeneralBookingListSearchDBDAOsearchBkgListFor301310EdiRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * searchBkgListFor301310Edi
	  * </pre>
	  */
	public GeneralBookingListSearchDBDAOsearchBkgListFor301310EdiRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bkg_to_dt",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("sls_ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("cust_seq",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("pol_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bkg_from_dt",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("cust_tp_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("vvd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("del_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("sales_rep",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("por_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bkg_stf_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("sc_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("cust_nm",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("pod_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bl_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bkg_ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("edi_receive_nm",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("msg_type_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bl_ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("cust_cnt_cd",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.esm.bkg.bookingconduct.generalbookingconduct.generalbookinglistsearch.integration").append("\n"); 
		query.append("FileName : GeneralBookingListSearchDBDAOsearchBkgListFor301310EdiRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("SELECT /*+ opt_param('_optimizer_skip_scan_enabled', 'false') */ " ).append("\n"); 
		query.append("          BKG_NO" ).append("\n"); 
		query.append("        , STATUS" ).append("\n"); 
		query.append("        , BL_NO" ).append("\n"); 
		query.append("        , CUST_TP_CD" ).append("\n"); 
		query.append("        , CUST_CD" ).append("\n"); 
		query.append("        , REPLACE(CUST_NM, CHR(13)||CHR(10), ' ') CUST_NM" ).append("\n"); 
		query.append("        , SC_NO" ).append("\n"); 
		query.append("        , GROUP_EDI_ID" ).append("\n"); 
		query.append("		, (SELECT /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("                  DECODE(CUST_SEQ, '0', '', CUST_CNT_CD||TRIM(TO_CHAR(CUST_SEQ, '000000')))" ).append("\n"); 
		query.append("			 FROM BKG_CUSTOMER CUST " ).append("\n"); 
		query.append("            WHERE CUST.BKG_NO = MST.BKG_NO " ).append("\n"); 
		query.append("              AND BKG_CUST_TP_CD = 'E') EDI_REF" ).append("\n"); 
		query.append("        , RECEIVER_NAME" ).append("\n"); 
		query.append("		, VVD" ).append("\n"); 
		query.append("        , POR_CD" ).append("\n"); 
		query.append("        , POL_CD" ).append("\n"); 
		query.append("        , POD_CD" ).append("\n"); 
		query.append("        , DEL_CD" ).append("\n"); 
		query.append("        , SENT_DT" ).append("\n"); 
		query.append("        , SND_USR_ID" ).append("\n"); 
		query.append("        , (SELECT usr_nm FROM com_user WHERE usr_id = SND_USR_ID AND ROWNUM = 1) SND_USR_NM" ).append("\n"); 
		query.append("        , SENT_STATUS" ).append("\n"); 
		query.append("        , ACK" ).append("\n"); 
		query.append("        , EDI_RECEIVE_ID RCV_ID" ).append("\n"); 
		query.append("        , GROUP_EDI_ID GROUP_ID" ).append("\n"); 
		query.append("        , CUST_CD REF_CODE" ).append("\n"); 
		query.append("        , '' BL_TP_CD" ).append("\n"); 
		query.append("        , EDI_CTRL_NO ISA_NO" ).append("\n"); 
		query.append("        , 'BKG Conf.'  DOC_TYPE" ).append("\n"); 
		query.append("        , DECODE(XTER_BKG_RQST_CD, 'NIS', 'OFF', 'APS', 'OFF', XTER_BKG_RQST_CD) XTER_RQST_VIA_CD" ).append("\n"); 
		query.append("        , TP_301" ).append("\n"); 
		query.append("  FROM (SELECT  /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("				MST.BKG_NO" ).append("\n"); 
		query.append("                , BK.BKG_STS_CD STATUS" ).append("\n"); 
		query.append("                , BK.BL_NO||BK.BL_TP_CD BL_NO" ).append("\n"); 
		query.append("                , BK.BL_TP_CD" ).append("\n"); 
		query.append("                , SUBSTR(RANK, 2, 2) CUST_TP_CD" ).append("\n"); 
		query.append("                , CUST.CUST_CNT_CD||TRIM(TO_CHAR(CUST.CUST_SEQ, '000009')) CUST_CD" ).append("\n"); 
		query.append("                , CUST.CUST_NM" ).append("\n"); 
		query.append("                , BK.SC_NO" ).append("\n"); 
		query.append("                , MST.GROUP_EDI_ID" ).append("\n"); 
		query.append("                , MST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                , MST.RECEIVER_NAME" ).append("\n"); 
		query.append("				, MST.VVD" ).append("\n"); 
		query.append("                , BK.POR_CD" ).append("\n"); 
		query.append("                , BK.POL_CD" ).append("\n"); 
		query.append("                , BK.POD_CD" ).append("\n"); 
		query.append("                , BK.DEL_CD" ).append("\n"); 
		query.append("                , TO_CHAR(NTC.SND_RQST_DT, 'YYYY-MM-DD') SENT_DT" ).append("\n"); 
		query.append("                , NTC.SND_USR_ID" ).append("\n"); 
		query.append("                , CASE WHEN NTC.SND_RQST_DT IS NULL THEN 'U'" ).append("\n"); 
		query.append("                       WHEN NTC.BKG_NTC_SND_RSLT_CD = 'A' THEN 'S'" ).append("\n"); 
		query.append("                       ELSE 'E'" ).append("\n"); 
		query.append("                       END AS SENT_STATUS" ).append("\n"); 
		query.append("                , null ACK" ).append("\n"); 
		query.append("		        , NTC.HIS_SEQ" ).append("\n"); 
		query.append("				, NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("				, NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                , NTC.EDI_CTRL_NO" ).append("\n"); 
		query.append("				, BK.XTER_BKG_RQST_CD" ).append("\n"); 
		query.append("                , 'C' TP_301" ).append("\n"); 
		query.append("          FROM BKG_CUSTOMER CUST, BKG_BOOKING BK, BKG_NTC_HIS NTC, " ).append("\n"); 
		query.append("                (SELECT BKG_NO" ).append("\n"); 
		query.append("                        , MIN(RANK) RANK" ).append("\n"); 
		query.append("                        , GROUP_EDI_ID" ).append("\n"); 
		query.append("                        , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                        , RECEIVER_NAME" ).append("\n"); 
		query.append("						, VVD" ).append("\n"); 
		query.append("                   FROM " ).append("\n"); 
		query.append("                        (SELECT /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("                                 BK.BKG_NO" ).append("\n"); 
		query.append("                                , MIN(TP_RANK.RANK) RANK" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.GROUP_EDI_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.RECEIVER_NAME" ).append("\n"); 
		query.append("								, VVD.VSL_CD||VVD.SKD_VOY_NO||VVD.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("                          FROM BKG_CUSTOMER CUST" ).append("\n"); 
		query.append("                                , BKG_BOOKING BK" ).append("\n"); 
		query.append("                                , BKG_VVD VVD" ).append("\n"); 
		query.append("								, BKG_BL_ISS ISS" ).append("\n"); 
		query.append("                                , BKG_BL_DOC DOC" ).append("\n"); 
		query.append("                                , (SELECT  GRP.ESVC_GRP_CD           GROUP_EDI_ID" ).append("\n"); 
		query.append("                                         , GRP.CUST_TRD_PRNR_ID     EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                         , GRP.ESVC_GRP_NM          RECEIVER_NAME" ).append("\n"); 
		query.append("                                         , grp_CUST.CNT_CD   " ).append("\n"); 
		query.append("                                         , grp_CUST.CUST_SEQ " ).append("\n"); 
		query.append("                                         , GRP_CUST.BKG_CUST_TP_DESC" ).append("\n"); 
		query.append("                                   FROM BKG_EDI_GRP_CUST GRP_CUST, BKG_EDI_GRP GRP" ).append("\n"); 
		query.append("                                  WHERE GRP.ESVC_GRP_CD         = GRP_CUST.ESVC_GRP_CD" ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = GRP_CUST.CO_CD" ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = 'H'" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_DELT_FLG   = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.CNT_CD         > ' '" ).append("\n"); 
		query.append("                                    AND GRP_CUST.CUST_SEQ       > 0" ).append("\n"); 
		query.append("                                    AND GRP_CUST.DELT_FLG       = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.BKG_CFM_FLG    = 'Y'" ).append("\n"); 
		query.append("                                    AND (@[msg_type_cd] = 'ALL' OR @[msg_type_cd] = 'B')" ).append("\n"); 
		query.append("#if(${edi_group_id} != '' && ${edi_receive_nm} != '')" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'G')--Group ID" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_CD  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'R')--Receive ID" ).append("\n"); 
		query.append("                                    AND GRP.CUST_TRD_PRNR_ID like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'N')--receive name" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_NM  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                                    ) EDI_BY_CUST               " ).append("\n"); 
		query.append("                                , (SELECT 'S' RCV_TP, '1SH' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'C' RCV_TP, '2CN' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'N' RCV_TP, '3NF' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'F' RCV_TP, '4FF' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'A' RCV_TP, '5AN' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'E' RCV_TP, '6EX' RANK FROM DUAL) TP_RANK" ).append("\n"); 
		query.append("                         WHERE EDI_BY_CUST.CNT_CD   = CUST.CUST_CNT_CD " ).append("\n"); 
		query.append("                           AND EDI_BY_CUST.CUST_SEQ = CUST.CUST_SEQ" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = CUST.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = ISS.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = DOC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = VVD.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.POL_CD        = VVD.POL_CD" ).append("\n"); 
		query.append("                           AND VVD.VSL_PRE_PST_CD IN ('T', 'S')" ).append("\n"); 
		query.append("                           AND CUST.BKG_CUST_TP_CD = TP_RANK.RCV_TP" ).append("\n"); 
		query.append("                           AND BK.BKG_STS_CD    IN ('F', 'W', 'S')" ).append("\n"); 
		query.append("                           AND BK.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("                           AND DECODE(BKG_CUST_TP_DESC,'ALL','ALL',CUST.BKG_CUST_TP_CD)" ).append("\n"); 
		query.append("                               IN (SELECT COLUMN_VALUE" ).append("\n"); 
		query.append("                                     FROM TABLE(BKG_SPLIT_FNC(BKG_CUST_TP_DESC,',')))" ).append("\n"); 
		query.append("                        ---------------------------조건절 시작   " ).append("\n"); 
		query.append("#if (${bkg_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_NO IN ( ${bkg_no} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BL_NO  = @[bl_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                        ---------------------------bkg or b/l no입력시 다른 조건 제외함" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT > TO_DATE(REPLACE(@[bkg_from_dt],'-',''),'RRRRMMDD')" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')         " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT > TO_DATE(REPLACE(@[bkg_from_dt],'-',''),'RRRRMMDD')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT < TO_DATE(REPLACE(@[bkg_to_dt],'-',''),'RRRRMMDD') + 1" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')  " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT < TO_DATE(REPLACE(@[bkg_to_dt],'-',''),'RRRRMMDD') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${xter_rqst_via_cd} != 'All' && ${xter_rqst_via_cd} != '') " ).append("\n"); 
		query.append("                           AND BK.XTER_BKG_RQST_CD IN ( ${xter_rqst_via_cd} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${vvd} != '')" ).append("\n"); 
		query.append("                           AND VVD.VSL_CD     = SUBSTR(@[vvd], 1, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_VOY_NO = SUBSTR(@[vvd], 5, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_DIR_CD = SUBSTR(@[vvd], 9, 1)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${por_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POR_CD = @[por_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pol_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POL_CD = @[pol_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pod_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POD_CD = @[pod_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${del_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.DEL_CD = @[del_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_OFC_CD = @[bkg_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_stf_cd} != '')" ).append("\n"); 
		query.append("                           AND UPPER(BK.DOC_USR_ID) = UPPER(@[bkg_stf_cd])" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sls_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SLS_OFC_CD = @[sls_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sales_rep} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SREP_CD = @[sales_rep]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND ISS.OBL_ISS_OFC_CD = @[bl_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_tp_cd} != 'All' && ${cust_tp_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.BKG_CUST_TP_CD = @[cust_tp_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_cnt_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_CNT_CD = @[cust_cnt_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_seq} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_SEQ = TO_NUMBER(@[cust_seq])" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_nm} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_NM LIKE UPPER(@[cust_nm])||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                         GROUP BY BK.BKG_NO" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.GROUP_EDI_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.RECEIVER_NAME" ).append("\n"); 
		query.append("								, VVD.VSL_CD||VVD.SKD_VOY_NO||VVD.SKD_DIR_CD" ).append("\n"); 
		query.append("                         UNION" ).append("\n"); 
		query.append("                          SELECT /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("                                  BK.BKG_NO" ).append("\n"); 
		query.append("                                , '7SC' RANK" ).append("\n"); 
		query.append("                                , EDI_BY_SC.GROUP_EDI_Id" ).append("\n"); 
		query.append("                                , EDI_BY_SC.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                , EDI_BY_SC.RECEIVER_NAME" ).append("\n"); 
		query.append("								, VVD.VSL_CD||VVD.SKD_VOY_NO||VVD.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("                          FROM BKG_CUSTOMER CUST" ).append("\n"); 
		query.append("                                , BKG_BOOKING BK" ).append("\n"); 
		query.append("                                , BKG_VVD VVD" ).append("\n"); 
		query.append("								, BKG_BL_ISS ISS" ).append("\n"); 
		query.append("                                , BKG_BL_DOC DOC" ).append("\n"); 
		query.append("                                , (SELECT  GRP.ESVC_GRP_CD          GROUP_EDI_ID" ).append("\n"); 
		query.append("                                         , GRP.CUST_TRD_PRNR_ID     EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                         , GRP.ESVC_GRP_NM          RECEIVER_NAME" ).append("\n"); 
		query.append("                                         , GRP_CUST.SC_NO" ).append("\n"); 
		query.append("                                         , GRP_CUST.BKG_CUST_TP_DESC" ).append("\n"); 
		query.append("                                         , GRP_CUST.BKG_CTRT_TP_CD" ).append("\n"); 
		query.append("                                   FROM BKG_EDI_GRP GRP, BKG_EDI_GRP_CUST GRP_CUST" ).append("\n"); 
		query.append("                                  WHERE GRP.ESVC_GRP_CD         = GRP_CUST.ESVC_GRP_CD" ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = GRP_CUST.CO_CD      " ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = 'H'" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_DELT_FLG   = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.SC_NO          > ' '              " ).append("\n"); 
		query.append("                                    AND GRP_CUST.DELT_FLG       = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.BKG_CFM_FLG    = 'Y'" ).append("\n"); 
		query.append("                                    AND (@[msg_type_cd] = 'ALL' OR @[msg_type_cd] = 'B')" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${edi_group_id} != '' && ${edi_receive_nm} != '')" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'G')--Group ID" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_CD  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'R')--Receive ID" ).append("\n"); 
		query.append("                                    AND GRP.CUST_TRD_PRNR_ID like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'N')--receive name" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_NM  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                                    ) EDI_BY_SC" ).append("\n"); 
		query.append("                         WHERE EDI_BY_SC.SC_NO  = DECODE(EDI_BY_SC.BKG_CTRT_TP_CD, '1', BK.SC_NO, '2', BK.RFA_NO)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = CUST.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = ISS.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = DOC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = VVD.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.POL_CD        = VVD.POL_CD" ).append("\n"); 
		query.append("                           AND VVD.VSL_PRE_PST_CD IN ('T', 'S')" ).append("\n"); 
		query.append("                           AND BK.BKG_STS_CD    IN ('F', 'A')" ).append("\n"); 
		query.append("                           AND BK.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("                           AND DECODE(BKG_CUST_TP_DESC,'ALL','ALL',CUST.BKG_CUST_TP_CD)" ).append("\n"); 
		query.append("                               IN (SELECT COLUMN_VALUE" ).append("\n"); 
		query.append("                                     FROM TABLE(BKG_SPLIT_FNC(BKG_CUST_TP_DESC,',')))" ).append("\n"); 
		query.append("                        ---------------------------조건절 시작   " ).append("\n"); 
		query.append("#if (${bkg_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_NO IN ( ${bkg_no} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BL_NO  = @[bl_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                        ---------------------------bkg or b/l no입력시 다른 조건 제외함" ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT > TO_DATE(@[bkg_from_dt], 'yyyy-mm-dd')" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')         " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT > TO_DATE(@[bkg_from_dt], 'yyyy-mm-dd')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT < TO_DATE(@[bkg_to_dt],   'yyyy-mm-dd') + 1" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')  " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT < TO_DATE(@[bkg_to_dt],   'yyyy-mm-dd') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${xter_rqst_via_cd} != 'All' && ${xter_rqst_via_cd} != '') " ).append("\n"); 
		query.append("                           AND BK.XTER_BKG_RQST_CD IN ( ${xter_rqst_via_cd} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${vvd} != '')" ).append("\n"); 
		query.append("                           AND VVD.VSL_CD     = SUBSTR(@[vvd], 1, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_VOY_NO = SUBSTR(@[vvd], 5, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_DIR_CD = SUBSTR(@[vvd], 9, 1)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${por_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POR_CD = @[por_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pol_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POL_CD = @[pol_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pod_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POD_CD = @[pod_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${del_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.DEL_CD = @[del_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_OFC_CD = @[bkg_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_stf_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.DOC_USR_ID = @[bkg_stf_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sls_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SLS_OFC_CD = @[sls_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sales_rep} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SREP_CD = @[sales_rep]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND ISS.OBL_ISS_OFC_CD = @[bl_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_tp_cd} != 'All' && ${cust_tp_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.BKG_CUST_TP_CD = @[cust_tp_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_cnt_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_CNT_CD = @[cust_cnt_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_seq} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_SEQ = TO_NUMBER(@[cust_seq])" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_nm} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_NM LIKE UPPER(@[cust_nm])||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sc_no} != '')" ).append("\n"); 
		query.append("                           AND BK.SC_NO = @[sc_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                           )" ).append("\n"); 
		query.append("                   GROUP BY BKG_NO" ).append("\n"); 
		query.append("                        , GROUP_EDI_ID" ).append("\n"); 
		query.append("                        , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                        , RECEIVER_NAME" ).append("\n"); 
		query.append("						, VVD) MST                " ).append("\n"); 
		query.append("          WHERE MST.BKG_NO             = CUST.BKG_NO(+)" ).append("\n"); 
		query.append("            AND SUBSTR(MST.RANK, 2, 1) = CUST.BKG_CUST_TP_CD(+)" ).append("\n"); 
		query.append("            AND MST.BKG_NO             = BK.BKG_NO" ).append("\n"); 
		query.append("#if (${sc_no} != '')" ).append("\n"); 
		query.append("            AND BK.SC_NO               = @[sc_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("            AND MST.BKG_NO             = NTC.BKG_NO    (+)" ).append("\n"); 
		query.append("            AND 'E'                    = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("            AND 'BK'                   = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("			AND MST.EDI_RECEIVE_ID 	   = NTC.EDI_ID(+)" ).append("\n"); 
		query.append("			AND MST.GROUP_EDI_ID   	   = NTC.ESVC_GRP_CD(+)" ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'R')         " ).append("\n"); 
		query.append("            AND NTC.SND_RQST_DT > TO_DATE(REPLACE(@[bkg_from_dt],'-',''),'RRRRMMDD')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'R')  " ).append("\n"); 
		query.append("            AND NTC.SND_RQST_DT < TO_DATE(REPLACE(@[bkg_to_dt],'-',''),'RRRRMMDD') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("            AND (EDI_RECEIVE_ID NOT IN ('INTTRA', 'INTTRANG2')" ).append("\n"); 
		query.append("                 OR EXISTS (SELECT 'X' " ).append("\n"); 
		query.append("                        FROM BKG_XTER_RQST_MST BXRM " ).append("\n"); 
		query.append("                        WHERE BXRM.BKG_NO = BK.BKG_NO" ).append("\n"); 
		query.append("                        AND BXRM.DOC_TP_CD = 'B'" ).append("\n"); 
		query.append("                        AND BXRM.BKG_UPLD_STS_CD = 'F'" ).append("\n"); 
		query.append("                        AND BXRM.XTER_RQST_VIA_CD = 'INT')" ).append("\n"); 
		query.append("                 )" ).append("\n"); 
		query.append("			" ).append("\n"); 
		query.append("        ) MST" ).append("\n"); 
		query.append(" WHERE 1 = 1" ).append("\n"); 
		query.append("   AND ((HIS_SEQ IS NOT NULL AND HIS_SEQ = (SELECT MAX(HIS.HIS_SEQ) " ).append("\n"); 
		query.append("                                              FROM BKG_NTC_HIS HIS" ).append("\n"); 
		query.append("                                             WHERE HIS.BKG_NO = MST.BKG_NO" ).append("\n"); 
		query.append("                                               AND HIS.NTC_VIA_CD = MST.NTC_VIA_CD" ).append("\n"); 
		query.append("                                               AND HIS.NTC_KND_CD = MST.NTC_KND_CD" ).append("\n"); 
		query.append("											   AND HIS.EDI_ID     = MST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("											   AND HIS.ESVC_GRP_CD= MST.GROUP_EDI_ID))" ).append("\n"); 
		query.append("        OR" ).append("\n"); 
		query.append("      (HIS_SEQ IS NULL))                                   " ).append("\n"); 
		query.append("#if (${edi_sent_sts_cd} != 'All' && ${edi_sent_sts_cd} == 'Y')" ).append("\n"); 
		query.append(" --edi_sent_status = sent" ).append("\n"); 
		query.append(" AND SENT_DT IS NOT NULL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${edi_sent_sts_cd} != 'All' && ${edi_sent_sts_cd} == 'N')" ).append("\n"); 
		query.append(" --edi_sent_status = unsent" ).append("\n"); 
		query.append(" AND SENT_DT IS NULL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("SELECT BKG_NO" ).append("\n"); 
		query.append("        , STATUS" ).append("\n"); 
		query.append("        , BL_NO" ).append("\n"); 
		query.append("        , '' CUST_TP_CD" ).append("\n"); 
		query.append("        , '' CUST_CD" ).append("\n"); 
		query.append("        , ''  CUST_NM" ).append("\n"); 
		query.append("        , SC_NO" ).append("\n"); 
		query.append("        , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("		, ''  EDI_REF" ).append("\n"); 
		query.append("        , '' RECEIVER_NAME" ).append("\n"); 
		query.append("		, VVD" ).append("\n"); 
		query.append("        , POR_CD" ).append("\n"); 
		query.append("        , POL_CD" ).append("\n"); 
		query.append("        , POD_CD" ).append("\n"); 
		query.append("        , DEL_CD" ).append("\n"); 
		query.append("        , SENT_DT" ).append("\n"); 
		query.append("        , SND_USR_ID" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER WHERE USR_ID = SND_USR_ID AND ROWNUM = 1) SND_USR_NM" ).append("\n"); 
		query.append("        , SENT_STATUS" ).append("\n"); 
		query.append("        , NULL ACK" ).append("\n"); 
		query.append("        , EDI_RECEIVE_ID RCV_ID" ).append("\n"); 
		query.append("        , '' GROUP_ID" ).append("\n"); 
		query.append("        , REF_CODE REF_CODE" ).append("\n"); 
		query.append("        , '' BL_TP_CD" ).append("\n"); 
		query.append("        , EDI_CTRL_NO ISA_NO" ).append("\n"); 
		query.append("        , 'BKG Conf.'  DOC_TYPE" ).append("\n"); 
		query.append("        , DECODE(XTER_BKG_RQST_CD, 'NIS', 'OFF', 'APS', 'OFF', XTER_BKG_RQST_CD) XTER_RQST_VIA_CD" ).append("\n"); 
		query.append("        , TP_301" ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append(" FROM (" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("      SELECT BK.BKG_NO" ).append("\n"); 
		query.append("            ,BK.BKG_STS_CD STATUS" ).append("\n"); 
		query.append("            ,BK.BL_NO||BK.BL_TP_CD BL_NO" ).append("\n"); 
		query.append("            , BK.BL_TP_CD" ).append("\n"); 
		query.append("            , BK.SC_NO" ).append("\n"); 
		query.append("            , MST.VVD" ).append("\n"); 
		query.append("            , BK.POR_CD" ).append("\n"); 
		query.append("            , BK.POL_CD" ).append("\n"); 
		query.append("            , BK.POD_CD" ).append("\n"); 
		query.append("            , BK.DEL_CD" ).append("\n"); 
		query.append("            , TO_CHAR(MST.SND_RQST_DT, 'YYYY-MM-DD') SENT_DT" ).append("\n"); 
		query.append("            , MST.SND_USR_ID" ).append("\n"); 
		query.append("            , CASE WHEN MST.SND_RQST_DT IS NULL THEN 'U'" ).append("\n"); 
		query.append("                   WHEN MST.BKG_NTC_SND_RSLT_CD = 'A' THEN 'S'" ).append("\n"); 
		query.append("                   ELSE 'E'" ).append("\n"); 
		query.append("                   END AS SENT_STATUS" ).append("\n"); 
		query.append("            , MST.HIS_SEQ" ).append("\n"); 
		query.append("            , MST.NTC_VIA_CD" ).append("\n"); 
		query.append("            , MST.NTC_KND_CD" ).append("\n"); 
		query.append("            , MST.EDI_CTRL_NO" ).append("\n"); 
		query.append("            , BK.XTER_BKG_RQST_CD" ).append("\n"); 
		query.append("            , '' REF_TP_CD" ).append("\n"); 
		query.append("            , MST.YD_CD REF_CODE" ).append("\n"); 
		query.append("             , MST.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , MST.SND_USR_ID SENDER" ).append("\n"); 
		query.append("             , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = MST.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("             , TO_CHAR(MST.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("             , MST.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("             , 'T' TP_301" ).append("\n"); 
		query.append("      FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("         , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                 , NTC.SND_USR_ID, NTC.SND_RQST_DT, NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                 , EDI_YD.EDI_RCV_ID EDI_ID, EDI_YD.YD_CD,NTC.HIS_SEQ,NTC.NTC_VIA_CD,NTC.NTC_KND_CD,NTC.EDI_CTRL_NO" ).append("\n"); 
		query.append("                 ,EDI_YD.VVD" ).append("\n"); 
		query.append("              FROM BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("                 , (SELECT DISTINCT EY.RCVR_TRD_PRNR_ID AS EDI_RCV_ID" ).append("\n"); 
		query.append("                         , EY.PRNR_PORT_CD AS PORT_CD" ).append("\n"); 
		query.append("                         , EY.PRNR_SUB_LNK_CD AS YD_CD" ).append("\n"); 
		query.append("                         , BK.BKG_NO" ).append("\n"); 
		query.append("                         , VVD.VSL_CD||VVD.SKD_VOY_NO||VVD.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("                      FROM BKG_EDI_TRD_PRNR_SUB_LNK EY" ).append("\n"); 
		query.append("                         , BKG_EDI_SUB_LNK_MSG MSG" ).append("\n"); 
		query.append("                         , BKG_VVD VVD" ).append("\n"); 
		query.append("                         , BKG_BOOKING BK" ).append("\n"); 
		query.append("                         , BKG_BL_ISS ISS" ).append("\n"); 
		query.append("                         , BKG_BL_DOC DOC" ).append("\n"); 
		query.append("                     WHERE 1=1" ).append("\n"); 
		query.append("#if (${bkg_no} != '')" ).append("\n"); 
		query.append("                       AND BK.BKG_NO IN ( ${bkg_no} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                       AND BK.BKG_STS_CD IN ('F', 'W', 'S')" ).append("\n"); 
		query.append("                       AND BK.BKG_NO = VVD.BKG_NO" ).append("\n"); 
		query.append("                       AND BK.BKG_NO = ISS.BKG_NO(+)" ).append("\n"); 
		query.append("                       AND BK.BKG_NO = DOC.BKG_NO(+)" ).append("\n"); 
		query.append("#if (${bl_no} != '')" ).append("\n"); 
		query.append("                       AND BK.BL_NO = @[bl_no]" ).append("\n"); 
		query.append("#end " ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                       AND BK.BKG_CRE_DT > TO_DATE(REPLACE(@[bkg_from_dt],'-',''),'RRRRMMDD')" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')         " ).append("\n"); 
		query.append("                       AND DOC.BL_OBRD_DT > TO_DATE(REPLACE(@[bkg_from_dt],'-',''),'RRRRMMDD')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                       AND BK.BKG_CRE_DT < TO_DATE(REPLACE(@[bkg_to_dt],'-',''),'RRRRMMDD') + 1" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')  " ).append("\n"); 
		query.append("                       AND DOC.BL_OBRD_DT < TO_DATE(REPLACE(@[bkg_to_dt],'-',''),'RRRRMMDD') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${xter_rqst_via_cd} != 'All' && ${xter_rqst_via_cd} != '') " ).append("\n"); 
		query.append("                       AND BK.XTER_BKG_RQST_CD IN ( ${xter_rqst_via_cd} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${xter_rqst_via_cd} != 'All' && ${xter_rqst_via_cd} != '') " ).append("\n"); 
		query.append("                           AND BK.XTER_BKG_RQST_CD IN ( ${xter_rqst_via_cd} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${vvd} != '')" ).append("\n"); 
		query.append("                           AND VVD.VSL_CD     = SUBSTR(@[vvd], 1, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_VOY_NO = SUBSTR(@[vvd], 5, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_DIR_CD = SUBSTR(@[vvd], 9, 1)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${por_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POR_CD = @[por_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pol_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POL_CD = @[pol_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pod_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POD_CD = @[pod_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${del_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.DEL_CD = @[del_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_OFC_CD = @[bkg_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_stf_cd} != '')" ).append("\n"); 
		query.append("                           AND UPPER(BK.DOC_USR_ID) = UPPER(@[bkg_stf_cd])" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sls_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SLS_OFC_CD = @[sls_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sales_rep} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SREP_CD = @[sales_rep]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND ISS.OBL_ISS_OFC_CD = @[bl_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sc_no} != '')" ).append("\n"); 
		query.append("                           AND BK.SC_NO      = @[sc_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                       AND EY.TRD_PRNR_SUB_LNK_SEQ = MSG.TRD_PRNR_SUB_LNK_SEQ" ).append("\n"); 
		query.append("                       AND EY.PRNR_SUB_LNK_DIV_CD = '1'" ).append("\n"); 
		query.append("                       AND MSG.EDI_MSG_TP_ID      = '301'" ).append("\n"); 
		query.append("#if(${edi_group_id} != '' && ${edi_receive_nm} != '')" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'G')--Group ID" ).append("\n"); 
		query.append("                       AND 1=2" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'R')--Receive ID" ).append("\n"); 
		query.append("                       AND EY.RCVR_TRD_PRNR_ID like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'N')--receive name" ).append("\n"); 
		query.append("                       AND 1=2                           " ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_tp_cd} != 'All' && ${cust_tp_cd} != '')" ).append("\n"); 
		query.append("                       AND 1=2    " ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_cnt_cd} != '')" ).append("\n"); 
		query.append("                       AND 1=2    " ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_seq} != '')" ).append("\n"); 
		query.append("                       AND 1=2    " ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_nm} != '')" ).append("\n"); 
		query.append("                       AND 1=2    " ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                       AND (   (EY.PRNR_SUB_LNK_CD = BK.POL_NOD_CD AND MSG.EDI_MSG_IND_CD IN ('1', '2')) -- BKG" ).append("\n"); 
		query.append("                            OR (EY.PRNR_SUB_LNK_CD = VVD.POL_YD_CD AND VVD.VSL_PRE_PST_CD IN ('S','T') AND MSG.EDI_MSG_IND_CD = '6') --PRE T/S PORT" ).append("\n"); 
		query.append("                            OR (EY.PRNR_SUB_LNK_CD = VVD.POL_YD_CD AND VVD.VSL_PRE_PST_CD = 'U' AND MSG.EDI_MSG_IND_CD = '7') --POST T/S PORT" ).append("\n"); 
		query.append("                           )" ).append("\n"); 
		query.append("                       AND (@[msg_type_cd] = 'ALL' OR @[msg_type_cd] = 'B')" ).append("\n"); 
		query.append("                    ) EDI_YD" ).append("\n"); 
		query.append("              WHERE 'E'  = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                AND 'BT' = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                AND EDI_YD.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                AND EDI_YD.EDI_RCV_ID = NTC.EDI_ID(+)" ).append("\n"); 
		query.append("                AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                    NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                        FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                       WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                         AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                         AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                         AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                         AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                     ),1)" ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'R')" ).append("\n"); 
		query.append("                AND NTC.SND_RQST_DT > TO_DATE(@[bkg_from_dt], 'yyyy-mm-dd')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'R')  " ).append("\n"); 
		query.append("                AND NTC.SND_RQST_DT < TO_DATE(@[bkg_to_dt],   'yyyy-mm-dd') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("        ) MST" ).append("\n"); 
		query.append("        WHERE MST.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(" )" ).append("\n"); 
		query.append(" #if (${edi_sent_sts_cd} != 'All' && ${edi_sent_sts_cd} == 'Y')" ).append("\n"); 
		query.append(" --edi_sent_status = sent" ).append("\n"); 
		query.append(" AND SENT_DT IS NOT NULL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${edi_sent_sts_cd} != 'All' && ${edi_sent_sts_cd} == 'N')" ).append("\n"); 
		query.append(" --edi_sent_status = unsent" ).append("\n"); 
		query.append(" AND SENT_DT IS NULL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("SELECT /*+ opt_param('_optimizer_skip_scan_enabled', 'false') */ " ).append("\n"); 
		query.append("          BKG_NO" ).append("\n"); 
		query.append("        , STATUS" ).append("\n"); 
		query.append("        , BL_NO" ).append("\n"); 
		query.append("        , CUST_TP_CD" ).append("\n"); 
		query.append("        , CUST_CD" ).append("\n"); 
		query.append("        , REPLACE(CUST_NM, CHR(13)||CHR(10), ' ') CUST_NM" ).append("\n"); 
		query.append("        , SC_NO" ).append("\n"); 
		query.append("        , GROUP_EDI_ID" ).append("\n"); 
		query.append("		, (SELECT /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("                  DECODE(CUST_SEQ, '0', '', CUST_CNT_CD||TRIM(TO_CHAR(CUST_SEQ, '000000')))" ).append("\n"); 
		query.append("			 FROM BKG_CUSTOMER CUST " ).append("\n"); 
		query.append("            WHERE CUST.BKG_NO = MST.BKG_NO " ).append("\n"); 
		query.append("              AND BKG_CUST_TP_CD = 'E') EDI_REF" ).append("\n"); 
		query.append("        , RECEIVER_NAME" ).append("\n"); 
		query.append("		, VVD" ).append("\n"); 
		query.append("        , POR_CD" ).append("\n"); 
		query.append("        , POL_CD" ).append("\n"); 
		query.append("        , POD_CD" ).append("\n"); 
		query.append("        , DEL_CD" ).append("\n"); 
		query.append("        , SENT_DT" ).append("\n"); 
		query.append("        , SND_USR_ID" ).append("\n"); 
		query.append("        , (SELECT usr_nm FROM com_user WHERE usr_id = SND_USR_ID AND ROWNUM = 1) SND_USR_NM" ).append("\n"); 
		query.append("        , SENT_STATUS" ).append("\n"); 
		query.append("        , ACK" ).append("\n"); 
		query.append("        , EDI_RECEIVE_ID RCV_ID" ).append("\n"); 
		query.append("        , GROUP_EDI_ID GROUP_ID" ).append("\n"); 
		query.append("        , CUST_CD REF_CODE" ).append("\n"); 
		query.append("        , NVL(BL_TP_CD,'D') BL_TP_CD" ).append("\n"); 
		query.append("        , EDI_CTRL_NO ISA_NO" ).append("\n"); 
		query.append("        , 'B/L' AS DOC_TYPE" ).append("\n"); 
		query.append("        , DECODE(XTER_BKG_RQST_CD, 'NIS', 'OFF', 'APS', 'OFF', XTER_BKG_RQST_CD) XTER_RQST_VIA_CD" ).append("\n"); 
		query.append("        , TP_301" ).append("\n"); 
		query.append("  FROM (SELECT  /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("				MST.BKG_NO" ).append("\n"); 
		query.append("                , BK.BKG_STS_CD STATUS" ).append("\n"); 
		query.append("                , BK.BL_NO||BK.BL_TP_CD BL_NO" ).append("\n"); 
		query.append("                , BK.BL_TP_CD" ).append("\n"); 
		query.append("                , SUBSTR(RANK, 2, 2) CUST_TP_CD" ).append("\n"); 
		query.append("                , CUST.CUST_CNT_CD||TRIM(TO_CHAR(CUST.CUST_SEQ, '000009')) CUST_CD" ).append("\n"); 
		query.append("                , CUST.CUST_NM" ).append("\n"); 
		query.append("                , BK.SC_NO" ).append("\n"); 
		query.append("                , MST.GROUP_EDI_ID" ).append("\n"); 
		query.append("                , MST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                , MST.RECEIVER_NAME" ).append("\n"); 
		query.append("				, MST.VVD" ).append("\n"); 
		query.append("                , BK.POR_CD" ).append("\n"); 
		query.append("                , BK.POL_CD" ).append("\n"); 
		query.append("                , BK.POD_CD" ).append("\n"); 
		query.append("                , BK.DEL_CD" ).append("\n"); 
		query.append("                , TO_CHAR(NTC.SND_RQST_DT, 'YYYY-MM-DD') SENT_DT" ).append("\n"); 
		query.append("                , NTC.SND_USR_ID" ).append("\n"); 
		query.append("                , CASE WHEN NTC.SND_RQST_DT IS NULL THEN 'U'" ).append("\n"); 
		query.append("                       WHEN NTC.BKG_NTC_SND_RSLT_CD = 'A' THEN 'S'" ).append("\n"); 
		query.append("                       ELSE 'E'" ).append("\n"); 
		query.append("                       END AS SENT_STATUS" ).append("\n"); 
		query.append("                , null ACK" ).append("\n"); 
		query.append("		        , NTC.HIS_SEQ" ).append("\n"); 
		query.append("				, NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("				, NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                , NTC.EDI_CTRL_NO" ).append("\n"); 
		query.append("  				, BK.XTER_BKG_RQST_CD" ).append("\n"); 
		query.append("                , '' TP_301" ).append("\n"); 
		query.append("          FROM BKG_CUSTOMER CUST, BKG_BOOKING BK, BKG_NTC_HIS NTC, " ).append("\n"); 
		query.append("                (SELECT BKG_NO" ).append("\n"); 
		query.append("                        , MIN(RANK) RANK" ).append("\n"); 
		query.append("                        , GROUP_EDI_ID" ).append("\n"); 
		query.append("                        , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                        , RECEIVER_NAME" ).append("\n"); 
		query.append("						, VVD" ).append("\n"); 
		query.append("                   FROM " ).append("\n"); 
		query.append("                        (SELECT /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("                                 BK.BKG_NO" ).append("\n"); 
		query.append("                                , MIN(TP_RANK.RANK) RANK" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.GROUP_EDI_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.RECEIVER_NAME" ).append("\n"); 
		query.append("								, VVD.VSL_CD||VVD.SKD_VOY_NO||VVD.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("                          FROM BKG_CUSTOMER CUST" ).append("\n"); 
		query.append("                                , BKG_BOOKING BK" ).append("\n"); 
		query.append("                                , BKG_VVD VVD" ).append("\n"); 
		query.append("								, BKG_BL_ISS ISS" ).append("\n"); 
		query.append("                                ,BKG_BL_DOC DOC" ).append("\n"); 
		query.append("                                , (SELECT  GRP.ESVC_GRP_CD           GROUP_EDI_ID" ).append("\n"); 
		query.append("                                         , GRP.CUST_TRD_PRNR_ID     EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                         , GRP.ESVC_GRP_NM          RECEIVER_NAME" ).append("\n"); 
		query.append("                                         , grp_CUST.CNT_CD   " ).append("\n"); 
		query.append("                                         , grp_CUST.CUST_SEQ " ).append("\n"); 
		query.append("                                         , GRP_CUST.BKG_CUST_TP_DESC" ).append("\n"); 
		query.append("                                   FROM BKG_EDI_GRP_CUST GRP_CUST, BKG_EDI_GRP GRP" ).append("\n"); 
		query.append("                                  WHERE GRP.ESVC_GRP_CD         = GRP_CUST.ESVC_GRP_CD" ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = GRP_CUST.CO_CD" ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = 'H'" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_DELT_FLG   = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.CNT_CD         > ' '" ).append("\n"); 
		query.append("                                    AND GRP_CUST.CUST_SEQ       > 0" ).append("\n"); 
		query.append("                                    AND GRP_CUST.DELT_FLG       = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.BL_DRFT_FLG    = 'Y'" ).append("\n"); 
		query.append("                                    AND (@[msg_type_cd] = 'ALL' OR @[msg_type_cd] = 'D')" ).append("\n"); 
		query.append("#if(${edi_group_id} != '' && ${edi_receive_nm} != '')" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'G')--Group ID" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_CD  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'R')--Receive ID" ).append("\n"); 
		query.append("                                    AND GRP.CUST_TRD_PRNR_ID like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'N')--receive name" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_NM  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                                    ) EDI_BY_CUST               " ).append("\n"); 
		query.append("                                , (SELECT 'S' RCV_TP, '1SH' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'C' RCV_TP, '2CN' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'N' RCV_TP, '3NF' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'F' RCV_TP, '4FF' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'A' RCV_TP, '5AN' RANK FROM DUAL " ).append("\n"); 
		query.append("                                   UNION SELECT 'E' RCV_TP, '6EX' RANK FROM DUAL) TP_RANK" ).append("\n"); 
		query.append("                         WHERE EDI_BY_CUST.CNT_CD   = CUST.CUST_CNT_CD " ).append("\n"); 
		query.append("                           AND EDI_BY_CUST.CUST_SEQ = CUST.CUST_SEQ" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = CUST.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = ISS.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = DOC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = VVD.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.POL_CD        = VVD.POL_CD" ).append("\n"); 
		query.append("                           AND VVD.VSL_PRE_PST_CD IN ('T', 'S')" ).append("\n"); 
		query.append("                           AND CUST.BKG_CUST_TP_CD = TP_RANK.RCV_TP" ).append("\n"); 
		query.append("                           AND BK.BKG_STS_CD    IN ('F', 'W', 'S')" ).append("\n"); 
		query.append("                           AND BK.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("                           AND DECODE(BKG_CUST_TP_DESC,'ALL','ALL',CUST.BKG_CUST_TP_CD)" ).append("\n"); 
		query.append("                               IN (SELECT COLUMN_VALUE" ).append("\n"); 
		query.append("                                     FROM TABLE(BKG_SPLIT_FNC(BKG_CUST_TP_DESC,',')))" ).append("\n"); 
		query.append("                        ---------------------------조건절 시작   " ).append("\n"); 
		query.append("#if (${bkg_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_NO IN ( ${bkg_no} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BL_NO  = @[bl_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                        ---------------------------bkg or b/l no입력시 다른 조건 제외함" ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT > TO_DATE(REPLACE(@[bkg_from_dt],'-',''),'RRRRMMDD')" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')         " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT > TO_DATE(REPLACE(@[bkg_from_dt],'-',''),'RRRRMMDD')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT < TO_DATE(REPLACE(@[bkg_to_dt],'-',''),'RRRRMMDD') + 1" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')  " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT < TO_DATE(REPLACE(@[bkg_to_dt],'-',''),'RRRRMMDD') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${xter_rqst_via_cd} != 'All' && ${xter_rqst_via_cd} != '') " ).append("\n"); 
		query.append("                           AND BK.XTER_BKG_RQST_CD IN ( ${xter_rqst_via_cd} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${vvd} != '')" ).append("\n"); 
		query.append("                           AND VVD.VSL_CD     = SUBSTR(@[vvd], 1, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_VOY_NO = SUBSTR(@[vvd], 5, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_DIR_CD = SUBSTR(@[vvd], 9, 1)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${por_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POR_CD = @[por_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pol_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POL_CD = @[pol_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pod_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POD_CD = @[pod_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${del_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.DEL_CD = @[del_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_OFC_CD = @[bkg_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_stf_cd} != '')" ).append("\n"); 
		query.append("                           AND UPPER(BK.DOC_USR_ID) = UPPER(@[bkg_stf_cd])" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sls_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SLS_OFC_CD = @[sls_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sales_rep} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SREP_CD = @[sales_rep]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND ISS.OBL_ISS_OFC_CD = @[bl_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_tp_cd} != 'All' && ${cust_tp_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.BKG_CUST_TP_CD = @[cust_tp_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_cnt_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_CNT_CD = @[cust_cnt_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_seq} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_SEQ = TO_NUMBER(@[cust_seq])" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_nm} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_NM LIKE UPPER(@[cust_nm])||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                         GROUP BY BK.BKG_NO" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.GROUP_EDI_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                , EDI_BY_CUST.RECEIVER_NAME" ).append("\n"); 
		query.append("								, VVD.VSL_CD||VVD.SKD_VOY_NO||VVD.SKD_DIR_CD" ).append("\n"); 
		query.append("                         UNION" ).append("\n"); 
		query.append("                          SELECT /*+ INDEX(CUST XAK1BKG_CUSTOMER) */" ).append("\n"); 
		query.append("                                  BK.BKG_NO" ).append("\n"); 
		query.append("                                , '7SC' RANK" ).append("\n"); 
		query.append("                                , EDI_BY_SC.GROUP_EDI_Id" ).append("\n"); 
		query.append("                                , EDI_BY_SC.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                , EDI_BY_SC.RECEIVER_NAME" ).append("\n"); 
		query.append("								, VVD.VSL_CD||VVD.SKD_VOY_NO||VVD.SKD_DIR_CD VVD" ).append("\n"); 
		query.append("                          FROM BKG_CUSTOMER CUST" ).append("\n"); 
		query.append("                                , BKG_BOOKING BK" ).append("\n"); 
		query.append("                                , BKG_VVD VVD" ).append("\n"); 
		query.append("								, BKG_BL_ISS ISS" ).append("\n"); 
		query.append("                                , BKG_BL_DOC DOC" ).append("\n"); 
		query.append("                                , (SELECT  GRP.ESVC_GRP_CD          GROUP_EDI_ID" ).append("\n"); 
		query.append("                                         , GRP.CUST_TRD_PRNR_ID     EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                         , GRP.ESVC_GRP_NM          RECEIVER_NAME" ).append("\n"); 
		query.append("                                         , GRP_CUST.SC_NO" ).append("\n"); 
		query.append("                                         , GRP_CUST.BKG_CUST_TP_DESC" ).append("\n"); 
		query.append("                                         , GRP_CUST.BKG_CTRT_TP_CD" ).append("\n"); 
		query.append("                                   FROM BKG_EDI_GRP GRP, BKG_EDI_GRP_CUST GRP_CUST" ).append("\n"); 
		query.append("                                  WHERE GRP.ESVC_GRP_CD         = GRP_CUST.ESVC_GRP_CD" ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = GRP_CUST.CO_CD      " ).append("\n"); 
		query.append("                                    AND GRP.CO_CD               = 'H'" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_DELT_FLG   = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.SC_NO          > ' '              " ).append("\n"); 
		query.append("                                    AND GRP_CUST.DELT_FLG       = 'N'" ).append("\n"); 
		query.append("                                    AND GRP_CUST.BL_DRFT_FLG    = 'Y'" ).append("\n"); 
		query.append("                                    AND (@[msg_type_cd] = 'ALL' OR @[msg_type_cd] = 'D')" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${edi_group_id} != '' && ${edi_receive_nm} != '')" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'G')--Group ID" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_CD  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'R')--Receive ID" ).append("\n"); 
		query.append("                                    AND GRP.CUST_TRD_PRNR_ID like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if(${edi_group_id} == 'N')--receive name" ).append("\n"); 
		query.append("                                    AND GRP.ESVC_GRP_NM  like @[edi_receive_nm]||'%'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                                    ) EDI_BY_SC" ).append("\n"); 
		query.append("                         WHERE EDI_BY_SC.SC_NO  = DECODE(EDI_BY_SC.BKG_CTRT_TP_CD, '1', BK.SC_NO, '2', BK.RFA_NO)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = CUST.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = ISS.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = DOC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO        = VVD.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.POL_CD        = VVD.POL_CD" ).append("\n"); 
		query.append("                           AND VVD.VSL_PRE_PST_CD IN ('T', 'S')" ).append("\n"); 
		query.append("                           AND BK.BKG_STS_CD    IN ('F', 'A')" ).append("\n"); 
		query.append("                           AND BK.BKG_CGO_TP_CD <> 'P'" ).append("\n"); 
		query.append("                           AND DECODE(BKG_CUST_TP_DESC,'ALL','ALL',CUST.BKG_CUST_TP_CD)" ).append("\n"); 
		query.append("                               IN (SELECT COLUMN_VALUE" ).append("\n"); 
		query.append("                                     FROM TABLE(BKG_SPLIT_FNC(BKG_CUST_TP_DESC,',')))" ).append("\n"); 
		query.append("                        ---------------------------조건절 시작   " ).append("\n"); 
		query.append("#if (${bkg_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_NO IN ( ${bkg_no} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_no} != '')" ).append("\n"); 
		query.append("                           AND BK.BL_NO  = @[bl_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                        ---------------------------bkg or b/l no입력시 다른 조건 제외함" ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT > TO_DATE(@[bkg_from_dt], 'yyyy-mm-dd')" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')         " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT > TO_DATE(@[bkg_from_dt], 'yyyy-mm-dd')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'B')" ).append("\n"); 
		query.append("                           AND BK.BKG_CRE_DT < TO_DATE(@[bkg_to_dt],   'yyyy-mm-dd') + 1" ).append("\n"); 
		query.append("    #elseif (${type_date} == 'O')  " ).append("\n"); 
		query.append("                           AND DOC.BL_OBRD_DT < TO_DATE(@[bkg_to_dt],   'yyyy-mm-dd') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${xter_rqst_via_cd} != 'All' && ${xter_rqst_via_cd} != '') " ).append("\n"); 
		query.append("                           AND BK.XTER_BKG_RQST_CD IN ( ${xter_rqst_via_cd} )" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${vvd} != '')" ).append("\n"); 
		query.append("                           AND VVD.VSL_CD     = SUBSTR(@[vvd], 1, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_VOY_NO = SUBSTR(@[vvd], 5, 4)" ).append("\n"); 
		query.append("                           AND VVD.SKD_DIR_CD = SUBSTR(@[vvd], 9, 1)" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${por_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POR_CD = @[por_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pol_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POL_CD = @[pol_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${pod_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.POD_CD = @[pod_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${del_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.DEL_CD = @[del_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.BKG_OFC_CD = @[bkg_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_stf_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.DOC_USR_ID = @[bkg_stf_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sls_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SLS_OFC_CD = @[sls_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sales_rep} != '')" ).append("\n"); 
		query.append("                           AND BK.OB_SREP_CD = @[sales_rep]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bl_ofc_cd} != '')" ).append("\n"); 
		query.append("                           AND ISS.OBL_ISS_OFC_CD = @[bl_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_tp_cd} != 'All' && ${cust_tp_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.BKG_CUST_TP_CD = @[cust_tp_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_cnt_cd} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_CNT_CD = @[cust_cnt_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_seq} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_SEQ = TO_NUMBER(@[cust_seq])" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${cust_nm} != '')" ).append("\n"); 
		query.append("                           AND CUST.CUST_NM LIKE UPPER(@[cust_nm])||'%'" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${sc_no} != '')" ).append("\n"); 
		query.append("                           AND BK.SC_NO = @[sc_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("                           )" ).append("\n"); 
		query.append("                   GROUP BY BKG_NO" ).append("\n"); 
		query.append("                        , GROUP_EDI_ID" ).append("\n"); 
		query.append("                        , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                        , RECEIVER_NAME" ).append("\n"); 
		query.append("						, VVD) MST                " ).append("\n"); 
		query.append("          WHERE MST.BKG_NO             = CUST.BKG_NO(+)" ).append("\n"); 
		query.append("            AND SUBSTR(MST.RANK, 2, 1) = CUST.BKG_CUST_TP_CD(+)" ).append("\n"); 
		query.append("            AND MST.BKG_NO             = BK.BKG_NO" ).append("\n"); 
		query.append("            AND MST.BKG_NO             = NTC.BKG_NO    (+)" ).append("\n"); 
		query.append("            AND 'E'                    = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("            AND 'BL'                   = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("#if (${sc_no} != '')" ).append("\n"); 
		query.append("            AND BK.SC_NO               = @[sc_no]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("			AND MST.EDI_RECEIVE_ID 	   = NTC.EDI_ID(+)" ).append("\n"); 
		query.append("			AND MST.GROUP_EDI_ID   	   = NTC.ESVC_GRP_CD(+)" ).append("\n"); 
		query.append("#if (${bkg_from_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'R')" ).append("\n"); 
		query.append("            AND NTC.SND_RQST_DT > TO_DATE(@[bkg_from_dt], 'yyyy-mm-dd')" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${bkg_to_dt} != '')" ).append("\n"); 
		query.append("    #if (${type_date} == 'R')  " ).append("\n"); 
		query.append("            AND NTC.SND_RQST_DT < TO_DATE(@[bkg_to_dt],   'yyyy-mm-dd') + 1" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("            AND (EDI_RECEIVE_ID NOT IN ('INTTRA', 'INTTRANG2')" ).append("\n"); 
		query.append("                 OR EXISTS (SELECT 'X' " ).append("\n"); 
		query.append("                        FROM BKG_XTER_RQST_MST BXRM " ).append("\n"); 
		query.append("                        WHERE BXRM.BKG_NO = BK.BKG_NO" ).append("\n"); 
		query.append("                        AND BXRM.DOC_TP_CD = 'S'" ).append("\n"); 
		query.append("                        AND BXRM.BKG_UPLD_STS_CD = 'F'" ).append("\n"); 
		query.append("                        AND BXRM.XTER_RQST_VIA_CD = 'INT')" ).append("\n"); 
		query.append("                 )" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("        ) MST" ).append("\n"); 
		query.append(" WHERE 1 = 1" ).append("\n"); 
		query.append("   AND ((HIS_SEQ IS NOT NULL AND HIS_SEQ = (SELECT MAX(HIS.HIS_SEQ) " ).append("\n"); 
		query.append("                                              FROM BKG_NTC_HIS HIS" ).append("\n"); 
		query.append("                                             WHERE HIS.BKG_NO = MST.BKG_NO" ).append("\n"); 
		query.append("                                               AND HIS.NTC_VIA_CD = MST.NTC_VIA_CD" ).append("\n"); 
		query.append("                                               AND HIS.NTC_KND_CD = MST.NTC_KND_CD" ).append("\n"); 
		query.append("											   AND HIS.EDI_ID     = MST.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("											   AND HIS.ESVC_GRP_CD= MST.GROUP_EDI_ID))" ).append("\n"); 
		query.append("        OR" ).append("\n"); 
		query.append("      (HIS_SEQ IS NULL))                                   " ).append("\n"); 
		query.append("#if (${edi_sent_sts_cd} != 'All' && ${edi_sent_sts_cd} == 'Y')" ).append("\n"); 
		query.append(" --edi_sent_status = sent" ).append("\n"); 
		query.append(" AND SENT_DT IS NOT NULL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${edi_sent_sts_cd} != 'All' && ${edi_sent_sts_cd} == 'N')" ).append("\n"); 
		query.append(" --edi_sent_status = unsent" ).append("\n"); 
		query.append(" AND SENT_DT IS NULL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("ORDER BY BKG_NO,DOC_TYPE,TP_301" ).append("\n"); 

	}
}