/*=========================================================
*Copyright(c) 2016 CyberLogitec
*@FileName : CollectionSummaryDBDAOsearchSumbyOfcRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2016.07.06
*@LastModifier : 
*@LastVersion : 1.0
* 2016.07.06 
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.ees.dod.dodreport.collectionsummary.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class CollectionSummaryDBDAOsearchSumbyOfcRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * Summary by Office 조회
	  * </pre>
	  */
	public CollectionSummaryDBDAOsearchSumbyOfcRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("to",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_cust_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_rtn_loc",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_curr_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("from",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.ees.dod.dodreport.collectionsummary.integration").append("\n"); 
		query.append("FileName : CollectionSummaryDBDAOsearchSumbyOfcRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("SELECT A.*" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(  " ).append("\n"); 
		query.append("SELECT  /*+ opt_param('_optimizer_cost_based_transformation','off') bypass_ujvc */" ).append("\n"); 
		query.append("	   A.TRO_IB_CFM_OFC_CD," ).append("\n"); 
		query.append("       A.LOC_CD," ).append("\n"); 
		query.append("       A.CNTR_TPSZ_CD," ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("	   #if(${s_curr_cd} == 'LOCAL')" ).append("\n"); 
		query.append("		   A.CURR_CD" ).append("\n"); 
		query.append("	   #else" ).append("\n"); 
		query.append("	   	   @[s_curr_cd] CURR_CD" ).append("\n"); 
		query.append("	   #end" ).append("\n"); 
		query.append("       " ).append("\n"); 
		query.append("	   ,SUM(A.GEN_TRF_CNTR) GEN_TRF_CNTR," ).append("\n"); 
		query.append("       SUM(A.GEN_TRF_AMT) GEN_TRF_AMT," ).append("\n"); 
		query.append("       SUM(A.SPC_TRF_CNTR) SPC_TRF_CNTR," ).append("\n"); 
		query.append("       SUM(A.SPC_TRF_AMT) SPC_TRF_AMT," ).append("\n"); 
		query.append("       SUM(A.ADJ_CNTR) ADJ_CNTR," ).append("\n"); 
		query.append("       SUM(A.ADJ_AMT) ADJ_AMT," ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       #if(${s_ar_if_yn} == 'N')" ).append("\n"); 
		query.append("         0 INV_CNTR," ).append("\n"); 
		query.append("         0 INV_AMT," ).append("\n"); 
		query.append("       #end" ).append("\n"); 
		query.append("       #if(${s_ar_if_yn} != 'N')" ).append("\n"); 
		query.append("          SUM(A.INV_CNTR) INV_CNTR," ).append("\n"); 
		query.append("          SUM(A.INV_AMT) INV_AMT," ).append("\n"); 
		query.append("       #end" ).append("\n"); 
		query.append("   " ).append("\n"); 
		query.append("       SUM(DECODE(A.PEN_SPC_AMT, NULL, DECODE(A.PEN_GEN_AMT, NULL, 0, 1), 1)) PEN_CNTR,     " ).append("\n"); 
		query.append("       SUM(DECODE(A.PEN_SPC_AMT, NULL, A.PEN_GEN_AMT, A.PEN_SPC_AMT))  PEN_AMT," ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       SUM(A.INV_CNTR2) INV_CNTR2" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("    SELECT E.CFM_OFC_CD  TRO_IB_CFM_OFC_CD" ).append("\n"); 
		query.append("           , SUBSTR(E.CNTR_RTN_YD_CD, 1, 5) LOC_CD" ).append("\n"); 
		query.append("           , E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("           , E.CURR_CD" ).append("\n"); 
		query.append("       " ).append("\n"); 
		query.append("         #if(${s_ar_if_yn} == 'A') " ).append("\n"); 
		query.append("          , (SELECT DECODE(NVL(G.DRP_OFF_CHG_TRF_SEQ, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) GEN_TRF_CNTR" ).append("\n"); 
		query.append("         #end" ).append("\n"); 
		query.append("         #if(${s_ar_if_yn} == 'Y') " ).append("\n"); 
		query.append("          , (SELECT DECODE(NVL(G.DRP_OFF_CHG_TRF_SEQ, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) GEN_TRF_CNTR" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("         #end" ).append("\n"); 
		query.append("         #if(${s_ar_if_yn} == 'N') " ).append("\n"); 
		query.append("          , (SELECT DECODE(NVL(G.DRP_OFF_CHG_TRF_SEQ, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) GEN_TRF_CNTR" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("         #end" ).append("\n"); 
		query.append("                         " ).append("\n"); 
		query.append("           , (SELECT CASE WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, G.GEN_TRF_AMT, 0) > 0 THEN " ).append("\n"); 
		query.append("			" ).append("\n"); 
		query.append("		    --G.GEN_TRF_AMT " ).append("\n"); 
		query.append("			-- Currency Convert" ).append("\n"); 
		query.append("			" ).append("\n"); 
		query.append("			#if(${s_curr_cd} == 'LOCAL')" ).append("\n"); 
		query.append("				ROUND( G.GEN_TRF_AMT,2 )" ).append("\n"); 
		query.append("			#else" ).append("\n"); 
		query.append("    	        ROUND( MNR_COMMON_PKG.MNR_CAL_CURR_RATE_FNC( TO_CHAR(G.TRO_IB_CFM_DT , 'YYYYMM') , G.CURR_CD, @[s_curr_cd] , G.GEN_TRF_AMT), 2 )" ).append("\n"); 
		query.append("			#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("             #if(${s_ar_if_yn} == 'A') " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("				 WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, G.GEN_TRF_AMT, 0) < 0 THEN 0" ).append("\n"); 
		query.append("                          ELSE 0" ).append("\n"); 
		query.append("                          END END" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) GEN_TRF_AMT" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("            #if(${s_ar_if_yn} == 'N') " ).append("\n"); 
		query.append("               WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, G.GEN_TRF_AMT, 0) < 0 THEN 0" ).append("\n"); 
		query.append("                          ELSE 0" ).append("\n"); 
		query.append("                          END END" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) GEN_TRF_AMT" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("           #if(${s_ar_if_yn} == 'Y') " ).append("\n"); 
		query.append("               WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, G.GEN_TRF_AMT, 0) < 0 THEN 0" ).append("\n"); 
		query.append("                          ELSE 0" ).append("\n"); 
		query.append("                          END END" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) GEN_TRF_AMT" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("                 " ).append("\n"); 
		query.append("         #if(${s_ar_if_yn} == 'A')            " ).append("\n"); 
		query.append("           , (SELECT DECODE(NVL(G.DRP_OFF_CHG_TRF_SPCL_SEQ, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) SPC_TRF_CNTR" ).append("\n"); 
		query.append("         #end" ).append("\n"); 
		query.append("         #if(${s_ar_if_yn} == 'N')" ).append("\n"); 
		query.append("          , (SELECT DECODE(NVL(G.DRP_OFF_CHG_TRF_SPCL_SEQ, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) SPC_TRF_CNTR" ).append("\n"); 
		query.append("         #end" ).append("\n"); 
		query.append("         #if(${s_ar_if_yn} == 'Y')" ).append("\n"); 
		query.append("          , (SELECT DECODE(NVL(G.DRP_OFF_CHG_TRF_SPCL_SEQ, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) SPC_TRF_CNTR" ).append("\n"); 
		query.append("         #end" ).append("\n"); 
		query.append("                                " ).append("\n"); 
		query.append("           , (SELECT CASE WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, 0, G.SPCL_TRF_AMT) > 0 THEN " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("			--G.SPCL_TRF_AMT" ).append("\n"); 
		query.append("			-- Currency Convert" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("			#if(${s_curr_cd} == 'LOCAL')" ).append("\n"); 
		query.append("				ROUND( G.SPCL_TRF_AMT,2 )" ).append("\n"); 
		query.append("			#else" ).append("\n"); 
		query.append("    	        ROUND( MNR_COMMON_PKG.MNR_CAL_CURR_RATE_FNC( TO_CHAR(G.TRO_IB_CFM_DT , 'YYYYMM') , G.CURR_CD, @[s_curr_cd] , G.SPCL_TRF_AMT), 2 )" ).append("\n"); 
		query.append("			#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("            #if(${s_ar_if_yn} == 'A') " ).append("\n"); 
		query.append("                   WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, 0, G.SPCL_TRF_AMT) < 0 THEN 0" ).append("\n"); 
		query.append("                          ELSE 0" ).append("\n"); 
		query.append("                          END END" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) SPC_TRF_AMT" ).append("\n"); 
		query.append("          #end" ).append("\n"); 
		query.append("          #if(${s_ar_if_yn} == 'N') " ).append("\n"); 
		query.append("                  WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, 0, G.SPCL_TRF_AMT) < 0 THEN 0" ).append("\n"); 
		query.append("                          ELSE 0" ).append("\n"); 
		query.append("                          END END" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) SPC_TRF_AMT" ).append("\n"); 
		query.append("          #end  " ).append("\n"); 
		query.append("          #if(${s_ar_if_yn} == 'Y') " ).append("\n"); 
		query.append("                  WHEN DECODE(G.DRP_OFF_CHG_TRF_SPCL_SEQ, NULL, 0, G.SPCL_TRF_AMT) < 0 THEN 0" ).append("\n"); 
		query.append("                          ELSE 0" ).append("\n"); 
		query.append("                          END END" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) SPC_TRF_AMT" ).append("\n"); 
		query.append("          #end " ).append("\n"); 
		query.append("                         " ).append("\n"); 
		query.append("          #if(${s_ar_if_yn} == 'A') " ).append("\n"); 
		query.append("            , (SELECT DECODE(NVL((-G.DC_AMT + G.SVC_FEE_AMT)*-1, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) ADJ_CNTR" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("           #if(${s_ar_if_yn} == 'N') " ).append("\n"); 
		query.append("             , (SELECT DECODE(NVL((-G.DC_AMT + G.SVC_FEE_AMT)*-1, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) ADJ_CNTR" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("           #if(${s_ar_if_yn} == 'Y') " ).append("\n"); 
		query.append("             , (SELECT DECODE(NVL((-G.DC_AMT + G.SVC_FEE_AMT)*-1, 0), 0, 0, 1)" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) ADJ_CNTR" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("			-- G.DC_AMT + SVC_FEE_AMT" ).append("\n"); 
		query.append("			-- Currency Convert" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("			#if(${s_curr_cd} == 'LOCAL')" ).append("\n"); 
		query.append("			, (SELECT  ROUND( (-G.DC_AMT + G.SVC_FEE_AMT)*-1 ,2 )" ).append("\n"); 
		query.append("			#else" ).append("\n"); 
		query.append("    	    , (SELECT  ROUND( MNR_COMMON_PKG.MNR_CAL_CURR_RATE_FNC( TO_CHAR(G.TRO_IB_CFM_DT , 'YYYYMM') , G.CURR_CD, @[s_curr_cd] , ROUND( (-G.DC_AMT + G.SVC_FEE_AMT)*-1 ,2 )), 2 )" ).append("\n"); 
		query.append("			#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("            #if(${s_ar_if_yn} == 'A') " ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) ADJ_AMT" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("            #if(${s_ar_if_yn} == 'N') " ).append("\n"); 
		query.append("               FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) ADJ_AMT" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("            #if(${s_ar_if_yn} == 'Y') " ).append("\n"); 
		query.append("               FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) ADJ_AMT" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("                 " ).append("\n"); 
		query.append("       #if(${s_ar_if_yn} == 'Y') " ).append("\n"); 
		query.append("        , (SELECT 1" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) INV_CNTR" ).append("\n"); 
		query.append("       #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       #if(${s_ar_if_yn} == 'A') " ).append("\n"); 
		query.append("        , (SELECT 1" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) INV_CNTR" ).append("\n"); 
		query.append("       #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("      , (SELECT 1" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO)) INV_CNTR2 " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       #if(${s_ar_if_yn} == 'N') " ).append("\n"); 
		query.append("        , (SELECT 1" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) INV_CNTR" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("           , (SELECT CASE WHEN G.TTL_AMT > 0 AND G.AR_IF_NO IS NOT NULL THEN" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("		   	    #if(${s_curr_cd} == 'LOCAL')" ).append("\n"); 
		query.append("				    ROUND( G.TTL_AMT ,2 )" ).append("\n"); 
		query.append("			    #else" ).append("\n"); 
		query.append("    	            ROUND( MNR_COMMON_PKG.MNR_CAL_CURR_RATE_FNC( TO_CHAR(G.TRO_IB_CFM_DT , 'YYYYMM') , G.CURR_CD, @[s_curr_cd] ,G.TTL_AMT), 2 )" ).append("\n"); 
		query.append("			    #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("              WHEN G.TTL_AMT < 0 THEN 0" ).append("\n"); 
		query.append("              ELSE 0" ).append("\n"); 
		query.append("              END END" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("             #if(${s_ar_if_yn} != 'N')" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) INV_AMT" ).append("\n"); 
		query.append("             #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("             #if(${s_ar_if_yn} == 'N')" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("               WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND G.AR_IF_NO IS NULL" ).append("\n"); 
		query.append("                 AND G.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                       WHERE C.BKG_NO = G.BKG_NO" ).append("\n"); 
		query.append("                         AND C.CNTR_NO = G.CNTR_NO) ) INV_AMT" ).append("\n"); 
		query.append("             #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("             ,( SELECT " ).append("\n"); 
		query.append("            #if(${s_curr_cd} == 'LOCAL')" ).append("\n"); 
		query.append("				ROUND( D.DRP_OFF_CHG_TRF_AMT ,2 )" ).append("\n"); 
		query.append("			#else" ).append("\n"); 
		query.append("    	        ROUND( MNR_COMMON_PKG.MNR_CAL_CURR_RATE_FNC( TO_CHAR(D.DRP_OFF_CHG_TRF_CFM_DT , 'YYYYMM') , D.CURR_CD, @[s_curr_cd] , D.DRP_OFF_CHG_TRF_AMT), 2 )" ).append("\n"); 
		query.append("			#end" ).append("\n"); 
		query.append("                  FROM DOD_DRP_OFF_CHG_TRF D" ).append("\n"); 
		query.append("                 WHERE 1 = 1" ).append("\n"); 
		query.append("                   AND DECODE(D.DEL_CD, NULL, '1', D.DEL_CD) = DECODE(D.DEL_CD, NULL, '1', B.POD_CD)" ).append("\n"); 
		query.append("                   AND D.CNTR_RTN_LOC_CD = SUBSTR(E.CNTR_RTN_YD_CD, 1, 5)" ).append("\n"); 
		query.append("                   AND DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', D.CNTR_RTN_YD_SFX_CD) = DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', SUBSTR(E.CNTR_RTN_YD_CD, 6, 2))" ).append("\n"); 
		query.append("                   AND D.POL_CONTI_CD = SUBSTR(B.ORG_SCONTI_CD, 1, 1)" ).append("\n"); 
		query.append("                   AND D.CNTR_TPSZ_CD = E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                   AND D.DRP_OFF_CHG_TRF_DIV_CD = 'S'" ).append("\n"); 
		query.append("                   AND D.DRP_OFF_CHG_TRF_CFM_FLG = 'Y'" ).append("\n"); 
		query.append("                   AND D.DRP_OFF_CHG_TRF_EXPT_FLG = 'N'" ).append("\n"); 
		query.append("                   AND B.POL_ETD_DT BETWEEN TO_DATE(D.DRP_OFF_CHG_TRF_EFF_DT, 'YYYYMMDD') + .0 AND TO_DATE(D.DRP_OFF_CHG_TRF_EXP_DT, 'YYYYMMDD') + .99999" ).append("\n"); 
		query.append("                   AND DECODE(D.SPCL_CUST_CNT_CD, NULL, '1', D.SPCL_CUST_CNT_CD) = DECODE(D.SPCL_CUST_CNT_CD, NULL, '1', B.AGMT_ACT_CNT_CD)" ).append("\n"); 
		query.append("                   AND DECODE(D.SPCL_CUST_SEQ, NULL, 1, D.SPCL_CUST_SEQ) = DECODE(D.SPCL_CUST_SEQ, NULL, 1, B.AGMT_ACT_CUST_SEQ)" ).append("\n"); 
		query.append("                   AND DECODE(D.SC_NO, NULL, D.RFA_NO, D.SC_NO) = DECODE(D.SC_NO, NULL, B.RFA_NO, B.SC_NO)" ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append("                   AND NVL(D.DEL_CD||D.CNTR_RTN_YD_SFX_CD, 1) = " ).append("\n"); 
		query.append("                     (SELECT NVL(MAX(D.DEL_CD)||MAX(D.CNTR_RTN_YD_SFX_CD), 1)" ).append("\n"); 
		query.append("                        FROM DOD_DRP_OFF_CHG_TRF D" ).append("\n"); 
		query.append("                         WHERE 1 = 1" ).append("\n"); 
		query.append("                           AND DECODE(D.DEL_CD, NULL, '1', D.DEL_CD) = DECODE(D.DEL_CD, NULL, '1', B.POD_CD)" ).append("\n"); 
		query.append("                           AND D.CNTR_RTN_LOC_CD = SUBSTR(E.CNTR_RTN_YD_CD, 1, 5)" ).append("\n"); 
		query.append("                           AND DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', D.CNTR_RTN_YD_SFX_CD) = DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', SUBSTR(E.CNTR_RTN_YD_CD, 6, 2))" ).append("\n"); 
		query.append("                           AND D.POL_CONTI_CD = SUBSTR(B.ORG_SCONTI_CD, 1, 1)" ).append("\n"); 
		query.append("                           AND D.CNTR_TPSZ_CD = E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                           AND D.DRP_OFF_CHG_TRF_DIV_CD = 'S'" ).append("\n"); 
		query.append("                           AND D.DRP_OFF_CHG_TRF_CFM_FLG = 'Y'" ).append("\n"); 
		query.append("                           AND D.DRP_OFF_CHG_TRF_EXPT_FLG = 'N'" ).append("\n"); 
		query.append("                           AND B.POL_ETD_DT BETWEEN TO_DATE(D.DRP_OFF_CHG_TRF_EFF_DT, 'YYYYMMDD') + .0 AND TO_DATE(D.DRP_OFF_CHG_TRF_EXP_DT, 'YYYYMMDD') + .99999" ).append("\n"); 
		query.append("                           AND DECODE(D.SPCL_CUST_CNT_CD, NULL, '1', D.SPCL_CUST_CNT_CD) = DECODE(D.SPCL_CUST_CNT_CD, NULL, '1', B.AGMT_ACT_CNT_CD)" ).append("\n"); 
		query.append("                           AND DECODE(D.SPCL_CUST_SEQ, NULL, 1, D.SPCL_CUST_SEQ) = DECODE(D.SPCL_CUST_SEQ, NULL, 1, B.AGMT_ACT_CUST_SEQ)" ).append("\n"); 
		query.append("                           AND DECODE(D.SC_NO, NULL, D.RFA_NO, D.SC_NO) = DECODE(D.SC_NO, NULL, B.RFA_NO, B.SC_NO)" ).append("\n"); 
		query.append("                           )" ).append("\n"); 
		query.append("                   " ).append("\n"); 
		query.append("                          AND NVL(D.SPCL_CUST_CNT_CD||D.SPCL_CUST_SEQ, 1) = " ).append("\n"); 
		query.append("                              (SELECT NVL(MAX(D.SPCL_CUST_CNT_CD||D.SPCL_CUST_SEQ), 1)" ).append("\n"); 
		query.append("                                FROM DOD_DRP_OFF_CHG_TRF D" ).append("\n"); 
		query.append("                               WHERE 1 = 1" ).append("\n"); 
		query.append("                                 AND DECODE(D.DEL_CD, NULL, '1', D.DEL_CD) = DECODE(D.DEL_CD, NULL, '1', B.POD_CD)" ).append("\n"); 
		query.append("                                 AND D.CNTR_RTN_LOC_CD = SUBSTR(E.CNTR_RTN_YD_CD, 1, 5)" ).append("\n"); 
		query.append("                                 AND DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', D.CNTR_RTN_YD_SFX_CD) = DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', SUBSTR(E.CNTR_RTN_YD_CD, 6, 2))" ).append("\n"); 
		query.append("                                 AND D.POL_CONTI_CD = SUBSTR(B.ORG_SCONTI_CD, 1, 1)" ).append("\n"); 
		query.append("                                 AND D.CNTR_TPSZ_CD = E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                                 AND D.DRP_OFF_CHG_TRF_DIV_CD = 'S'" ).append("\n"); 
		query.append("                                 AND D.DRP_OFF_CHG_TRF_CFM_FLG = 'Y'" ).append("\n"); 
		query.append("                                 AND D.DRP_OFF_CHG_TRF_EXPT_FLG = 'N'" ).append("\n"); 
		query.append("                                 AND B.POL_ETD_DT BETWEEN TO_DATE(D.DRP_OFF_CHG_TRF_EFF_DT, 'YYYYMMDD') + .0 AND TO_DATE(D.DRP_OFF_CHG_TRF_EXP_DT, 'YYYYMMDD') + .99999" ).append("\n"); 
		query.append("                                 AND DECODE(D.SPCL_CUST_CNT_CD, NULL, '1', D.SPCL_CUST_CNT_CD) = DECODE(D.SPCL_CUST_CNT_CD, NULL, '1', B.AGMT_ACT_CNT_CD)" ).append("\n"); 
		query.append("                                 AND DECODE(D.SPCL_CUST_SEQ, NULL, 1, D.SPCL_CUST_SEQ) = DECODE(D.SPCL_CUST_SEQ, NULL, 1, B.AGMT_ACT_CUST_SEQ)" ).append("\n"); 
		query.append("                                 AND DECODE(D.SC_NO, NULL, D.RFA_NO, D.SC_NO) = DECODE(D.SC_NO, NULL, B.RFA_NO, B.SC_NO)         " ).append("\n"); 
		query.append("                                 )   " ).append("\n"); 
		query.append("                           AND NOT EXISTS (SELECT 'OK'" ).append("\n"); 
		query.append("                                          FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("                                         WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                                           AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                                            )      " ).append("\n"); 
		query.append("            ) PEN_SPC_AMT" ).append("\n"); 
		query.append("            " ).append("\n"); 
		query.append("            ,( SELECT " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("			-- D.DRP_OFF_CHG_TRF_AMT " ).append("\n"); 
		query.append("			-- Currency Convert" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("			#if(${s_curr_cd} == 'LOCAL')" ).append("\n"); 
		query.append("				ROUND( D.DRP_OFF_CHG_TRF_AMT ,2 )" ).append("\n"); 
		query.append("			#else" ).append("\n"); 
		query.append("    	        ROUND( MNR_COMMON_PKG.MNR_CAL_CURR_RATE_FNC( TO_CHAR(D.DRP_OFF_CHG_TRF_CFM_DT , 'YYYYMM') , D.CURR_CD, @[s_curr_cd] , D.DRP_OFF_CHG_TRF_AMT), 2 )" ).append("\n"); 
		query.append("			#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG_TRF D" ).append("\n"); 
		query.append("               WHERE 1 = 1" ).append("\n"); 
		query.append("                 AND DECODE(D.DEL_CD, NULL, '1', D.DEL_CD) = DECODE(D.DEL_CD, NULL, '1', B.POD_CD)" ).append("\n"); 
		query.append("                 AND D.CNTR_RTN_LOC_CD = SUBSTR(E.CNTR_RTN_YD_CD, 1, 5)" ).append("\n"); 
		query.append("                 AND DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', D.CNTR_RTN_YD_SFX_CD) = DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', SUBSTR(E.CNTR_RTN_YD_CD, 6, 2))" ).append("\n"); 
		query.append("                 AND D.POL_CONTI_CD = SUBSTR(B.ORG_SCONTI_CD, 1, 1)" ).append("\n"); 
		query.append("                 AND D.CNTR_TPSZ_CD = E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                 AND D.DRP_OFF_CHG_TRF_DIV_CD = 'G'" ).append("\n"); 
		query.append("                 AND D.DRP_OFF_CHG_TRF_CFM_FLG = 'Y'" ).append("\n"); 
		query.append("                 AND D.DRP_OFF_CHG_TRF_EXPT_FLG = 'N'" ).append("\n"); 
		query.append("                 AND B.POL_ETD_DT BETWEEN TO_DATE(D.DRP_OFF_CHG_TRF_EFF_DT, 'YYYYMMDD') + .0 AND TO_DATE(D.DRP_OFF_CHG_TRF_EXP_DT, 'YYYYMMDD') + .99999" ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append("                  AND NVL(D.DEL_CD||D.CNTR_RTN_YD_SFX_CD, 1) = " ).append("\n"); 
		query.append("                       (SELECT NVL(MAX(D.DEL_CD)||MAX(D.CNTR_RTN_YD_SFX_CD), 1)" ).append("\n"); 
		query.append("                         FROM DOD_DRP_OFF_CHG_TRF D" ).append("\n"); 
		query.append("                            WHERE 1 = 1" ).append("\n"); 
		query.append("                         AND DECODE(D.DEL_CD, NULL, '1', D.DEL_CD) = DECODE(D.DEL_CD, NULL, '1', B.POD_CD)" ).append("\n"); 
		query.append("                              AND D.CNTR_RTN_LOC_CD = SUBSTR(E.CNTR_RTN_YD_CD, 1, 5)" ).append("\n"); 
		query.append("                              AND DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', D.CNTR_RTN_YD_SFX_CD) = DECODE(D.CNTR_RTN_YD_SFX_CD, NULL, '1', SUBSTR(E.CNTR_RTN_YD_CD, 6, 2))" ).append("\n"); 
		query.append("                              AND D.POL_CONTI_CD = SUBSTR(B.ORG_SCONTI_CD, 1, 1)" ).append("\n"); 
		query.append("                              AND D.CNTR_TPSZ_CD = E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("                              AND D.DRP_OFF_CHG_TRF_DIV_CD = 'G'" ).append("\n"); 
		query.append("                              AND D.DRP_OFF_CHG_TRF_CFM_FLG = 'Y'" ).append("\n"); 
		query.append("                              AND D.DRP_OFF_CHG_TRF_EXPT_FLG = 'N'" ).append("\n"); 
		query.append("                              AND B.POL_ETD_DT BETWEEN TO_DATE(D.DRP_OFF_CHG_TRF_EFF_DT, 'YYYYMMDD') + .0 AND TO_DATE(D.DRP_OFF_CHG_TRF_EXP_DT, 'YYYYMMDD') + .99999" ).append("\n"); 
		query.append("                         )" ).append("\n"); 
		query.append("                 AND NOT EXISTS (SELECT 'OK'" ).append("\n"); 
		query.append("                                    FROM DOD_DRP_OFF_CHG G" ).append("\n"); 
		query.append("                                   WHERE G.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                                     AND G.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                                 )     " ).append("\n"); 
		query.append("              ) PEN_GEN_AMT" ).append("\n"); 
		query.append("    FROM BKG_EUR_TRO E" ).append("\n"); 
		query.append("       , BKG_BOOKING B" ).append("\n"); 
		query.append("    WHERE 1=1" ).append("\n"); 
		query.append("     AND E.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("     AND E.IO_BND_CD = 'I'" ).append("\n"); 
		query.append("     AND E.HLG_TP_CD = 'M'" ).append("\n"); 
		query.append("     AND SUBSTR(E.CNTR_RTN_YD_CD, 1, 5) <> B.DEL_CD" ).append("\n"); 
		query.append("     AND E.CXL_FLG = 'N'" ).append("\n"); 
		query.append("     AND E.CFM_FLG = 'Y'" ).append("\n"); 
		query.append("     AND E.TRO_SEQ = (SELECT MAX(TT.TRO_SEQ)" ).append("\n"); 
		query.append("                               FROM BKG_EUR_TRO TT" ).append("\n"); 
		query.append("                              WHERE TT.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                                AND TT.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                                AND TT.IO_BND_CD = 'I') " ).append("\n"); 
		query.append(" " ).append("\n"); 
		query.append("       -- TRO DATE (DATE, MONTH, WEEK 별)" ).append("\n"); 
		query.append("	#if (${period} == 'W') " ).append("\n"); 
		query.append("		AND	E.CFM_DT	BETWEEN	( " ).append("\n"); 
		query.append("							SELECT TO_DATE(K.WK_ST_DT,'YYYYMMDD') + .0" ).append("\n"); 
		query.append("							FROM   EQR_WK_PRD K" ).append("\n"); 
		query.append("							WHERE  K.PLN_YR||K.PLN_WK = @[from]" ).append("\n"); 
		query.append("							)	" ).append("\n"); 
		query.append("			AND				( " ).append("\n"); 
		query.append("							 SELECT TO_DATE(K.WK_END_DT,'YYYYMMDD') + .99999" ).append("\n"); 
		query.append("							 FROM   EQR_WK_PRD K" ).append("\n"); 
		query.append("							 WHERE  K.PLN_YR||K.PLN_WK = @[to]" ).append("\n"); 
		query.append("							) " ).append("\n"); 
		query.append("	" ).append("\n"); 
		query.append("	#elseif (${period} == 'D' || ${period} == 'M') " ).append("\n"); 
		query.append("    	AND 	E.CFM_DT BETWEEN 	TO_DATE( @[from], 'YYYYMMDD') + .0 " ).append("\n"); 
		query.append("	  	AND 							TO_DATE( @[to], 'YYYYMMDD') + .99999" ).append("\n"); 
		query.append("	#end " ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  -- RETURN LOCATION 조건" ).append("\n"); 
		query.append("  #if(${s_rtn_loc} != '')" ).append("\n"); 
		query.append("  AND E.CNTR_RTN_YD_CD LIKE @[s_rtn_loc]||'%'" ).append("\n"); 
		query.append("  #end     " ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("  -- CNTR TYPE 조건" ).append("\n"); 
		query.append("	AND	SUBSTR(E.CNTR_TPSZ_CD,1,1)	IN (" ).append("\n"); 
		query.append("					#foreach( $cntr_tp in ${cntr_tp_list} )" ).append("\n"); 
		query.append("						#if ($cntr_tp == 'S')" ).append("\n"); 
		query.append("							'F', 'O', 'T', 'P', 'S', 'A'" ).append("\n"); 
		query.append("						#elseif ($cntr_tp == 'D' || $cntr_tp == 'R')" ).append("\n"); 
		query.append("							'$cntr_tp'" ).append("\n"); 
		query.append("						#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("						#if($velocityCount < $cntr_tp_list.size()) , #end" ).append("\n"); 
		query.append("					#end" ).append("\n"); 
		query.append("				)" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    -- AR I/F 조건" ).append("\n"); 
		query.append("   #if(${s_ar_if_yn} == 'Y')" ).append("\n"); 
		query.append("    AND EXISTS  (SELECT 'OK'" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG GG" ).append("\n"); 
		query.append("               WHERE GG.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                 AND GG.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("                 AND GG.AR_IF_NO IS NOT NULL" ).append("\n"); 
		query.append("                 AND GG.DRP_OFF_CHG_SEQ = (SELECT MAX(C.DRP_OFF_CHG_SEQ)" ).append("\n"); 
		query.append("                                             FROM DOD_DRP_OFF_CHG C" ).append("\n"); 
		query.append("                                            WHERE C.BKG_NO = GG.BKG_NO" ).append("\n"); 
		query.append("                                              AND C.CNTR_NO = GG.CNTR_NO)) " ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    -- INV CUST 조건" ).append("\n"); 
		query.append("  #if(${s_cust_cd} != '')" ).append("\n"); 
		query.append("    AND EXISTS (SELECT 'OK'" ).append("\n"); 
		query.append("                FROM DOD_DRP_OFF_CHG GG" ).append("\n"); 
		query.append("                WHERE GG.BKG_NO = E.BKG_NO" ).append("\n"); 
		query.append("                  AND GG.CNTR_NO = E.CNTR_NO" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    AND GG.CUST_CNT_CD || LPAD(GG.CUST_SEQ, 6, '0') = @[s_cust_cd]" ).append("\n"); 
		query.append("	)" ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("                 " ).append("\n"); 
		query.append("  -- DOD OFFICE" ).append("\n"); 
		query.append("  #if (${ofc_flg} == 'O')" ).append("\n"); 
		query.append("    AND   E.CFM_OFC_CD IN (" ).append("\n"); 
		query.append("        #foreach( $an_ofc in ${ofc_cd_list} )" ).append("\n"); 
		query.append("          #if($velocityCount < $ofc_cd_list.size()) '$an_ofc', #else '$an_ofc' #end" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("        )" ).append("\n"); 
		query.append("  #elseif (${ofc_flg} == 'R' && ${ofc_cd} != 'All')" ).append("\n"); 
		query.append("    AND @[ofc_cd] = (SELECT DISTINCT OFC_CD " ).append("\n"); 
		query.append("					 FROM MDM_ORGANIZATION" ).append("\n"); 
		query.append("					 WHERE 1 = 1" ).append("\n"); 
		query.append("						 AND OFC_KND_CD = '2'" ).append("\n"); 
		query.append("						 AND PRNT_OFC_CD = 'SELDC'" ).append("\n"); 
		query.append("						 START WITH OFC_CD = E.CFM_OFC_CD " ).append("\n"); 
		query.append("						 CONNECT BY PRIOR PRNT_OFC_CD = OFC_CD)" ).append("\n"); 
		query.append(" " ).append("\n"); 
		query.append("  #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("GROUP BY A.TRO_IB_CFM_OFC_CD, A.LOC_CD, A.CNTR_TPSZ_CD, A.CURR_CD" ).append("\n"); 
		query.append(") A" ).append("\n"); 
		query.append("#if(${s_ar_if_yn} == 'N')" ).append("\n"); 
		query.append("WHERE PEN_CNTR > 0" ).append("\n"); 
		query.append(" OR GEN_TRF_CNTR > 0" ).append("\n"); 
		query.append(" OR SPC_TRF_CNTR > 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if(${s_ar_if_yn} == 'A')" ).append("\n"); 
		query.append("WHERE PEN_CNTR > 0" ).append("\n"); 
		query.append(" OR GEN_TRF_CNTR > 0" ).append("\n"); 
		query.append(" OR SPC_TRF_CNTR > 0" ).append("\n"); 
		query.append(" OR INV_CNTR2 > 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 

	}
}