/*=========================================================
*Copyright(c) 2011 CyberLogitec
*@FileName : JOStatusInquiryDBDAOSearchProcessListRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2011.09.23
*@LastModifier : 박찬민
*@LastVersion : 1.0
* 2011.09.23 박찬민
* 1.0 Creation
=========================================================*/
package com.clt.apps.opus.esd.tpb.jocasemanage.jostatusinquiry.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.clt.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class JOStatusInquiryDBDAOSearchProcessListRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * JO TPB -> JO TPB Process Inquiry
	  * </pre>
	  */
	public JOStatusInquiryDBDAOSearchProcessListRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_cd_value",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_if_ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_ofc_cd_for_rhq",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_edate",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_if_rhq_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("s_sdate",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.esd.tpb.jocasemanage.jostatusinquiry.integration").append("\n"); 
		query.append("FileName : JOStatusInquiryDBDAOSearchProcessListRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("WITH TES AS" ).append("\n"); 
		query.append("(" ).append("\n"); 
		query.append("SELECT H.COST_OFC_CD" ).append("\n"); 
		query.append(",A.CSR_NO" ).append("\n"); 
		query.append(",H.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",H.INV_NO" ).append("\n"); 
		query.append(",D.LGS_COST_CD" ).append("\n"); 
		query.append(",H.CURR_CD" ).append("\n"); 
		query.append(",D.INV_AMT" ).append("\n"); 
		query.append(",D.TML_CRR_CD" ).append("\n"); 
		query.append(",D.CALC_RMK" ).append("\n"); 
		query.append(",(CASE WHEN D.INV_AMT>0 THEN 'Y' ELSE 'N' END) IF_TPB_FLG   --'Y'case Only TPB I/F; Only Plus JO (with TPB I/F)" ).append("\n"); 
		query.append(",D.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append(",D.TML_SO_SEQ" ).append("\n"); 
		query.append(",D.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("FROM TES_TML_SO_HDR H" ).append("\n"); 
		query.append(",TES_TML_SO_DTL D" ).append("\n"); 
		query.append(",AP_INV_HDR A" ).append("\n"); 
		query.append("WHERE D.TML_SO_OFC_CTY_CD=H.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND D.TML_SO_SEQ=H.TML_SO_SEQ" ).append("\n"); 
		query.append("AND D.LGS_COST_CD='SVXXJO'" ).append("\n"); 
		query.append("AND A.CSR_NO=H.CSR_NO" ).append("\n"); 
		query.append("AND NVL(H.DELT_FLG,'N')='N'" ).append("\n"); 
		query.append("/* 화면 조건 */" ).append("\n"); 
		query.append("AND A.GL_DT >= TO_CHAR(TPB_GET_SRCH_DATE_FNC(@[s_sdate],'YYYY-MM-DD',@[s_ofc_cd_for_rhq]),'YYYYMMDD')" ).append("\n"); 
		query.append("AND A.GL_DT < TO_CHAR(TPB_GET_SRCH_DATE_FNC(@[s_edate],'YYYY-MM-DD',@[s_ofc_cd_for_rhq]) + 1,'YYYYMMDD')" ).append("\n"); 
		query.append("AND H.COST_OFC_CD IN (" ).append("\n"); 
		query.append("SELECT OFC_CD" ).append("\n"); 
		query.append("FROM TPB_HNDL_OFC" ).append("\n"); 
		query.append("WHERE N3PTY_OFC_TP_CD = 'G'" ).append("\n"); 
		query.append("AND DELT_FLG = 'N'" ).append("\n"); 
		query.append("AND N3PTY_OFC_CD IN (" ).append("\n"); 
		query.append("SELECT OFC_CD" ).append("\n"); 
		query.append("FROM TPB_HNDL_OFC" ).append("\n"); 
		query.append("WHERE DELT_FLG = 'N'" ).append("\n"); 
		query.append("#if (${s_if_rhq_cd} != '')" ).append("\n"); 
		query.append("AND RHQ_CD = @[s_if_rhq_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${s_if_ofc_cd} != '')" ).append("\n"); 
		query.append("AND OFC_CD = @[s_if_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${s_cd_kind} == 'C' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND A.CSR_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#elseif (${s_cd_kind} == 'S' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND H.INV_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[H Inquiry case] PLUS JO (TPB Only)" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("SELECT H.COST_OFC_CD" ).append("\n"); 
		query.append(",A.CSR_NO" ).append("\n"); 
		query.append(",H.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",H.INV_NO" ).append("\n"); 
		query.append(",D.LGS_COST_CD" ).append("\n"); 
		query.append(",H.CURR_CD" ).append("\n"); 
		query.append(",D.INV_AMT" ).append("\n"); 
		query.append(",D.TML_CRR_CD" ).append("\n"); 
		query.append(",D.CALC_RMK" ).append("\n"); 
		query.append(",(CASE WHEN D.INV_AMT > 0 THEN 'Y' ELSE 'N' END) IF_TPB_FLG   --'Y'case Only TPB I/F; Only Plus JO (with TPB I/F)" ).append("\n"); 
		query.append(",D.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append(",D.TML_SO_SEQ" ).append("\n"); 
		query.append(",D.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("FROM TES_TML_SO_HDR H" ).append("\n"); 
		query.append(",TES_TML_SO_DTL D" ).append("\n"); 
		query.append(",AP_INV_HDR A" ).append("\n"); 
		query.append(",TPB_OTS_DTL TD" ).append("\n"); 
		query.append("WHERE D.TML_SO_OFC_CTY_CD = H.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND D.TML_SO_SEQ = H.TML_SO_SEQ" ).append("\n"); 
		query.append("AND D.LGS_COST_CD = 'SVXXJO'" ).append("\n"); 
		query.append("AND A.CSR_NO = H.CSR_NO" ).append("\n"); 
		query.append("AND H.INV_NO = TD.N3PTY_SRC_NO" ).append("\n"); 
		query.append("AND NVL(H.DELT_FLG,'N')='N'" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("/* 화면 조건 */" ).append("\n"); 
		query.append("AND A.GL_DT >= TO_CHAR(TPB_GET_SRCH_DATE_FNC(@[s_sdate],'YYYY-MM-DD',@[s_ofc_cd_for_rhq]),'YYYYMMDD')" ).append("\n"); 
		query.append("AND A.GL_DT < TO_CHAR(TPB_GET_SRCH_DATE_FNC(@[s_edate],'YYYY-MM-DD',@[s_ofc_cd_for_rhq]) + 1,'YYYYMMDD')" ).append("\n"); 
		query.append("AND H.COST_OFC_CD IN (" ).append("\n"); 
		query.append("SELECT OFC_CD" ).append("\n"); 
		query.append("FROM TPB_HNDL_OFC" ).append("\n"); 
		query.append("WHERE N3PTY_OFC_TP_CD = 'G'" ).append("\n"); 
		query.append("AND DELT_FLG = 'N'" ).append("\n"); 
		query.append("AND N3PTY_OFC_CD IN (" ).append("\n"); 
		query.append("SELECT OFC_CD" ).append("\n"); 
		query.append("FROM TPB_HNDL_OFC" ).append("\n"); 
		query.append("WHERE DELT_FLG = 'N'" ).append("\n"); 
		query.append("#if (${s_if_rhq_cd} != '')" ).append("\n"); 
		query.append("AND RHQ_CD = @[s_if_rhq_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("#if (${s_if_ofc_cd} != '')" ).append("\n"); 
		query.append("AND OFC_CD = @[s_if_ofc_cd]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if (${s_cd_kind} == 'C' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND TD.CSR_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#elseif (${s_cd_kind} == 'S' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND H.INV_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[J Inquiry case] PLUS JO (=TES Only)" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",TES.CURR_CD" ).append("\n"); 
		query.append(",TES.INV_AMT" ).append("\n"); 
		query.append(",TES.TML_CRR_CD" ).append("\n"); 
		query.append(",TES.CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL OTS_STS_NM" ).append("\n"); 
		query.append(",NULL N3PTY_NO" ).append("\n"); 
		query.append(",NULL N3PTY_INV_NO" ).append("\n"); 
		query.append(",NULL TRD_PARTY_CODE" ).append("\n"); 
		query.append(",NULL TRD_PARTY_NAME" ).append("\n"); 
		query.append(",NULL IF_CURR_CD" ).append("\n"); 
		query.append(",NULL IF_AMT" ).append("\n"); 
		query.append(",NULL CFM_AMT" ).append("\n"); 
		query.append(",NULL INV_AMT1" ).append("\n"); 
		query.append(",NULL INV_IF_DT" ).append("\n"); 
		query.append(",NULL CRE_USR_ID" ).append("\n"); 
		query.append(",NULL INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(NULL) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",NULL CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL GL_EFF_DT" ).append("\n"); 
		query.append(",NULL INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",NULL AR_CURR_CD" ).append("\n"); 
		query.append(",NULL CHG_AMT" ).append("\n"); 
		query.append(",NULL AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'J'  DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TES_N3RD_PTY_IF T" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG='Y'" ).append("\n"); 
		query.append("/*TPB 조건 */" ).append("\n"); 
		query.append("AND T.TML_SO_OFC_CTY_CD = TES.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND T.TML_SO_SEQ = TES.TML_SO_SEQ" ).append("\n"); 
		query.append("AND T.TML_SO_DTL_SEQ = TES.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("AND NOT EXISTS (" ).append("\n"); 
		query.append("SELECT 'X'" ).append("\n"); 
		query.append("FROM TPB_OTS_DTL OTPB" ).append("\n"); 
		query.append("WHERE OTPB.CSR_NO = T.CSR_NO" ).append("\n"); 
		query.append("AND OTPB.IF_OFC_CD = T.TML_IF_OFC_CD" ).append("\n"); 
		query.append("AND OTPB.SRC_IF_SEQ_NO = T.TML_IF_SEQ" ).append("\n"); 
		query.append("AND OTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[I Inquiry case New CSR NOT Interfaced] = [H Inquiry case](=New CSR TES Only)  (+)  [TPB(+) + INV(+)](=Old CSR TPB Only)" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",TES.CURR_CD" ).append("\n"); 
		query.append(",TES.INV_AMT" ).append("\n"); 
		query.append(",TES.TML_CRR_CD" ).append("\n"); 
		query.append(",TES.CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",COMMCODE_PKG.GET_COMDTL_NAME_FNC('CD00588', NVL(OTPC.OTS_STS_CD,'Z'))" ).append("\n"); 
		query.append("AS OTS_STS_NM" ).append("\n"); 
		query.append(",CTPB.N3PTY_NO" ).append("\n"); 
		query.append(",OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN LPAD(TO_CHAR(CTPB.VNDR_SEQ), 6, '0') WHEN 'C' THEN CTPB.CUST_CNT_CD||LPAD(CTPB.CUST_SEQ, 6, '0') WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_CODE" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN CTPB.VNDR_LGL_ENG_NM WHEN 'C' THEN CTPB.CUST_LGL_ENG_NM WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_NAME" ).append("\n"); 
		query.append(",CTPB.IF_CURR_CD" ).append("\n"); 
		query.append(",CTPB.IF_AMT" ).append("\n"); 
		query.append(",CTPB.CFM_AMT" ).append("\n"); 
		query.append(",CTPB.INV_AMT  AS INV_AMT1" ).append("\n"); 
		query.append(",OTPS.INV_IF_DT" ).append("\n"); 
		query.append(",OTPS.CRE_USR_ID" ).append("\n"); 
		query.append(",OTPS.INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(CTPB.N3PTY_NO) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",CTPB.CSR_NO CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL GL_EFF_DT" ).append("\n"); 
		query.append(",NULL INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",NULL AR_CURR_CD" ).append("\n"); 
		query.append(",NULL CHG_AMT" ).append("\n"); 
		query.append(",NULL AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'I'  DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TPB_OTS_DTL CTPB" ).append("\n"); 
		query.append(",TPB_OTS_GRP OTPG" ).append("\n"); 
		query.append(",TPB_OTS_GRP_STS OTPC" ).append("\n"); 
		query.append(",TPB_INV_IF_SMRY OTPS" ).append("\n"); 
		query.append("WHERE CTPB.N3PTY_SRC_NO = TES.INV_NO" ).append("\n"); 
		query.append("AND CTPB.CSR_NO <> TES.CSR_NO" ).append("\n"); 
		query.append("AND CTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND NOT EXISTS (" ).append("\n"); 
		query.append("SELECT 'X'" ).append("\n"); 
		query.append("FROM TPB_OTS_DTL D" ).append("\n"); 
		query.append("WHERE D.CSR_NO = TES.CSR_NO" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND OTPG.N3PTY_NO(+) = CTPB.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.N3PTY_NO(+) = OTPG.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.OTS_STS_LST_FLG(+) = 'Y'" ).append("\n"); 
		query.append("AND OTPG.N3PTY_INV_NO(+) IS NOT NULL" ).append("\n"); 
		query.append("AND OTPS.IF_BL_NO(+) = OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[G Inquiry case] MINUS JO" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",TES.CURR_CD" ).append("\n"); 
		query.append(",TES.INV_AMT" ).append("\n"); 
		query.append(",TES.TML_CRR_CD" ).append("\n"); 
		query.append(",TES.CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL OTS_STS_NM" ).append("\n"); 
		query.append(",NULL N3PTY_NO" ).append("\n"); 
		query.append(",NULL N3PTY_INV_NO" ).append("\n"); 
		query.append(",NULL TRD_PARTY_CODE" ).append("\n"); 
		query.append(",NULL TRD_PARTY_NAME" ).append("\n"); 
		query.append(",NULL IF_CURR_CD" ).append("\n"); 
		query.append(",NULL IF_AMT" ).append("\n"); 
		query.append(",NULL CFM_AMT" ).append("\n"); 
		query.append(",NULL INV_AMT1" ).append("\n"); 
		query.append(",NULL INV_IF_DT" ).append("\n"); 
		query.append(",NULL CRE_USR_ID" ).append("\n"); 
		query.append(",NULL INV_IF_OFC_CD" ).append("\n"); 
		query.append(",NULL CLT_ACT_YN" ).append("\n"); 
		query.append(",NULL CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL GL_EFF_DT" ).append("\n"); 
		query.append(",NULL INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",NULL AR_CURR_CD" ).append("\n"); 
		query.append(",NULL CHG_AMT" ).append("\n"); 
		query.append(",NULL AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'G' DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG = 'N'" ).append("\n"); 
		query.append("#if ((${s_cd_kind} == 'T' || ${s_cd_kind} == 'I') && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND 1 = 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[F Inquiry case] PLUS JO + CANDIDATE TPB" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",TES.CURR_CD" ).append("\n"); 
		query.append(",TES.INV_AMT" ).append("\n"); 
		query.append(",TES.TML_CRR_CD" ).append("\n"); 
		query.append(",TES.CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("--,NULL OTS_STS_NM" ).append("\n"); 
		query.append(",COMMCODE_PKG.GET_COMDTL_NAME_FNC('CD00588','Z') OTS_STS_NM" ).append("\n"); 
		query.append(",OTPB.N3PTY_NO" ).append("\n"); 
		query.append(",NULL N3PTY_INV_NO" ).append("\n"); 
		query.append(",CASE OTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN LPAD(TO_CHAR(OTPB.VNDR_SEQ), 6, '0') WHEN 'C' THEN OTPB.CUST_CNT_CD||LPAD(OTPB.CUST_SEQ, 6, '0') WHEN 'S' THEN OTPB.N3PTY_OFC_CD END AS TRD_PARTY_CODE" ).append("\n"); 
		query.append(",CASE OTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN OTPB.VNDR_LGL_ENG_NM WHEN 'C' THEN OTPB.CUST_LGL_ENG_NM WHEN 'S' THEN OTPB.N3PTY_OFC_CD END AS TRD_PARTY_NAME" ).append("\n"); 
		query.append(",OTPB.IF_CURR_CD" ).append("\n"); 
		query.append(",OTPB.IF_AMT" ).append("\n"); 
		query.append(",OTPB.CFM_AMT" ).append("\n"); 
		query.append(",OTPB.INV_AMT  AS INV_AMT1" ).append("\n"); 
		query.append(",NULL INV_IF_DT" ).append("\n"); 
		query.append(",NULL CRE_USR_ID" ).append("\n"); 
		query.append(",NULL INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(OTPB.N3PTY_NO) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",NULL CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL GL_EFF_DT" ).append("\n"); 
		query.append(",NULL INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",NULL AR_CURR_CD" ).append("\n"); 
		query.append(",NULL CHG_AMT" ).append("\n"); 
		query.append(",NULL AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'F'  DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TES_N3RD_PTY_IF T" ).append("\n"); 
		query.append(",TPB_OTS_DTL OTPB" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG = 'Y'" ).append("\n"); 
		query.append("/*TPB 조건 */" ).append("\n"); 
		query.append("AND T.TML_SO_OFC_CTY_CD = TES.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND T.TML_SO_SEQ = TES.TML_SO_SEQ" ).append("\n"); 
		query.append("AND T.TML_SO_DTL_SEQ = TES.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("AND OTPB.CSR_NO = T.CSR_NO" ).append("\n"); 
		query.append("AND OTPB.IF_OFC_CD = T.TML_IF_OFC_CD" ).append("\n"); 
		query.append("AND OTPB.SRC_IF_SEQ_NO = T.TML_IF_SEQ" ).append("\n"); 
		query.append("AND OTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND OTPB.N3PTY_NO IS NULL" ).append("\n"); 
		query.append("#if ((${s_cd_kind} == 'T' || ${s_cd_kind} == 'I') && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND 1 = 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[E Inquiry case] PLUS JO + TPB + NON-INV" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",TES.CURR_CD" ).append("\n"); 
		query.append(",TES.INV_AMT" ).append("\n"); 
		query.append(",TES.TML_CRR_CD" ).append("\n"); 
		query.append(",TES.CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",COMMCODE_PKG.GET_COMDTL_NAME_FNC('CD00588', OTPC.OTS_STS_CD) AS OTS_STS_NM" ).append("\n"); 
		query.append(",OTPB.N3PTY_NO" ).append("\n"); 
		query.append(",OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append(",CASE OTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN LPAD(TO_CHAR(OTPB.VNDR_SEQ), 6, '0') WHEN 'C' THEN OTPB.CUST_CNT_CD||LPAD(OTPB.CUST_SEQ, 6, '0') WHEN 'S' THEN OTPB.N3PTY_OFC_CD END AS TRD_PARTY_CODE" ).append("\n"); 
		query.append(",CASE OTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN OTPB.VNDR_LGL_ENG_NM WHEN 'C' THEN OTPB.CUST_LGL_ENG_NM WHEN 'S' THEN OTPB.N3PTY_OFC_CD END AS TRD_PARTY_NAME" ).append("\n"); 
		query.append(",OTPB.IF_CURR_CD" ).append("\n"); 
		query.append(",OTPB.IF_AMT" ).append("\n"); 
		query.append(",OTPB.CFM_AMT" ).append("\n"); 
		query.append(",OTPB.INV_AMT  AS INV_AMT1" ).append("\n"); 
		query.append(",NULL INV_IF_DT" ).append("\n"); 
		query.append(",NULL CRE_USR_ID" ).append("\n"); 
		query.append(",NULL INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(OTPB.N3PTY_NO) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",NULL CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL GL_EFF_DT" ).append("\n"); 
		query.append(",NULL INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",NULL AR_CURR_CD" ).append("\n"); 
		query.append(",NULL CHG_AMT" ).append("\n"); 
		query.append(",NULL AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'E'  DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TES_N3RD_PTY_IF T" ).append("\n"); 
		query.append(",TPB_OTS_DTL OTPB" ).append("\n"); 
		query.append(",TPB_OTS_GRP OTPG" ).append("\n"); 
		query.append(",TPB_OTS_GRP_STS OTPC" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG='Y'" ).append("\n"); 
		query.append("/*TPB 조건 */" ).append("\n"); 
		query.append("AND T.TML_SO_OFC_CTY_CD = TES.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND T.TML_SO_SEQ = TES.TML_SO_SEQ" ).append("\n"); 
		query.append("AND T.TML_SO_DTL_SEQ = TES.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("AND OTPB.CSR_NO = T.CSR_NO" ).append("\n"); 
		query.append("AND OTPB.IF_OFC_CD = T.TML_IF_OFC_CD" ).append("\n"); 
		query.append("AND OTPB.SRC_IF_SEQ_NO = T.TML_IF_SEQ" ).append("\n"); 
		query.append("AND OTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND OTPB.N3PTY_NO IS NOT NULL" ).append("\n"); 
		query.append("AND OTPG.N3PTY_NO = OTPB.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.N3PTY_NO = OTPG.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.OTS_STS_LST_FLG = 'Y'" ).append("\n"); 
		query.append("AND OTPG.N3PTY_INV_NO IS NULL" ).append("\n"); 
		query.append("/* 화면 조건 */" ).append("\n"); 
		query.append("#if (${s_cd_kind} == 'T' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND OTPB.N3PTY_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#elseif (${s_cd_kind} == 'I' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND 1 = 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[D Inquiry case] PLUS JO + TPB + INV" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",TES.CURR_CD" ).append("\n"); 
		query.append(",TES.INV_AMT" ).append("\n"); 
		query.append(",TES.TML_CRR_CD" ).append("\n"); 
		query.append(",TES.CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",COMMCODE_PKG.GET_COMDTL_NAME_FNC('CD00588', OTPC.OTS_STS_CD) AS OTS_STS_NM" ).append("\n"); 
		query.append(",OTPB.N3PTY_NO" ).append("\n"); 
		query.append(",OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append(",CASE OTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN LPAD(TO_CHAR(OTPB.VNDR_SEQ), 6, '0') WHEN 'C' THEN OTPB.CUST_CNT_CD||LPAD(OTPB.CUST_SEQ, 6, '0') WHEN 'S' THEN OTPB.N3PTY_OFC_CD END AS TRD_PARTY_CODE" ).append("\n"); 
		query.append(",CASE OTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN OTPB.VNDR_LGL_ENG_NM WHEN 'C' THEN OTPB.CUST_LGL_ENG_NM WHEN 'S' THEN OTPB.N3PTY_OFC_CD END AS TRD_PARTY_NAME" ).append("\n"); 
		query.append(",OTPB.IF_CURR_CD" ).append("\n"); 
		query.append(",OTPB.IF_AMT" ).append("\n"); 
		query.append(",OTPB.CFM_AMT" ).append("\n"); 
		query.append(",OTPB.INV_AMT AS INV_AMT1" ).append("\n"); 
		query.append(",OTPS.INV_IF_DT" ).append("\n"); 
		query.append(",OTPS.CRE_USR_ID" ).append("\n"); 
		query.append(",OTPS.INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(OTPB.N3PTY_NO) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",NULL CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",BB.GL_EFF_DT" ).append("\n"); 
		query.append(",DD.INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",CC.CURR_CD AS AR_CURR_CD" ).append("\n"); 
		query.append(",CC.CHG_AMT" ).append("\n"); 
		query.append(",BB.AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'D' DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TES_N3RD_PTY_IF T" ).append("\n"); 
		query.append(",TPB_OTS_DTL OTPB" ).append("\n"); 
		query.append(",TPB_OTS_GRP OTPG" ).append("\n"); 
		query.append(",TPB_OTS_GRP_STS OTPC" ).append("\n"); 
		query.append(",TPB_INV_IF_SMRY OTPS" ).append("\n"); 
		query.append(",INV_AR_IF_MN AA" ).append("\n"); 
		query.append(",INV_AR_MN BB" ).append("\n"); 
		query.append(",INV_AR_CHG CC" ).append("\n"); 
		query.append(",INV_AR_AMT DD" ).append("\n"); 
		query.append(",INV_AR_IF_CHG EE" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG = 'Y'" ).append("\n"); 
		query.append("AND T.TML_SO_OFC_CTY_CD = TES.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND T.TML_SO_SEQ = TES.TML_SO_SEQ" ).append("\n"); 
		query.append("AND T.TML_SO_DTL_SEQ = TES.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("AND OTPB.CSR_NO = T.CSR_NO" ).append("\n"); 
		query.append("AND OTPB.IF_OFC_CD = T.TML_IF_OFC_CD" ).append("\n"); 
		query.append("AND OTPB.SRC_IF_SEQ_NO = T.TML_IF_SEQ" ).append("\n"); 
		query.append("AND OTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND OTPB.N3PTY_NO IS NOT NULL" ).append("\n"); 
		query.append("AND OTPG.N3PTY_NO = OTPB.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.N3PTY_NO = OTPG.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.OTS_STS_LST_FLG = 'Y'" ).append("\n"); 
		query.append("AND OTPG.N3PTY_INV_NO IS NOT NULL" ).append("\n"); 
		query.append("AND OTPS.IF_BL_NO = OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append("/* 화면 조건 */" ).append("\n"); 
		query.append("#if (${s_cd_kind} == 'T' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND OTPB.N3PTY_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#elseif (${s_cd_kind} == 'I' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND OTPG.N3PTY_INV_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("/*AR 조건 */" ).append("\n"); 
		query.append("AND AA.IF_SRC_CD = 'TPB'" ).append("\n"); 
		query.append("AND AA.BL_SRC_NO = OTPS.IF_BL_NO" ).append("\n"); 
		query.append("AND AA.INV_SRC_NO = OTPS.N3PTY_INV_NO" ).append("\n"); 
		query.append("AND BB.AR_IF_NO = AA.AR_IF_NO" ).append("\n"); 
		query.append("AND CC.AR_IF_NO = BB.AR_IF_NO" ).append("\n"); 
		query.append("AND DD.AR_IF_NO = BB.AR_IF_NO" ).append("\n"); 
		query.append("AND EE.SRC_IF_DT = AA.SRC_IF_DT" ).append("\n"); 
		query.append("AND EE.SRC_IF_SEQ = AA.SRC_IF_SEQ" ).append("\n"); 
		query.append("AND CC.CHG_SEQ = EE.CHG_SEQ" ).append("\n"); 
		query.append("AND CC.AR_IF_SER_NO = DD.AR_IF_SER_NO" ).append("\n"); 
		query.append("AND CC.CHG_AMT = OTPB.IF_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[C Inquiry case] PLUS JO + TPB + INV" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",NULL CURR_CD" ).append("\n"); 
		query.append(",NULL INV_AMT" ).append("\n"); 
		query.append(",NULL TML_CRR_CD" ).append("\n"); 
		query.append(",NULL CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",COMMCODE_PKG.GET_COMDTL_NAME_FNC('CD00588', OTPC.OTS_STS_CD) AS OTS_STS_NM" ).append("\n"); 
		query.append(",CTPB.N3PTY_NO" ).append("\n"); 
		query.append(",OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN LPAD(TO_CHAR(CTPB.VNDR_SEQ), 6, '0') WHEN 'C' THEN CTPB.CUST_CNT_CD||LPAD(CTPB.CUST_SEQ, 6, '0') WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_CODE" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN CTPB.VNDR_LGL_ENG_NM WHEN 'C' THEN CTPB.CUST_LGL_ENG_NM WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_NAME" ).append("\n"); 
		query.append(",CTPB.IF_CURR_CD" ).append("\n"); 
		query.append(",CTPB.IF_AMT" ).append("\n"); 
		query.append(",CTPB.CFM_AMT" ).append("\n"); 
		query.append(",CTPB.INV_AMT  AS INV_AMT1" ).append("\n"); 
		query.append(",OTPS.INV_IF_DT" ).append("\n"); 
		query.append(",OTPS.CRE_USR_ID" ).append("\n"); 
		query.append(",OTPS.INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(CTPB.N3PTY_NO) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",CTPB.CSR_NO CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",BB.GL_EFF_DT" ).append("\n"); 
		query.append(",DD.INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",CC.CURR_CD AS AR_CURR_CD" ).append("\n"); 
		query.append(",CC.CHG_AMT" ).append("\n"); 
		query.append(",BB.AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'C'  DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TES_N3RD_PTY_IF T" ).append("\n"); 
		query.append(",TPB_OTS_DTL OTPB" ).append("\n"); 
		query.append(",TPB_OTS_DTL CTPB" ).append("\n"); 
		query.append(",TPB_OTS_GRP OTPG" ).append("\n"); 
		query.append(",TPB_OTS_GRP_STS OTPC" ).append("\n"); 
		query.append(",TPB_INV_IF_SMRY OTPS" ).append("\n"); 
		query.append(",INV_AR_IF_MN AA" ).append("\n"); 
		query.append(",INV_AR_MN BB" ).append("\n"); 
		query.append(",INV_AR_CHG CC" ).append("\n"); 
		query.append(",INV_AR_AMT DD" ).append("\n"); 
		query.append(",INV_AR_IF_CHG EE" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG = 'Y'" ).append("\n"); 
		query.append("AND T.TML_SO_OFC_CTY_CD = TES.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND T.TML_SO_SEQ = TES.TML_SO_SEQ" ).append("\n"); 
		query.append("AND T.TML_SO_DTL_SEQ = TES.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("AND OTPB.CSR_NO = T.CSR_NO" ).append("\n"); 
		query.append("AND OTPB.IF_OFC_CD = T.TML_IF_OFC_CD" ).append("\n"); 
		query.append("AND OTPB.SRC_IF_SEQ_NO = T.TML_IF_SEQ" ).append("\n"); 
		query.append("AND OTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND OTPB.OTS_DTL_SEQ IN (" ).append("\n"); 
		query.append("SELECT MIN(OTS_DTL_SEQ)" ).append("\n"); 
		query.append("FROM TPB_OTS_DTL O" ).append("\n"); 
		query.append("WHERE O.CSR_NO=T.CSR_NO" ).append("\n"); 
		query.append("GROUP BY N3PTY_SRC_NO" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND CTPB.N3PTY_SRC_NO = OTPB.N3PTY_SRC_NO" ).append("\n"); 
		query.append("AND CTPB.CSR_NO <> OTPB.CSR_NO" ).append("\n"); 
		query.append("AND CTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND CTPB.N3PTY_NO IS NOT NULL" ).append("\n"); 
		query.append("AND OTPG.N3PTY_NO = CTPB.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.N3PTY_NO = OTPG.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.OTS_STS_LST_FLG = 'Y'" ).append("\n"); 
		query.append("AND OTPG.N3PTY_INV_NO IS NOT NULL" ).append("\n"); 
		query.append("AND OTPS.IF_BL_NO = OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append("/* 화면 조건 */" ).append("\n"); 
		query.append("#if (${s_cd_kind} == 'T' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND CTPB.N3PTY_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#elseif (${s_cd_kind} == 'I' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND OTPG.N3PTY_INV_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("/*AR 조건 */" ).append("\n"); 
		query.append("AND AA.IF_SRC_CD = 'TPB'" ).append("\n"); 
		query.append("AND AA.BL_SRC_NO = OTPS.IF_BL_NO" ).append("\n"); 
		query.append("AND AA.INV_SRC_NO = OTPS.N3PTY_INV_NO" ).append("\n"); 
		query.append("AND BB.AR_IF_NO = AA.AR_IF_NO" ).append("\n"); 
		query.append("AND CC.AR_IF_NO = BB.AR_IF_NO" ).append("\n"); 
		query.append("AND DD.AR_IF_NO = BB.AR_IF_NO" ).append("\n"); 
		query.append("AND EE.SRC_IF_DT = AA.SRC_IF_DT" ).append("\n"); 
		query.append("AND EE.SRC_IF_SEQ = AA.SRC_IF_SEQ" ).append("\n"); 
		query.append("AND CC.CHG_SEQ = EE.CHG_SEQ" ).append("\n"); 
		query.append("AND CC.AR_IF_SER_NO = DD.AR_IF_SER_NO" ).append("\n"); 
		query.append("AND CC.CHG_AMT = CTPB.IF_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[B Inquiry case] PLUS JO + TPB + NON-INV" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",NULL CURR_CD" ).append("\n"); 
		query.append(",NULL INV_AMT" ).append("\n"); 
		query.append(",NULL TML_CRR_CD" ).append("\n"); 
		query.append(",NULL CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",COMMCODE_PKG.GET_COMDTL_NAME_FNC('CD00588', OTPC.OTS_STS_CD) AS OTS_STS_NM" ).append("\n"); 
		query.append(",CTPB.N3PTY_NO" ).append("\n"); 
		query.append(",OTPG.N3PTY_INV_NO" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN LPAD(TO_CHAR(CTPB.VNDR_SEQ), 6, '0') WHEN 'C' THEN CTPB.CUST_CNT_CD||LPAD(CTPB.CUST_SEQ, 6, '0') WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_CODE" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN CTPB.VNDR_LGL_ENG_NM WHEN 'C' THEN CTPB.CUST_LGL_ENG_NM WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_NAME" ).append("\n"); 
		query.append(",CTPB.IF_CURR_CD" ).append("\n"); 
		query.append(",CTPB.IF_AMT" ).append("\n"); 
		query.append(",CTPB.CFM_AMT" ).append("\n"); 
		query.append(",CTPB.INV_AMT AS INV_AMT1" ).append("\n"); 
		query.append(",NULL INV_IF_DT" ).append("\n"); 
		query.append(",NULL CRE_USR_ID" ).append("\n"); 
		query.append(",NULL INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(CTPB.N3PTY_NO) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",CTPB.CSR_NO CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL GL_EFF_DT" ).append("\n"); 
		query.append(",NULL INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",NULL AR_CURR_CD" ).append("\n"); 
		query.append(",NULL CHG_AMT" ).append("\n"); 
		query.append(",NULL AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'B'  DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TES_N3RD_PTY_IF T" ).append("\n"); 
		query.append(",TPB_OTS_DTL OTPB" ).append("\n"); 
		query.append(",TPB_OTS_DTL CTPB" ).append("\n"); 
		query.append(",TPB_OTS_GRP OTPG" ).append("\n"); 
		query.append(",TPB_OTS_GRP_STS OTPC" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG = 'Y'" ).append("\n"); 
		query.append("AND T.TML_SO_OFC_CTY_CD = TES.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND T.TML_SO_SEQ = TES.TML_SO_SEQ" ).append("\n"); 
		query.append("AND T.TML_SO_DTL_SEQ = TES.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("AND OTPB.CSR_NO = T.CSR_NO" ).append("\n"); 
		query.append("AND OTPB.IF_OFC_CD = T.TML_IF_OFC_CD" ).append("\n"); 
		query.append("AND OTPB.SRC_IF_SEQ_NO = T.TML_IF_SEQ" ).append("\n"); 
		query.append("AND OTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND OTPB.OTS_DTL_SEQ IN (" ).append("\n"); 
		query.append("SELECT MIN(OTS_DTL_SEQ)" ).append("\n"); 
		query.append("FROM TPB_OTS_DTL O" ).append("\n"); 
		query.append("WHERE O.CSR_NO=T.CSR_NO" ).append("\n"); 
		query.append("GROUP BY N3PTY_SRC_NO" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND CTPB.N3PTY_SRC_NO = OTPB.N3PTY_SRC_NO" ).append("\n"); 
		query.append("AND CTPB.CSR_NO <> OTPB.CSR_NO" ).append("\n"); 
		query.append("AND CTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND CTPB.N3PTY_NO IS NOT NULL" ).append("\n"); 
		query.append("AND OTPG.N3PTY_NO = CTPB.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.N3PTY_NO = OTPG.N3PTY_NO" ).append("\n"); 
		query.append("AND OTPC.OTS_STS_LST_FLG = 'Y'" ).append("\n"); 
		query.append("AND OTPG.N3PTY_INV_NO IS NULL" ).append("\n"); 
		query.append("/* 화면 조건 */" ).append("\n"); 
		query.append("#if (${s_cd_kind} == 'T' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND CTPB.N3PTY_NO = @[s_cd_value]" ).append("\n"); 
		query.append("#elseif (${s_cd_kind} == 'I' && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND 1 = 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("--[A Inquiry case] PLUS JO + CANDIDATE TPB" ).append("\n"); 
		query.append("SELECT --[TES]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("TES.COST_OFC_CD" ).append("\n"); 
		query.append(",TES.CSR_NO" ).append("\n"); 
		query.append(",TES.TML_INV_RJCT_STS_CD" ).append("\n"); 
		query.append(",TES.INV_NO" ).append("\n"); 
		query.append(",TES.LGS_COST_CD" ).append("\n"); 
		query.append(",NULL CURR_CD" ).append("\n"); 
		query.append(",NULL INV_AMT" ).append("\n"); 
		query.append(",NULL TML_CRR_CD" ).append("\n"); 
		query.append(",NULL CALC_RMK" ).append("\n"); 
		query.append("--[TPB]-----------------------------------------------------------------------------------------" ).append("\n"); 
		query.append("--,NULL OTS_STS_NM" ).append("\n"); 
		query.append(",COMMCODE_PKG.GET_COMDTL_NAME_FNC('CD00588','Z') OTS_STS_NM" ).append("\n"); 
		query.append(",CTPB.N3PTY_NO" ).append("\n"); 
		query.append(",NULL N3PTY_INV_NO" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN LPAD(TO_CHAR(CTPB.VNDR_SEQ), 6, '0') WHEN 'C' THEN CTPB.CUST_CNT_CD||LPAD(CTPB.CUST_SEQ, 6, '0') WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_CODE" ).append("\n"); 
		query.append(",CASE CTPB.VNDR_CUST_DIV_CD WHEN 'V' THEN CTPB.VNDR_LGL_ENG_NM WHEN 'C' THEN CTPB.CUST_LGL_ENG_NM WHEN 'S' THEN CTPB.N3PTY_OFC_CD END AS TRD_PARTY_NAME" ).append("\n"); 
		query.append(",CTPB.IF_CURR_CD" ).append("\n"); 
		query.append(",CTPB.IF_AMT" ).append("\n"); 
		query.append(",CTPB.CFM_AMT" ).append("\n"); 
		query.append(",CTPB.INV_AMT AS INV_AMT1" ).append("\n"); 
		query.append(",NULL INV_IF_DT" ).append("\n"); 
		query.append(",NULL CRE_USR_ID" ).append("\n"); 
		query.append(",NULL INV_IF_OFC_CD" ).append("\n"); 
		query.append(",TPB_GET_RCVR_ACT_YN_FNC(CTPB.N3PTY_NO) AS CLT_ACT_YN" ).append("\n"); 
		query.append(",CTPB.CSR_NO CXL_CSR_NO" ).append("\n"); 
		query.append("--[AR]------------------------------------------------------------------------------------------" ).append("\n"); 
		query.append(",NULL GL_EFF_DT" ).append("\n"); 
		query.append(",NULL INV_ERP_IF_STS_CD" ).append("\n"); 
		query.append(",NULL AS AR_CURR_CD" ).append("\n"); 
		query.append(",NULL CHG_AMT" ).append("\n"); 
		query.append(",NULL AP_AR_OFFST_NO" ).append("\n"); 
		query.append(",'A'  DISPLAY_TYPE" ).append("\n"); 
		query.append("FROM TES" ).append("\n"); 
		query.append(",TES_N3RD_PTY_IF T" ).append("\n"); 
		query.append(",TPB_OTS_DTL OTPB" ).append("\n"); 
		query.append(",TPB_OTS_DTL CTPB" ).append("\n"); 
		query.append("WHERE TES.IF_TPB_FLG = 'Y'" ).append("\n"); 
		query.append("AND T.TML_SO_OFC_CTY_CD = TES.TML_SO_OFC_CTY_CD" ).append("\n"); 
		query.append("AND T.TML_SO_SEQ = TES.TML_SO_SEQ" ).append("\n"); 
		query.append("AND T.TML_SO_DTL_SEQ = TES.TML_SO_DTL_SEQ" ).append("\n"); 
		query.append("AND OTPB.CSR_NO = T.CSR_NO" ).append("\n"); 
		query.append("AND OTPB.IF_OFC_CD = T.TML_IF_OFC_CD" ).append("\n"); 
		query.append("AND OTPB.SRC_IF_SEQ_NO = T.TML_IF_SEQ" ).append("\n"); 
		query.append("AND OTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND OTPB.OTS_DTL_SEQ IN (" ).append("\n"); 
		query.append("SELECT MIN(OTS_DTL_SEQ)" ).append("\n"); 
		query.append("FROM TPB_OTS_DTL O" ).append("\n"); 
		query.append("WHERE O.CSR_NO=T.CSR_NO" ).append("\n"); 
		query.append("GROUP BY N3PTY_SRC_NO" ).append("\n"); 
		query.append(")" ).append("\n"); 
		query.append("AND CTPB.N3PTY_SRC_NO = OTPB.N3PTY_SRC_NO" ).append("\n"); 
		query.append("AND CTPB.CSR_NO <> OTPB.CSR_NO" ).append("\n"); 
		query.append("AND CTPB.N3PTY_BIL_TP_CD = 'JO'" ).append("\n"); 
		query.append("AND CTPB.N3PTY_NO IS NULL" ).append("\n"); 
		query.append("/* 화면 조건 */" ).append("\n"); 
		query.append("#if ((${s_cd_kind} == 'T' || ${s_cd_kind} == 'I') && ${s_cd_value} != '')" ).append("\n"); 
		query.append("AND 1 = 0" ).append("\n"); 
		query.append("#end" ).append("\n"); 

	}
}