/*=========================================================
*Copyright(c) 2017 CyberLogitec
*@FileName : TCharterIOEstimatedDBDAOSearchEstimatedRevenueListVORSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2017.05.24
*@LastModifier : 
*@LastVersion : 1.0
* 2017.05.24 
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.esm.fms.timecharterinoutaccounting.tcharterioestimated.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class TCharterIOEstimatedDBDAOSearchEstimatedRevenueListVORSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  *    
	  * </pre>
	  */
	public TCharterIOEstimatedDBDAOSearchEstimatedRevenueListVORSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("flet_ctrt_tp_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("to_duration",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("fr_duration",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.esm.fms.timecharterinoutaccounting.tcharterioestimated.integration").append("\n"); 
		query.append("FileName : TCharterIOEstimatedDBDAOSearchEstimatedRevenueListVORSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("-- 첫번째 UNION ALL (TI 조회)  " ).append("\n"); 
		query.append("SELECT 'I' ibflag," ).append("\n"); 
		query.append("		@[to_duration] EXE_YRMON, A.REV_YRMON, A.REV_YRMON||A.FLET_CTRT_TP_CD SUBSUMCOL," ).append("\n"); 
		query.append("       A.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("       A.RLANE_CD, A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD||A.REV_DIR_CD VVD_CD," ).append("\n"); 
		query.append("       A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("       A.VST_DT, A.VED_DT," ).append("\n"); 
		query.append("       B.HIRE_AMT," ).append("\n"); 
		query.append("       SUM(B.EST_AMT) EST_AMT," ).append("\n"); 
		query.append("       SUM(NVL(C.ACT_AMT,0)+NVL(D.AMOUNT,0)) ACT_AMT," ).append("\n"); 
		query.append("       CASE WHEN NVL(E.FLET_ACCL_AMT, 0) = 0" ).append("\n"); 
		query.append("          THEN " ).append("\n"); 
		query.append("              CASE WHEN SUM(B.EST_AMT) - SUM(NVL(C.ACT_AMT,0)+NVL(D.AMOUNT,0))  < 0" ).append("\n"); 
		query.append("                THEN 0  " ).append("\n"); 
		query.append("                ELSE SUM(B.EST_AMT) - SUM(NVL(C.ACT_AMT,0)+NVL(D.AMOUNT,0))   " ).append("\n"); 
		query.append("              END" ).append("\n"); 
		query.append("          ELSE E.ACCL_AMT" ).append("\n"); 
		query.append("        END ACC_AMT," ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append("       TO_CHAR(E.FLET_ACCL_AMT) FLET_ACCL_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("		(SELECT DISTINCT A.REV_YRMON," ).append("\n"); 
		query.append("		        B.FLET_CTRT_NO, B.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("		        A.RLANE_CD, A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD||A.REV_DIR_CD VVD_CD," ).append("\n"); 
		query.append("		        A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("		        A.VST_DT, A.VED_DT" ).append("\n"); 
		query.append("		FROM 	FMS_VVD A," ).append("\n"); 
		query.append("				(SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                   FROM FMS_CONTRACT" ).append("\n"); 
		query.append("				  WHERE FLET_CTRT_TP_CD = 'TI' " ).append("\n"); 
		query.append("                    AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                    AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("				 UNION ALL" ).append("\n"); 
		query.append("				 SELECT FI.VSL_CD, FC.FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                   FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("				  WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                    AND FC.FLET_CTRT_TP_CD = 'TI' " ).append("\n"); 
		query.append("                    AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                    AND FC.FLET_CTRT_FACT_CD = 'ACT') B" ).append("\n"); 
		query.append("		WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("		  AND 	A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("		) A," ).append("\n"); 
		query.append("			(SELECT VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON," ).append("\n"); 
		query.append("					FLET_CTRT_NO,  MIN(HIRE_EFF_DT) HIRE_EFF_DT,MAX(HIRE_EXP_DT) HIRE_EXP_DT," ).append("\n"); 
		query.append("					MIN(HIRE_N1ST_AMT + HIRE_N2ND_AMT) HIRE_AMT," ).append("\n"); 
		query.append("					SUM(DAYS*(HIRE_N1ST_AMT + HIRE_N2ND_AMT)) EST_AMT" ).append("\n"); 
		query.append("			 FROM (" ).append("\n"); 
		query.append("                SELECT  A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON, A.FLET_CTRT_NO, A.HIRE_EFF_DT," ).append("\n"); 
		query.append("                               CASE WHEN A.RN = 1 AND A.CNT > 1 THEN A.HIRE_EXP_DT -1 ELSE A.HIRE_EXP_DT END AS HIRE_EXP_DT," ).append("\n"); 
		query.append("                               CASE WHEN A.RN = 1 AND A.CNT > 1 THEN A.HIRE_EXP_DT -1 ELSE A.HIRE_EXP_DT END - A.HIRE_EFF_DT + 1 AS DAYS," ).append("\n"); 
		query.append("                               A.HIRE_N1ST_AMT, A.HIRE_N2ND_AMT" ).append("\n"); 
		query.append("                FROM (" ).append("\n"); 
		query.append("					SELECT  A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON," ).append("\n"); 
		query.append("							C.FLET_CTRT_NO," ).append("\n"); 
		query.append("							CASE WHEN A.VST_DT >= TO_CHAR(C.EFF_DT,'YYYYMMDD') THEN TO_DATE(A.VST_DT, 'YYYYMMDD') ELSE TRUNC(C.EFF_DT) END HIRE_EFF_DT," ).append("\n"); 
		query.append("							CASE WHEN A.VED_DT > TO_CHAR(C.EXP_DT,'YYYYMMDD') THEN TRUNC(C.EXP_DT)-1 ELSE TO_DATE(A.VED_DT, 'YYYYMMDD') END HIRE_EXP_DT," ).append("\n"); 
		query.append("                            ROW_NUMBER() OVER (PARTITION BY A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON, C.FLET_CTRT_NO, CASE WHEN A.VED_DT > TO_CHAR(C.EXP_DT,'YYYYMMDD') THEN TRUNC(C.EXP_DT)-1 ELSE TO_DATE(A.VED_DT, 'YYYYMMDD') END ORDER BY CASE WHEN A.VST_DT >= TO_CHAR(C.EFF_DT,'YYYYMMDD') THEN TO_DATE(A.VST_DT, 'YYYYMMDD') ELSE TRUNC(C.EFF_DT) END) AS RN," ).append("\n"); 
		query.append("                                COUNT(1) OVER(PARTITION BY A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON, C.FLET_CTRT_NO, CASE WHEN A.VED_DT > TO_CHAR(C.EXP_DT,'YYYYMMDD') THEN TRUNC(C.EXP_DT)-1 ELSE TO_DATE(A.VED_DT, 'YYYYMMDD') END) AS CNT," ).append("\n"); 
		query.append("						    CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("									  NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																									WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("								 ELSE" ).append("\n"); 
		query.append("									  FIRST_VALUE(NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																											   WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																			OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("							 END HIRE_N1ST_AMT," ).append("\n"); 
		query.append("							CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("									  NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																									WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("								 ELSE" ).append("\n"); 
		query.append("									  FIRST_VALUE(NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																											   WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																			OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("							 END HIRE_N2ND_AMT" ).append("\n"); 
		query.append("					FROM 	FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD FROM FMS_CONTRACT" ).append("\n"); 
		query.append("										WHERE FLET_CTRT_TP_CD = 'TI' AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("										UNION ALL" ).append("\n"); 
		query.append("										SELECT FI.VSL_CD, FC.FLET_CTRT_NO, FLET_CTRT_TP_CD FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("										WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO AND FC.FLET_CTRT_TP_CD = 'TI' AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' AND FC.FLET_CTRT_FACT_CD = 'ACT') B," ).append("\n"); 
		query.append("							FMS_HIRE C" ).append("\n"); 
		query.append("					WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("					  AND 	B.FLET_CTRT_NO = C.FLET_CTRT_NO" ).append("\n"); 
		query.append("					  --AND 	A.VST_DT <= TO_CHAR(C.EXP_DT,'YYYYMMDD') " ).append("\n"); 
		query.append("					  AND   A.VST_DT <= TO_CHAR(DECODE(DECODE(TO_NUMBER(SUBSTR(TO_CHAR(C.EXP_DT, 'YYYYMMDDHH24MI'), 9)), 0, 'A', 'B'), 'A', C.EXP_DT - 1, C.EXP_DT),'YYYYMMDD')" ).append("\n"); 
		query.append("					  AND 	A.VED_DT >= TO_CHAR(C.EFF_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("					  AND 	A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("              ) A" ).append("\n"); 
		query.append("            )" ).append("\n"); 
		query.append("            WHERE DAYS > 0  -- 추가" ).append("\n"); 
		query.append("			GROUP BY VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON, FLET_CTRT_NO" ).append("\n"); 
		query.append("			) B," ).append("\n"); 
		query.append("            (SELECT A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON," ).append("\n"); 
		query.append("            		B.FLET_CTRT_NO," ).append("\n"); 
		query.append("					SUM(FS.CSR_AMT/DECODE(FS.CSR_CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1)" ).append("\n"); 
		query.append("                                                                       FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																	  WHERE FS.CSR_CURR_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON =  SUBSTR(FC.EFF_DT,1,6)  AND EX1.ACCT_XCH_RT_LVL = '3'))) ACT_AMT," ).append("\n"); 
		query.append("					MIN(FS.VVD_EFF_DT) SLP_EFF_DT, MAX(FS.VVD_EXP_DT) SLP_EXP_DT" ).append("\n"); 
		query.append("			   FROM FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO " ).append("\n"); 
		query.append("                                  FROM FMS_CONTRACT" ).append("\n"); 
		query.append("								 WHERE FLET_CTRT_TP_CD = 'TI' " ).append("\n"); 
		query.append("                                   AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                   AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("								 UNION ALL" ).append("\n"); 
		query.append("								 SELECT FI.VSL_CD, FC.FLET_CTRT_NO " ).append("\n"); 
		query.append("                                   FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("								  WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                                    AND FC.FLET_CTRT_TP_CD = 'TI' " ).append("\n"); 
		query.append("                                    AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                    AND FC.FLET_CTRT_FACT_CD = 'ACT') B," ).append("\n"); 
		query.append("				 	FMS_CONSULTATION FC, FMS_CSUL_SLP FS" ).append("\n"); 
		query.append("			WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("			  AND 	B.FLET_CTRT_NO = FC.FLET_CTRT_NO" ).append("\n"); 
		query.append("			  AND 	A.VST_DT <= TO_CHAR(FS.VVD_EXP_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("			  AND 	A.VED_DT >= TO_CHAR(FS.VVD_EFF_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("			  AND 	A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("			  AND 	FC.SLP_TP_CD = FS.SLP_TP_CD" ).append("\n"); 
		query.append("			  AND 	FC.SLP_FUNC_CD = FS.SLP_FUNC_CD" ).append("\n"); 
		query.append("			  AND 	FC.SLP_OFC_CD = FS.SLP_OFC_CD" ).append("\n"); 
		query.append("			  AND 	FC.SLP_ISS_DT = FS.SLP_ISS_DT" ).append("\n"); 
		query.append("			  AND 	FC.SLP_SER_NO = FS.SLP_SER_NO" ).append("\n"); 
		query.append("			  AND 	A.VSL_CD = FS.VSL_CD" ).append("\n"); 
		query.append("			  AND 	A.SKD_VOY_NO = FS.SKD_VOY_NO" ).append("\n"); 
		query.append("			  AND 	A.SKD_DIR_CD = FS.SKD_DIR_CD" ).append("\n"); 
		query.append("			  AND 	A.REV_DIR_CD = FS.REV_DIR_CD" ).append("\n"); 
		query.append("			  AND 	FS.ACCT_CD = '510911'" ).append("\n"); 
		query.append("			  AND 	FC.APRO_FLG = 'Y'" ).append("\n"); 
		query.append("              AND   FC.CXL_FLG = 'N'" ).append("\n"); 
		query.append("              AND   SUBSTR(FC.EFF_DT,1,6) BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("			  AND 	NVL(FS.FLET_SRC_TP_CD,'%') LIKE DECODE(FS.SLP_FUNC_CD,'P','99','%')" ).append("\n"); 
		query.append("			GROUP BY A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON, B.FLET_CTRT_NO) C," ).append("\n"); 
		query.append("			(SELECT VSL_CD,SKD_VOY_NO,SKD_DIR_CD,REV_DIR_CD, SUM(CSR_AMT) AMOUNT" ).append("\n"); 
		query.append("			   FROM FMS_ESTM_IF" ).append("\n"); 
		query.append("			  WHERE ACCT_CD = '510911'" ).append("\n"); 
		query.append("			  GROUP BY VSL_CD,SKD_VOY_NO,SKD_DIR_CD,REV_DIR_CD) D, GL_ESTM_IF_ERP E" ).append("\n"); 
		query.append("WHERE A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("  AND A.SKD_VOY_NO = B.SKD_VOY_NO" ).append("\n"); 
		query.append("  AND A.SKD_DIR_CD = B.SKD_DIR_CD" ).append("\n"); 
		query.append("  AND A.REV_DIR_CD = B.REV_DIR_CD" ).append("\n"); 
		query.append("  AND A.REV_YRMON = B.REV_YRMON" ).append("\n"); 
		query.append("  AND A.FLET_CTRT_NO = B.FLET_CTRT_NO" ).append("\n"); 
		query.append("  AND A.VSL_CD = C.VSL_CD(+)" ).append("\n"); 
		query.append("  AND A.SKD_VOY_NO = C.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("  AND A.SKD_DIR_CD = C.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("  AND A.REV_DIR_CD = C.REV_DIR_CD(+)" ).append("\n"); 
		query.append("  AND A.REV_YRMON = C.REV_YRMON(+)" ).append("\n"); 
		query.append("  AND A.FLET_CTRT_NO = C.FLET_CTRT_NO(+)" ).append("\n"); 
		query.append("  AND A.VSL_CD = D.VSL_CD(+)" ).append("\n"); 
		query.append("  AND A.SKD_VOY_NO = D.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("  AND A.SKD_DIR_CD = D.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("  AND A.REV_DIR_CD = D.REV_DIR_CD(+)" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("  AND E.EXE_YRMON(+) =  TO_CHAR(ADD_MONTHS(TO_DATE(@[to_duration], 'YYYYMM'), -1), 'YYYYMM')" ).append("\n"); 
		query.append("  AND E.SYS_SRC_ID(+) = 'CDA'" ).append("\n"); 
		query.append("  AND A.VSL_CD     = E.VSL_CD(+)" ).append("\n"); 
		query.append("  AND A.SKD_VOY_NO = E.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("  AND A.SKD_DIR_CD = E.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("  AND A.REV_DIR_CD = E.REV_DIR_CD(+)" ).append("\n"); 
		query.append("  AND A.REV_YRMON  = E.REV_YRMON(+)" ).append("\n"); 
		query.append("  AND E.ACCT_CD(+) = '510911'" ).append("\n"); 
		query.append("  AND A.FLET_CTRT_TP_CD    = DECODE(E.ACCT_CD(+), '510911', 'TI', 'TO')" ).append("\n"); 
		query.append("  AND E.ACCL_AMT(+) = 0" ).append("\n"); 
		query.append("  AND E.FLET_ACCL_AMT(+) IS NOT NULL" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("GROUP BY A.REV_YRMON," ).append("\n"); 
		query.append("         A.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("         A.RLANE_CD," ).append("\n"); 
		query.append("         A.VSL_CD, " ).append("\n"); 
		query.append("		 A.SKD_VOY_NO, " ).append("\n"); 
		query.append("         A.SKD_DIR_CD, " ).append("\n"); 
		query.append("         A.REV_DIR_CD," ).append("\n"); 
		query.append("         A.VST_DT, " ).append("\n"); 
		query.append("         A.VED_DT," ).append("\n"); 
		query.append("         B.HIRE_AMT," ).append("\n"); 
		query.append("      E.ACCL_AMT," ).append("\n"); 
		query.append("      E.FLET_ACCL_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- 두번째 UNION ALL (TO 조회)" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT 'I' ibflag," ).append("\n"); 
		query.append("		@[to_duration] EXE_YRMON, A.REV_YRMON, A.REV_YRMON||A.FLET_CTRT_TP_CD SUBSUMCOL," ).append("\n"); 
		query.append("       A.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("       A.RLANE_CD, A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD||A.REV_DIR_CD VVD_CD," ).append("\n"); 
		query.append("       A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("       A.VST_DT, A.VED_DT," ).append("\n"); 
		query.append("       B.HIRE_AMT," ).append("\n"); 
		query.append("       SUM(C.ACT_APPR_YAMT + C.ACT_APPR_NAMT) EST_AMT," ).append("\n"); 
		query.append("       SUM(C.ACT_APPR_YAMT) ACT_AMT," ).append("\n"); 
		query.append("       SUM(C.ACT_APPR_NAMT) ACC_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("	 ,  '' FLET_ACCL_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("		(SELECT DISTINCT A.REV_YRMON," ).append("\n"); 
		query.append("		       B.FLET_CTRT_NO, B.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("		       A.RLANE_CD, A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD||A.REV_DIR_CD VVD_CD," ).append("\n"); 
		query.append("		       A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("		       A.VST_DT, A.VED_DT" ).append("\n"); 
		query.append("		FROM FMS_VVD A," ).append("\n"); 
		query.append("					(SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                       FROM FMS_CONTRACT" ).append("\n"); 
		query.append("					  WHERE FLET_CTRT_TP_CD = 'TO' " ).append("\n"); 
		query.append("                        AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                        AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("					 UNION ALL" ).append("\n"); 
		query.append("					 SELECT FI.VSL_CD, FC.FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                       FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("					  WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                        AND FC.FLET_CTRT_TP_CD = 'TO' " ).append("\n"); 
		query.append("                        AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                        AND FC.FLET_CTRT_FACT_CD = 'ACT') B" ).append("\n"); 
		query.append("		WHERE A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("		  AND A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("		) A," ).append("\n"); 
		query.append("		(SELECT VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON," ).append("\n"); 
		query.append("				FLET_CTRT_NO," ).append("\n"); 
		query.append("				MIN(HIRE_N1ST_AMT + HIRE_N2ND_AMT) HIRE_AMT" ).append("\n"); 
		query.append("		 FROM (" ).append("\n"); 
		query.append("				SELECT A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON," ).append("\n"); 
		query.append("						C.FLET_CTRT_NO," ).append("\n"); 
		query.append("						CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("								  NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																								WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("							 ELSE" ).append("\n"); 
		query.append("								  FIRST_VALUE(NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																										   WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																		OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("						 END HIRE_N1ST_AMT," ).append("\n"); 
		query.append("						CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("								  NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																								WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("							 ELSE" ).append("\n"); 
		query.append("								  FIRST_VALUE(NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																										   WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																		OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("						 END HIRE_N2ND_AMT" ).append("\n"); 
		query.append("				FROM 	FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                                      FROM FMS_CONTRACT" ).append("\n"); 
		query.append("									 WHERE FLET_CTRT_TP_CD = 'TO' " ).append("\n"); 
		query.append("                                       AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                       AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("									UNION ALL" ).append("\n"); 
		query.append("									SELECT FI.VSL_CD, FC.FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                                      FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("									 WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_TP_CD = 'TO' " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_FACT_CD = 'ACT') B," ).append("\n"); 
		query.append("						FMS_HIRE C" ).append("\n"); 
		query.append("				WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("				  AND 	B.FLET_CTRT_NO = C.FLET_CTRT_NO" ).append("\n"); 
		query.append("				  --AND   A.VST_DT <= TO_CHAR(C.EXP_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.VST_DT <= TO_CHAR(DECODE(DECODE(TO_NUMBER(SUBSTR(TO_CHAR(C.EXP_DT, 'YYYYMMDDHH24MI'), 9)), 0, 'A', 'B'), 'A', C.EXP_DT - 1, C.EXP_DT),'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.VED_DT >= TO_CHAR(C.EFF_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration])" ).append("\n"); 
		query.append("		GROUP BY VSL_CD, " ).append("\n"); 
		query.append("                 SKD_VOY_NO, " ).append("\n"); 
		query.append("                 SKD_DIR_CD, " ).append("\n"); 
		query.append("                 REV_DIR_CD, " ).append("\n"); 
		query.append("                 REV_YRMON," ).append("\n"); 
		query.append("				 FLET_CTRT_NO" ).append("\n"); 
		query.append("		) B," ).append("\n"); 
		query.append("        (SELECT VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON," ).append("\n"); 
		query.append("        	    FLET_CTRT_NO," ).append("\n"); 
		query.append("                INV_YAMT" ).append("\n"); 
		query.append("                + (SELECT NVL(SUM(DECODE(FCH.APRO_FLG,'Y',FCD.CSR_AMT,0)/DECODE(FCD.CSR_CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																					WHERE FCD.CSR_CURR_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = AA.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3'))), 0)" ).append("\n"); 
		query.append("				   FROM FMS_CONSULTATION FCH, FMS_CSUL_SLP FCD" ).append("\n"); 
		query.append("                   WHERE AA.SLP_TP_CD = FCD.ORG_SLP_TP_CD" ).append("\n"); 
		query.append("                   AND AA.SLP_FUNC_CD = FCD.ORG_SLP_FUNC_CD" ).append("\n"); 
		query.append("                   AND AA.SLP_OFC_CD = FCD.ORG_SLP_OFC_CD" ).append("\n"); 
		query.append("                   AND AA.SLP_ISS_DT = FCD.ORG_ISS_DT" ).append("\n"); 
		query.append("                   AND AA.SLP_SER_NO = FCD.ORG_SLP_SER_NO" ).append("\n"); 
		query.append("                   AND FCD.SLP_TP_CD = FCH.SLP_TP_CD" ).append("\n"); 
		query.append("                   AND FCD.SLP_FUNC_CD = FCH.SLP_FUNC_CD" ).append("\n"); 
		query.append("                   AND FCD.SLP_OFC_CD = FCH.SLP_OFC_CD" ).append("\n"); 
		query.append("                   AND FCD.SLP_ISS_DT = FCH.SLP_ISS_DT" ).append("\n"); 
		query.append("                   AND FCD.SLP_SER_NO = FCH.SLP_SER_NO" ).append("\n"); 
		query.append("                   AND FCD.ACCT_CD = '110811') ACT_APPR_YAMT,  " ).append("\n"); 
		query.append("                INV_NAMT" ).append("\n"); 
		query.append("                + (SELECT NVL(SUM(DECODE(FCH.APRO_FLG,'N',FCD.CSR_AMT,0)/DECODE(FCD.CSR_CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																					WHERE FCD.CSR_CURR_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = AA.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3'))), 0)                                                               " ).append("\n"); 
		query.append("		           FROM FMS_CONSULTATION FCH, FMS_CSUL_SLP FCD" ).append("\n"); 
		query.append("                   WHERE AA.SLP_TP_CD = FCD.ORG_SLP_TP_CD" ).append("\n"); 
		query.append("                   AND AA.SLP_FUNC_CD = FCD.ORG_SLP_FUNC_CD" ).append("\n"); 
		query.append("                   AND AA.SLP_OFC_CD = FCD.ORG_SLP_OFC_CD" ).append("\n"); 
		query.append("                   AND AA.SLP_ISS_DT = FCD.ORG_ISS_DT" ).append("\n"); 
		query.append("                   AND AA.SLP_SER_NO = FCD.ORG_SLP_SER_NO" ).append("\n"); 
		query.append("                   AND FCD.SLP_TP_CD = FCH.SLP_TP_CD" ).append("\n"); 
		query.append("                   AND FCD.SLP_FUNC_CD = FCH.SLP_FUNC_CD" ).append("\n"); 
		query.append("                   AND FCD.SLP_OFC_CD = FCH.SLP_OFC_CD" ).append("\n"); 
		query.append("                   AND FCD.SLP_ISS_DT = FCH.SLP_ISS_DT" ).append("\n"); 
		query.append("                   AND FCD.SLP_SER_NO = FCH.SLP_SER_NO" ).append("\n"); 
		query.append("                   AND FCD.ACCT_CD = '110811') ACT_APPR_NAMT" ).append("\n"); 
		query.append("         FROM (     " ).append("\n"); 
		query.append("		 SELECT FC.SLP_TP_CD, FC.SLP_FUNC_CD, FC.SLP_OFC_CD, FC.SLP_ISS_DT, FC.SLP_SER_NO," ).append("\n"); 
		query.append("				A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON," ).append("\n"); 
		query.append("        		B.FLET_CTRT_NO," ).append("\n"); 
		query.append("				SUM(DECODE(FC.APRO_FLG,'Y',FS.INV_AMT,0)/DECODE(FS.CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																					WHERE FS.CURR_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3'))) INV_YAMT," ).append("\n"); 
		query.append("				SUM(DECODE(FC.APRO_FLG,'N',FS.INV_AMT,0)/DECODE(FS.CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																					WHERE FS.CURR_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3'))) INV_NAMT" ).append("\n"); 
		query.append("		FROM FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO " ).append("\n"); 
		query.append("                           FROM FMS_CONTRACT" ).append("\n"); 
		query.append("						  WHERE FLET_CTRT_TP_CD = 'TO' " ).append("\n"); 
		query.append("                            AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                            AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("						 UNION ALL" ).append("\n"); 
		query.append("						 SELECT FI.VSL_CD, FC.FLET_CTRT_NO " ).append("\n"); 
		query.append("                           FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("						  WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                            AND FC.FLET_CTRT_TP_CD = 'TO' " ).append("\n"); 
		query.append("                            AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                            AND FC.FLET_CTRT_FACT_CD = 'ACT') B," ).append("\n"); 
		query.append("			  FMS_CONSULTATION FC, FMS_INV_DTL FS" ).append("\n"); 
		query.append("		WHERE A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("		  AND B.FLET_CTRT_NO = FC.FLET_CTRT_NO" ).append("\n"); 
		query.append("		  AND A.VST_DT <= TO_CHAR(FS.EXP_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("		  AND A.VED_DT >= TO_CHAR(FS.EFF_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("		  AND A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("		  AND FC.SLP_TP_CD = FS.SLP_TP_CD" ).append("\n"); 
		query.append("		  AND FC.SLP_FUNC_CD = FS.SLP_FUNC_CD" ).append("\n"); 
		query.append("		  AND FC.SLP_OFC_CD = FS.SLP_OFC_CD" ).append("\n"); 
		query.append("		  AND FC.SLP_ISS_DT = FS.SLP_ISS_DT" ).append("\n"); 
		query.append("		  AND FC.SLP_SER_NO = FS.SLP_SER_NO" ).append("\n"); 
		query.append("		  AND A.VSL_CD = FS.VSL_CD" ).append("\n"); 
		query.append("		  AND A.SKD_VOY_NO = FS.SKD_VOY_NO" ).append("\n"); 
		query.append("		  AND A.SKD_DIR_CD = FS.SKD_DIR_CD" ).append("\n"); 
		query.append("		  AND A.REV_DIR_CD = FS.REV_DIR_CD" ).append("\n"); 
		query.append("		  AND FS.FLET_ISS_TP_CD = 'PRE'" ).append("\n"); 
		query.append("          --AND FS.ACCT_CD = '510911'" ).append("\n"); 
		query.append("		GROUP BY A.VSL_CD, " ).append("\n"); 
		query.append("				 A.SKD_VOY_NO, " ).append("\n"); 
		query.append("                 A.SKD_DIR_CD, " ).append("\n"); 
		query.append("                 A.REV_DIR_CD, " ).append("\n"); 
		query.append("                 A.REV_YRMON, " ).append("\n"); 
		query.append("                 B.FLET_CTRT_NO," ).append("\n"); 
		query.append("                 FC.SLP_TP_CD," ).append("\n"); 
		query.append("                 FC.SLP_FUNC_CD," ).append("\n"); 
		query.append("                 FC.SLP_OFC_CD," ).append("\n"); 
		query.append("                 FC.SLP_ISS_DT," ).append("\n"); 
		query.append("                 FC.SLP_SER_NO) AA ) C" ).append("\n"); 
		query.append("WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("  AND 	A.SKD_VOY_NO = B.SKD_VOY_NO" ).append("\n"); 
		query.append("  AND 	A.SKD_DIR_CD = B.SKD_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_DIR_CD = B.REV_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_YRMON = B.REV_YRMON" ).append("\n"); 
		query.append("  AND 	A.FLET_CTRT_NO = B.FLET_CTRT_NO" ).append("\n"); 
		query.append("  AND 	A.VSL_CD = C.VSL_CD" ).append("\n"); 
		query.append("  AND 	A.SKD_VOY_NO = C.SKD_VOY_NO" ).append("\n"); 
		query.append("  AND 	A.SKD_DIR_CD = C.SKD_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_DIR_CD = C.REV_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_YRMON = C.REV_YRMON" ).append("\n"); 
		query.append("  AND 	A.FLET_CTRT_NO = C.FLET_CTRT_NO" ).append("\n"); 
		query.append("GROUP BY A.REV_YRMON," ).append("\n"); 
		query.append("         A.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("         A.RLANE_CD," ).append("\n"); 
		query.append("         A.VSL_CD, " ).append("\n"); 
		query.append("         A.SKD_VOY_NO, " ).append("\n"); 
		query.append("         A.SKD_DIR_CD, " ).append("\n"); 
		query.append("         A.REV_DIR_CD," ).append("\n"); 
		query.append("         A.VST_DT, " ).append("\n"); 
		query.append("         A.VED_DT," ).append("\n"); 
		query.append("         B.HIRE_AMT" ).append("\n"); 
		query.append("-- 세번째 UNION ALL (Off-Hire 조회)" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT 'I' ibflag," ).append("\n"); 
		query.append("		@[to_duration] EXE_YRMON, A.REV_YRMON, A.REV_YRMON||A.FLET_CTRT_TP_CD SUBSUMCOL," ).append("\n"); 
		query.append("       A.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("       A.RLANE_CD, A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD||A.REV_DIR_CD VVD_CD," ).append("\n"); 
		query.append("       A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("       TO_CHAR(C.VVD_EFF_DT,'YYYYMMDD') VST_DT, TO_CHAR(C.VVD_EXP_DT,'YYYYMMDD') VED_DT," ).append("\n"); 
		query.append("       B.HIRE_AMT," ).append("\n"); 
		query.append("       C.ACT_AMT + C.ACT_APPR_NAMT EST_AMT," ).append("\n"); 
		query.append("	   (C.ACT_AMT) ACT_AMT," ).append("\n"); 
		query.append("       -1*(C.ACT_APPR_NAMT) ACC_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("	 ,  '' FLET_ACCL_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("		(SELECT DISTINCT A.REV_YRMON," ).append("\n"); 
		query.append("		       B.FLET_CTRT_NO, B.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("		       A.RLANE_CD, A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD||A.REV_DIR_CD VVD_CD," ).append("\n"); 
		query.append("		       A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("		       A.VST_DT, A.VED_DT" ).append("\n"); 
		query.append("		FROM FMS_VVD A," ).append("\n"); 
		query.append("			(SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("               FROM FMS_CONTRACT" ).append("\n"); 
		query.append("			  WHERE FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("			 UNION ALL" ).append("\n"); 
		query.append("			 SELECT FI.VSL_CD, FC.FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("               FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("			  WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                AND FC.FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                AND FC.FLET_CTRT_FACT_CD = 'ACT') B" ).append("\n"); 
		query.append("		WHERE A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("		  AND A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("		) A," ).append("\n"); 
		query.append("		(SELECT VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON," ).append("\n"); 
		query.append("				FLET_CTRT_NO," ).append("\n"); 
		query.append("				MIN(HIRE_N1ST_AMT + HIRE_N2ND_AMT) HIRE_AMT" ).append("\n"); 
		query.append("		 FROM (" ).append("\n"); 
		query.append("				SELECT A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON," ).append("\n"); 
		query.append("						C.FLET_CTRT_NO," ).append("\n"); 
		query.append("						CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("								  NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																								WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("							 ELSE" ).append("\n"); 
		query.append("								  FIRST_VALUE(NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																										   WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																		OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("						 END HIRE_N1ST_AMT," ).append("\n"); 
		query.append("						CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("								  NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																								WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("							 ELSE" ).append("\n"); 
		query.append("								  FIRST_VALUE(NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																										   WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																		OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("						 END HIRE_N2ND_AMT" ).append("\n"); 
		query.append("				FROM 	FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                                      FROM FMS_CONTRACT" ).append("\n"); 
		query.append("									 WHERE FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                                       AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                       AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("									UNION ALL" ).append("\n"); 
		query.append("									SELECT FI.VSL_CD, FC.FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                                      FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("									 WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_FACT_CD = 'ACT') B," ).append("\n"); 
		query.append("						FMS_HIRE C" ).append("\n"); 
		query.append("				WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("				  AND 	B.FLET_CTRT_NO = C.FLET_CTRT_NO" ).append("\n"); 
		query.append("				  --AND   A.VST_DT <= TO_CHAR(C.EXP_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.VST_DT <= TO_CHAR(DECODE(DECODE(TO_NUMBER(SUBSTR(TO_CHAR(C.EXP_DT, 'YYYYMMDDHH24MI'), 9)), 0, 'A', 'B'), 'A', C.EXP_DT - 1, C.EXP_DT),'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.VED_DT >= TO_CHAR(C.EFF_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration])" ).append("\n"); 
		query.append("		GROUP BY VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON, FLET_CTRT_NO" ).append("\n"); 
		query.append("		) B," ).append("\n"); 
		query.append("        (SELECT A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON, fc.slp_tp_cd||fc.slp_func_cd||fc.slp_ofc_cd||fc.slp_iss_dt||fc.slp_ser_no CSR_NO," ).append("\n"); 
		query.append("        		B.FLET_CTRT_NO, FS.VVD_EFF_DT, FS.VVD_EXP_DT," ).append("\n"); 
		query.append("                DECODE(FC.APRO_FLG,'Y',FS.CSR_AMT,0)/DECODE(FS.CSR_CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("                                  WHERE FS.CSR_CURR_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = SUBSTR(FC.EFF_DT,1,6) AND EX1.ACCT_XCH_RT_LVL = '3')) ACT_AMT," ).append("\n"); 
		query.append("                DECODE(FC.APRO_FLG,'Y',0,FS.CSR_AMT)/DECODE(FS.CSR_CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("							      WHERE FS.CSR_CURR_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')) ACT_APPR_NAMT" ).append("\n"); 
		query.append("		 FROM   FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO " ).append("\n"); 
		query.append("                              FROM FMS_CONTRACT" ).append("\n"); 
		query.append("							 WHERE FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                               AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                               AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("							 UNION ALL" ).append("\n"); 
		query.append("							 SELECT FI.VSL_CD, FC.FLET_CTRT_NO " ).append("\n"); 
		query.append("                               FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("							  WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                                AND FC.FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                                AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                AND FC.FLET_CTRT_FACT_CD = 'ACT') B," ).append("\n"); 
		query.append("				FMS_CONSULTATION FC, FMS_CSUL_SLP FS" ).append("\n"); 
		query.append("		WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("		  AND 	B.FLET_CTRT_NO = FC.FLET_CTRT_NO" ).append("\n"); 
		query.append("		  AND 	A.VST_DT <= TO_CHAR(FS.VVD_EXP_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("		  AND 	A.VED_DT >= TO_CHAR(FS.VVD_EFF_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("		  AND 	A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("		  AND 	FC.SLP_TP_CD = FS.SLP_TP_CD" ).append("\n"); 
		query.append("		  AND 	FC.SLP_FUNC_CD = FS.SLP_FUNC_CD" ).append("\n"); 
		query.append("		  AND 	FC.SLP_OFC_CD = FS.SLP_OFC_CD" ).append("\n"); 
		query.append("		  AND 	FC.SLP_ISS_DT = FS.SLP_ISS_DT" ).append("\n"); 
		query.append("		  AND 	FC.SLP_SER_NO = FS.SLP_SER_NO" ).append("\n"); 
		query.append("		  AND 	A.VSL_CD = FS.VSL_CD" ).append("\n"); 
		query.append("		  AND 	A.SKD_VOY_NO = FS.SKD_VOY_NO" ).append("\n"); 
		query.append("		  AND 	A.SKD_DIR_CD = FS.SKD_DIR_CD" ).append("\n"); 
		query.append("		  AND 	A.REV_DIR_CD = FS.REV_DIR_CD" ).append("\n"); 
		query.append("		  AND 	FS.SLP_FUNC_CD = 'P'" ).append("\n"); 
		query.append("          AND 	FC.APRO_FLG = 'Y'" ).append("\n"); 
		query.append("          AND   FC.CXL_FLG = 'N'" ).append("\n"); 
		query.append("          AND   SUBSTR(FC.EFF_DT,1,6) BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("		  AND 	FS.ACCT_CD = '510911'" ).append("\n"); 
		query.append("          AND   FS.FLET_SRC_TP_CD = '02') C" ).append("\n"); 
		query.append("WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("  AND 	A.SKD_VOY_NO = B.SKD_VOY_NO" ).append("\n"); 
		query.append("  AND 	A.SKD_DIR_CD = B.SKD_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_DIR_CD = B.REV_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_YRMON = B.REV_YRMON" ).append("\n"); 
		query.append("  AND 	A.FLET_CTRT_NO = B.FLET_CTRT_NO" ).append("\n"); 
		query.append("  AND 	A.VSL_CD = C.VSL_CD" ).append("\n"); 
		query.append("  AND 	A.SKD_VOY_NO = C.SKD_VOY_NO" ).append("\n"); 
		query.append("  AND 	A.SKD_DIR_CD = C.SKD_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_DIR_CD = C.REV_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_YRMON = C.REV_YRMON" ).append("\n"); 
		query.append("  AND 	A.FLET_CTRT_NO = C.FLET_CTRT_NO" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("-- 마지막 Manual Slip (98) Payment Slip (99) UNION ALL (TI 조회) " ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT 'I' ibflag," ).append("\n"); 
		query.append("	    	@[to_duration] EXE_YRMON, A.REV_YRMON, A.REV_YRMON||A.FLET_CTRT_TP_CD SUBSUMCOL," ).append("\n"); 
		query.append("        A.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("        A.RLANE_CD, A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD||A.REV_DIR_CD VVD_CD," ).append("\n"); 
		query.append("        A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("        A.VST_DT, A.VED_DT," ).append("\n"); 
		query.append("        B.HIRE_AMT," ).append("\n"); 
		query.append("        A.ACT_AMT EST_AMT," ).append("\n"); 
		query.append("        A.ACT_AMT ACT_AMT," ).append("\n"); 
		query.append("        0 ACC_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("		,  '' FLET_ACCL_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("FROM" ).append("\n"); 
		query.append("(  " ).append("\n"); 
		query.append("      SELECT A.REV_YRMON, A.VST_DT, A.VED_DT, A.RLANE_CD," ).append("\n"); 
		query.append("            		         B.FLET_CTRT_NO, B.FLET_CTRT_TP_CD," ).append("\n"); 
		query.append("            		        A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD," ).append("\n"); 
		query.append("      					      FS.CSR_AMT/DECODE(FS.CSR_CURR_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1)" ).append("\n"); 
		query.append("                                                                                                       FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("      																	                                                              WHERE FS.CSR_CURR_CD = EX1.CURR_CD " ).append("\n"); 
		query.append("                                                                                                      AND EX1.ACCT_XCH_RT_YRMON =  SUBSTR(FC.EFF_DT,1,6) " ).append("\n"); 
		query.append("                                                                                                       AND EX1.ACCT_XCH_RT_LVL = '3' )) ACT_AMT" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("      FROM FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD" ).append("\n"); 
		query.append("                                              FROM FMS_CONTRACT" ).append("\n"); 
		query.append("                            								 WHERE FLET_CTRT_TP_CD = 'TI' " ).append("\n"); 
		query.append("                                                 AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                                 AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("                      								 UNION ALL" ).append("\n"); 
		query.append("                      								 SELECT FI.VSL_CD, FC.FLET_CTRT_NO , FLET_CTRT_TP_CD" ).append("\n"); 
		query.append("                                          FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("                      								  WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                                            AND FC.FLET_CTRT_TP_CD = 'TI' " ).append("\n"); 
		query.append("                                            AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                            AND FC.FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("                                  ) B," ).append("\n"); 
		query.append("      				    	     FMS_CONSULTATION FC, FMS_CSUL_SLP FS" ).append("\n"); 
		query.append("      WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("         AND 	A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("         AND 	FC.SLP_TP_CD = FS.SLP_TP_CD" ).append("\n"); 
		query.append("         AND 	FC.SLP_FUNC_CD = FS.SLP_FUNC_CD" ).append("\n"); 
		query.append("         AND 	FC.SLP_OFC_CD = FS.SLP_OFC_CD" ).append("\n"); 
		query.append("         AND 	FC.SLP_ISS_DT = FS.SLP_ISS_DT" ).append("\n"); 
		query.append("         AND 	FC.SLP_SER_NO = FS.SLP_SER_NO" ).append("\n"); 
		query.append("         AND 	A.VSL_CD = FS.VSL_CD" ).append("\n"); 
		query.append("         AND 	A.SKD_VOY_NO = FS.SKD_VOY_NO" ).append("\n"); 
		query.append("         AND 	A.SKD_DIR_CD = FS.SKD_DIR_CD" ).append("\n"); 
		query.append("         AND 	A.REV_DIR_CD = FS.REV_DIR_CD" ).append("\n"); 
		query.append("         AND 	FS.ACCT_CD = '510911'" ).append("\n"); 
		query.append("         AND 	FC.APRO_FLG = 'Y'" ).append("\n"); 
		query.append("        AND   FC.CXL_FLG = 'N'" ).append("\n"); 
		query.append("        AND   SUBSTR(FC.EFF_DT,1,6) BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("         AND  FS.FLET_SRC_TP_CD IN  ('98', '99')" ).append("\n"); 
		query.append("       ) A," ).append("\n"); 
		query.append("   " ).append("\n"); 
		query.append("   (SELECT VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON," ).append("\n"); 
		query.append("				FLET_CTRT_NO," ).append("\n"); 
		query.append("				MIN(HIRE_N1ST_AMT + HIRE_N2ND_AMT) HIRE_AMT" ).append("\n"); 
		query.append("		 FROM (" ).append("\n"); 
		query.append("				SELECT A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, A.REV_YRMON," ).append("\n"); 
		query.append("						C.FLET_CTRT_NO," ).append("\n"); 
		query.append("						CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("								  NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																								WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("							 ELSE" ).append("\n"); 
		query.append("								  FIRST_VALUE(NVL(C.HIR_RT_N1ST_AMT/DECODE(C.HIR_CURR_N1ST_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																										   WHERE C.HIR_CURR_N1ST_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																		OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("						 END HIRE_N1ST_AMT," ).append("\n"); 
		query.append("						CASE WHEN SUBSTR(TO_CHAR(FIRST_VALUE(C.EXP_DT) OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD ORDER BY C.EXP_DT),'YYYYMMDDHH24MISS'),9,4) = '0000' AND C.HIR_CURR_N2ND_CD IS NULL THEN" ).append("\n"); 
		query.append("								  NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																								WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0)" ).append("\n"); 
		query.append("							 ELSE" ).append("\n"); 
		query.append("								  FIRST_VALUE(NVL(C.HIR_RT_N2ND_AMT/DECODE(C.HIR_CURR_N2ND_CD, 'USD', 1, (SELECT NVL(EX1.USD_LOCL_XCH_RT,1) FROM GL_MON_XCH_RT EX1" ).append("\n"); 
		query.append("																										   WHERE C.HIR_CURR_N2ND_CD = EX1.CURR_CD AND EX1.ACCT_XCH_RT_YRMON = A.REV_YRMON AND EX1.ACCT_XCH_RT_LVL = '3')),0))" ).append("\n"); 
		query.append("																		OVER(PARTITION BY C.FLET_CTRT_NO, A.VSL_CD, A.SKD_VOY_NO, A.SKD_DIR_CD, A.REV_DIR_CD, C.EXP_DT ORDER BY C.EXP_DT DESC)" ).append("\n"); 
		query.append("						 END HIRE_N2ND_AMT" ).append("\n"); 
		query.append("				FROM 	FMS_VVD A, (SELECT VSL_CD, FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                                      FROM FMS_CONTRACT" ).append("\n"); 
		query.append("									 WHERE FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                                       AND FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                       AND FLET_CTRT_FACT_CD = 'ACT'" ).append("\n"); 
		query.append("									UNION ALL" ).append("\n"); 
		query.append("									SELECT FI.VSL_CD, FC.FLET_CTRT_NO, FLET_CTRT_TP_CD " ).append("\n"); 
		query.append("                                      FROM FMS_CONTRACT FC, FMS_ID_VSL FI" ).append("\n"); 
		query.append("									 WHERE FC.FLET_CTRT_NO = FI.FLET_CTRT_NO " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_TP_CD <> 'OW' " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_TP_CD LIKE @[flet_ctrt_tp_cd]||'%' " ).append("\n"); 
		query.append("                                       AND FC.FLET_CTRT_FACT_CD = 'ACT') B," ).append("\n"); 
		query.append("						FMS_HIRE C, FMS_CSUL_SLP FS" ).append("\n"); 
		query.append("				WHERE 	A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("			    AND 	 C.FLET_CTRT_NO = B.FLET_CTRT_NO" ).append("\n"); 
		query.append("				  --AND   A.VST_DT <= TO_CHAR(C.EXP_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("				AND   A.VST_DT <= TO_CHAR(DECODE(DECODE(TO_NUMBER(SUBSTR(TO_CHAR(C.EXP_DT, 'YYYYMMDDHH24MI'), 9)), 0, 'A', 'B'), 'A', C.EXP_DT - 1, C.EXP_DT),'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.VED_DT >= TO_CHAR(C.EFF_DT,'YYYYMMDD')" ).append("\n"); 
		query.append("				  AND   A.REV_YRMON BETWEEN @[fr_duration] AND @[to_duration]" ).append("\n"); 
		query.append("          AND 	A.VSL_CD = FS.VSL_CD" ).append("\n"); 
		query.append("          AND 	A.SKD_VOY_NO = FS.SKD_VOY_NO" ).append("\n"); 
		query.append("          AND 	A.SKD_DIR_CD = FS.SKD_DIR_CD" ).append("\n"); 
		query.append("          AND 	A.REV_DIR_CD = FS.REV_DIR_CD" ).append("\n"); 
		query.append("          AND 	FS.ACCT_CD = '510911'" ).append("\n"); 
		query.append("          AND  FS.FLET_SRC_TP_CD IN  ('98', '99') )" ).append("\n"); 
		query.append("		GROUP BY VSL_CD, SKD_VOY_NO, SKD_DIR_CD, REV_DIR_CD, REV_YRMON, FLET_CTRT_NO" ).append("\n"); 
		query.append("		) B" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("WHERE   A.VSL_CD = B.VSL_CD" ).append("\n"); 
		query.append("  AND 	A.SKD_VOY_NO = B.SKD_VOY_NO" ).append("\n"); 
		query.append("  AND 	A.SKD_DIR_CD = B.SKD_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_DIR_CD = B.REV_DIR_CD" ).append("\n"); 
		query.append("  AND 	A.REV_YRMON = B.REV_YRMON" ).append("\n"); 
		query.append("  AND 	A.FLET_CTRT_NO = B.FLET_CTRT_NO" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("ORDER BY REV_YRMON, FLET_CTRT_TP_CD" ).append("\n"); 

	}
}