/*=========================================================
*Copyright(c) 2015 CyberLogitec
*@FileName : UsaCustomsReportDBDAOsearchAmsReportListbyDateRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2015.12.31
*@LastModifier : 김민정
*@LastVersion : 1.0
* 2015.12.31 김민정
* 1.0 Creation
=========================================================*/
package com.clt.apps.opus.esm.bkg.customsdeclaration.customsreport.usa.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.clt.framework.support.db.ISQLTemplate;

/**
 *
 * @author Minjung Kim
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class UsaCustomsReportDBDAOsearchAmsReportListbyDateRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * dwkim, 0041 Ams Report 조회. 생성 VO명 : UsaAmsReportListDetailVO
	  * </pre>
	  */
	public UsaCustomsReportDBDAOsearchAmsReportListbyDateRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("tod",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("fromd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("cntr_tp",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("customs_result_code_grp",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("fromt",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("hub",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("mbl_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("tot",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("customer_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("pol",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("del",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("l_rep",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("pmib_tp",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("end_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("pod",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("rhq",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("rcv_term_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("de_term_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("ams_file_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("vvd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("customs_result_code",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("cntr_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("sc_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("start_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("b_stf",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.clt.apps.opus.esm.bkg.customsdeclaration.customsreport.usa.integration").append("\n"); 
		query.append("FileName : UsaCustomsReportDBDAOsearchAmsReportListbyDateRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("#if (${cntr_prt_flg} == '1' && ${general_or_rail} == 'RAILAMS')" ).append("\n"); 
		query.append("SELECT TB.*" ).append("\n"); 
		query.append("      ,'' AS SEQ" ).append("\n"); 
		query.append("      ,REPLACE(REPLACE(REPLACE(CUST.CUST_NM, CHR(13)||CHR(10),' '), CHR(13), ' '), CHR(10), ' ') AS CUST_NM" ).append("\n"); 
		query.append("  FROM (" ).append("\n"); 
		query.append("        SELECT COUNT(*) OVER() AS TOTAL" ).append("\n"); 
		query.append("              ,PBL.CNT_CD" ).append("\n"); 
		query.append("              ,NVL(CR.DSPO_CD,' ') AS DSPO_CD" ).append("\n"); 
		query.append("              ,BR.BL_NO AS MBL_NO" ).append("\n"); 
		query.append("              ,PBL.BL_NO  AS AMS_FILE_NO" ).append("\n"); 
		query.append("              ,DECODE(PBL.MF_NO, NULL, PBL.CSTMS_FILE_TP_CD, '0') FILER" ).append("\n"); 
		query.append("              ,PBL.MF_STS_CD" ).append("\n"); 
		query.append("              ,PBL.CSTMS_MF_TP_CD" ).append("\n"); 
		query.append("              ,PBL.POD_CD" ).append("\n"); 
		query.append("              ,PBL.DEL_CD" ).append("\n"); 
		query.append("              ,PBL.HUB_LOC_CD" ).append("\n"); 
		query.append("              ,E.CNTR_NO" ).append("\n"); 
		query.append("              --,(SELECT DECODE(CNTR_VOL_QTY, 1, 'N', 'Y') FROM BKG_CONTAINER	WHERE BKG_NO = BR.BKG_NO AND CNTR_NO = E.CNTR_NO) CNTR_PRT_FLG" ).append("\n"); 
		query.append("			  ,DECODE(BC.CNTR_VOL_QTY, 1, 'N', 'Y') CNTR_PRT_FLG" ).append("\n"); 
		query.append("              ,E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("              ,NVL(B.FRT_CLT_FLG, 'N') AS FRT_CLT_FLG" ).append("\n"); 
		query.append("              ,NVL(B.OBL_RDEM_FLG, 'N') AS OBL_RDEM_FLG" ).append("\n"); 
		query.append("              ,IBD.IBD_TRSP_NO" ).append("\n"); 
		query.append("              ,IBD.IBD_TRSP_TP_CD" ).append("\n"); 
		query.append("              ,IBD.FREE_TRD_ZN_FLG" ).append("\n"); 
		query.append("              ,TO_CHAR(IBD.IBD_TRSP_ISS_DT, 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ISS_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(IBD.IBD_TRSP_ACPT_DT, 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ACPT_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.ARR_DT, IBD.IBD_TRSP_ARR_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ARR_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.CGO_ARR_ACPT_DT, IBD.IBD_TRSP_ARR_ACPT_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ARR_ACPT_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.XPT_DT, IBD.IBD_TRSP_XPT_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_XPT_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.XPT_ACPT_DT, IBD.IBD_TRSP_XPT_ACPT_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_XPT_ACPT_DT" ).append("\n"); 
		query.append("              ,PBL.RCV_TERM_CD" ).append("\n"); 
		query.append("              ,PBL.DE_TERM_CD" ).append("\n"); 
		query.append("              ,TO_CHAR(CR.RCV_DT, 'YYYY-MM-DD HH24:MI') AS ARR_DT" ).append("\n"); 
		query.append("              ,BR.SC_NO" ).append("\n"); 
		query.append("              ,AD.CSTMS_DSPO_NM" ).append("\n"); 
		query.append("              ,PBL.CSTMS_POL_CD POL_CD" ).append("\n"); 
		query.append("              ,PBL.BKG_NO" ).append("\n"); 
		query.append("              ,PBL.VSL_CD||PBL.SKD_VOY_NO||PBL.SKD_DIR_CD AS VVD" ).append("\n"); 
		query.append("              ,CC.RAIL_CRR_REF_NO" ).append("\n"); 
		query.append("              ,CC.USA_IB_TRSP_NO" ).append("\n"); 
		query.append("              ,SPF.PKUP_NO" ).append("\n"); 
		query.append("              ,DECODE(SPF.NTFC_DT, NULL, 'N', 'Y') AS PKUP_RELEASED" ).append("\n"); 
		query.append("              ,TO_CHAR(SPF.NTFC_DT, 'YYYY-MM-DD HH24:MI') AS PKUP_DATE" ).append("\n"); 
		query.append("              ,CASE WHEN PBL.CSTMS_POD_CD NOT LIKE 'US%' AND PBL.DEL_CD LIKE 'US%' THEN NVL(CR.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("                    ELSE NVL(B.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("               END CSTMS_CLR_CD" ).append("\n"); 
		query.append("              ,ROW_NUMBER() OVER(ORDER BY E.BL_NO, E.CNTR_NO) AS RNUM" ).append("\n"); 
		query.append("              ,DECODE(PBL.MF_NO, NULL, DECODE(BR.CUST_TO_ORD_FLG, 'Y', 'N', 'C'), 'C') AS BKG_CUST_TP_CD" ).append("\n"); 
		query.append("              ,COUNT(DISTINCT PBL.BL_NO) OVER() AS BL_CNT" ).append("\n"); 
		query.append("			  ,CASE WHEN A.CSTMS_POD_CD NOT LIKE 'US%' AND A.DEL_CD LIKE 'US%' THEN NVL(CR.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("                    ELSE NVL(B.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("               END C_FLAG" ).append("\n"); 
		query.append("			  ,DECODE( CC.RAIL_CRR_REF_NO , NULL, '', 'Y' ) MASTER" ).append("\n"); 
		query.append("			  ,CASE WHEN NVL(B.CSTMS_CLR_CD, 'N') IN ('Y', 'W', 'T', 'E')  THEN 'Y' ELSE 'N' END RLSE_EDI" ).append("\n"); 
		query.append("			  ,( SELECT NVL(SUM(CM.PCK_QTY), 0) FROM BKG_CSTMS_ADV_CNTR_MF CM" ).append("\n"); 
		query.append("				    WHERE CM.CNT_CD = PCNTR.CNT_CD" ).append("\n"); 
		query.append("			    	AND CM.BL_NO = PCNTR.BL_NO" ).append("\n"); 
		query.append("				    AND CM.CNTR_NO = PCNTR.CNTR_NO" ).append("\n"); 
		query.append("			    ) SUM_CM_QTY" ).append("\n"); 
		query.append("			  ,NVL2(CC.RAIL_CRR_REF_NO, ( SELECT " ).append("\n"); 
		query.append("					SUBSTR( NVL( MAX( DECODE (DSPO_CD , '55', LPAD(CSTMS_SEQ,3,'0')||CNTR_QTY ) ) " ).append("\n"); 
		query.append("                	,MAX( DECODE (DSPO_CD , '69', LPAD(CSTMS_SEQ,3,'0')||CNTR_QTY ) ) )" ).append("\n"); 
		query.append("           				, 4 ) QTY " ).append("\n"); 
		query.append("         		 FROM BKG_CSTMS_ADV_CNTR_RSLT CRQ" ).append("\n"); 
		query.append("			    WHERE PCNTR.CNT_cD = CRQ.CNT_cD" ).append("\n"); 
		query.append("    			  AND PCNTR.BL_NO = CRQ.BL_NO" ).append("\n"); 
		query.append("    			  AND PCNTR.CNTR_NO  LIKE TRIM(CRQ.CNTR_NO) || '%'" ).append("\n"); 
		query.append("			    ), '') R_QTY" ).append("\n"); 
		query.append("			  ,NVL2(CC.RAIL_CRR_REF_NO, ( SELECT " ).append("\n"); 
		query.append("					NVL(" ).append("\n"); 
		query.append("			        SUM(DECODE(DSPO_CD, '1C', CNTR_QTY, 0)) " ).append("\n"); 
		query.append("			      + SUM(DECODE(DSPO_CD, '1W', CNTR_QTY, 0)) " ).append("\n"); 
		query.append("			      - SUM(DECODE(DSPO_CD, '4E', CNTR_QTY, 0)), 0)" ).append("\n"); 
		query.append("		         FROM BKG_CSTMS_ADV_CNTR_RSLT CRQ" ).append("\n"); 
		query.append("			    WHERE PCNTR.CNT_CD = CRQ.CNT_CD" ).append("\n"); 
		query.append("				  AND PCNTR.BL_NO = CRQ.BL_NO" ).append("\n"); 
		query.append("			      AND PCNTR.CNTR_NO  LIKE TRIM(CRQ.CNTR_NO) || '%'" ).append("\n"); 
		query.append("			    ), '') RLSE_QTY" ).append("\n"); 
		query.append("			  ,(SELECT 'Y' FROM TRS_TRSP_RAIL_BIL_ORD TR" ).append("\n"); 
		query.append("				WHERE TR.BKG_NO = PBL.BKG_NO" ).append("\n"); 
		query.append("				AND TR.EQ_NO = PCNTR.CNTR_NO" ).append("\n"); 
		query.append("				AND TR.TRSP_SO_STS_CD = 'I' " ).append("\n"); 
		query.append("				AND DELT_FLG ='N'" ).append("\n"); 
		query.append("				AND ROWNUM=1" ).append("\n"); 
		query.append("				) R_BILLING" ).append("\n"); 
		query.append("			  ,'' FEU" ).append("\n"); 
		query.append("			  ,'' TEU" ).append("\n"); 
		query.append("              ,BKG_JOIN_FNC(CURSOR(SELECT SUM(RS.CNTR_QTY * DECODE(CD.ATTR_CTNT2, 'MINUS', -1, 1)) AS J_QTY" ).append("\n"); 
		query.append("                                     FROM BKG_CSTMS_ADV_RSLT RS" ).append("\n"); 
		query.append("                                         ,BKG_CSTMS_CD_CONV_CTNT CD" ).append("\n"); 
		query.append("                                    WHERE RS.CNT_CD        = A.CNT_CD" ).append("\n"); 
		query.append("                                      AND RS.BL_NO         = A.BL_NO" ).append("\n"); 
		query.append("                                      AND RS.CNT_CD        = CD.CNT_CD(+)" ).append("\n"); 
		query.append("                                      AND RS.DSPO_CD       = CD.ATTR_CTNT3(+)" ).append("\n"); 
		query.append("                                      AND NVL(RS.RSND_FLG, 'N') <> 'Y'" ).append("\n"); 
		query.append("                                      AND RS.BL_NVOCC_TP_CD = 'M'" ).append("\n"); 
		query.append("                                      AND CD.CSTMS_DIV_ID = 'CARGO_RLS_J_CD'" ).append("\n"); 
		query.append("                                 GROUP BY SUBSTR(RS.ENTR_NO, 1, 3)" ).append("\n"); 
		query.append("                                  )) AS J_QTY" ).append("\n"); 
		query.append("               ,A.PCK_QTY" ).append("\n"); 
		query.append("               ,(SELECT SUM(RS.CNTR_QTY) AS C_QTY" ).append("\n"); 
		query.append("                   FROM BKG_CSTMS_ADV_RSLT RS" ).append("\n"); 
		query.append("                  WHERE RS.CNT_CD        = A.CNT_CD" ).append("\n"); 
		query.append("                    AND RS.BL_NO         = A.BL_NO" ).append("\n"); 
		query.append("                    AND NVL(RS.RSND_FLG, 'N') <> 'Y'" ).append("\n"); 
		query.append("                    AND RS.BL_NVOCC_TP_CD = 'M'" ).append("\n"); 
		query.append("                    AND RS.DSPO_CD = '1C'" ).append("\n"); 
		query.append("                ) AS C_QTY" ).append("\n"); 
		query.append("          FROM BKG_CSTMS_ADV_BL A" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_IBD IBD" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_CNTR E " ).append("\n"); 
		query.append("			  ,BKG_CSTMS_ADV_BL PBL" ).append("\n"); 
		query.append("			  ,BKG_CSTMS_ADV_CNTR PCNTR " ).append("\n"); 
		query.append("			  ,BKG_BOOKING BR " ).append("\n"); 
		query.append("			  ,BKG_CONTAINER BC" ).append("\n"); 
		query.append("			  ,BKG_CGO_RLSE B" ).append("\n"); 
		query.append("			  ,BKG_CSTMS_ADV_CNTR_RSLT CR" ).append("\n"); 
		query.append("			  ,BKG_PKUP_NTC SPF" ).append("\n"); 
		query.append("			  ,BKG_CSTMS_ADV_CNTR CC" ).append("\n"); 
		query.append("			  ,BKG_CSTMS_ADV_DSPO AD" ).append("\n"); 
		query.append("              ,MDM_LOCATION LO" ).append("\n"); 
		query.append("			  ,VSK_VSL_PORT_SKD VS" ).append("\n"); 
		query.append("         WHERE A.CNT_CD  = 'US'" ).append("\n"); 
		query.append("		   AND A.MF_STS_CD     	 = 'A'" ).append("\n"); 
		query.append("		   AND A.CNT_CD       	 = E.CNT_CD" ).append("\n"); 
		query.append("		   AND A.BL_NO         	 = E.BL_NO" ).append("\n"); 
		query.append("		   AND PBL.CNT_CD        = PCNTR.CNT_CD" ).append("\n"); 
		query.append("		   AND PBL.BL_NO         = PCNTR.BL_NO" ).append("\n"); 
		query.append("		   AND PCNTR.CNT_CD      = E.CNT_CD" ).append("\n"); 
		query.append("		   AND PCNTR.CNTR_NO     = E.CNTR_NO" ).append("\n"); 
		query.append("        #if (${mbl_no} == '')" ).append("\n"); 
		query.append("		   AND PBL.BL_NO       	 = A.BL_NO" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("		   AND PBL.VSL_CD        = A.VSL_CD" ).append("\n"); 
		query.append("		   AND PBL.SKD_VOY_NO    = A.SKD_VOY_NO" ).append("\n"); 
		query.append("		   AND PBL.SKD_DIR_CD    = A.SKD_DIR_CD" ).append("\n"); 
		query.append("		   AND PBL.MF_STS_CD     = 'A'" ).append("\n"); 
		query.append("		   AND PBL.MF_NO IS NULL" ).append("\n"); 
		query.append("		   AND A.MF_NO IS NULL" ).append("\n"); 
		query.append("		   AND PBL.BKG_NO = BR.BKG_NO" ).append("\n"); 
		query.append("		   AND PBL.BL_NO = B.BL_NO(+)" ).append("\n"); 
		query.append("		   AND PCNTR.CNT_CD = CR.CNT_CD(+)" ).append("\n"); 
		query.append("		   AND PCNTR.BL_NO= CR.BL_NO(+)" ).append("\n"); 
		query.append("		   AND PCNTR.CNTR_NO  LIKE TRIM(CR.CNTR_NO(+)) || '%'" ).append("\n"); 
		query.append("		   AND ( CR.CSTMS_SEQ IS NULL" ).append("\n"); 
		query.append("      				OR CR.CSTMS_SEQ = (" ).append("\n"); 
		query.append("                        SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                        FROM BKG_CSTMS_ADV_CNTR_RSLT" ).append("\n"); 
		query.append("                        WHERE BL_NO = CR.BL_NO" ).append("\n"); 
		query.append("                          AND CNT_CD = CR.CNT_CD" ).append("\n"); 
		query.append("                          AND CNTR_NO LIKE SUBSTR(TRIM(CR.CNTR_NO), 1, 10) || '%' ) )" ).append("\n"); 
		query.append("  		  AND BR.BKG_NO = SPF.BKG_NO(+)" ).append("\n"); 
		query.append("		  AND ( SPF.NTC_SEQ IS NULL" ).append("\n"); 
		query.append("		      OR SPF.NTC_SEQ =(" ).append("\n"); 
		query.append("        		SELECT MAX(NTC_SEQ)" ).append("\n"); 
		query.append("		        FROM BKG_PKUP_NTC" ).append("\n"); 
		query.append("		        WHERE BKG_NO = BR.BKG_NO ) )  " ).append("\n"); 
		query.append("		  AND CC.CNT_CD = 'CA'" ).append("\n"); 
		query.append("		  AND PCNTR.BL_NO = CC.BL_NO" ).append("\n"); 
		query.append("		  AND PCNTR.CNTR_NO = CC.CNTR_NO" ).append("\n"); 
		query.append("		  AND CR.CNT_CD = AD.CNT_CD(+)" ).append("\n"); 
		query.append("		  AND CR.DSPO_CD = AD.CSTMS_DSPO_CD(+)" ).append("\n"); 
		query.append("		  AND PBL.CNT_CD = IBD.CNT_CD" ).append("\n"); 
		query.append("		  AND PBL.BL_NO = IBD.BL_NO" ).append("\n"); 
		query.append("		  AND BR.BKG_NO = BC.BKG_NO" ).append("\n"); 
		query.append("		  AND PCNTR.CNTR_NO = BC.CNTR_NO" ).append("\n"); 
		query.append(" 		  AND VS.VSL_CD(+) = PBL.VSL_CD" ).append("\n"); 
		query.append("		  AND VS.SKD_VOY_NO(+) = PBL.SKD_VOY_NO" ).append("\n"); 
		query.append("		  AND VS.SKD_DIR_CD(+) = PBL.SKD_DIR_CD" ).append("\n"); 
		query.append("		  AND VS.VPS_PORT_CD(+) =PBL.POD_CD" ).append("\n"); 
		query.append("		  AND ( VS.CLPT_IND_SEQ IS NULL" ).append("\n"); 
		query.append("                    OR VS.CLPT_IND_SEQ =(SELECT MAX(CLPT_IND_SEQ)" ).append("\n"); 
		query.append("                          FROM VSK_VSL_PORT_SKD" ).append("\n"); 
		query.append("                         WHERE VSL_CD = PBL.VSL_CD" ).append("\n"); 
		query.append("                           AND SKD_VOY_NO = PBL.SKD_VOY_NO" ).append("\n"); 
		query.append("                           AND SKD_DIR_CD = PBL.SKD_DIR_CD" ).append("\n"); 
		query.append("                           AND VPS_PORT_CD =PBL.POD_CD) )" ).append("\n"); 
		query.append("		   #if (${sc_no} != '')" ).append("\n"); 
		query.append("             AND BR.SC_NO = @[sc_no]" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("		   #if (${cntr_tp} != '')" ).append("\n"); 
		query.append("             AND E.CNTR_TPSZ_CD = @[cntr_tp]" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("		   #if (${cntr_no} != '')" ).append("\n"); 
		query.append("             AND E.CNTR_NO = @[cntr_no]" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("		#if (${customs_result_code_grp} == 'WP')" ).append("\n"); 
		query.append("		  AND CR.ENTR_NO LIKE BKG_GET_BKG_CTMS_CD_FNC('US','AMS_ASGN_CO_CD',1,1)||'%'" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("           AND A.DEL_CD  = LO.LOC_CD" ).append("\n"); 
		query.append("        #if (${tmp3} != '')" ).append("\n"); 
		query.append("--             AND A.CNT_CD = CR.CNT_CD(+)" ).append("\n"); 
		query.append("--             AND A.BL_NO  = CR.BL_NO(+)" ).append("\n"); 
		query.append("            #if (${tmp3} == '2Z')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD = '2Z'" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                AND  CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '6H6I')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     CR.CSTMS_SEQ IN (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD IN ('6H','6I')" ).append("\n"); 
		query.append("                                  GROUP BY DSPO_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '3Z')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     NOT EXISTS (SELECT CSTMS_SEQ" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                    AND BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                    AND DSPO_CD = '3Z'" ).append("\n"); 
		query.append("                                 )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                    )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '2Q4Q')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     CR.CSTMS_SEQ IN (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD IN ('2Q','4Q')" ).append("\n"); 
		query.append("                                  GROUP BY DSPO_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '2R4R')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     CR.CSTMS_SEQ IN (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD IN ('2R','4R')" ).append("\n"); 
		query.append("                                  GROUP BY DSPO_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("        #elseif (${customs_result_code} != '')" ).append("\n"); 
		query.append("--             AND A.CNT_CD = CR.CNT_CD" ).append("\n"); 
		query.append("--             AND A.BL_NO  = CR.BL_NO" ).append("\n"); 
		query.append("             AND " ).append("\n"); 
		query.append("				  #if (${final_flg} == '1')" ).append("\n"); 
		query.append("				  (" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = PBL.CNT_CD                                   " ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("				  )" ).append("\n"); 
		query.append("				  AND C.DSPO_CD = @[customs_result_code]" ).append("\n"); 
		query.append("				  #else" ).append("\n"); 
		query.append("                  ( " ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                    AND DSPO_CD = @[customs_result_code]" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("				  )" ).append("\n"); 
		query.append("				  #end	" ).append("\n"); 
		query.append("        #elseif (${customs_result_code_grp} != '' && ${customs_result_code_grp} != 'ALL')" ).append("\n"); 
		query.append("--             AND A.CNT_CD = CR.CNT_CD" ).append("\n"); 
		query.append("--             AND A.BL_NO  = CR.BL_NO" ).append("\n"); 
		query.append("             AND " ).append("\n"); 
		query.append("                 #if (${final_flg} == '1')" ).append("\n"); 
		query.append("				 (" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT R" ).append("\n"); 
		query.append("                                       ,BKG_CSTMS_ADV_DSPO D" ).append("\n"); 
		query.append("                                  WHERE R.BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = D.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.DSPO_CD = D.CSTMS_DSPO_CD" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                 )" ).append("\n"); 
		query.append("				 AND CR.DSPO_CD IN ( SELECT CSTMS_DSPO_CD FROM BKG_CSTMS_ADV_DSPO WHERE DSPO_TP_CD = @[customs_result_code_grp] )" ).append("\n"); 
		query.append("				 #else                " ).append("\n"); 
		query.append("				 (" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT R" ).append("\n"); 
		query.append("                                       ,BKG_CSTMS_ADV_DSPO D" ).append("\n"); 
		query.append("                                  WHERE R.BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = D.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.DSPO_CD = D.CSTMS_DSPO_CD" ).append("\n"); 
		query.append("                                    AND D.DSPO_TP_CD = @[customs_result_code_grp]" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                  )" ).append("\n"); 
		query.append("				  #end" ).append("\n"); 
		query.append("        #elseif (${tmp1} == 'C')" ).append("\n"); 
		query.append("--             AND A.CNT_CD = CR.CNT_CD (+)" ).append("\n"); 
		query.append("--             AND A.BL_NO  = CR.BL_NO (+)" ).append("\n"); 
		query.append("             AND (" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ IS NULL" ).append("\n"); 
		query.append("                  OR" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                 )" ).append("\n"); 
		query.append("                  )" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("--             AND A.CNT_CD = CR.CNT_CD" ).append("\n"); 
		query.append("--             AND A.BL_NO  = CR.BL_NO" ).append("\n"); 
		query.append("             AND (" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = PBL.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = PBL.CNT_CD" ).append("\n"); 
		query.append("                                 )" ).append("\n"); 
		query.append("                  )" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("        #if (${excl_rls} == '01') --Excl.Rls" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') NOT IN ('Y', 'W', 'T', 'E')" ).append("\n"); 
		query.append("        #elseif (${excl_rls} == '02')  --Excl.Rls + 1J" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') NOT IN ('Y', 'W', 'T', 'E', 'J', 'V', 'I')" ).append("\n"); 
		query.append("        #elseif (${excl_rls} == '03')  --Rls" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') IN ('Y', 'W', 'T', 'E')" ).append("\n"); 
		query.append("        #elseif (${excl_rls} == '04')  --Rls + 1J" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') IN ('Y', 'W', 'T', 'E', 'J', 'V', 'I')" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("        #if (${mbl_no} != '')" ).append("\n"); 
		query.append("                AND (A.MF_NO = @[mbl_no] OR A.BL_NO = @[mbl_no])" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("            #if (${ams_file_no} != '')" ).append("\n"); 
		query.append("                AND A.BL_NO = @[ams_file_no]" ).append("\n"); 
		query.append("            #else" ).append("\n"); 
		query.append("                #if (${vvd} != '')" ).append("\n"); 
		query.append("                    AND A.VSL_CD = SUBSTR(@[vvd],1,4)" ).append("\n"); 
		query.append("                    AND A.SKD_VOY_NO = SUBSTR(@[vvd], 5, 4)" ).append("\n"); 
		query.append("                    AND A.SKD_DIR_CD = SUBSTR(@[vvd], 9, 1)" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${pod} != '')" ).append("\n"); 
		query.append("                    AND A.CSTMS_POD_CD = @[pod]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${pol} != '')" ).append("\n"); 
		query.append("                    AND A.CSTMS_POL_CD = @[pol]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${del} != '')" ).append("\n"); 
		query.append("                    AND A.DEL_CD = @[del]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${hub} != '')" ).append("\n"); 
		query.append("                    AND A.HUB_LOC_CD = @[hub]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${rcv_term_cd} != '')" ).append("\n"); 
		query.append("                    AND A.RCV_TERM_CD = @[rcv_term_cd]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${de_term_cd} != '')" ).append("\n"); 
		query.append("                    AND A.DE_TERM_CD = @[de_term_cd]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("		#if (${eq_ofc} != '' && ${eq_ofc} != 'ALL') " ).append("\n"); 
		query.append("	    AND LO.EQ_CTRL_OFC_CD  IN ( " ).append("\n"); 
		query.append("			#foreach($eqofc in ${vel_eq_ofc})  " ).append("\n"); 
		query.append("				'$eqofc',  " ).append("\n"); 
		query.append("				#end  " ).append("\n"); 
		query.append("				'') " ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("                #if (${b_stf} != '')" ).append("\n"); 
		query.append("                    AND BR.DOC_USR_ID = @[b_stf]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${l_rep} != '')" ).append("\n"); 
		query.append("                    AND BR.OB_SREP_CD = @[l_rep]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${filer} != '')" ).append("\n"); 
		query.append("                    AND (${filer})" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                #if (${pmib_tp} == '61' || ${pmib_tp} == '62' || ${pmib_tp} == '63')" ).append("\n"); 
		query.append("                    AND IBD.IBD_TRSP_TP_CD = @[pmib_tp]" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'I' || ${pmib_tp} == 'L')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = @[pmib_tp]" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'IL')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'L'" ).append("\n"); 
		query.append("                    AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'Y'" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'LI')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'I'" ).append("\n"); 
		query.append("                    AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'N'" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'IPIL')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'L'" ).append("\n"); 
		query.append("                    --AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'Y'" ).append("\n"); 
		query.append("                    AND EXISTS (SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RSLT RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.DSPO_CD IN ('1J', '1W')" ).append("\n"); 
		query.append("                                UNION ALL" ).append("\n"); 
		query.append("                                SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RCV_LOG RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO  = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.RCV_MSG_TP_ID = 'TR'" ).append("\n"); 
		query.append("                               )" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'IPILY')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'L'" ).append("\n"); 
		query.append("                    --AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'Y'" ).append("\n"); 
		query.append("                    AND EXISTS (SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RSLT RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.DSPO_CD IN ('1J', '1W')" ).append("\n"); 
		query.append("                                UNION ALL" ).append("\n"); 
		query.append("                                SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RCV_LOG RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO  = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.RCV_MSG_TP_ID = 'TR'" ).append("\n"); 
		query.append("                               )" ).append("\n"); 
		query.append("                    AND B.CSTMS_CLR_CD = 'Y'" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'CYN')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_CNG_FLG = 'Y'" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                #if (${date_search} != '' && ${cust_arr_exp} != '' && ${fromd} != '' && ${tod} != '')" ).append("\n"); 
		query.append("                    #if (${cust_arr_exp} == 'RCV')" ).append("\n"); 
		query.append("                        AND CR.RCV_DT" ).append("\n"); 
		query.append("                            BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                    #elseif (${cust_arr_exp} == 'ARR')" ).append("\n"); 
		query.append("                        AND (" ).append("\n"); 
		query.append("                                ER.ARR_DT" ).append("\n"); 
		query.append("                                BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                OR" ).append("\n"); 
		query.append("                                (" ).append("\n"); 
		query.append("                                ER.ARR_DT IS NULL" ).append("\n"); 
		query.append("                                AND" ).append("\n"); 
		query.append("                                IBD.IBD_TRSP_ARR_DT" ).append("\n"); 
		query.append("                                BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                            )" ).append("\n"); 
		query.append("                    #elseif (${cust_arr_exp} == 'EXP')" ).append("\n"); 
		query.append("                        AND (" ).append("\n"); 
		query.append("                                E.XPT_DT" ).append("\n"); 
		query.append("                                BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                OR" ).append("\n"); 
		query.append("                                (" ).append("\n"); 
		query.append("                                E.XPT_DT IS NULL" ).append("\n"); 
		query.append("                                AND IBD.IBD_TRSP_XPT_DT" ).append("\n"); 
		query.append("                                 BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI') " ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                            )" ).append("\n"); 
		query.append("					#elseif (${cust_arr_exp} == 'ETA')" ).append("\n"); 
		query.append("						AND VS.VPS_ETA_DT" ).append("\n"); 
		query.append("                            BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                    #end" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("	#if (${cntr_prt_flg} == '1')" ).append("\n"); 
		query.append("		AND BC.CNTR_VOL_QTY != 1  " ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       ) TB" ).append("\n"); 
		query.append("      ,BKG_CSTMS_ADV_CUST CUST" ).append("\n"); 
		query.append("  WHERE TB.RNUM BETWEEN @[start_no] AND @[end_no]" ).append("\n"); 
		query.append("	AND TB.CNT_CD = CUST.CNT_CD(+)" ).append("\n"); 
		query.append("	AND TB.AMS_FILE_NO = CUST.BL_NO(+)" ).append("\n"); 
		query.append("	AND TB.BKG_CUST_TP_CD = CUST.BKG_CUST_TP_CD(+)" ).append("\n"); 
		query.append("	#if (${customer_cd} != '')" ).append("\n"); 
		query.append("	  AND CUST.CUST_CNT_CD||CUST.CUST_SEQ = @[customer_cd]" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("	#if (${rbilling_yn} == 'Y')" ).append("\n"); 
		query.append("	  AND TB.R_BILLING = 'Y'" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("    #if (${excl_rls} == '05')  --Excl + 1C" ).append("\n"); 
		query.append("      AND (TB.C_QTY <> TB.PCK_QTY" ).append("\n"); 
		query.append("            OR TB.C_QTY IS NULL" ).append("\n"); 
		query.append("          )" ).append("\n"); 
		query.append("    #elseif (${excl_rls} == '06')  --H at POD" ).append("\n"); 
		query.append("      AND TB.DSPO_CD IN (SELECT A.CSTMS_DSPO_CD" ).append("\n"); 
		query.append("                          FROM  BKG_CSTMS_ADV_DSPO A" ).append("\n"); 
		query.append("                               ,BKG_CSTMS_CD_CONV_CTNT B" ).append("\n"); 
		query.append("                         WHERE  A.CNT_CD = B.CNT_CD(+)" ).append("\n"); 
		query.append("                           AND  A.CSTMS_DSPO_CD = B.ATTR_CTNT3(+)" ).append("\n"); 
		query.append("                           AND  B.CSTMS_DIV_ID(+) = 'CARGO_RLS_H_CD'" ).append("\n"); 
		query.append("                           AND  A.CNT_CD = 'US'" ).append("\n"); 
		query.append("                           AND  A.DSPO_TP_CD = 'HP')" ).append("\n"); 
		query.append("    #elseif (${excl_rls} == '07')  --C Status is H" ).append("\n"); 
		query.append("      AND TB.CSTMS_CLR_CD = 'H'" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#else" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("SELECT TB.*" ).append("\n"); 
		query.append("      ,'' AS SEQ" ).append("\n"); 
		query.append("      ,REPLACE(REPLACE(REPLACE(CUST.CUST_NM, CHR(13)||CHR(10),' '), CHR(13), ' '), CHR(10), ' ') AS CUST_NM" ).append("\n"); 
		query.append("  FROM (" ).append("\n"); 
		query.append("        SELECT COUNT(*) OVER() AS TOTAL" ).append("\n"); 
		query.append("              ,A.CNT_CD" ).append("\n"); 
		query.append("              ,NVL(C.DSPO_CD,' ') AS DSPO_CD" ).append("\n"); 
		query.append("              ,BR.BL_NO AS MBL_NO" ).append("\n"); 
		query.append("              ,A.BL_NO  AS AMS_FILE_NO" ).append("\n"); 
		query.append("              ,DECODE(A.MF_NO, NULL, A.CSTMS_FILE_TP_CD, '0') FILER" ).append("\n"); 
		query.append("              ,A.MF_STS_CD" ).append("\n"); 
		query.append("              ,A.CSTMS_MF_TP_CD" ).append("\n"); 
		query.append("              ,A.POD_CD" ).append("\n"); 
		query.append("              ,A.DEL_CD" ).append("\n"); 
		query.append("              ,A.HUB_LOC_CD" ).append("\n"); 
		query.append("              ,E.CNTR_NO" ).append("\n"); 
		query.append("              --,(SELECT DECODE(CNTR_VOL_QTY, 1, 'N', 'Y') FROM BKG_CONTAINER	WHERE BKG_NO = BR.BKG_NO AND CNTR_NO = E.CNTR_NO) CNTR_PRT_FLG" ).append("\n"); 
		query.append("			  ,DECODE(BC.CNTR_VOL_QTY, 1, 'N', 'Y') CNTR_PRT_FLG" ).append("\n"); 
		query.append("              ,E.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("              ,NVL(B.FRT_CLT_FLG, 'N') AS FRT_CLT_FLG" ).append("\n"); 
		query.append("              ,NVL(B.OBL_RDEM_FLG, 'N') AS OBL_RDEM_FLG" ).append("\n"); 
		query.append("              ,IBD.IBD_TRSP_NO" ).append("\n"); 
		query.append("              ,IBD.IBD_TRSP_TP_CD" ).append("\n"); 
		query.append("              ,IBD.FREE_TRD_ZN_FLG" ).append("\n"); 
		query.append("              ,TO_CHAR(IBD.IBD_TRSP_ISS_DT, 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ISS_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(IBD.IBD_TRSP_ACPT_DT, 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ACPT_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.ARR_DT, IBD.IBD_TRSP_ARR_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ARR_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.CGO_ARR_ACPT_DT, IBD.IBD_TRSP_ARR_ACPT_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_ARR_ACPT_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.XPT_DT, IBD.IBD_TRSP_XPT_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_XPT_DT" ).append("\n"); 
		query.append("              ,TO_CHAR(NVL(E.XPT_ACPT_DT, IBD.IBD_TRSP_XPT_ACPT_DT), 'YYYY-MM-DD HH24:MI') AS IBD_TRSP_XPT_ACPT_DT" ).append("\n"); 
		query.append("              ,A.RCV_TERM_CD" ).append("\n"); 
		query.append("              ,A.DE_TERM_CD" ).append("\n"); 
		query.append("              ,TO_CHAR(C.ARR_DT, 'YYYY-MM-DD HH24:MI') AS ARR_DT" ).append("\n"); 
		query.append("              ,BR.SC_NO" ).append("\n"); 
		query.append("              ,AD.CSTMS_DSPO_NM" ).append("\n"); 
		query.append("              ,A.CSTMS_POL_CD POL_CD" ).append("\n"); 
		query.append("              ,A.BKG_NO" ).append("\n"); 
		query.append("              ,A.VSL_CD||A.SKD_VOY_NO||A.SKD_DIR_CD AS VVD" ).append("\n"); 
		query.append("        #if(${general_or_rail} == 'RAILAMS')" ).append("\n"); 
		query.append("              ,CC.RAIL_CRR_REF_NO" ).append("\n"); 
		query.append("              ,CC.USA_IB_TRSP_NO" ).append("\n"); 
		query.append("              ,SPF.PKUP_NO" ).append("\n"); 
		query.append("              ,DECODE(SPF.NTFC_DT, NULL, 'N', 'Y') AS PKUP_RELEASED" ).append("\n"); 
		query.append("              ,TO_CHAR(SPF.NTFC_DT, 'YYYY-MM-DD HH24:MI') AS PKUP_DATE" ).append("\n"); 
		query.append("              ,CASE WHEN A.CSTMS_POD_CD NOT LIKE 'US%' AND A.DEL_CD LIKE 'US%' THEN NVL(CR.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("                    ELSE NVL(B.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("               END CSTMS_CLR_CD" ).append("\n"); 
		query.append("			  ,CASE WHEN A.CSTMS_POD_CD NOT LIKE 'US%' AND A.DEL_CD LIKE 'US%' THEN NVL(CR.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("                    ELSE NVL(B.CSTMS_CLR_CD, 'N')" ).append("\n"); 
		query.append("               END C_FLAG" ).append("\n"); 
		query.append("			  ,DECODE( CC.RAIL_CRR_REF_NO , NULL, '', 'Y' ) MASTER" ).append("\n"); 
		query.append("			  ,CASE WHEN NVL(B.CSTMS_CLR_CD, 'N') IN ('Y', 'W', 'T', 'E')  THEN 'Y' ELSE 'N' END RLSE_EDI" ).append("\n"); 
		query.append("			  ,'' SUM_CM_QTY" ).append("\n"); 
		query.append("			  ,'' R_QTY" ).append("\n"); 
		query.append("			  ,'' RLSE_QTY" ).append("\n"); 
		query.append("			  ,'' R_BILLING" ).append("\n"); 
		query.append("			  ,DECODE( E.CNTR_TPSZ_CD , 'X2', 1, 0 ) FEU" ).append("\n"); 
		query.append("			  ,DECODE( E.CNTR_TPSZ_CD , 'X2', 0, 1 ) TEU" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("              ,'' RAIL_CRR_REF_NO" ).append("\n"); 
		query.append("              ,'' USA_IB_TRSP_NO" ).append("\n"); 
		query.append("              ,'' PKUP_NO" ).append("\n"); 
		query.append("              ,'' PKUP_RELEASED" ).append("\n"); 
		query.append("              ,'' PKUP_DATE" ).append("\n"); 
		query.append("              ,NVL(B.CSTMS_CLR_CD, 'N') AS CSTMS_CLR_CD" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("              ,ROW_NUMBER() OVER(ORDER BY E.BL_NO, E.CNTR_NO) AS RNUM" ).append("\n"); 
		query.append("              ,DECODE(A.MF_NO, NULL, DECODE(BR.CUST_TO_ORD_FLG, 'Y', 'N', 'C'), 'C') AS BKG_CUST_TP_CD" ).append("\n"); 
		query.append("              ,COUNT(DISTINCT A.BL_NO) OVER() AS BL_CNT" ).append("\n"); 
		query.append("              ,BKG_JOIN_FNC(CURSOR(SELECT SUM(RS.CNTR_QTY * DECODE(CD.ATTR_CTNT2, 'MINUS', -1, 1)) AS J_QTY" ).append("\n"); 
		query.append("                                     FROM BKG_CSTMS_ADV_RSLT RS" ).append("\n"); 
		query.append("                                         ,BKG_CSTMS_CD_CONV_CTNT CD" ).append("\n"); 
		query.append("                                    WHERE RS.CNT_CD        = A.CNT_CD" ).append("\n"); 
		query.append("                                      AND RS.BL_NO         = A.BL_NO" ).append("\n"); 
		query.append("                                      AND RS.CNT_CD        = CD.CNT_CD(+)" ).append("\n"); 
		query.append("                                      AND RS.DSPO_CD       = CD.ATTR_CTNT3(+)" ).append("\n"); 
		query.append("                                      AND NVL(RS.RSND_FLG, 'N') <> 'Y'" ).append("\n"); 
		query.append("                                      AND RS.BL_NVOCC_TP_CD = 'M'" ).append("\n"); 
		query.append("                                      AND CD.CSTMS_DIV_ID = 'CARGO_RLS_J_CD'" ).append("\n"); 
		query.append("                                 GROUP BY SUBSTR(RS.ENTR_NO, 1, 3)" ).append("\n"); 
		query.append("                                  )) AS J_QTY" ).append("\n"); 
		query.append("               ,A.PCK_QTY" ).append("\n"); 
		query.append("               ,(SELECT SUM(RS.CNTR_QTY) AS C_QTY" ).append("\n"); 
		query.append("                   FROM BKG_CSTMS_ADV_RSLT RS" ).append("\n"); 
		query.append("                  WHERE RS.CNT_CD        = A.CNT_CD" ).append("\n"); 
		query.append("                    AND RS.BL_NO         = A.BL_NO" ).append("\n"); 
		query.append("                    AND NVL(RS.RSND_FLG, 'N') <> 'Y'" ).append("\n"); 
		query.append("                    AND RS.BL_NVOCC_TP_CD = 'M'" ).append("\n"); 
		query.append("                    AND RS.DSPO_CD = '1C'" ).append("\n"); 
		query.append("                ) AS C_QTY" ).append("\n"); 
		query.append("          FROM BKG_CSTMS_ADV_BL A" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_IBD IBD" ).append("\n"); 
		query.append("              ,BKG_CGO_RLSE B" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_RSLT C" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_CNTR E" ).append("\n"); 
		query.append("              ,BKG_BOOKING BR" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_DSPO AD" ).append("\n"); 
		query.append("              ,MDM_LOCATION LO" ).append("\n"); 
		query.append("              ,MDM_LOCATION LO1" ).append("\n"); 
		query.append("			  ,BKG_CONTAINER BC" ).append("\n"); 
		query.append("        #if(${general_or_rail} == 'RAILAMS')" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_CNTR_RSLT CR" ).append("\n"); 
		query.append("              ,BKG_CSTMS_ADV_CNTR  CC" ).append("\n"); 
		query.append("              ,BKG_PKUP_NTC SPF" ).append("\n"); 
		query.append("			  ,VSK_VSL_PORT_SKD VS" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("		#if (${rhq} != '')" ).append("\n"); 
		query.append("			,(" ).append("\n"); 
		query.append("			SELECT OFC_N2ND_LVL_CD REGION , OFC_N8TH_LVL_CD OFC_CD" ).append("\n"); 
		query.append("			FROM (" ).append("\n"); 
		query.append("			SELECT OFC_KIND OFC_KND_CD , A.DEL , A.OFC_CD OFC_N8TH_LVL_CD , L1 OFC_LVL , DECODE(A.L1, 1, A.OFC_CD, 2, A.OFC_CD, 3, A.OFC_CD, 4, A.OFC_CD, 5, A.OFC_CD, 6, A.OFC_CD, 7, A.OFC_CD, 8, B.OFC_CD) OFC_N7TH_LVL_CD , DECODE(A.L1, 1, A.OFC_CD, 2, A.OFC_CD, 3, A.OFC_CD, 4, A.OFC_CD, 5, A.OFC_CD, 6, A.OFC_CD, 7, B.OFC_CD, 8, C.OFC_CD) OFC_N6TH_LVL_CD , DECODE(A.L1, 1, A.OFC_CD, 2, A.OFC_CD, 3, A.OFC_CD, 4, A.OFC_CD, 5, A.OFC_CD, 6, B.OFC_CD, 7, C.OFC_CD, 8, D.OFC_CD) OFC_N5TH_LVL_CD , DECODE(A.L1, 1, A.OFC_CD, 2, A.OFC_CD, 3, A.OFC_CD, 4, A.OFC_CD, 5, B.OFC_CD, 6, C.OFC_CD, 7, D.OFC_CD, 8, E.OFC_CD) OFC_N4TH_LVL_CD , DECODE(A.L1, 1, A.OFC_CD, 2, A.OFC_CD, 3, A.OFC_CD, 4, B.OFC_CD, 5, C.OFC_CD, 6, D.OFC_CD, 7, E.OFC_CD, 8, F.OFC_CD) OFC_N3RD_LVL_CD , DECODE(A.L1, 1, A.OFC_CD, 2, A.OFC_CD, 3, B.OFC_CD, 4, C.OFC_CD, 5, D.OFC_CD, 6, E.OFC_CD, 7, F.OFC_CD, 8, G.OFC_CD) OFC_N2ND_LVL_CD , DECODE(A.L1, 1, A.OFC_CD, 2, B.OFC_CD, 3, C.OFC_CD, 4, D.OFC_CD, 5, E.OFC_CD, 6, F.OFC_CD, 7, G.OFC_CD, 8, H.OFC_CD) OFC_N1ST_LVL_CD" ).append("\n"); 
		query.append("			FROM (" ).append("\n"); 
		query.append("			SELECT OFC_CD , LOC_CD , PRNT_OFC_CD , DELT_FLG DEL , A.OFC_KND_CD OFC_KIND , LEVEL L1" ).append("\n"); 
		query.append("			FROM MDM_ORGANIZATION A START WITH A.OFC_CD = COM_ConstantMgr_PKG.COM_getHeadOfficeCode_FNC() CONNECT BY PRIOR A.OFC_CD = A.PRNT_OFC_CD ) A , MDM_ORGANIZATION B , MDM_ORGANIZATION C , MDM_ORGANIZATION D , MDM_ORGANIZATION E , MDM_ORGANIZATION F , MDM_ORGANIZATION G , MDM_ORGANIZATION H" ).append("\n"); 
		query.append("			WHERE A.PRNT_OFC_CD = B.OFC_CD(+)" ).append("\n"); 
		query.append("			AND B.PRNT_OFC_CD = C.OFC_CD(+)" ).append("\n"); 
		query.append("			AND C.PRNT_OFC_CD = D.OFC_CD(+)" ).append("\n"); 
		query.append("			AND D.PRNT_OFC_CD = E.OFC_CD(+)" ).append("\n"); 
		query.append("			AND E.PRNT_OFC_CD = F.OFC_CD(+)" ).append("\n"); 
		query.append("			AND F.PRNT_OFC_CD = G.OFC_CD(+)" ).append("\n"); 
		query.append("			AND G.PRNT_OFC_CD = H.OFC_CD(+) )" ).append("\n"); 
		query.append("			WHERE 1=1" ).append("\n"); 
		query.append("			--  AND NVL(DEL, 'N') = 'N'" ).append("\n"); 
		query.append("			--AND OFC_N3RD_LVL_CD IS NOT NULL" ).append("\n"); 
		query.append("			--AND OFC_N3RD_LVL_CD IN (" ).append("\n"); 
		query.append("			--SELECT OFC_CD" ).append("\n"); 
		query.append("			--FROM (" ).append("\n"); 
		query.append("			--SELECT OFC_CD , LOC_CD , PRNT_OFC_CD , DELT_FLG DEL , A.OFC_KND_CD OFC_KIND , LEVEL L1" ).append("\n"); 
		query.append("			--FROM MDM_ORGANIZATION A START WITH A.OFC_CD = COM_ConstantMgr_PKG.COM_getHeadOfficeCode_FNC() CONNECT BY PRIOR A.OFC_CD = A.PRNT_OFC_CD )" ).append("\n"); 
		query.append("			--WHERE L1 =3" ).append("\n"); 
		query.append("			--AND OFC_KIND = '2' )" ).append("\n"); 
		query.append("			--AND OFC_N6TH_LVL_CD IS NOT NULL" ).append("\n"); 
		query.append("			) OLA" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("         WHERE A.CNT_CD  = 'US'" ).append("\n"); 
		query.append("           AND A.CNT_CD  = IBD.CNT_CD" ).append("\n"); 
		query.append("           AND A.BL_NO   = IBD.BL_NO" ).append("\n"); 
		query.append("           AND A.BL_NO   = B.BL_NO(+)" ).append("\n"); 
		query.append("           AND C.CNT_CD  = AD.CNT_CD(+)" ).append("\n"); 
		query.append("           AND C.DSPO_CD = AD.CSTMS_DSPO_CD(+)" ).append("\n"); 
		query.append("           AND A.CNT_CD  = E.CNT_CD" ).append("\n"); 
		query.append("           AND A.BL_NO   = E.BL_NO" ).append("\n"); 
		query.append("           AND A.BKG_NO  = BR.BKG_NO" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("           AND BR.BKG_NO = BC.BKG_NO" ).append("\n"); 
		query.append("           AND E.CNTR_NO = BC.CNTR_NO" ).append("\n"); 
		query.append("		#if (${customs_result_code_grp} == 'WP')" ).append("\n"); 
		query.append("		   AND C.ENTR_NO LIKE BKG_GET_BKG_CTMS_CD_FNC('US','AMS_ASGN_CO_CD',1,1)||'%'" ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("           AND A.DEL_CD  = LO.LOC_CD" ).append("\n"); 
		query.append("           AND A.POL_CD  = LO1.LOC_CD" ).append("\n"); 
		query.append("        #if (${general_or_rail} == 'RAILAMS')" ).append("\n"); 
		query.append("           AND E.CNT_CD  = CR.CNT_CD(+)" ).append("\n"); 
		query.append("           AND E.BL_NO   = CR.BL_NO(+)" ).append("\n"); 
		query.append("           AND E.CNTR_NO LIKE TRIM(CR.CNTR_NO(+)) || '%'" ).append("\n"); 
		query.append("           AND (" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ IS NULL" ).append("\n"); 
		query.append("                  OR" ).append("\n"); 
		query.append("                  CR.CSTMS_SEQ =  (" ).append("\n"); 
		query.append("                                      SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                        FROM BKG_CSTMS_ADV_CNTR_RSLT" ).append("\n"); 
		query.append("                                       WHERE BL_NO = E.BL_NO" ).append("\n"); 
		query.append("                                         AND CNT_CD = E.CNT_CD" ).append("\n"); 
		query.append("                                         AND CNTR_NO LIKE SUBSTR(TRIM(E.CNTR_NO), 1, 10) || '%'" ).append("\n"); 
		query.append("                                  )" ).append("\n"); 
		query.append("                )" ).append("\n"); 
		query.append("           AND CC.CNT_CD = 'CA'" ).append("\n"); 
		query.append("           AND E.BL_NO   = CC.BL_NO" ).append("\n"); 
		query.append("           AND E.CNTR_NO = CC.CNTR_NO" ).append("\n"); 
		query.append("           AND A.BKG_NO  = SPF.BKG_NO(+)" ).append("\n"); 
		query.append("           AND (" ).append("\n"); 
		query.append("                  SPF.NTC_SEQ IS NULL" ).append("\n"); 
		query.append("                  OR" ).append("\n"); 
		query.append("                  SPF.NTC_SEQ =(SELECT MAX(NTC_SEQ)" ).append("\n"); 
		query.append("                                  FROM BKG_PKUP_NTC" ).append("\n"); 
		query.append("                                 WHERE BKG_NO = A.BKG_NO" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                 )" ).append("\n"); 
		query.append("           AND SPF.PKUP_NTC_TP_CD(+) > ' '" ).append("\n"); 
		query.append("           AND A.POD_CD NOT LIKE 'US%'" ).append("\n"); 
		query.append("           AND A.DEL_CD LIKE 'US%'" ).append("\n"); 
		query.append("           AND A.MF_NO IS NULL" ).append("\n"); 
		query.append(" 		   AND VS.VSL_CD(+) = A.VSL_CD" ).append("\n"); 
		query.append("		   AND VS.SKD_VOY_NO(+) = A.SKD_VOY_NO" ).append("\n"); 
		query.append("		   AND VS.SKD_DIR_CD(+) = A.SKD_DIR_CD" ).append("\n"); 
		query.append("		   AND VS.VPS_PORT_CD(+) = A.POD_CD" ).append("\n"); 
		query.append("		   AND ( VS.CLPT_IND_SEQ IS NULL" ).append("\n"); 
		query.append("                    OR VS.CLPT_IND_SEQ =(SELECT MAX(CLPT_IND_SEQ)" ).append("\n"); 
		query.append("                          FROM VSK_VSL_PORT_SKD" ).append("\n"); 
		query.append("                         WHERE VSL_CD = A.VSL_CD" ).append("\n"); 
		query.append("                           AND SKD_VOY_NO = A.SKD_VOY_NO" ).append("\n"); 
		query.append("                           AND SKD_DIR_CD = A.SKD_DIR_CD" ).append("\n"); 
		query.append("                           AND VPS_PORT_CD = A.POD_CD) )" ).append("\n"); 
		query.append("		   #if (${sc_no} != '')" ).append("\n"); 
		query.append("             AND BR.SC_NO = @[sc_no]" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("		   #if (${cntr_tp} != '')" ).append("\n"); 
		query.append("             AND E.CNTR_TPSZ_CD = @[cntr_tp]" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("		   #if (${cntr_no} != '')" ).append("\n"); 
		query.append("             AND E.CNTR_NO = @[cntr_no]" ).append("\n"); 
		query.append("           #end" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("        #if (${tmp3} != '')" ).append("\n"); 
		query.append("             AND A.CNT_CD = C.CNT_CD(+)" ).append("\n"); 
		query.append("             AND A.BL_NO  = C.BL_NO(+)" ).append("\n"); 
		query.append("            #if (${tmp3} == '2Z')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD = '2Z'" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                AND  C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '6H6I')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     C.CSTMS_SEQ IN (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD IN ('6H','6I')" ).append("\n"); 
		query.append("                                  GROUP BY DSPO_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '3Z')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     NOT EXISTS (SELECT CSTMS_SEQ" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                    AND BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                    AND DSPO_CD = '3Z'" ).append("\n"); 
		query.append("                                 )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                    )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '2Q4Q')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     C.CSTMS_SEQ IN (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD IN ('2Q','4Q')" ).append("\n"); 
		query.append("                                  GROUP BY DSPO_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #elseif (${tmp3} == '2R4R')" ).append("\n"); 
		query.append("                AND (" ).append("\n"); 
		query.append("                     C.CSTMS_SEQ IN (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                      FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                     WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                       AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                       AND DSPO_CD IN ('2R','4R')" ).append("\n"); 
		query.append("                                  GROUP BY DSPO_CD" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("                     )" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("        #elseif (${customs_result_code} != '')" ).append("\n"); 
		query.append("             AND A.CNT_CD = C.CNT_CD" ).append("\n"); 
		query.append("             AND A.BL_NO  = C.BL_NO" ).append("\n"); 
		query.append("             AND " ).append("\n"); 
		query.append("				  #if (${final_flg} == '1')" ).append("\n"); 
		query.append("				  (" ).append("\n"); 
		query.append("                  C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = A.CNT_CD                                   " ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("				  )" ).append("\n"); 
		query.append("				  AND C.DSPO_CD = @[customs_result_code]" ).append("\n"); 
		query.append("				  #else" ).append("\n"); 
		query.append("                  ( " ).append("\n"); 
		query.append("                  C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                    AND DSPO_CD = @[customs_result_code]" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("				  )" ).append("\n"); 
		query.append("				  #end	" ).append("\n"); 
		query.append("        #elseif (${customs_result_code_grp} != '' && ${customs_result_code_grp} != 'ALL')" ).append("\n"); 
		query.append("             AND A.CNT_CD = C.CNT_CD" ).append("\n"); 
		query.append("             AND A.BL_NO  = C.BL_NO" ).append("\n"); 
		query.append("             AND " ).append("\n"); 
		query.append("                 #if (${final_flg} == '1')" ).append("\n"); 
		query.append("				 (" ).append("\n"); 
		query.append("                  C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT R" ).append("\n"); 
		query.append("                                       ,BKG_CSTMS_ADV_DSPO D" ).append("\n"); 
		query.append("                                  WHERE R.BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = D.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.DSPO_CD = D.CSTMS_DSPO_CD" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                 )" ).append("\n"); 
		query.append("				 AND C.DSPO_CD IN ( SELECT CSTMS_DSPO_CD FROM BKG_CSTMS_ADV_DSPO WHERE DSPO_TP_CD = @[customs_result_code_grp] )" ).append("\n"); 
		query.append("				 #else                " ).append("\n"); 
		query.append("				 (" ).append("\n"); 
		query.append("                  C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT R" ).append("\n"); 
		query.append("                                       ,BKG_CSTMS_ADV_DSPO D" ).append("\n"); 
		query.append("                                  WHERE R.BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.CNT_CD = D.CNT_CD" ).append("\n"); 
		query.append("                                    AND R.DSPO_CD = D.CSTMS_DSPO_CD" ).append("\n"); 
		query.append("                                    AND D.DSPO_TP_CD = @[customs_result_code_grp]" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                  )" ).append("\n"); 
		query.append("				  #end" ).append("\n"); 
		query.append("        #elseif (${tmp1} == 'C')" ).append("\n"); 
		query.append("             AND A.CNT_CD = C.CNT_CD (+)" ).append("\n"); 
		query.append("             AND A.BL_NO  = C.BL_NO (+)" ).append("\n"); 
		query.append("             AND (" ).append("\n"); 
		query.append("                  C.CSTMS_SEQ IS NULL" ).append("\n"); 
		query.append("                  OR" ).append("\n"); 
		query.append("                  C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                 )" ).append("\n"); 
		query.append("                  )" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("             AND A.CNT_CD = C.CNT_CD" ).append("\n"); 
		query.append("             AND A.BL_NO  = C.BL_NO" ).append("\n"); 
		query.append("             AND (" ).append("\n"); 
		query.append("                  C.CSTMS_SEQ = (SELECT MAX( CSTMS_SEQ )" ).append("\n"); 
		query.append("                                   FROM BKG_CSTMS_ADV_RSLT" ).append("\n"); 
		query.append("                                  WHERE BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                    AND CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                 )" ).append("\n"); 
		query.append("                  )" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append("        #if (${excl_rls} == '01') --Excl.Rls" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') NOT IN ('Y', 'W', 'T', 'E')" ).append("\n"); 
		query.append("        #elseif (${excl_rls} == '02')  --Excl.Rls + 1J" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') NOT IN ('Y', 'W', 'T', 'E', 'J', 'V', 'I')" ).append("\n"); 
		query.append("        #elseif (${excl_rls} == '03')  --Rls" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') IN ('Y', 'W', 'T', 'E')" ).append("\n"); 
		query.append("        #elseif (${excl_rls} == '04')  --Rls + 1J" ).append("\n"); 
		query.append("             AND NVL(B.CSTMS_CLR_CD, 'N') IN ('Y', 'W', 'T', 'E', 'J', 'V', 'I')" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("        #if (${mbl_no} != '')" ).append("\n"); 
		query.append("                AND (A.MF_NO = @[mbl_no] OR A.BL_NO = @[mbl_no])" ).append("\n"); 
		query.append("        #else" ).append("\n"); 
		query.append("            #if (${ams_file_no} != '')" ).append("\n"); 
		query.append("                AND A.BL_NO = @[ams_file_no]" ).append("\n"); 
		query.append("            #else" ).append("\n"); 
		query.append("                #if (${vvd} != '')" ).append("\n"); 
		query.append("                    AND A.VSL_CD = SUBSTR(@[vvd],1,4)" ).append("\n"); 
		query.append("                    AND A.SKD_VOY_NO = SUBSTR(@[vvd], 5, 4)" ).append("\n"); 
		query.append("                    AND A.SKD_DIR_CD = SUBSTR(@[vvd], 9, 1)" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${pod} != '')" ).append("\n"); 
		query.append("                    AND A.CSTMS_POD_CD = @[pod]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${pol} != '')" ).append("\n"); 
		query.append("                    AND A.CSTMS_POL_CD = @[pol]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${del} != '')" ).append("\n"); 
		query.append("                    AND A.DEL_CD = @[del]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${hub} != '')" ).append("\n"); 
		query.append("                    AND A.HUB_LOC_CD = @[hub]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${rcv_term_cd} != '')" ).append("\n"); 
		query.append("                    AND A.RCV_TERM_CD = @[rcv_term_cd]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${de_term_cd} != '')" ).append("\n"); 
		query.append("                    AND A.DE_TERM_CD = @[de_term_cd]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("		#if (${eq_ofc} != '' && ${eq_ofc} != 'ALL') " ).append("\n"); 
		query.append("	    AND LO.EQ_CTRL_OFC_CD  IN ( " ).append("\n"); 
		query.append("			#foreach($eqofc in ${vel_eq_ofc})  " ).append("\n"); 
		query.append("				'$eqofc',  " ).append("\n"); 
		query.append("				#end  " ).append("\n"); 
		query.append("				'') " ).append("\n"); 
		query.append("		#end" ).append("\n"); 
		query.append("                #if (${b_stf} != '')" ).append("\n"); 
		query.append("                    AND BR.DOC_USR_ID = @[b_stf]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${l_rep} != '')" ).append("\n"); 
		query.append("                    AND BR.OB_SREP_CD = @[l_rep]" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${rhq} != '')" ).append("\n"); 
		query.append("					AND OLA.OFC_CD = LO1.EQ_CTRL_OFC_CD" ).append("\n"); 
		query.append("					AND OLA.REGION = @[rhq] " ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("                #if (${filer} != '')" ).append("\n"); 
		query.append("                    AND (${filer})" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                #if (${pmib_tp} == '61' || ${pmib_tp} == '62' || ${pmib_tp} == '63')" ).append("\n"); 
		query.append("                    AND IBD.IBD_TRSP_TP_CD = @[pmib_tp]" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'I' || ${pmib_tp} == 'L')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = @[pmib_tp]" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'IL')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'L'" ).append("\n"); 
		query.append("                    AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'Y'" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'LI')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'I'" ).append("\n"); 
		query.append("                    AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'N'" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'IPIL')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'L'" ).append("\n"); 
		query.append("                    --AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'Y'" ).append("\n"); 
		query.append("                    AND EXISTS (SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RSLT RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.DSPO_CD IN ('1J', '1W')" ).append("\n"); 
		query.append("                                UNION ALL" ).append("\n"); 
		query.append("                                SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RCV_LOG RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO  = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.RCV_MSG_TP_ID = 'TR'" ).append("\n"); 
		query.append("                               )" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'IPILY')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_TP_CD = 'L'" ).append("\n"); 
		query.append("                    --AND IBD.LOCL_CLR_IPI_MVMT_FLG = 'Y'" ).append("\n"); 
		query.append("                    AND EXISTS (SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RSLT RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.DSPO_CD IN ('1J', '1W')" ).append("\n"); 
		query.append("                                UNION ALL" ).append("\n"); 
		query.append("                                SELECT '1'" ).append("\n"); 
		query.append("                                  FROM BKG_CSTMS_ADV_RCV_LOG RR" ).append("\n"); 
		query.append("                                 WHERE RR.CNT_CD = A.CNT_CD" ).append("\n"); 
		query.append("                                   AND RR.BL_NO  = A.BL_NO" ).append("\n"); 
		query.append("                                   AND RR.RCV_MSG_TP_ID = 'TR'" ).append("\n"); 
		query.append("                               )" ).append("\n"); 
		query.append("                    AND B.CSTMS_CLR_CD = 'Y'" ).append("\n"); 
		query.append("                #elseif (${pmib_tp} == 'CYN')" ).append("\n"); 
		query.append("                    AND IBD.CSTMS_CLR_CNG_FLG = 'Y'" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                #if (${date_search} != '' && ${cust_arr_exp} != '' && ${fromd} != '' && ${tod} != '')" ).append("\n"); 
		query.append("                    #if (${cust_arr_exp} == 'RCV')" ).append("\n"); 
		query.append("                        AND C.ARR_DT" ).append("\n"); 
		query.append("                            BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                    #elseif (${cust_arr_exp} == 'ARR')" ).append("\n"); 
		query.append("                        AND (" ).append("\n"); 
		query.append("                                E.ARR_DT" ).append("\n"); 
		query.append("                                BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                OR" ).append("\n"); 
		query.append("                                (	" ).append("\n"); 
		query.append("                                E.ARR_DT IS NULL" ).append("\n"); 
		query.append("                                AND" ).append("\n"); 
		query.append("                                IBD.IBD_TRSP_ARR_DT" ).append("\n"); 
		query.append("                                BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                            )" ).append("\n"); 
		query.append("                    #elseif (${cust_arr_exp} == 'EXP')" ).append("\n"); 
		query.append("                        AND (" ).append("\n"); 
		query.append("                                E.XPT_DT" ).append("\n"); 
		query.append("                                BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                OR" ).append("\n"); 
		query.append("                                (" ).append("\n"); 
		query.append("                                E.XPT_DT IS NULL" ).append("\n"); 
		query.append("                                AND IBD.IBD_TRSP_XPT_DT" ).append("\n"); 
		query.append("                                 BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI') " ).append("\n"); 
		query.append("                                    AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                )" ).append("\n"); 
		query.append("                            )" ).append("\n"); 
		query.append("					#elseif (${general_or_rail} == 'RAILAMS' && ${cust_arr_exp} == 'ETA')" ).append("\n"); 
		query.append("						AND VS.VPS_ETA_DT" ).append("\n"); 
		query.append("                            BETWEEN TO_DATE(REPLACE(@[fromd], '-', '') || REPLACE(@[fromt], ':', '') ,'YYYYMMDDHH24MI')" ).append("\n"); 
		query.append("                                AND TO_DATE(REPLACE(@[tod], '-', '')   || REPLACE(@[tot], ':', '')   ,'YYYYMMDDHH24MI')              " ).append("\n"); 
		query.append("                    #end" ).append("\n"); 
		query.append("                #end" ).append("\n"); 
		query.append("            #end" ).append("\n"); 
		query.append("        #end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("	#if (${cntr_prt_flg} == '1')" ).append("\n"); 
		query.append("		AND BC.CNTR_VOL_QTY != 1  " ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       ) TB" ).append("\n"); 
		query.append("      ,BKG_CSTMS_ADV_CUST CUST" ).append("\n"); 
		query.append("  WHERE TB.RNUM BETWEEN @[start_no] AND @[end_no]" ).append("\n"); 
		query.append("	AND TB.CNT_CD = CUST.CNT_CD(+)" ).append("\n"); 
		query.append("	AND TB.AMS_FILE_NO = CUST.BL_NO(+)" ).append("\n"); 
		query.append("	AND TB.BKG_CUST_TP_CD = CUST.BKG_CUST_TP_CD(+)" ).append("\n"); 
		query.append("	#if (${customer_cd} != '')" ).append("\n"); 
		query.append("	  AND CUST.CUST_CNT_CD||CUST.CUST_SEQ = @[customer_cd]" ).append("\n"); 
		query.append("	#end" ).append("\n"); 
		query.append("    " ).append("\n"); 
		query.append("    #if (${excl_rls} == '05')  --Excl + 1C" ).append("\n"); 
		query.append("      AND (TB.C_QTY <> TB.PCK_QTY" ).append("\n"); 
		query.append("            OR TB.C_QTY IS NULL" ).append("\n"); 
		query.append("          )" ).append("\n"); 
		query.append("    #elseif (${excl_rls} == '06')  --H at POD" ).append("\n"); 
		query.append("      AND TB.DSPO_CD IN (SELECT A.CSTMS_DSPO_CD" ).append("\n"); 
		query.append("                          FROM  BKG_CSTMS_ADV_DSPO A" ).append("\n"); 
		query.append("                               ,BKG_CSTMS_CD_CONV_CTNT B" ).append("\n"); 
		query.append("                         WHERE  A.CNT_CD = B.CNT_CD(+)" ).append("\n"); 
		query.append("                           AND  A.CSTMS_DSPO_CD = B.ATTR_CTNT3(+)" ).append("\n"); 
		query.append("                           AND  B.CSTMS_DIV_ID(+) = 'CARGO_RLS_H_CD'" ).append("\n"); 
		query.append("                           AND  A.CNT_CD = 'US'" ).append("\n"); 
		query.append("                           AND  A.DSPO_TP_CD = 'HP')" ).append("\n"); 
		query.append("    #elseif (${excl_rls} == '07')  --C Status is H" ).append("\n"); 
		query.append("      AND TB.CSTMS_CLR_CD = 'H'" ).append("\n"); 
		query.append("    #end" ).append("\n"); 
		query.append("#end" ).append("\n"); 

	}
}