/*=========================================================
*Copyright(c) 2016 CyberLogitec
*@FileName : CLLCDLManifestDBDAOaddCdlEdiMainCSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2016.12.21
*@LastModifier : 
*@LastVersion : 1.0
* 2016.12.21 
* 1.0 Creation
=========================================================*/
package com.clt.apps.opus.esm.bkg.terminaldocumentation.cllcdlmanifest.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.clt.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class CLLCDLManifestDBDAOaddCdlEdiMainCSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * [BKG] #8811 [1월 반영 추가] Special handling code - COPRAR by 진마리아
	  * </pre>
	  */
	public CLLCDLManifestDBDAOaddCdlEdiMainCSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("in_pod_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("in_edi_msg_func",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("in_rcv_id",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("in_yd_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bkg_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("in_area_id",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("in_vvd_cd",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("in_pol_cd",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.clt.apps.opus.esm.bkg.terminaldocumentation.cllcdlmanifest.integration").append("\n"); 
		query.append("FileName : CLLCDLManifestDBDAOaddCdlEdiMainCSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("INSERT INTO BKG_CSTMS_TML_EDI_GEN_TMP (N1ST_EDI_GEN_ORD_NO,N2ND_EDI_GEN_ORD_NO,N3RD_EDI_GEN_ORD_NO,TML_EDI_CTNT)" ).append("\n"); 
		query.append("WITH BKG_CSTMS_TML_EDI_TMP_KEY AS" ).append("\n"); 
		query.append("    (" ).append("\n"); 
		query.append("     SELECT  /*+ MATERIALIZE */ " ).append("\n"); 
		query.append("             VVD_CD, POD_CD, BKG_NO, CNTR_NO," ).append("\n"); 
		query.append("             ROW_NUMBER() OVER (PARTITION BY VVD_CD ORDER BY BKG_NO, CNTR_NO) ORD " ).append("\n"); 
		query.append("     FROM    BKG_CSTMS_TML_EDI_TMP" ).append("\n"); 
		query.append("     ORDER BY BKG_NO, CNTR_NO" ).append("\n"); 
		query.append("    )" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("SELECT  0            ORD1, " ).append("\n"); 
		query.append("        2            ORD2," ).append("\n"); 
		query.append("        1            ORD3," ).append("\n"); 
		query.append("        TO_CLOB( NVL(A.PSEUDO_VVD, B.PSEUDO_VVD) )  PSEUDO_VVD" ).append("\n"); 
		query.append("FROM   (" ).append("\n"); 
		query.append("		SELECT  MAX( " ).append("\n"); 
		query.append("                'BRAC:'||NVL(DECODE(@[in_edi_msg_func], 'ORIGINAL','O'," ).append("\n"); 
		query.append("                'REPLACE', 'U'," ).append("\n"); 
		query.append("                'CANCEL',  'C'," ).append("\n"); 
		query.append("                'CHANGE',  'G'," ).append("\n"); 
		query.append("                'ADDITION','A', 'O'),'O')||CHR(10)||" ).append("\n"); 
		query.append("                'VVD:'||NVL(A.VSL_CD,' ')||NVL(A.SKD_VOY_NO,' ')||NVL(A.SKD_DIR_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'VSL_CALLSIGN:'||NVL(D.CALL_SGN_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'VSL_LLOYDCODE:'||NVL(D.LLOYD_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'VSL_FULLNAME:'||NVL(D.VSL_ENG_NM,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'LANE_CD:'||NVL(A.SLAN_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'VVD_REF_NO:'||(SELECT PSA_VOY_DIR_CD" ).append("\n"); 
		query.append("	                              FROM BKG_CSTMS_MY_VVD PSA" ).append("\n"); 
		query.append("	                             WHERE PSA.VSL_CD = A.VSL_CD" ).append("\n"); 
		query.append("	                               AND PSA.SKD_VOY_NO = A.SKD_VOY_NO" ).append("\n"); 
		query.append("	                               AND PSA.SKD_DIR_CD = A.SKD_DIR_CD" ).append("\n"); 
		query.append("	                               AND ROWNUM = 1" ).append("\n"); 
		query.append("	                           )||CHR(10)||" ).append("\n"); 
		query.append("				'UVRN:'||NVL((SELECT /*+ INDEX_ASC(BKG_CSTMS_RTM_VSL XAK1BKG_CSTMS_RTM_VSL) */" ).append("\n"); 
		query.append("							 		 VSL_CALL_REF_NO" ).append("\n"); 
		query.append("								FROM BKG_CSTMS_RTM_VSL RTM" ).append("\n"); 
		query.append("							   WHERE RTM.VSL_CD = A.VSL_CD" ).append("\n"); 
		query.append("								 AND RTM.SKD_VOY_NO = A.SKD_VOY_NO" ).append("\n"); 
		query.append("								 AND RTM.SKD_DIR_CD = A.SKD_DIR_CD" ).append("\n"); 
		query.append("								 AND ROWNUM = 1),' ')||CHR(10)||" ).append("\n"); 
		query.append("				'CONSORT_VOY:'||A.IB_CSSM_VOY_NO||CHR(10)||" ).append("\n"); 
		query.append("                'FEEDER_VSL:'||	NVL((SELECT B.VSL_CD" ).append("\n"); 
		query.append("									   FROM (SELECT BKG_NO" ).append("\n"); 
		query.append("													,VSL_PRE_PST_CD" ).append("\n"); 
		query.append("													,LAG(VSL_SEQ, 1, 0) OVER (PARTITION BY BKG_NO ORDER BY VSL_PRE_PST_CD, VSL_SEQ) AS VSL_SEQ" ).append("\n"); 
		query.append("											   FROM BKG_VVD) A" ).append("\n"); 
		query.append("											,BKG_VVD B " ).append("\n"); 
		query.append("									  WHERE A.VSL_PRE_PST_CD = 'T' " ).append("\n"); 
		query.append("										AND B.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("										AND A.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("										AND 'S' = B.VSL_PRE_PST_CD" ).append("\n"); 
		query.append("										AND A.VSL_SEQ = B.VSL_SEQ),' ')||CHR(10)||" ).append("\n"); 
		query.append("				'FEEDER_VOY:'||	NVL((SELECT B.SKD_VOY_NO" ).append("\n"); 
		query.append("									   FROM (SELECT BKG_NO" ).append("\n"); 
		query.append("													,VSL_PRE_PST_CD" ).append("\n"); 
		query.append("													,LAG(VSL_SEQ, 1, 0) OVER (PARTITION BY BKG_NO ORDER BY VSL_PRE_PST_CD, VSL_SEQ) AS VSL_SEQ" ).append("\n"); 
		query.append("											   FROM BKG_VVD) A" ).append("\n"); 
		query.append("											,BKG_VVD B " ).append("\n"); 
		query.append("									  WHERE A.VSL_PRE_PST_CD = 'T' " ).append("\n"); 
		query.append("										AND B.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("										AND A.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("										AND 'S' = B.VSL_PRE_PST_CD" ).append("\n"); 
		query.append("										AND A.VSL_SEQ = B.VSL_SEQ),' ')||CHR(10)||" ).append("\n"); 
		query.append("                'PORT:'||NVL(DECODE(@[in_pol_cd],NULL,@[in_pod_cd],@[in_pol_cd]),'')||CHR(10)||  " ).append("\n"); 
		query.append("				'PORTNAME:'||NVL( (SELECT  A.LOC_NM" ).append("\n"); 
		query.append("                                   FROM    MDM_LOCATION  A" ).append("\n"); 
		query.append("                                   WHERE   A.LOC_CD = NVL(@[in_pod_cd],@[in_pol_cd])" ).append("\n"); 
		query.append("                                  ),'')||CHR(10)|| " ).append("\n"); 
		query.append("				'POL_YDCD:'||CHR(10)||" ).append("\n"); 
		query.append("				'POL_YDNM:'||CHR(10)||" ).append("\n"); 
		query.append("				'POD_YDCD:'||A.YD_CD||CHR(10)||" ).append("\n"); 
		query.append("				'POD_YDNM:'||(SELECT YD_NM FROM MDM_YARD WHERE YD_CD = A.YD_CD)||CHR(10)||" ).append("\n"); 
		query.append("                'ETA:'||NVL(TO_CHAR(A.VPS_ETA_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("                'ETD:'||NVL(TO_CHAR(A.VPS_ETD_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("                DECODE(@[in_pol_cd],NULL,'NEXTPORT:'||CHR(10)||" ).append("\n"); 
		query.append("                'NEXTPORT_ETA:'||CHR(10)||" ).append("\n"); 
		query.append("                'PREVPORT:'||NVL(B.VPS_PORT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'PREVPORT_ETD:'||NVL(TO_CHAR(B.VPS_ETD_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)," ).append("\n"); 
		query.append("                'NEXTPORT:'||NVL(C.VPS_PORT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'NEXTPORT_ETA:'||NVL(TO_CHAR(C.VPS_ETA_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("                'PREVPORT:'||CHR(10)||" ).append("\n"); 
		query.append("                'PREVPORT_ETD:'||CHR(10)" ).append("\n"); 
		query.append("                )||" ).append("\n"); 
		query.append("                'IO_IND:'||'CDL'||CHR(10)||" ).append("\n"); 
		query.append("                'COMP_ID:'||CHR(10)||" ).append("\n"); 
		query.append("                'MRN:'||NVL(E.MAPG_CRR_CD,E.CRR_CD)||CHR(10)||" ).append("\n"); 
		query.append("                'MRN_NAME:'||NVL(E.CRR_NM,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'CRN_NO:'||F.VSL_CALL_REF_NO||CHR(10)" ).append("\n"); 
		query.append("                )  PSEUDO_VVD" ).append("\n"); 
		query.append("        FROM    VSK_VSL_PORT_SKD A," ).append("\n"); 
		query.append("                VSK_VSL_PORT_SKD B," ).append("\n"); 
		query.append("                VSK_VSL_PORT_SKD C," ).append("\n"); 
		query.append("                MDM_VSL_CNTR D," ).append("\n"); 
		query.append("                MDM_CARRIER E," ).append("\n"); 
		query.append("                BKG_CSTMS_RTM_VSL F" ).append("\n"); 
		query.append("        WHERE   A.VSL_CD                 = SUBSTR(@[in_vvd_cd],1,4)" ).append("\n"); 
		query.append("        AND     A.SKD_VOY_NO             = SUBSTR(@[in_vvd_cd],5,4)" ).append("\n"); 
		query.append("        AND     A.SKD_DIR_CD             = SUBSTR(@[in_vvd_cd],9,1)" ).append("\n"); 
		query.append("        AND     A.CLPT_IND_SEQ           = '1'" ).append("\n"); 
		query.append("        AND     A.VPS_PORT_CD            = NVL(@[in_pol_cd],@[in_pod_cd]) " ).append("\n"); 
		query.append("        AND     (A.CLPT_SEQ - 1)         = B.CLPT_SEQ(+)" ).append("\n"); 
		query.append("        AND     A.VSL_CD                 = B.VSL_CD(+)" ).append("\n"); 
		query.append("        AND     A.SKD_VOY_NO             = B.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("        AND     A.SKD_DIR_CD             = B.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("        AND     B.CLPT_IND_SEQ(+)        = '1'" ).append("\n"); 
		query.append("        AND     (A.CLPT_SEQ + 1)         = C.CLPT_SEQ(+)" ).append("\n"); 
		query.append("        AND     A.VSL_CD                 = C.VSL_CD(+)" ).append("\n"); 
		query.append("        AND     A.SKD_VOY_NO             = C.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("        AND     A.SKD_DIR_CD             = C.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("        AND     C.CLPT_IND_SEQ(+)        = '1'" ).append("\n"); 
		query.append("        AND     A.VSL_CD                 = D.VSL_CD" ).append("\n"); 
		query.append("        AND     D.CRR_CD                 = E.CRR_CD" ).append("\n"); 
		query.append("        AND     A.VSL_CD                 = F.VSL_CD(+)  " ).append("\n"); 
		query.append("        AND     A.SKD_VOY_NO             = F.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("        AND     A.SKD_DIR_CD             = F.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("        AND     F.VSL_CALL_REF_STS_CD(+) = 'Y' " ).append("\n"); 
		query.append("       )  A," ).append("\n"); 
		query.append("       (SELECT  MAX(" ).append("\n"); 
		query.append("                'BRAC:'||NVL(DECODE(@[in_edi_msg_func], 'ORIGINAL','O', 'REPLACE','U', 'CANCEL','C', 'O'),'O')||CHR(10)||" ).append("\n"); 
		query.append("                'VVD:'||SUBSTR(@[in_vvd_cd],1,4)||SUBSTR(@[in_vvd_cd],5,4)||SUBSTR(@[in_vvd_cd],9,1)||CHR(10)||" ).append("\n"); 
		query.append("                'VSL_CALLSIGN:'||CHR(10)||" ).append("\n"); 
		query.append("                'VSL_LLOYDCODE:'||CHR(10)||" ).append("\n"); 
		query.append("                'VSL_FULLNAME:'||NVL(A.VSL_ENG_NM,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'LANE_CD:'||CHR(10)||" ).append("\n"); 
		query.append("                'VVD_REF_NO:'||CHR(10)||" ).append("\n"); 
		query.append("                'UVRN:'||CHR(10)||" ).append("\n"); 
		query.append("                'CONSORT_VOY:'||CHR(10)||" ).append("\n"); 
		query.append("                'FEEDER_VSL:'||CHR(10)||" ).append("\n"); 
		query.append("                'FEEDER_VOY:'||CHR(10)||" ).append("\n"); 
		query.append("                'PORT:'||NVL(DECODE(@[in_pol_cd], NULL, @[in_pod_cd],@[in_pol_cd]),'')||CHR(10)||" ).append("\n"); 
		query.append("                'PORTNAME:'||NVL((SELECT  A.LOC_NM" ).append("\n"); 
		query.append("                                   FROM    MDM_LOCATION  A" ).append("\n"); 
		query.append("                                   WHERE   A.LOC_CD = NVL(@[in_pod_cd],@[in_pol_cd])" ).append("\n"); 
		query.append("                                  ),'')||CHR(10)||" ).append("\n"); 
		query.append("				'POL_YDCD:'||CHR(10)||" ).append("\n"); 
		query.append("				'POL_YDNM:'||CHR(10)||" ).append("\n"); 
		query.append("				'POD_YDCD:'||CHR(10)||" ).append("\n"); 
		query.append("				'POD_YDNM:'||CHR(10)||" ).append("\n"); 
		query.append("                'ETA:'||CHR(10)||" ).append("\n"); 
		query.append("                'ETD:'||CHR(10)||" ).append("\n"); 
		query.append("                'NEXTPORT:'||CHR(10)||" ).append("\n"); 
		query.append("                'NEXTPORT_ETA:'||CHR(10)||" ).append("\n"); 
		query.append("                'PREVPORT:'||CHR(10)||" ).append("\n"); 
		query.append("                'PREVPORT_ETD:'||CHR(10)||" ).append("\n"); 
		query.append("                'IO_IND:'||'CDL'||CHR(10)||" ).append("\n"); 
		query.append("                'COMP_ID:'||CHR(10)||" ).append("\n"); 
		query.append("                'MRN:'||NVL(B.MAPG_CRR_CD,B.CRR_CD)||CHR(10)||" ).append("\n"); 
		query.append("                'MRN_NAME:'||NVL(B.CRR_NM,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'CRN_NO:'||CHR(10)" ).append("\n"); 
		query.append("                )  PSEUDO_VVD" ).append("\n"); 
		query.append("        FROM     MDM_VSL_CNTR A," ).append("\n"); 
		query.append("                 MDM_CARRIER B" ).append("\n"); 
		query.append("        WHERE    A.VSL_CD(+) = SUBSTR(@[in_vvd_cd],1,4)" ).append("\n"); 
		query.append("        AND      A.CRR_CD    = B.CRR_CD" ).append("\n"); 
		query.append("       )  B" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  /*+ ORDERED USE_NL(X B ISS BCS BCC C1 C2 C3 C4 C5 E COM) */" ).append("\n"); 
		query.append("        X.ORD        ORD1," ).append("\n"); 
		query.append("        1            ORD2," ).append("\n"); 
		query.append("        1            ORD3," ).append("\n"); 
		query.append("        TO_CLOB( '{BL_INFO'||chr(10)||" ).append("\n"); 
		query.append("        'BLNBR:'||NVL(B.BL_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BLPOL:'||NVL(B.POL_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'POL_AMS:'||C1.LOC_AMS_PORT_CD||CHR(10)||" ).append("\n"); 
		query.append("        'POL_FULLNAME:'||C1.LOC_NM||CHR(10)||" ).append("\n"); 
		query.append("        'BLPOD:'||NVL(B.POD_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'POD_AMS:'||C2.LOC_AMS_PORT_CD||CHR(10)||" ).append("\n"); 
		query.append("        'POD_FULLNAME:'||C2.LOC_NM||CHR(10)||" ).append("\n"); 
		query.append("	    'BLCK_STWG_CD:'||B.BLCK_STWG_CD||CHR(10)||" ).append("\n"); 
		query.append("        'BLPOR:'||NVL(B.POR_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'POR_AMS:'||C3.LOC_AMS_PORT_CD||CHR(10)||" ).append("\n"); 
		query.append("        'POR_FULLNAME:'||C3.LOC_NM||CHR(10)||" ).append("\n"); 
		query.append("        'BLDEL:'||NVL(B.DEL_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'DEL_AMS:'||C4.LOC_AMS_PORT_CD||CHR(10)||" ).append("\n"); 
		query.append("        'DEL_FULLNAME:'||C4.LOC_NM||CHR(10)||" ).append("\n"); 
		query.append("        'BLRLY:'||decode(@[in_pol_cd], NULL,NVL(B.PST_RLY_PORT_CD,' '),NVL(B.PRE_RLY_PORT_CD,' '))||CHR(10)|| " ).append("\n"); 
		query.append("        'RLY_AMS:'||C5.LOC_AMS_PORT_CD||CHR(10)||" ).append("\n"); 
		query.append("        'RLY_FULLNAME:'||C5.LOC_NM||CHR(10)||" ).append("\n"); 
		query.append("        'UCR_NO:'||CHR(10)||" ).append("\n"); 
		query.append("        'UCR_CODE:'||CHR(10)||" ).append("\n"); 
		query.append("        'BLPLACE:'||NVL(E.LOC_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BLDATE:'||NVL(TO_CHAR(ISS.OBL_ISS_DT,'RRMMDD'),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'SHPRCN:'||NVL(BCS.CUST_CNT_CD,'')||CHR(10)||" ).append("\n"); 
		query.append("        'SHPRCD:'||DECODE(TO_CHAR(BCS.CUST_SEQ),'0','',TO_CHAR(BCS.CUST_SEQ))||CHR(10)||" ).append("\n"); 
		query.append("        'SHPR1:'||REPLACE(BKG_TOKEN_NL_FNC(BCS.CUST_NM,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'SHPR2:'||REPLACE(BKG_TOKEN_NL_FNC(BCS.CUST_NM,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'SHPR3:'||REPLACE(BKG_TOKEN_NL_FNC(BCS.CUST_ADDR,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'SHPR4:'||REPLACE(BKG_TOKEN_NL_FNC(BCS.CUST_ADDR,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'SHPR5:'||REPLACE(BKG_TOKEN_NL_FNC(BCS.CUST_ADDR,3,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'SHPRTAXID:'||CHR(10)||" ).append("\n"); 
		query.append("        'CNEECN:'||NVL(BCC.CUST_CNT_CD,'')||CHR(10)||" ).append("\n"); 
		query.append("        'CNEECD:'||DECODE(TO_CHAR(BCC.CUST_SEQ),'0','',TO_CHAR(BCC.CUST_SEQ))||CHR(10)||" ).append("\n"); 
		query.append("        'CNEE1:'||REPLACE(BKG_TOKEN_NL_FNC(BCC.CUST_NM,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'CNEE2:'||REPLACE(BKG_TOKEN_NL_FNC(BCC.CUST_NM,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'CNEE3:'||REPLACE(BKG_TOKEN_NL_FNC(BCC.CUST_ADDR,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'CNEE4:'||REPLACE(BKG_TOKEN_NL_FNC(BCC.CUST_ADDR,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'CNEE5:'||REPLACE(BKG_TOKEN_NL_FNC(BCC.CUST_ADDR,3,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'CNEETAXID:'||CHR(10) ) BL_INFO" ).append("\n"); 
		query.append("FROM   (SELECT  BKG_NO," ).append("\n"); 
		query.append("                MIN(ORD)  ORD" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY" ).append("\n"); 
		query.append("        WHERE   ROWNUM >= 1" ).append("\n"); 
		query.append("        GROUP BY BKG_NO" ).append("\n"); 
		query.append("       )  X," ).append("\n"); 
		query.append("        BKG_BOOKING      B, " ).append("\n"); 
		query.append("        BKG_BL_ISS       ISS," ).append("\n"); 
		query.append("        BKG_CUSTOMER     BCS," ).append("\n"); 
		query.append("        BKG_CUSTOMER     BCC," ).append("\n"); 
		query.append("        MDM_LOCATION     C1," ).append("\n"); 
		query.append("        MDM_LOCATION     C2," ).append("\n"); 
		query.append("        MDM_LOCATION     C3," ).append("\n"); 
		query.append("        MDM_LOCATION     C4," ).append("\n"); 
		query.append("        MDM_LOCATION     C5," ).append("\n"); 
		query.append("        MDM_ORGANIZATION E," ).append("\n"); 
		query.append("        MDM_COMMODITY    COM" ).append("\n"); 
		query.append("WHERE   X.BKG_NO                = B.BKG_NO" ).append("\n"); 
		query.append("AND     B.BKG_NO                = ISS.BKG_NO(+)" ).append("\n"); 
		query.append("AND     B.POL_CD                = C1.LOC_CD(+)" ).append("\n"); 
		query.append("AND     B.POD_CD                = C2.LOC_CD(+)" ).append("\n"); 
		query.append("AND     B.POR_CD                = C3.LOC_CD(+)" ).append("\n"); 
		query.append("AND     B.DEL_CD                = C4.LOC_CD(+)" ).append("\n"); 
		query.append("AND     DECODE(@[in_pol_cd], NULL, NVL(B.PST_RLY_PORT_CD,' '),NVL(B.PRE_RLY_PORT_CD,' ')) = C5.LOC_CD(+)" ).append("\n"); 
		query.append("AND     ISS.OBL_ISS_OFC_CD      = E.OFC_CD(+)" ).append("\n"); 
		query.append("AND     B.CMDT_CD               = COM.CMDT_CD(+)" ).append("\n"); 
		query.append("AND     B.BKG_NO                = BCS.BKG_NO" ).append("\n"); 
		query.append("AND     BCS.BKG_CUST_TP_CD      = 'S'" ).append("\n"); 
		query.append("AND     B.BKG_NO                = BCC.BKG_NO" ).append("\n"); 
		query.append("AND     BCC.BKG_CUST_TP_CD      = 'C'" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  /*+ ORDERED USE_NL(X BK DOC BL F BCN BCA BCF BCE C1 C2 C3 C4 C5 COM REF) */" ).append("\n"); 
		query.append("        X.ORD        ORD1," ).append("\n"); 
		query.append("        2            ORD2," ).append("\n"); 
		query.append("        1            ORD3," ).append("\n"); 
		query.append("        TO_CLOB( 'NTFYCN:'||NVL(BCN.CUST_CNT_CD,'')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFYCD:'||DECODE(TO_CHAR(BCN.CUST_SEQ),'0','',TO_CHAR(BCN.CUST_SEQ))||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY1:'||REPLACE(BKG_TOKEN_NL_FNC(BCN.CUST_NM,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY2:'||REPLACE(BKG_TOKEN_NL_FNC(BCN.CUST_NM,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY3:'||REPLACE(BKG_TOKEN_NL_FNC(BCN.CUST_ADDR,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY4:'||REPLACE(BKG_TOKEN_NL_FNC(BCN.CUST_ADDR,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY5:'||REPLACE(BKG_TOKEN_NL_FNC(BCN.CUST_ADDR,3,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFYTAXID:'||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY2CN:'||NVL(BCA.CUST_CNT_CD,'')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY2CD:'||DECODE(TO_CHAR(BCA.CUST_SEQ),'0','',TO_CHAR(BCA.CUST_SEQ))||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY21:'||REPLACE(BKG_TOKEN_NL_FNC(BCA.CUST_NM,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY22:'||REPLACE(BKG_TOKEN_NL_FNC(BCA.CUST_NM,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY23:'||REPLACE(BKG_TOKEN_NL_FNC(BCA.CUST_NM,3,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY24:'||REPLACE(BKG_TOKEN_NL_FNC(BCA.CUST_NM,4,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'NTFY25:'||REPLACE(BKG_TOKEN_NL_FNC(BCA.CUST_NM,5,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'FFWDCN:'||NVL(BCF.CUST_CNT_CD,'')||CHR(10)||" ).append("\n"); 
		query.append("        'FFWDCD:'||DECODE(TO_CHAR(BCF.CUST_SEQ),'0','',TO_CHAR(BCF.CUST_SEQ))||CHR(10)||" ).append("\n"); 
		query.append("        'FFWD1:'||REPLACE(BKG_TOKEN_NL_FNC(BCF.CUST_NM,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'FFWD2:'||REPLACE(BKG_TOKEN_NL_FNC(BCF.CUST_NM,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'FFWD3:'||REPLACE(BKG_TOKEN_NL_FNC(BCF.CUST_NM,3,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'FFWD4:'||REPLACE(BKG_TOKEN_NL_FNC(BCF.CUST_NM,4,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'FFWD5:'||REPLACE(BKG_TOKEN_NL_FNC(BCF.CUST_NM,5,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'EXPOCN:'||NVL(BCE.CUST_CNT_CD,'')||CHR(10)||" ).append("\n"); 
		query.append("        'EXPOCD:'||DECODE(TO_CHAR(BCE.CUST_SEQ),'0','',TO_CHAR(BCE.CUST_SEQ))||CHR(10)||" ).append("\n"); 
		query.append("        'EXPO1:'||REPLACE(BKG_TOKEN_NL_FNC(BCE.CUST_NM,1,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'EXPO2:'||REPLACE(BKG_TOKEN_NL_FNC(BCE.CUST_NM,2,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'EXPO3:'||REPLACE(BKG_TOKEN_NL_FNC(BCE.CUST_NM,3,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'EXPO4:'||REPLACE(BKG_TOKEN_NL_FNC(BCE.CUST_NM,4,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'EXPO5:'||REPLACE(BKG_TOKEN_NL_FNC(BCE.CUST_NM,5,''),'*','-')||CHR(10)||" ).append("\n"); 
		query.append("        'BLCOPY:'||NVL(BL.BL_CPY_KNT,0)||CHR(10)||" ).append("\n"); 
		query.append("        'BLORG:1'||CHR(10)||" ).append("\n"); 
		query.append("        'BLPKG:'||NVL(DOC.PCK_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("        'BLPKGU:'||NVL(DOC.PCK_TP_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BLWGT:'||NVL(DOC.ACT_WGT,0)||CHR(10)||" ).append("\n"); 
		query.append("        'BL_WGT_UNIT:'||NVL(DOC.WGT_UT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BLMEA:'||NVL(DOC.MEAS_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("        'BL_MEA_UNIT:'||NVL(DOC.MEAS_UT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'RDTYPE:'||NVL(BK.RCV_TERM_CD,' ')||NVL(BK.DE_TERM_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'CARGOTYPE:'||NVL(BK.BKG_CGO_TP_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'COMMODITY:'||NVL(BK.CMDT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BLCMD:'||NVL(TRANSLATE(NVL(COM.CMDT_NM,' '),chr(10),' '),' ')||CHR(10)||  " ).append("\n"); 
		query.append("        'BLREPCMDCD:'||NVL(BK.REP_CMDT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BLREPCMD:'||NVL((SELECT  TRANSLATE(NVL(REP.REP_CMDT_NM,' '),CHR(10),' ') REP_CMDT_NM" ).append("\n"); 
		query.append("                          FROM    MDM_REP_CMDT REP" ).append("\n"); 
		query.append("                          WHERE   REP.REP_CMDT_CD = BK.REP_CMDT_CD" ).append("\n"); 
		query.append("                         ),' ')||CHR(10)||" ).append("\n"); 
		query.append("        TO_CLOB('REMARK:'||REPLACE(REPLACE(REPLACE(Translate(NVL(BK.XTER_RMK,' '),chr(10),' '),'$','S'),'#',' '),'*','-'))||CHR(10)||" ).append("\n"); 
		query.append("        'AUS_QUAR:'||' '||CHR(10)||" ).append("\n"); 
		query.append("        'SRNBR:'||CHR(10)||" ).append("\n"); 
		query.append("        'BKGNBR:'||NVL(BK.BKG_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BKG_DT:'||NVL(TO_CHAR(BK.BKG_CRE_DT,'RRRRMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'RGN_BKGNBR:'||NVL(REF.CUST_REF_NO_CTNT,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PPDOFC:'||NVL(F.PPD_RCV_OFC_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'CCTOFC:'||NVL(F.CLT_OFC_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'THDOFC:'||CHR(10)||" ).append("\n"); 
		query.append("        'SCNO:'||NVL(BK.SC_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'RFANO:'||NVL(BK.RFA_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'WAYBILL_IND:'||DECODE(BK.BL_TP_CD,'W','Y','N')||CHR(10)||" ).append("\n"); 
		query.append("        'CUSTREF_NUM:'||(SELECT NVL(MAX('U'),'N')  CUSTREF_NUM" ).append("\n"); 
		query.append("                         FROM   BKG_NTC_HIS" ).append("\n"); 
		query.append("                         WHERE  BKG_NO      = BK.BKG_NO" ).append("\n"); 
		query.append("                         AND    NTC_VIA_CD  = 'E'" ).append("\n"); 
		query.append("                         AND    ( NTC_KND_CD  = 'IM' OR NTC_KND_CD  = 'DL' )" ).append("\n"); 
		query.append("                         AND    EDI_ID      = @[in_rcv_id]" ).append("\n"); 
		query.append("                         AND    ROWNUM      = 1" ).append("\n"); 
		query.append("                        )||CHR(10)|| " ).append("\n"); 
		query.append("        'FINAL_ETA:'||CHR(10)||" ).append("\n"); 
		query.append("        'FUNC_CODE:'||CHR(10)||" ).append("\n"); 
		query.append("        'ONBOARD:'||CHR(10)||" ).append("\n"); 
		query.append("        'INBOND_TP:'||NVL((SELECT IBD_TRSP_TP_CD" ).append("\n"); 
		query.append("						  FROM BKG_CSTMS_ADV_IBD IBD" ).append("\n"); 
		query.append("						 WHERE IBD.BL_NO = BK.BL_NO" ).append("\n"); 
		query.append("						   AND ROWNUM = 1" ).append("\n"); 
		query.append("						),'')||CHR(10)||" ).append("\n"); 
		query.append("        'INBOND_NO:'||NVL((SELECT  IBD.IBD_TRSP_NO" ).append("\n"); 
		query.append("                        FROM    BKG_CSTMS_ADV_IBD IBD" ).append("\n"); 
		query.append("                        WHERE   IBD.CNT_CD = 'US'" ).append("\n"); 
		query.append("                        AND     IBD.BL_NO  = BK.BL_NO" ).append("\n"); 
		query.append("                        AND     IBD.IBD_TRSP_NO IS NOT NULL" ).append("\n"); 
		query.append("                       ),'')||CHR(10)||" ).append("\n"); 
		query.append("        'BLTS:'||CHR(10)||" ).append("\n"); 
		query.append("        'BLTP:'||CHR(10)||" ).append("\n"); 
		query.append("        'MSN:'||CHR(10)||" ).append("\n"); 
		query.append("        'MSNCFM:'||CHR(10)||" ).append("\n"); 
		query.append("        'CMDESC:'||CHR(10)||" ).append("\n"); 
		query.append("        'LOCAL_IPI:'||NVL( (" ).append("\n"); 
		query.append("                            /** pod location이 USA 지역인 경우 **/" ).append("\n"); 
		query.append("                            SELECT  CASE WHEN I.CSTMS_CLR_TP_CD = 'L' AND DECODE(BL.CSTMS_POD_CD,'USLAX','USLGB',BL.CSTMS_POD_CD) <> DECODE(BL.HUB_LOC_CD,'USLAX','USLGB',BL.HUB_LOC_CD) THEN 'Y'" ).append("\n"); 
		query.append("									ELSE I.CSTMS_CLR_TP_CD END" ).append("\n"); 
		query.append("									||" ).append("\n"); 
		query.append("                                    NVL(L.LOC_CD,'     ')||" ).append("\n"); 
		query.append("                                    DECODE(LENGTH(RTRIM(L.LOC_AMS_PORT_CD)),4,'D',5,'K','N')||" ).append("\n"); 
		query.append("                                    RPAD(RTRIM(L.LOC_AMS_PORT_CD),5)||" ).append("\n"); 
		query.append("                                    L.LOC_NM LOCAL_IPI" ).append("\n"); 
		query.append("                            FROM    BKG_CSTMS_ADV_IBD I," ).append("\n"); 
		query.append("                                    MDM_LOCATION      L," ).append("\n"); 
		query.append("                                    BKG_CSTMS_ADV_BL  BL" ).append("\n"); 
		query.append("                            WHERE   @[in_area_id]    = 'USA'      " ).append("\n"); 
		query.append("                            AND     I.CNT_CD       = 'US'" ).append("\n"); 
		query.append("                            AND     BL.CNT_CD      = 'US'" ).append("\n"); 
		query.append("                            AND     BK.BL_NO       = BL.BL_NO" ).append("\n"); 
		query.append("                            AND     BL.BL_NO       = I.BL_NO" ).append("\n"); 
		query.append("                            AND     BL.HUB_LOC_CD  = L.LOC_CD(+)" ).append("\n"); 
		query.append("                            UNION ALL" ).append("\n"); 
		query.append("                            /** pod location이 USA 지역이 아닌 경우 **/" ).append("\n"); 
		query.append("                            SELECT  DECODE(C2.SCC_CD, C4.SCC_CD," ).append("\n"); 
		query.append("                                    DECODE(SUBSTR(BK.POD_CD,1,2), SUBSTR(BK.DEL_CD,1,2), 'L', 'I'), 'I')" ).append("\n"); 
		query.append("                                    ||(SELECT  L3.LOC_CD||L3.LOC_NM" ).append("\n"); 
		query.append("                                       FROM    MDM_LOCATION L3" ).append("\n"); 
		query.append("                                       WHERE   L3.LOC_CD = C4.SCC_CD" ).append("\n"); 
		query.append("                                      )  LOCAL_IPI" ).append("\n"); 
		query.append("                            FROM    DUAL" ).append("\n"); 
		query.append("                            WHERE   @[in_area_id]  <>  'USA'  " ).append("\n"); 
		query.append("                           ),' ')||CHR(10)|| " ).append("\n"); 
		query.append("        'EQREL:'||BK.MTY_PKUP_YD_CD|| CHR(10)||" ).append("\n"); 
		query.append("        'EQPICKDT:'||TO_CHAR(BK.MTY_PKUP_DT,'RRRRMMDDHH24MI')|| CHR(10)||" ).append("\n"); 
		query.append("        'EQRTN:'||BK.FULL_RTN_YD_CD|| CHR(10)||" ).append("\n"); 
		query.append("        'TRANS_MODE:'||NVL((SELECT  'F' TRANS_MODE" ).append("\n"); 
		query.append("                            FROM    BKG_VVD" ).append("\n"); 
		query.append("                            WHERE   BKG_NO         = BK.BKG_NO" ).append("\n"); 
		query.append("                            AND     VSL_PRE_PST_CD = 'U'" ).append("\n"); 
		query.append("                            AND     POL_CD         = @[in_pod_cd]" ).append("\n"); 
		query.append("                            AND     ROWNUM         = 1" ).append("\n"); 
		query.append("                           ),' ')|| CHR(10)||" ).append("\n"); 
		query.append("        'UD_CD:'||NVL(BK.STWG_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'LOC_GOODS:'||(SELECT SUBSTR(IBD_LOC_GDS_DESC,1,9) FROM BKG_CSTMS_ADV_BL CN_LOC WHERE CN_LOC.CNT_CD = 'CA' AND CN_LOC.BKG_NO = BK.BKG_NO AND CN_LOC.BL_NO = BK.BL_NO)||CHR(10) " ).append("\n"); 
		query.append("        ) CUST_INFO" ).append("\n"); 
		query.append("FROM   (SELECT  BKG_NO," ).append("\n"); 
		query.append("                MIN(ORD)  ORD" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY" ).append("\n"); 
		query.append("        WHERE   ROWNUM >= 1" ).append("\n"); 
		query.append("        GROUP BY BKG_NO" ).append("\n"); 
		query.append("       )  X," ).append("\n"); 
		query.append("        BKG_BOOKING   BK," ).append("\n"); 
		query.append("        BKG_BL_DOC    DOC," ).append("\n"); 
		query.append("        BKG_BL_ISS    BL," ).append("\n"); 
		query.append("        BKG_RATE      F," ).append("\n"); 
		query.append("        BKG_CUSTOMER  BCN," ).append("\n"); 
		query.append("        BKG_CUSTOMER  BCA," ).append("\n"); 
		query.append("        BKG_CUSTOMER  BCF," ).append("\n"); 
		query.append("        BKG_CUSTOMER  BCE," ).append("\n"); 
		query.append("        MDM_LOCATION  C1," ).append("\n"); 
		query.append("        MDM_LOCATION  C2," ).append("\n"); 
		query.append("        MDM_LOCATION  C3," ).append("\n"); 
		query.append("        MDM_LOCATION  C4," ).append("\n"); 
		query.append("        MDM_LOCATION  C5," ).append("\n"); 
		query.append("        MDM_COMMODITY COM," ).append("\n"); 
		query.append("        BKG_REFERENCE REF" ).append("\n"); 
		query.append("WHERE   X.BKG_NO                = BK.BKG_NO" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = BL.BKG_NO (+)" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = REF.BKG_NO (+)" ).append("\n"); 
		query.append("AND     REF.BKG_REF_TP_CD(+)    = 'PSAN'" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = DOC.BKG_NO" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = F.BKG_NO (+)" ).append("\n"); 
		query.append("AND     BK.POL_CD               = C1.LOC_CD(+)" ).append("\n"); 
		query.append("AND     BK.POD_CD               = C2.LOC_CD(+)" ).append("\n"); 
		query.append("AND     BK.POR_CD               = C3.LOC_CD(+)" ).append("\n"); 
		query.append("AND     BK.DEL_CD               = C4.LOC_CD(+)" ).append("\n"); 
		query.append("AND     DECODE(@[in_pol_cd],NULL,NVL(BK.PST_RLY_PORT_CD,' '),NVL(BK.PRE_RLY_PORT_CD,' ')) = C5.LOC_CD(+)" ).append("\n"); 
		query.append("AND     BK.CMDT_CD              = COM.CMDT_CD(+)" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = BCN.BKG_NO (+)" ).append("\n"); 
		query.append("AND     BCN.BKG_CUST_TP_CD (+)  = 'N'" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = BCA.BKG_NO (+)" ).append("\n"); 
		query.append("AND     BCA.BKG_CUST_TP_CD (+)  = 'A'" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = BCF.BKG_NO (+)" ).append("\n"); 
		query.append("AND     BCF.BKG_CUST_TP_CD (+)  = 'F'" ).append("\n"); 
		query.append("AND     BK.BKG_NO               = BCE.BKG_NO (+)" ).append("\n"); 
		query.append("AND     BCE.BKG_CUST_TP_CD (+)  = 'E'" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  /*+ OPT_PARAM('_gby_hash_aggregation_enabled','false') ORDERED USE_NL(X A) */" ).append("\n"); 
		query.append("        X.ORD        ORD1," ).append("\n"); 
		query.append("        DECODE(B.CPY_NO, 1, 3, 4)  ORD2," ).append("\n"); 
		query.append("        1                          ORD3," ).append("\n"); 
		query.append("        TO_CLOB( CASE WHEN B.CPY_NO = 1 THEN" ).append("\n"); 
		query.append("            MAX(" ).append("\n"); 
		query.append("            '{CHARGE'||CHR(10)||" ).append("\n"); 
		query.append("            'FCTYPE:'||NVL(A.CHG_CD, ' ')||CHR(10)||" ).append("\n"); 
		query.append("            'RATE:'||NVL(A.CHG_UT_AMT, 0)||CHR(10)||" ).append("\n"); 
		query.append("            'REVENUETON:'||NVL(A.RAT_AS_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("            DECODE(A.FRT_TERM_CD,'P','PPD:'||" ).append("\n"); 
		query.append("            NVL(A.CHG_AMT,0),'PPD:'||0.0)||CHR(10)||" ).append("\n"); 
		query.append("            DECODE(A.FRT_TERM_CD,'C','CCT:'||" ).append("\n"); 
		query.append("            NVL(A.CHG_AMT,0),'CCT:'||0.0)||CHR(10)||" ).append("\n"); 
		query.append("            'CURRENCYCODE:'||NVL(A.CURR_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("            'EXCHRATE:'||CHR(10)||" ).append("\n"); 
		query.append("            'TARIFF:'||NVL(A.TRF_ITM_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("            'PERTYPE:'||NVL(A.RAT_UT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("            'RATEOFC:'||NVL(A.N3PTY_RCV_OFC_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("            '}CHARGE'||CHR(10)" ).append("\n"); 
		query.append("            )  " ).append("\n"); 
		query.append("        ELSE " ).append("\n"); 
		query.append("            '{CHARGE_TTL'||CHR(10)||" ).append("\n"); 
		query.append("            'PPD_TOTAL:'||sum(DECODE(FRT_TERM_CD,'P',CHG_AMT,0))||CHR(10)||" ).append("\n"); 
		query.append("            'CCT_TOTAL:'||sum(DECODE(FRT_TERM_CD,'C',CHG_AMT,0))||CHR(10)||" ).append("\n"); 
		query.append("            'TOTAL_CUR:'||NVL(CURR_CD, ' ')||CHR(10)||" ).append("\n"); 
		query.append("            '}CHARGE_TTL'||CHR(10) " ).append("\n"); 
		query.append("        END ) CHARGE_INFO" ).append("\n"); 
		query.append("FROM   (SELECT  BKG_NO," ).append("\n"); 
		query.append("                MIN(ORD)  ORD" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY" ).append("\n"); 
		query.append("        WHERE   ROWNUM >= 1" ).append("\n"); 
		query.append("        GROUP BY BKG_NO" ).append("\n"); 
		query.append("       )  X," ).append("\n"); 
		query.append("        BKG_CHG_RT   A," ).append("\n"); 
		query.append("       (SELECT  LEVEL  CPY_NO" ).append("\n"); 
		query.append("        FROM    DUAL" ).append("\n"); 
		query.append("        CONNECT BY LEVEL <= 2" ).append("\n"); 
		query.append("       )  B  " ).append("\n"); 
		query.append("WHERE   X.BKG_NO = A.BKG_NO " ).append("\n"); 
		query.append("AND     A.FRT_INCL_XCLD_DIV_CD = 'N'" ).append("\n"); 
		query.append("GROUP BY X.ORD, " ).append("\n"); 
		query.append("         B.CPY_NO," ).append("\n"); 
		query.append("         DECODE(B.CPY_NO, 1, A.BKG_NO), " ).append("\n"); 
		query.append("         DECODE(B.CPY_NO, 1, A.RT_SEQ)," ).append("\n"); 
		query.append("         A.FRT_TERM_CD, NVL(A.CURR_CD,' ')" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  X.ORD        ORD1," ).append("\n"); 
		query.append("        5            ORD2," ).append("\n"); 
		query.append("        1            ORD3," ).append("\n"); 
		query.append("        TO_CLOB( '{CUS_DESC' || CHR(10) || 'CUSTOMS_DESC:'|| replace(replace(replace(A.CSTMS_DESC,CHR(63),CHR(63)||CHR(63)), CHR(39),CHR(63)||CHR(39)), CHR(58),CHR(63)||CHR(58))|| CHR(10) || '}CUS_DESC'||chr(10)  ) BCD_DESC" ).append("\n"); 
		query.append("FROM   (SELECT  BKG_NO," ).append("\n"); 
		query.append("                MIN(ORD)  ORD" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY" ).append("\n"); 
		query.append("        WHERE   ROWNUM >= 1" ).append("\n"); 
		query.append("        GROUP BY BKG_NO" ).append("\n"); 
		query.append("       )  X," ).append("\n"); 
		query.append("        BKG_BL_DOC   A" ).append("\n"); 
		query.append("WHERE   X.BKG_NO = A.BKG_NO (+)" ).append("\n"); 
		query.append("AND     @[in_pod_cd] IN ('CNXMN', 'CNDLC', 'CNXGG', 'CNNBO')  " ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  /*+ ORDERED USE_NL(C R A) */" ).append("\n"); 
		query.append("        X.ORD        ORD1," ).append("\n"); 
		query.append("        7            ORD2," ).append("\n"); 
		query.append("        1            ORD3," ).append("\n"); 
		query.append("       TO_CLOB( '{CNTR_INFO'||CHR(10)||" ).append("\n"); 
		query.append("        'CNTRNBR:'||NVL(C.CNTR_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'TS_IND:'||DECODE(B.POD_CD, (SELECT POD_CD FROM BKG_VVD V WHERE V.BKG_NO = B.BKG_NO AND V.POD_CD = @[in_pod_cd]), 'L', 'T')||CHR(10)||" ).append("\n"); 
		query.append("        'RAIL_DEST:'||NVL((SELECT D.NOD_CD" ).append("\n"); 
		query.append("                         FROM SCE_COP_HDR H, SCE_COP_DTL D" ).append("\n"); 
		query.append("                        WHERE H.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("                          AND H.CNTR_NO = C.CNTR_NO" ).append("\n"); 
		query.append("                          AND H.COP_NO = D.COP_NO" ).append("\n"); 
		query.append("                          AND H.COP_STS_CD <> 'X'" ).append("\n"); 
		query.append("                          AND D.COP_DTL_SEQ = (SELECT MAX(COP_DTL_SEQ) FROM SCE_COP_DTL WHERE COP_NO = H.COP_NO AND ACT_CD = 'FIRRAD')" ).append("\n"); 
		query.append("                       ),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PUNIT:'||NVl(C.PCK_TP_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        DECODE(@[in_yd_cd],'CNXMN','PUNIT_DESC:'||NVL(P.PCK_NM,' ')||CHR(10),'')||" ).append("\n"); 
		query.append("        'PKG:'||NVL(C.PCK_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("        'CNTRWGT:'||ROUND(DECODE(DECODE(C.CNTR_WGT,0,NVL(D.WGT_UT_CD,' '),NVL(C.WGT_UT_CD,' ')),'LBS',0.4536,1) * " ).append("\n"); 
		query.append("                    DECODE(C.CNTR_WGT,0,ROUND(NVL(D.ACT_WGT,0) * DECODE(SUBSTR(C.CNTR_TPSZ_CD,2,1),'2',1,2) / (SELECT SUM(DECODE(SUBSTR(CNTR_TPSZ_CD,2,1),'2',1,2)) FROM BKG_CONTAINER BC WHERE BC.BKG_NO = C.BKG_NO),2),C.CNTR_WGT),2)" ).append("\n"); 
		query.append("                   ||CHR(10)||" ).append("\n"); 
		query.append("        'CNTRGWGT:'||ROUND(DECODE(DECODE(C.CNTR_WGT,0,NVL(D.WGT_UT_CD,' '),NVL(C.WGT_UT_CD,' ')),'LBS',0.4536,1) * " ).append("\n"); 
		query.append("                    DECODE(C.CNTR_WGT,0,ROUND(NVL(D.ACT_WGT,0) * DECODE(SUBSTR(C.CNTR_TPSZ_CD,2,1),'2',1,2) / (SELECT SUM(DECODE(SUBSTR(CNTR_TPSZ_CD,2,1),'2',1,2)) FROM BKG_CONTAINER BC WHERE BC.BKG_NO = C.BKG_NO),2),C.CNTR_WGT)" ).append("\n"); 
		query.append("                     + DECODE(NVL(DECODE(NVL(SPEC.TARE_WGT, 0), 0, DECODE(NVL(MDM.CNTR_TPSZ_TARE_WGT, 0), 0, DECODE(O.CNTR_TPSZ_CD, 'T2', 3600, 'T4', 5200, 0), MDM.CNTR_TPSZ_TARE_WGT), SPEC.TARE_WGT  ),0),0,(SELECT CNTR_TPSZ_TARE_WGT FROM MDM_CNTR_TP_SZ WHERE CNTR_TPSZ_CD = O.CNTR_TPSZ_CD), NVL(DECODE(NVL(SPEC.TARE_WGT, 0), 0, DECODE(NVL(MDM.CNTR_TPSZ_TARE_WGT, 0), 0, DECODE(O.CNTR_TPSZ_CD, 'T2', 3600, 'T4', 5200, 0), MDM.CNTR_TPSZ_TARE_WGT), SPEC.TARE_WGT  ),0)),2)" ).append("\n"); 
		query.append("                   ||CHR(10)||" ).append("\n"); 
		query.append("        'CNTR_WGT_UNIT:'||'KGS'||CHR(10)||" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("        'CNTR_TOTAL_WGT:'|| (" ).append("\n"); 
		query.append("							 SELECT" ).append("\n"); 
		query.append("							 SUM( DECODE( NVL(WGT_UT_CD, ' ') , 'LBS', ROUND(NVL(CNTR_WGT, 0)*0.4536, 0) , NVL(CNTR_WGT, 0) )  ) CNTR_TOTAL_WGT" ).append("\n"); 
		query.append("							 FROM BKG_CONTAINER BC , BKG_BOOKING BK" ).append("\n"); 
		query.append("							WHERE 1=1" ).append("\n"); 
		query.append("							 AND BC.CNTR_NO = C.CNTR_NO" ).append("\n"); 
		query.append("							 AND BC.BKG_NO= BK.BKG_NO" ).append("\n"); 
		query.append("							 AND B.VSL_CD = BK.VSL_CD" ).append("\n"); 
		query.append("							 AND B.SKD_VOY_NO= BK.SKD_VOY_NO" ).append("\n"); 
		query.append("							 AND B.SKD_DIR_CD = BK.SKD_DIR_CD" ).append("\n"); 
		query.append("							 AND BK.BKG_STS_CD NOT IN ('X','S')" ).append("\n"); 
		query.append("                            ) ||CHR(10)||" ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append("        " ).append("\n"); 
		query.append("        'CNTR_TOTAL_WGT_UNIT:'||'KGS'||CHR(10)||" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("        'CNTRTRW:'||DECODE(NVL(SPEC.TARE_WGT, 0), 0" ).append("\n"); 
		query.append("        , DECODE(NVL(MDM.CNTR_TPSZ_TARE_WGT, 0), 0" ).append("\n"); 
		query.append("        , DECODE(O.CNTR_TPSZ_CD, 'T2', 3600, 'T4', 5200, 0), MDM.CNTR_TPSZ_TARE_WGT)" ).append("\n"); 
		query.append("        , SPEC.TARE_WGT  )||CHR(10)||" ).append("\n"); 
		query.append("        'CNTRTYPE:'||NVL(C.CNTR_TPSZ_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'SEALNBR:'||(  SELECT NVL(MIN(CNTR_SEAL_NO),' ') " ).append("\n"); 
		query.append("		   FROM BKG_CNTR_SEAL_NO" ).append("\n"); 
		query.append("		   WHERE BKG_NO = C.BKG_NO" ).append("\n"); 
		query.append("		   AND CNTR_NO = C.CNTR_NO" ).append("\n"); 
		query.append("		   )||CHR(10)||" ).append("\n"); 
		query.append("        'FM_IND:'||DECODE(B.BKG_CGO_TP_CD,'F','F','M')||CHR(10)||" ).append("\n"); 
		query.append("        'RF_IND:'||NVL(B.RC_FLG,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'DG_IND:'||NVL(B.DCGO_FLG,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'AK_IND:'||NVL(B.AWK_CGO_FLG,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BK_IND:'||NVL(B.BB_CGO_FLG,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'TEMPMIN:'||NVL(R.CDO_TEMP,0)||CHR(10)||" ).append("\n"); 
		query.append("        'TEMPMAX:'||NVL(R.CDO_TEMP,0)||CHR(10)||" ).append("\n"); 
		query.append("        'TEMP:'||NVL(R.FDO_TEMP,0)||CHR(10)||" ).append("\n"); 
		query.append("        'TUNIT:F'||CHR(10)||" ).append("\n"); 
		query.append("        'TEMP_C:'||NVL(R.CDO_TEMP,0)||CHR(10)||" ).append("\n"); 
		query.append("        'TUNIT_C:C'||CHR(10)||" ).append("\n"); 
		query.append("		'VENT:' || CASE WHEN R.VENT_RTO = 0 THEN 'C'" ).append("\n"); 
		query.append("						WHEN R.VENT_RTO > 0 AND R.VENT_RTO < 35 THEN 'Q'" ).append("\n"); 
		query.append("						WHEN R.VENT_RTO >= 35 AND R.VENT_RTO < 65 THEN 'H'" ).append("\n"); 
		query.append("						WHEN R.VENT_RTO >= 65 AND R.VENT_RTO < 100 THEN 'T'" ).append("\n"); 
		query.append("						WHEN R.VENT_RTO = 100 THEN 'O' END		|| CHR(10)||" ).append("\n"); 
		query.append("		'VENT_NUM:' || DECODE(NVL(R.VENT_RTO, 0), 0, '', R.VENT_RTO) ||CHR(10)||" ).append("\n"); 
		query.append("		'VENT_CMH:' || DECODE(NVL(R.CBM_PER_HR_QTY, 0), 0, '', R.CBM_PER_HR_QTY) ||CHR(10)||" ).append("\n"); 
		query.append("		'HUMID:'    || NVL(R.HUMID_NO, 0) ||CHR(10)||" ).append("\n"); 
		query.append("        'MEASURE:'||NVL(C.MEAS_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("        'MEASURE_UNIT:'||NVL(C.MEAS_UT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'RDTYPE:'||NVL(C.RCV_TERM_CD,' ')||NVL(C. DE_TERM_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'CMDT_DESC:'||(SELECT  TRANSLATE(NVL(COM.CMDT_NM,' '),CHR(10),' ') CMDT_NM" ).append("\n"); 
		query.append("                       FROM    MDM_COMMODITY COM" ).append("\n"); 
		query.append("                       WHERE   COM.CMDT_CD = B.CMDT_CD" ).append("\n"); 
		query.append("                      )||CHR(10)||" ).append("\n"); 
		query.append("        'CMDTCD:'||NVL(B.CMDT_CD,' ')||CHR(10)||        " ).append("\n"); 
		query.append("        'RF_REMARK:'||replace(NVL(R.DIFF_RMK,' '),CHR(10),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'RFDRY_IND:'||DECODE(NVL(B.RD_CGO_FLG,' '),'N','0','Y','1',NVL(B.RD_CGO_FLG,' '))||CHR(10)||" ).append("\n"); 
		query.append("        'OVF:'||NVL(A.OVR_FWRD_LEN,0)||CHR(10)||" ).append("\n"); 
		query.append("        'OVR:'||NVL(A.OVR_BKWD_LEN,0)||CHR(10)||" ).append("\n"); 
		query.append("        'OVH:'||NVL(A.OVR_HGT,0)||CHR(10)||" ).append("\n"); 
		query.append("        'OVLW:'||NVL(A.OVR_LF_LEN,0)||CHR(10)||" ).append("\n"); 
		query.append("        'OVRW:'||NVL(A.OVR_RT_LEN,0)||CHR(10)||" ).append("\n"); 
		query.append("        'OVWGT:'||NVL(A.GRS_WGT,0)||CHR(10)||" ).append("\n"); 
		query.append("        'OVWGT_UNIT:'||NVL(A.WGT_UT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'VOID_SLOT:'||NVL(A.OVR_VOID_SLT_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("        'STWG_REQ:'||CHR(10)||" ).append("\n"); 
		query.append("        'SOCIND:'||NVL(C.SOC_FLG,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'SOCNAME:'||DECODE(C.SOC_FLG,'Y',(SELECT VNDR_LGL_ENG_NM" ).append("\n"); 
		query.append("                                            FROM MDM_VENDOR T1" ).append("\n"); 
		query.append("                                                ,MST_CONTAINER T2" ).append("\n"); 
		query.append("                                           WHERE T1.VNDR_SEQ = T2.VNDR_SEQ" ).append("\n"); 
		query.append("                                             AND T2.CNTR_NO = C.CNTR_NO),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'VANNING:'||NVL(B.POR_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'HAULAGE:'||DECODE(B.RCV_TERM_CD, 'D', 'P', 'H')" ).append("\n"); 
		query.append("					||NVL((SELECT DECODE(TRO.HLG_TP_CD, 'C', 'P', 'H')" ).append("\n"); 
		query.append("                             FROM BKG_EUR_TRO TRO" ).append("\n"); 
		query.append("                            WHERE TRO.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("                              AND TRO.CNTR_NO = C.CNTR_NO" ).append("\n"); 
		query.append("                              AND TRO.IO_BND_CD = 'I'" ).append("\n"); 
		query.append("                              AND TRO.CXL_FLG = 'N'), DECODE(B.DE_TERM_CD, 'D', 'P', 'H'))||CHR(10)||" ).append("\n"); 
		query.append("		'HAULAGENAME:'||DECODE(B.RCV_TERM_CD, 'D', 'carrier outbound', 'merchant outbound')" ).append("\n"); 
		query.append("                     	||'-'||NVL((SELECT DECODE(TRO.HLG_TP_CD, 'C', 'carrier inbound', 'merchant inbound')" ).append("\n"); 
		query.append("                                      FROM BKG_EUR_TRO TRO" ).append("\n"); 
		query.append("                                     WHERE TRO.BKG_NO = B.BKG_NO" ).append("\n"); 
		query.append("                                       AND TRO.CNTR_NO = C.CNTR_NO" ).append("\n"); 
		query.append("                                       AND TRO.IO_BND_CD = 'I'" ).append("\n"); 
		query.append("                                       AND TRO.CXL_FLG = 'N'), DECODE(B.DE_TERM_CD, 'D', 'carrier inbound', 'merchant inbound'))||CHR(10)||" ).append("\n"); 
		query.append("        'BKWGT:'||CHR(10)||" ).append("\n"); 
		query.append("        'BKWGTU:'||CHR(10)||" ).append("\n"); 
		query.append("        'BKW:'||CHR(10)||" ).append("\n"); 
		query.append("        'BKH:'||CHR(10)||" ).append("\n"); 
		query.append("        'BKL:'||CHR(10)||" ).append("\n"); 
		query.append("        'CNTROWN:'||NVL(O.OWNR_CO_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'CNTRTRM:'||NVL(O.LSTM_CD,' ')||CHR(10) )	 CNTR_INFO" ).append("\n"); 
		query.append("FROM    " ).append("\n"); 
		query.append("        BKG_CSTMS_TML_EDI_TMP_KEY      X," ).append("\n"); 
		query.append("        BKG_BOOKING      B," ).append("\n"); 
		query.append("        BKG_CONTAINER    C," ).append("\n"); 
		query.append("        MST_CONTAINER    O," ).append("\n"); 
		query.append("        MDM_PCK_TP       P," ).append("\n"); 
		query.append("        MST_CNTR_SPEC    SPEC," ).append("\n"); 
		query.append("        MDM_CNTR_TP_SZ   MDM," ).append("\n"); 
		query.append("        BKG_RF_CGO       R," ).append("\n"); 
		query.append("        BKG_AWK_CGO      A," ).append("\n"); 
		query.append("		BKG_BL_DOC		 D" ).append("\n"); 
		query.append("WHERE   X.BKG_NO           = B.BKG_NO" ).append("\n"); 
		query.append("AND     X.BKG_NO           = C.BKG_NO" ).append("\n"); 
		query.append("AND     X.CNTR_NO          = C.CNTR_NO" ).append("\n"); 
		query.append("AND     C.BKG_NO           = R.BKG_NO(+)" ).append("\n"); 
		query.append("AND     C.CNTR_NO          = R.CNTR_NO(+)" ).append("\n"); 
		query.append("AND     C.BKG_NO           = A.BKG_NO(+)" ).append("\n"); 
		query.append("AND     C.CNTR_NO          = A.CNTR_NO(+)" ).append("\n"); 
		query.append("AND     C.PCK_TP_CD        = P.PCK_CD(+)" ).append("\n"); 
		query.append("AND     O.CNTR_NO          = C.CNTR_NO" ).append("\n"); 
		query.append("AND     O.CNTR_SPEC_NO     = SPEC.CNTR_SPEC_NO(+)" ).append("\n"); 
		query.append("AND     O.CNTR_TPSZ_CD     = MDM.CNTR_TPSZ_CD" ).append("\n"); 
		query.append("AND     B.BKG_NO     	   = D.BKG_NO" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("        X.ORD        ORD1," ).append("\n"); 
		query.append("        7.5          ORD2," ).append("\n"); 
		query.append("        1            ORD3," ).append("\n"); 
		query.append("        TO_CLOB(" ).append("\n"); 
		query.append("        	  '{VGM'                                           || CHR(10)" ).append("\n"); 
		query.append("			|| 'DOC_ID:'       || VGM.DOC_ID                   || CHR(10)" ).append("\n"); 
		query.append("        	|| 'MEAS:'         || CNTR.VGM_WGT                 || CHR(10)" ).append("\n"); 
		query.append("        	|| 'MEAS_UT:'      || SUBSTR(CNTR.VGM_WGT_UT_CD,1,1)   || CHR(10)" ).append("\n"); 
		query.append("        	|| 'DOC_TP:'       || VGM.VGM_DOC_TP               || CHR(10)" ).append("\n"); 
		query.append("			|| 'DATE_TP:'      || VGM.VGM_DT_TP_CD             || CHR(10)" ).append("\n"); 
		query.append("			|| 'DATE:'         || VGM.VGM_HNDL_DT              || CHR(10)" ).append("\n"); 
		query.append("        	|| 'CUST_CNTC_TP:' || VGM.CUST_CNTC_TP             || CHR(10)" ).append("\n"); 
		query.append("			|| 'CUST_CNTC_NM:' || CUST_CNTC_NM                 || CHR(10)" ).append("\n"); 
		query.append("			|| 'CUST_FAX:'     || VGM.CUST_FAX                 || CHR(10)" ).append("\n"); 
		query.append("        	|| 'CUST_EML:'     || VGM.CUST_EML                 || CHR(10)" ).append("\n"); 
		query.append("			|| 'CUST_PHN:'     || VGM.VGM_CUST_PHN_NO          || CHR(10)" ).append("\n"); 
		query.append("			|| 'CUST_ML_ADDR:' || VGM.VGM_CUST_PST_ADDR        || CHR(10)" ).append("\n"); 
		query.append("        	|| '}VGM'          || CHR(10)" ).append("\n"); 
		query.append("        )	 CNTR_VGM" ).append("\n"); 
		query.append("FROM    BKG_CSTMS_TML_EDI_TMP_KEY  X," ).append("\n"); 
		query.append("        BKG_CONTAINER CNTR," ).append("\n"); 
		query.append("		(SELECT * " ).append("\n"); 
		query.append("           FROM (SELECT BKG_NO, " ).append("\n"); 
		query.append("                        CNTR_NO, " ).append("\n"); 
		query.append("                        DOC_ID," ).append("\n"); 
		query.append("                        VGM_DOC_TP," ).append("\n"); 
		query.append("                        VGM_DT_TP_CD," ).append("\n"); 
		query.append("                        VGM_HNDL_DT," ).append("\n"); 
		query.append("                        CUST_CNTC_TP," ).append("\n"); 
		query.append("                        CUST_CNTC_NM," ).append("\n"); 
		query.append("                        CUST_FAX," ).append("\n"); 
		query.append("                        CUST_EML," ).append("\n"); 
		query.append("                        VGM_CUST_PHN_NO," ).append("\n"); 
		query.append("                        VGM_CUST_PST_ADDR," ).append("\n"); 
		query.append("                        ROW_NUMBER() OVER (PARTITION BY BKG_NO, CNTR_NO ORDER BY VGM_HNDL_DT DESC) AS RNUM" ).append("\n"); 
		query.append("                   FROM (SELECT REF_ID AS DOC_ID," ).append("\n"); 
		query.append("                                DECODE(XTER_VGM.USR_ID,'COD','SM1'" ).append("\n"); 
		query.append("                                                              ,'322','SM1'" ).append("\n"); 
		query.append("                                                              ,'304',NVL(XTER_VGM.VGM_DOC_TP_CD,'SM2')" ).append("\n"); 
		query.append("                                                              ,DECODE(XTER_VGM.WGT_TP_CD,'V','SM1','C','SM2')) VGM_DOC_TP,                       " ).append("\n"); 
		query.append("                                'WAT' AS VGM_DT_TP_CD," ).append("\n"); 
		query.append("                                TO_CHAR(XTER_VGM.VGM_CRE_LOCL_DT,'YYYYMMDDHH24MI') AS VGM_HNDL_DT," ).append("\n"); 
		query.append("                                DECODE(ESIG_CO_NM, NULL, '', 'RP') AS CUST_CNTC_TP," ).append("\n"); 
		query.append("                                DECODE(ESIG_CO_NM, NULL, '', ESIG_CO_NM) AS CUST_CNTC_NM," ).append("\n"); 
		query.append("                                NULL AS CUST_FAX," ).append("\n"); 
		query.append("                                XTER_VGM.CUST_EML," ).append("\n"); 
		query.append("                                NULL AS VGM_CUST_PHN_NO," ).append("\n"); 
		query.append("                                NULL AS VGM_CUST_PST_ADDR," ).append("\n"); 
		query.append("                                BC.BKG_NO," ).append("\n"); 
		query.append("                                BC.CNTR_NO," ).append("\n"); 
		query.append("                                XTER_VGM.XTER_VGM_RQST_CD AS VGM_VIA," ).append("\n"); 
		query.append("                                BC.VGM_WGT AS XTER_VGM_WGT," ).append("\n"); 
		query.append("                                'K' AS XTER_VGM_WGT_UT_CD," ).append("\n"); 
		query.append("                                XTER_VGM.USR_ID AS IN_USR," ).append("\n"); 
		query.append("                                DECODE(XTER_VGM.ESIG_CO_NM, NULL, 'N', 'Y') AS ESIG," ).append("\n"); 
		query.append("                                XTER_VGM.VGM_SEQ AS VGM_SEQ," ).append("\n"); 
		query.append("                                XTER_VGM.ESIG_CO_NM" ).append("\n"); 
		query.append("                           FROM BKG_CSTMS_TML_EDI_TMP_KEY KEY, BKG_CONTAINER BC, BKG_XTER_VGM XTER_VGM" ).append("\n"); 
		query.append("                          WHERE KEY.BKG_NO = BC.BKG_NO" ).append("\n"); 
		query.append("                            AND KEY.CNTR_NO = BC.CNTR_NO" ).append("\n"); 
		query.append("                            AND BC.XTER_VGM_DOC_ID = XTER_VGM.BKG_NO" ).append("\n"); 
		query.append("                            AND BC.CNTR_NO = XTER_VGM.CNTR_NO" ).append("\n"); 
		query.append("                            AND BC.XTER_VGM_RQST_SEQ = XTER_VGM.VGM_SEQ" ).append("\n"); 
		query.append("                            AND XTER_VGM.USR_ID = BC.XTER_VGM_USR_ID" ).append("\n"); 
		query.append("                            AND BC.XTER_SNDR_ID = 'WEB'" ).append("\n"); 
		query.append("                            AND XTER_VGM.VGM_CRE_GDT = (SELECT MAX(VGM_CRE_GDT)" ).append("\n"); 
		query.append("                                                          FROM BKG_XTER_VGM" ).append("\n"); 
		query.append("                                                         WHERE BKG_NO = XTER_VGM.BKG_NO" ).append("\n"); 
		query.append("                                                           AND CNTR_NO = XTER_VGM.CNTR_NO" ).append("\n"); 
		query.append("                                                           AND VGM_SEQ = XTER_VGM.VGM_SEQ" ).append("\n"); 
		query.append("                                                           AND ACT_TP_CD = 'I')" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("                         UNION ALL" ).append("\n"); 
		query.append("                         SELECT BXVC.VGM_DOC_ID," ).append("\n"); 
		query.append("                                NVL((SELECT VGM_DOC_TP_CD" ).append("\n"); 
		query.append("                                       FROM BKG_XTER_VGM_CUST" ).append("\n"); 
		query.append("                                      WHERE BXVR.XTER_SNDR_ID = XTER_SNDR_ID" ).append("\n"); 
		query.append("                                        AND BXVR.XTER_VGM_DOC_ID = XTER_VGM_DOC_ID" ).append("\n"); 
		query.append("                                        AND BXVR.XTER_VGM_RQST_SEQ = XTER_VGM_RQST_SEQ" ).append("\n"); 
		query.append("                                        AND BXVR.CNTR_NO = CNTR_NO" ).append("\n"); 
		query.append("                                        AND VGM_DOC_TP_CD IN ('SM1', 'SM2')" ).append("\n"); 
		query.append("                                        AND ROWNUM = 1), 'SM1') VGM_DOC_TP," ).append("\n"); 
		query.append("                                BXVC.VGM_DT_TP_CD," ).append("\n"); 
		query.append("                                TO_CHAR(GLOBALDATE_PKG.TIME_CONV_FNC('KRPUS', BXVR.UPD_DT, (SELECT POL_CD" ).append("\n"); 
		query.append("                                                                                              FROM BKG_BOOKING" ).append("\n"); 
		query.append("                                                                                             WHERE BKG_NO = REFNO.REF_NO)), 'YYYYMMDDHH24MI') VGM_HNDL_DT," ).append("\n"); 
		query.append("                                BXVC.VGM_CUST_CNTC_TP_CD AS CUST_CNTC_TP," ).append("\n"); 
		query.append("                                BXVC.VGM_CUST_CNTC_NM AS CUST_CNTC_NM," ).append("\n"); 
		query.append("                                BXVC.VGM_CUST_FAX_NO," ).append("\n"); 
		query.append("                                BXVC.VGM_CUST_EML," ).append("\n"); 
		query.append("                                BXVC.VGM_CUST_PHN_NO," ).append("\n"); 
		query.append("                                BXVC.VGM_CUST_PST_ADDR," ).append("\n"); 
		query.append("                                BC.BKG_NO BKG_NO," ).append("\n"); 
		query.append("                                BC.CNTR_NO CNTR_NO," ).append("\n"); 
		query.append("                                'EDI' VGM_VIA," ).append("\n"); 
		query.append("                                BC.VGM_WGT XTER_VGM_WGT," ).append("\n"); 
		query.append("                                'K' XTER_VGM_WGT_UT_CD," ).append("\n"); 
		query.append("                                BXVR.XTER_SNDR_ID IN_USR," ).append("\n"); 
		query.append("                                DECODE(BXVC.VGM_CUST_CNTC_NM, NULL, 'N', 'Y') ESIG," ).append("\n"); 
		query.append("                                BXVR.XTER_VGM_RQST_SEQ VGM_SEQ," ).append("\n"); 
		query.append("                                BXVC.VGM_CUST_CNTC_NM ESIG_CO_NM" ).append("\n"); 
		query.append("                           FROM BKG_XTER_VGM_RQST BXVR," ).append("\n"); 
		query.append("                                BKG_XTER_VGM_CUST BXVC," ).append("\n"); 
		query.append("                                BKG_XTER_VGM_REF_NO REFNO," ).append("\n"); 
		query.append("                                BKG_CSTMS_TML_EDI_TMP_KEY KEY," ).append("\n"); 
		query.append("                                BKG_CONTAINER BC" ).append("\n"); 
		query.append("                          WHERE KEY.BKG_NO = BC.BKG_NO" ).append("\n"); 
		query.append("                            AND KEY.CNTR_NO = BC.CNTR_NO" ).append("\n"); 
		query.append("                            AND BXVR.XTER_SNDR_ID = BXVC.XTER_SNDR_ID(+)" ).append("\n"); 
		query.append("                            AND BXVR.XTER_VGM_DOC_ID = BXVC.XTER_VGM_DOC_ID(+)" ).append("\n"); 
		query.append("                            AND BXVR.XTER_VGM_RQST_SEQ = BXVC.XTER_VGM_RQST_SEQ(+)" ).append("\n"); 
		query.append("                            AND BXVR.CNTR_NO = BXVC.CNTR_NO(+)" ).append("\n"); 
		query.append("                            AND BXVC.VGM_CUST_CNTC_TP_CD(+) = 'RP'" ).append("\n"); 
		query.append("                            AND BXVR.XTER_SNDR_ID = REFNO.XTER_SNDR_ID" ).append("\n"); 
		query.append("                            AND BXVR.XTER_VGM_DOC_ID = REFNO.XTER_VGM_DOC_ID" ).append("\n"); 
		query.append("                            AND BXVR.XTER_VGM_RQST_SEQ = REFNO.XTER_VGM_RQST_SEQ" ).append("\n"); 
		query.append("                            AND BXVR.CNTR_NO = REFNO.CNTR_NO" ).append("\n"); 
		query.append("                            AND NVL(REFNO.XTER_REF_SEQ, 0) = NVL((SELECT MAX(XTER_REF_SEQ)" ).append("\n"); 
		query.append("                                                                    FROM BKG_XTER_VGM_REF_NO" ).append("\n"); 
		query.append("                                                                   WHERE REFNO.XTER_SNDR_ID = XTER_SNDR_ID" ).append("\n"); 
		query.append("                                                                     AND REFNO.XTER_VGM_DOC_ID = XTER_VGM_DOC_ID" ).append("\n"); 
		query.append("                                                                     AND REFNO.XTER_VGM_RQST_SEQ = XTER_VGM_RQST_SEQ" ).append("\n"); 
		query.append("                                                                     AND REFNO.CNTR_NO = CNTR_NO" ).append("\n"); 
		query.append("                                                                     AND REFNO.REF_NO = REF_NO" ).append("\n"); 
		query.append("                                                                     AND XTER_REF_TP_CD IN ('BN', 'BM')), 0)" ).append("\n"); 
		query.append("                            AND BC.XTER_SNDR_ID = REFNO.XTER_SNDR_ID" ).append("\n"); 
		query.append("                            AND BC.XTER_VGM_DOC_ID = REFNO.XTER_VGM_DOC_ID" ).append("\n"); 
		query.append("                            AND BC.XTER_VGM_RQST_SEQ = REFNO.XTER_VGM_RQST_SEQ" ).append("\n"); 
		query.append("                            AND BC.CNTR_NO = REFNO.CNTR_NO" ).append("\n"); 
		query.append("                            AND NVL(BC.XTER_SNDR_ID,'X') <> 'WEB'" ).append("\n"); 
		query.append("                        )" ).append("\n"); 
		query.append("            )" ).append("\n"); 
		query.append("            WHERE RNUM = 1" ).append("\n"); 
		query.append("     ) VGM" ).append("\n"); 
		query.append("WHERE   X.BKG_NO = CNTR.BKG_NO" ).append("\n"); 
		query.append("AND     X.CNTR_NO = CNTR.CNTR_NO" ).append("\n"); 
		query.append("AND     X.BKG_NO  = VGM.BKG_NO(+)" ).append("\n"); 
		query.append("AND     X.CNTR_NO = VGM.CNTR_NO(+)" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT " ).append("\n"); 
		query.append("        X.ORD        ORD1," ).append("\n"); 
		query.append("        8            ORD2," ).append("\n"); 
		query.append("        ROW_NUMBER() OVER (PARTITION BY X.ORD ORDER BY X.ORD, SEAL.CNTR_SEAL_SEQ)  ORD3," ).append("\n"); 
		query.append("        TO_CLOB(" ).append("\n"); 
		query.append("            '{CNTR_SEAL_NO'||CHR(10)||" ).append("\n"); 
		query.append("            'SEAL_TP:'||NVL(SEAL.SEAL_PTY_TP_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("            'SEAL_NO:'||NVL(SEAL.CNTR_SEAL_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("            '}CNTR_SEAL_NO'||CHR(10) " ).append("\n"); 
		query.append("        )	CNTR_SEAL_INFO" ).append("\n"); 
		query.append("FROM    BKG_CSTMS_TML_EDI_TMP_KEY  X," ).append("\n"); 
		query.append("        BKG_CNTR_SEAL_NO   SEAL" ).append("\n"); 
		query.append("WHERE   X.BKG_NO  = SEAL.BKG_NO(+)" ).append("\n"); 
		query.append("AND     X.CNTR_NO = SEAL.CNTR_NO(+)" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  X.ORD       ORD1," ).append("\n"); 
		query.append("        8.5         ORD2," ).append("\n"); 
		query.append("        1           ORD3," ).append("\n"); 
		query.append("        TO_CLOB( '{SPCL_INST'||CHR(10)||" ).append("\n"); 
		query.append("			'SPCL_CD:'||BHCC.ATTR_CTNT2||CHR(10)||" ).append("\n"); 
		query.append("			'SPCL_DESC:'||BHCC.ATTR_CTNT3||CHR(10)||" ).append("\n"); 
		query.append("		    '}SPCL_INST'||CHR(10)" ).append("\n"); 
		query.append("	    ) CNTR_SPCL_INST" ).append("\n"); 
		query.append("  FROM  BKG_CSTMS_TML_EDI_TMP_KEY  X," ).append("\n"); 
		query.append("        BKG_BOOKING BK," ).append("\n"); 
		query.append("        BKG_CONTAINER BC, " ).append("\n"); 
		query.append("        BKG_HRD_CDG_CTNT BHCC " ).append("\n"); 
		query.append("WHERE X.BKG_NO = BK.BKG_NO" ).append("\n"); 
		query.append("AND X.CNTR_NO = BC.CNTR_NO" ).append("\n"); 
		query.append("AND BK.BKG_NO = BC.BKG_NO" ).append("\n"); 
		query.append("AND ((BK.AWK_CGO_FLG = 'Y' AND BHCC.HRD_CDG_ID = 'VNDR301_INSTRUCT' AND BHCC.ATTR_CTNT1 = BC.CNTR_TPSZ_CD)" ).append("\n"); 
		query.append("  OR (BK.BB_CGO_FLG = 'Y' AND BHCC.HRD_CDG_ID = 'VNDR301_INSTRUCT' AND BHCC.ATTR_CTNT1 = 'BK')" ).append("\n"); 
		query.append("  OR (BHCC.HRD_CDG_ID = 'VNDR301_INSTRUCT' AND BHCC.ATTR_CTNT1 IN (SELECT BSC.STWG_CD FROM BKG_STWG_CGO BSC WHERE BSC.BKG_NO = BK.BKG_NO)))" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  /*+ USE_NL(X DG) */" ).append("\n"); 
		query.append("        X.ORD        ORD1," ).append("\n"); 
		query.append("        9            ORD2," ).append("\n"); 
		query.append("        1            ORD3," ).append("\n"); 
		query.append("        TO_CLOB( '{CNTR_DANGER'||CHR(10)||" ).append("\n"); 
		query.append("        'UNNBR:'||NVL(DG.IMDG_UN_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'CLASS:'||NVL(DG.IMDG_CLSS_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'DG_DESC:'||NVL(DG.PRP_SHP_NM,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PHONE:'||NVL(DG.EMER_CNTC_PHN_NO_CTNT,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PERSON:'||NVL(DG.EMER_CNTC_PSON_NM,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PAGE:'||CHR(10)||" ).append("\n"); 
		query.append("        'FLSH_TEMP:'||DG.FLSH_PNT_CDO_TEMP||CHR(10)||" ).append("\n"); 
		query.append("        'FLSH_UNIT:C'||CHR(10)||" ).append("\n"); 
		query.append("        'DG_REMARK:'||REPLACE(NVL(DG.DIFF_RMK,' '),CHR(10),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'EMSNO:'||NVL(DG.EMS_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PSACLS:'||NVL(DG.PSA_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PKGGRP:'||NVL(DG.IMDG_PCK_GRP_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'MFAG1:'||CHR(10)||" ).append("\n"); 
		query.append("        'MFAG2:'||CHR(10)||" ).append("\n"); 
		query.append("        'MAR_POLL:'||NVL(DG.MRN_POLUT_FLG,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'LABEL_CD:'||NVL(DG.IMDG_SUBS_RSK_LBL_CD1,' ')||' '||NVL(DG.IMDG_SUBS_RSK_LBL_CD2,' ')||' '||NVL(DG.IMDG_SUBS_RSK_LBL_CD3,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'LABEL_DESC:'||CHR(10)||" ).append("\n"); 
		query.append("        'D_PKG:'||NVL(DG.OUT_IMDG_PCK_QTY1,0)||CHR(10)||" ).append("\n"); 
		query.append("        'D_PKGUNIT:'||NVL(DG.OUT_IMDG_PCK_CD1,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'NWGT:'||NVL(DG.NET_WGT,0)||CHR(10)||" ).append("\n"); 
		query.append("        'NWGT_UNIT:KGS'||CHR(10)||" ).append("\n"); 
		query.append("        'GWGT:'||NVL(DG.GRS_WGT,0)||CHR(10)||" ).append("\n"); 
		query.append("        'GWGT_UNIT:'||NVL(DG.WGT_UT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'MEA:'||NVL(DG.MEAS_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("        'MEA_UNIT:'||NVL(DG.MEAS_UT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'HAZ_CONT:'||NVL(DG.HZD_DESC,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'STWG:'||NVL(DG.SPCL_STWG_RQST_DESC,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'LABEL:'||NVL(DG.IMDG_SUBS_RSK_LBL_CD1,' ')||' '||NVL(DG.IMDG_SUBS_RSK_LBL_CD2,' ')||' '||NVL(DG.IMDG_SUBS_RSK_LBL_CD3,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'DG_APPROVE_NO:'||NVL(NVL(DG.APLY_NO, " ).append("\n"); 
		query.append("                                 (SELECT /*+ INDEX_DESC(A XPKSCG_AUTHORIZATION) */ A.APRO_REF_NO " ).append("\n"); 
		query.append("                                    FROM SCG_AUTHORIZATION A" ).append("\n"); 
		query.append("                                   WHERE SPCL_CGO_CATE_CD = 'DG'" ).append("\n"); 
		query.append("                                     AND A.BKG_NO = X.BKG_NO" ).append("\n"); 
		query.append("                                     AND A.VSL_PRE_PST_CD||A.VSL_SEQ IN ( SELECT MIN(VSL_PRE_PST_CD||VSL_SEQ) FROM BKG_VVD WHERE BKG_NO = A.BKG_NO )" ).append("\n"); 
		query.append("                                     AND ROWNUM = 1)),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'DG_REF_NO:'|| NVL(DG.DCGO_REF_NO, '')||CHR(10)||" ).append("\n"); 
		query.append("        '}CNTR_DANGER'||CHR(10) )	CNTR_DG_INFO" ).append("\n"); 
		query.append("FROM    BKG_CSTMS_TML_EDI_TMP_KEY  X," ).append("\n"); 
		query.append("        BKG_DG_CGO   DG" ).append("\n"); 
		query.append("WHERE   X.BKG_NO  = DG.BKG_NO" ).append("\n"); 
		query.append("AND     X.CNTR_NO = DG.CNTR_NO" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  *" ).append("\n"); 
		query.append("FROM   (WITH  CNTR_DESC  AS" ).append("\n"); 
		query.append("               (SELECT  /*+ ORDERED USE_NL(X A B) INDEX(B XAK1BKG_CSTMS_ADV_CNTR_MF) */" ).append("\n"); 
		query.append("                        X.ORD        ORD1," ).append("\n"); 
		query.append("                        10            ORD2," ).append("\n"); 
		query.append("                        ROW_NUMBER() OVER (PARTITION BY X.ORD ORDER BY X.ORD, B.CMDT_GDS_SEQ)  ORD3," ).append("\n"); 
		query.append("                        '{CNTR_DESC'||CHR(10)||" ).append("\n"); 
		query.append("                        'D_CMDT:'||CHR(10)||" ).append("\n"); 
		query.append("                        'D_PUNIT:'||NVL(AMS_PCK_TP_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("                        'D_PKG:'||NVL(B.PCK_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("                        'D_WGT:'||DECODE(NVL(B.WGT_UT_CD,' ')," ).append("\n"); 
		query.append("                        'LBS',ROUND(NVL(GRS_WGT,0)*0.4536,3)," ).append("\n"); 
		query.append("                        NVL(GRS_WGT,0)" ).append("\n"); 
		query.append("                        )||CHR(10)||" ).append("\n"); 
		query.append("                        'D_MEAS:'||CHR(10)||" ).append("\n"); 
		query.append("                        'D_HS_CD:'||CHR(10)||" ).append("\n"); 
		query.append("						'D_HTS_CD:'||CHR(10)||" ).append("\n"); 
		query.append("						'D_NCM_CD:'||CHR(10)||" ).append("\n"); 
		query.append("                        'D_DESC:'||CHR(10)||" ).append("\n"); 
		query.append("                        '}CNTR_DESC'||CHR(10) CNTR_DESC" ).append("\n"); 
		query.append("                FROM    BKG_CSTMS_TML_EDI_TMP_KEY            X," ).append("\n"); 
		query.append("                        BKG_BOOKING            A," ).append("\n"); 
		query.append("                        BKG_CSTMS_ADV_CNTR_MF  B," ).append("\n"); 
		query.append("						BKG_CONTAINER C" ).append("\n"); 
		query.append("                WHERE   X.BKG_NO = A.BKG_NO" ).append("\n"); 
		query.append("                AND     A.BL_NO = B.BL_NO" ).append("\n"); 
		query.append("                AND     X.CNTR_NO = B.CNTR_NO" ).append("\n"); 
		query.append("				AND		B.CNT_CD = 'US'" ).append("\n"); 
		query.append("				AND A.BKG_NO = C.BKG_NO" ).append("\n"); 
		query.append("				AND B.CNTR_NO = C.CNTR_NO" ).append("\n"); 
		query.append("               )" ).append("\n"); 
		query.append("        SELECT  ORD1, ORD2, ORD3, TO_CLOB( CNTR_DESC )" ).append("\n"); 
		query.append("        FROM    CNTR_DESC" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT  /*+ ORDERED USE_NL(A X B) */" ).append("\n"); 
		query.append("                X.ORD        ORD1," ).append("\n"); 
		query.append("                11           ORD2," ).append("\n"); 
		query.append("                1            ORD3," ).append("\n"); 
		query.append("                TO_CLOB( '{CNTR_DESC'||CHR(10)||" ).append("\n"); 
		query.append("                'D_CMDT:'||NVL(BK.CMDT_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'D_PUNIT:'||NVL(PCK_TP_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("                'D_PKG:'||NVL(PCK_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("                'D_WGT:'||DECODE(NVL(WGT_UT_CD,' ')," ).append("\n"); 
		query.append("                'LBS',ROUND(NVL(CNTR_MF_WGT,0)*0.4536,3)," ).append("\n"); 
		query.append("                NVL(CNTR_MF_WGT,0)" ).append("\n"); 
		query.append("                )||CHR(10)||" ).append("\n"); 
		query.append("                'D_MEAS:'||DECODE(NVL(MEAS_UT_CD,' ')," ).append("\n"); 
		query.append("                'CBF',ROUND(NVL(MEAS_QTY,0)*0.0283,3)," ).append("\n"); 
		query.append("                NVL(MEAS_QTY,0)" ).append("\n"); 
		query.append("                )||CHR(10)||" ).append("\n"); 
		query.append("                'D_HS_CD:'||NVL(B.CMDT_HS_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("				'D_HTS_CD:'||NVL(B.HAMO_TRF_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("				'D_NCM_CD:'||NVL(B.NCM_NO,' ')||CHR(10)               )" ).append("\n"); 
		query.append("                " ).append("\n"); 
		query.append("                ||" ).append("\n"); 
		query.append("                TO_CLOB('D_DESC:'||Translate(NVL(CNTR_MF_GDS_DESC,' '),chr(10),' ')||chr(10)           )||" ).append("\n"); 
		query.append("                " ).append("\n"); 
		query.append("                TO_CLOB(" ).append("\n"); 
		query.append("                decode(CNTR_MF_MK_DESC, NULL,''," ).append("\n"); 
		query.append("                '{CUS_MARK'||chr(10)||'D_MARK:' ||" ).append("\n"); 
		query.append("                CASE WHEN LENGTH(REPLACE(CNTR_MF_MK_DESC,CHR(10),CHR(10)||'D_MARK:')) > 3800" ).append("\n"); 
		query.append("                       THEN" ).append("\n"); 
		query.append("                         --REPLACE(DBMS_LOB.SUBSTR(CNTR_MF_MK_DESC, 2000,1),CHR(10),CHR(10)||'D_MARK:')" ).append("\n"); 
		query.append("						   DBMS_LOB.SUBSTR(REPLACE(CNTR_MF_MK_DESC,CHR(10),CHR(10)||'D_MARK:'), 3800,1)" ).append("\n"); 
		query.append("                       ELSE" ).append("\n"); 
		query.append("                         REPLACE(CNTR_MF_MK_DESC,CHR(10),CHR(10)||'D_MARK:')" ).append("\n"); 
		query.append("                     END" ).append("\n"); 
		query.append("                ||chr(10)||" ).append("\n"); 
		query.append("                '}CUS_MARK'||CHR(10)" ).append("\n"); 
		query.append("                )" ).append("\n"); 
		query.append("                " ).append("\n"); 
		query.append("                ||" ).append("\n"); 
		query.append("                '}CNTR_DESC'||chr(10) )" ).append("\n"); 
		query.append("                AS CNTR_DESC_END" ).append("\n"); 
		query.append("        FROM   (SELECT  ROWNUM" ).append("\n"); 
		query.append("                FROM    DUAL" ).append("\n"); 
		query.append("                WHERE   NOT EXISTS (SELECT  'X'" ).append("\n"); 
		query.append("                                    FROM    CNTR_DESC" ).append("\n"); 
		query.append("                                   )" ).append("\n"); 
		query.append("               ) A," ).append("\n"); 
		query.append("                BKG_CSTMS_TML_EDI_TMP_KEY       X," ).append("\n"); 
		query.append("                BKG_CNTR_MF_DESC  B," ).append("\n"); 
		query.append("				BKG_BOOKING BK" ).append("\n"); 
		query.append("        WHERE   X.BKG_NO  = B.BKG_NO" ).append("\n"); 
		query.append("        AND     X.CNTR_NO = B.CNTR_NO" ).append("\n"); 
		query.append("		AND		X.BKG_NO = BK.BKG_NO" ).append("\n"); 
		query.append("        UNION ALL" ).append("\n"); 
		query.append("        SELECT  X.ORD          ORD1," ).append("\n"); 
		query.append("                12             ORD2," ).append("\n"); 
		query.append("                1              ORD3," ).append("\n"); 
		query.append("                TO_CLOB( '}CNTR_INFO'||chr(10) )  STR" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY  X," ).append("\n"); 
		query.append("				BKG_CONTAINER A" ).append("\n"); 
		query.append("		WHERE X.BKG_NO = A.BKG_NO" ).append("\n"); 
		query.append("		  AND X.CNTR_NO = A.CNTR_NO" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("       )" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  X.ORD    ORD1," ).append("\n"); 
		query.append("        13       ORD2," ).append("\n"); 
		query.append("        1        ORD3," ).append("\n"); 
		query.append("        TO_CLOB( '{QTY'||CHR(10)||" ).append("\n"); 
		query.append("        'TYPESIZE:'||NVL(CNTR_TPSZ_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'COUNT:'||NVL(OP_CNTR_QTY,0)||CHR(10)||" ).append("\n"); 
		query.append("        '}QTY'||CHR(10) )	BKG_QTY_INFO" ).append("\n"); 
		query.append("FROM   (SELECT  BKG_NO," ).append("\n"); 
		query.append("                MAX(ORD)  ORD" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY" ).append("\n"); 
		query.append("        WHERE   ROWNUM >= 1" ).append("\n"); 
		query.append("        GROUP BY BKG_NO" ).append("\n"); 
		query.append("       )  X," ).append("\n"); 
		query.append("        BKG_QUANTITY   A" ).append("\n"); 
		query.append("WHERE   X.BKG_NO = A.BKG_NO" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  /*+ ORDERED USE_NL(X A D E F B C) INDEX(A XPKBKG_VVD) */" ).append("\n"); 
		query.append("        X.ORD    ORD1," ).append("\n"); 
		query.append("        14       ORD2," ).append("\n"); 
		query.append("        ROW_NUMBER() OVER (PARTITION BY X.ORD ORDER BY X.ORD, A.VSL_PRE_PST_CD, A.VSL_SEQ)  ORD3," ).append("\n"); 
		query.append("        TO_CLOB( '{BKGVVD'||chr(10)||" ).append("\n"); 
		query.append("        'BVVD1:'||NVL(A.VSL_CD,' ')||NVL(A.SKD_VOY_NO,' ')||" ).append("\n"); 
		query.append("        NVL(A.SKD_DIR_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BVVD_CONSORT_VOY:'||NVL(C.IB_CSSM_VOY_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'BVVD_LANE:'||NVL(A.SLAN_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'VSL_CALLSIGN1:'||NVL(D.CALL_SGN_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'VSL_LLOYDCODE1:'||NVL(D.LLOYD_NO,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'VSL_FULLNAME1:'||NVL(D.VSL_ENG_NM,' ')||CHR(10)||" ).append("\n"); 
		query.append("        'VVD_REF_NO1:'||(SELECT PSA_VOY_DIR_CD" ).append("\n"); 
		query.append("	                       FROM BKG_CSTMS_MY_VVD PSA" ).append("\n"); 
		query.append("	                      WHERE PSA.VSL_CD = A.VSL_CD" ).append("\n"); 
		query.append("	                        AND PSA.SKD_VOY_NO = A.SKD_VOY_NO" ).append("\n"); 
		query.append("	                        AND PSA.SKD_DIR_CD = A.SKD_DIR_CD" ).append("\n"); 
		query.append("	                        AND ROWNUM = 1" ).append("\n"); 
		query.append("	                    )||CHR(10)||" ).append("\n"); 
		query.append("        'BLPOL1:'||NVL(A.POL_CD,' ')||chr(10)||" ).append("\n"); 
		query.append("		'BLPOL_YDCD1:'||NVL(A.POL_YD_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("		'BLPOL_YDNM1:'||(SELECT YD_NM FROM MDM_YARD WHERE YD_CD = A.POL_YD_CD)||CHR(10)||" ).append("\n"); 
		query.append("        'POL_FULLNAME1:'||E.LOC_NM||chr(10)||" ).append("\n"); 
		query.append("        'BLPOD1:'||NVL(A.POD_CD,' ')||chr(10)||" ).append("\n"); 
		query.append("		'BLPOD_YDCD1:'||NVL(A.POD_YD_CD,' ')||CHR(10)||" ).append("\n"); 
		query.append("		'BLPOD_YDNM1:'||(SELECT YD_NM FROM MDM_YARD WHERE YD_CD = A.POD_YD_CD)||CHR(10)||" ).append("\n"); 
		query.append("        'POD_FULLNAME1:'||F.LOC_NM||chr(10)||" ).append("\n"); 
		query.append("        'POLETA1:'||NVL(TO_CHAR(b.VPS_ETA_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'POLETD1:'||NVL(TO_CHAR(b.VPS_ETD_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PODETA1:'||NVL(TO_CHAR(c.VPS_ETA_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'PODETD1:'||NVL(TO_CHAR(c.VPS_ETD_DT,'YYYYMMDDHH24MI'),' ')||CHR(10)||" ).append("\n"); 
		query.append("        'OP_CODE:'||CHR(10)||" ).append("\n"); 
		query.append("        '}BKGVVD'||CHR(10) )	BKG_VVD_INFO" ).append("\n"); 
		query.append("FROM   (SELECT  BKG_NO," ).append("\n"); 
		query.append("                MAX(ORD)  ORD" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY" ).append("\n"); 
		query.append("        WHERE   ROWNUM >= 1" ).append("\n"); 
		query.append("        GROUP BY BKG_NO" ).append("\n"); 
		query.append("       )  X," ).append("\n"); 
		query.append("        BKG_VVD          A," ).append("\n"); 
		query.append("        MDM_VSL_CNTR     D," ).append("\n"); 
		query.append("        MDM_LOCATION     E," ).append("\n"); 
		query.append("        MDM_LOCATION     F," ).append("\n"); 
		query.append("        VSK_VSL_PORT_SKD B," ).append("\n"); 
		query.append("        VSK_VSL_PORT_SKD C" ).append("\n"); 
		query.append("WHERE   X.BKG_NO          = A.BKG_NO" ).append("\n"); 
		query.append("AND     A.VSL_CD          = B.VSL_CD(+)" ).append("\n"); 
		query.append("AND     A.SKD_VOY_NO      = B.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("AND     A.SKD_DIR_CD      = B.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("AND     A.POL_CD          = B.VPS_PORT_CD(+)" ).append("\n"); 
		query.append("AND     B.CLPT_IND_SEQ(+) = '1'" ).append("\n"); 
		query.append("AND     A.VSL_CD          = C.VSL_CD(+)" ).append("\n"); 
		query.append("AND     A.SKD_VOY_NO      = C.SKD_VOY_NO(+)" ).append("\n"); 
		query.append("AND     A.SKD_DIR_CD      = C.SKD_DIR_CD(+)" ).append("\n"); 
		query.append("AND     A.POD_CD          = C.VPS_PORT_CD(+)" ).append("\n"); 
		query.append("AND     C.CLPT_IND_SEQ(+) = '1'" ).append("\n"); 
		query.append("AND     A.VSL_CD          = D.VSL_CD(+)" ).append("\n"); 
		query.append("AND     A.POL_CD          = E.LOC_CD(+)" ).append("\n"); 
		query.append("AND     A.POD_CD          = F.LOC_CD(+)" ).append("\n"); 
		query.append("UNION ALL" ).append("\n"); 
		query.append("SELECT  X.ORD          ORD1," ).append("\n"); 
		query.append("        15             ORD2," ).append("\n"); 
		query.append("        1              ORD3," ).append("\n"); 
		query.append("        TO_CLOB( '}BL_INFO'||chr(10) )  STR" ).append("\n"); 
		query.append("FROM   (SELECT  BKG_NO," ).append("\n"); 
		query.append("                MAX(ORD)  ORD" ).append("\n"); 
		query.append("        FROM    BKG_CSTMS_TML_EDI_TMP_KEY" ).append("\n"); 
		query.append("        GROUP BY BKG_NO" ).append("\n"); 
		query.append("       )  X" ).append("\n"); 

	}
}