/*=========================================================
*Copyright(c) 2014 CyberLogitec
*@FileName : GeneralBookingSearchDBDAOsearchFaxEmailForNoticeRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2014.06.09
*@LastModifier : 
*@LastVersion : 1.0
* 2014.06.09 
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.esm.bkg.bookingconduct.generalbookingconduct.generalbookingsearch.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class GeneralBookingSearchDBDAOsearchFaxEmailForNoticeRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * searchFaxEmailForNotice
	  * </pre>
	  */
	public GeneralBookingSearchDBDAOsearchFaxEmailForNoticeRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bkg_no",new String[]{arrTmp[0],arrTmp[1]});

		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("ofc_cd",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.esm.bkg.bookingconduct.generalbookingconduct.generalbookingsearch.integration").append("\n"); 
		query.append("FileName : GeneralBookingSearchDBDAOsearchFaxEmailForNoticeRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("--BOOKING RECEIPT " ).append("\n"); 
		query.append(" SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */1 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'BK') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'BK' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML, CNTC.CNTC_PSON_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NULL FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NULL FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NULL FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NULL FRT_HDN_FLG" ).append("\n"); 
		query.append("        , NULL DISPLAY_HIDDEN" ).append("\n"); 
		query.append("         , REGEXP_REPLACE((SELECT (" ).append("\n"); 
		query.append("                  (SELECT RCT_NTC_RMK ||  chr(13) || chr(10)" ).append("\n"); 
		query.append("                     FROM BKG_BOOKING A1, BKG_RPT_ITM_STUP A2" ).append("\n"); 
		query.append("                    WHERE A1.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                      AND A1.BKG_OFC_CD = A2.BKG_OFC_CD" ).append("\n"); 
		query.append("                      AND A2.CUST_CNT_CD IS NULL" ).append("\n"); 
		query.append("                      AND A2.CUST_SEQ IS NULL" ).append("\n"); 
		query.append("                      AND ROWNUM = 1)" ).append("\n"); 
		query.append("                      ) " ).append("\n"); 
		query.append("                    ||" ).append("\n"); 
		query.append("                   (SELECT RCT_NTC_RMK" ).append("\n"); 
		query.append("                     FROM BKG_BOOKING A1, BKG_CUSTOMER A2, BKG_RPT_ITM_STUP A3" ).append("\n"); 
		query.append("                    WHERE A1.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                      AND A1.BKG_OFC_CD = A3.BKG_OFC_CD" ).append("\n"); 
		query.append("                      AND A1.BKG_NO = A2.BKG_NO" ).append("\n"); 
		query.append("                      AND A2.BKG_CUST_TP_CD IN('S', 'F')" ).append("\n"); 
		query.append("                      AND A2.CUST_CNT_CD = A3.CUST_CNT_CD" ).append("\n"); 
		query.append("                      AND A2.CUST_SEQ = A3.CUST_SEQ" ).append("\n"); 
		query.append("                      AND ROWNUM = 1)" ).append("\n"); 
		query.append("                      FROM DUAL) ,'[[:cntrl:]]$','') REMARK" ).append("\n"); 
		query.append("		, 'Y' ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD" ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'BK'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'BK'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC.BKG_CNTC_PSON_TP_CD = 'BK'" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--Simple S/I" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */2 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'SS') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'SS' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML, CNTC.CNTC_PSON_EML) EML -- SI CONTACT EMAIL" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ALL_FLG ELSE EML.FRT_ALL_FLG END,'N') FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CLT_FLG ELSE EML.FRT_CLT_FLG END,'N') FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_PPD_FLG ELSE EML.FRT_PPD_FLG END,'N') FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CHG_FLG ELSE EML.FRT_CHG_FLG END,'N') FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ARR_FLG ELSE EML.FRT_ARR_FLG END,'N') FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_HDN_FLG ELSE EML.FRT_HDN_FLG END,'N') FRT_HDN_FLG" ).append("\n"); 
		query.append("        , 'Display Hidden' DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, BKG_DRAFT_REMARK_FNC(BK.BKG_NO, '6', 'N','') REMARK" ).append("\n"); 
		query.append("		, 'Y' ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD        " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("		, (" ).append("\n"); 
		query.append("            SELECT BKG_NO, CNTC_PSON_FAX_NO, CNTC_PSON_EML " ).append("\n"); 
		query.append("            FROM BKG_CNTC_PSON CNTC" ).append("\n"); 
		query.append("            WHERE BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("             AND ROWNUM = 1" ).append("\n"); 
		query.append("           ) CNTC" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'SS'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'SS'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC.BKG_NO" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION   " ).append("\n"); 
		query.append("--RELEASE ORDER" ).append("\n"); 
		query.append(" SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */3 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'CN') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'CN' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, PKUP.FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML,    PKUP.YD_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NULL FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NULL FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NULL FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NULL FRT_HDN_FLG" ).append("\n"); 
		query.append("        , NULL DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, '' REMARK" ).append("\n"); 
		query.append("		, 'Y' ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD        " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append("        , MDM_YARD PKUP" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'CN'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'CN'      = EML.NTC_KND_CD(+)  " ).append("\n"); 
		query.append("   AND BK.MTY_PKUP_YD_CD = PKUP.YD_CD(+)" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--DRAFT B/L" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */4 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'BL') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'BL' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(NVL(EML.NTC_EML, CNTC.CNTC_PSON_EML),(SELECT CNTC_PSON_EML FROM BKG_CNTC_PSON WHERE BKG_NO = BK.BKG_NO AND 'BK' = BKG_CNTC_PSON_TP_CD AND ROWNUM = 1)) AS EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ALL_FLG ELSE EML.FRT_ALL_FLG END,'N') FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CLT_FLG ELSE EML.FRT_CLT_FLG END,'N') FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_PPD_FLG ELSE EML.FRT_PPD_FLG END,'N') FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CHG_FLG ELSE EML.FRT_CHG_FLG END,'N') FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ARR_FLG ELSE EML.FRT_ARR_FLG END,'N') FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_HDN_FLG ELSE EML.FRT_HDN_FLG END,'N') FRT_HDN_FLG" ).append("\n"); 
		query.append("        , 'Display Hidden' DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, BKG_DRAFT_REMARK_FNC(BK.BKG_NO, '6', 'N','') REMARK" ).append("\n"); 
		query.append("		, 'Y' ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD        " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'BL'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'BL'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC.BKG_CNTC_PSON_TP_CD = 'SI'" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--N/N Copy" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */5 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'NN') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'NN' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML,    CNTC.CNTC_PSON_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ALL_FLG ELSE EML.FRT_ALL_FLG END,'N') FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CLT_FLG ELSE EML.FRT_CLT_FLG END,'N') FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_PPD_FLG ELSE EML.FRT_PPD_FLG END,'N') FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CHG_FLG ELSE EML.FRT_CHG_FLG END,'N') FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ARR_FLG ELSE EML.FRT_ARR_FLG END,'N') FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_HDN_FLG ELSE EML.FRT_HDN_FLG END,'N') FRT_HDN_FLG" ).append("\n"); 
		query.append("        , 'Display Hidden' AS DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, '' AS REMARK" ).append("\n"); 
		query.append("		, NVL((SELECT OBL_ISS_FLG FROM BKG_BL_ISS WHERE BKG_NO = BK.BKG_NO),'N') AS ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD        " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'NN'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'NN'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC.BKG_CNTC_PSON_TP_CD = 'SI'" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--Revised Rate" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */6 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'RR') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'RR' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML, CNTC.CNTC_PSON_EML) EML -- SI CONTACT EMAIL" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ALL_FLG ELSE EML.FRT_ALL_FLG END,'N') FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CLT_FLG ELSE EML.FRT_CLT_FLG END,'N') FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_PPD_FLG ELSE EML.FRT_PPD_FLG END,'N') FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CHG_FLG ELSE EML.FRT_CHG_FLG END,'N') FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ARR_FLG ELSE EML.FRT_ARR_FLG END,'N') FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_HDN_FLG ELSE EML.FRT_HDN_FLG END,'N') FRT_HDN_FLG" ).append("\n"); 
		query.append("        , 'Display Hidden' DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, BKG_DRAFT_REMARK_FNC(BK.BKG_NO, '6', 'N','') REMARK" ).append("\n"); 
		query.append("		, 'Y' ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD        " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("		, (" ).append("\n"); 
		query.append("            SELECT BKG_NO, CNTC_PSON_FAX_NO, CNTC_PSON_EML " ).append("\n"); 
		query.append("            FROM BKG_CNTC_PSON CNTC" ).append("\n"); 
		query.append("            WHERE BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("             AND ROWNUM = 1" ).append("\n"); 
		query.append("           ) CNTC" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'RR'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'RR'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC.BKG_NO" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--WAY B/L" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */7 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'WB') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'WB' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML,    CNTC.CNTC_PSON_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ALL_FLG ELSE EML.FRT_ALL_FLG END,'N') FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CLT_FLG ELSE EML.FRT_CLT_FLG END,'N') FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_PPD_FLG ELSE EML.FRT_PPD_FLG END,'N') FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CHG_FLG ELSE EML.FRT_CHG_FLG END,'N') FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ARR_FLG ELSE EML.FRT_ARR_FLG END,'N') FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_HDN_FLG ELSE EML.FRT_HDN_FLG END,'N') FRT_HDN_FLG" ).append("\n"); 
		query.append("        , 'Display Hidden' DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, '' REMARK" ).append("\n"); 
		query.append("		, DECODE(BK.BL_TP_CD, 'W', 'Y', 'N') ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD        " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'WB'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'WB'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC.BKG_CNTC_PSON_TP_CD = 'SI'   " ).append("\n"); 
		query.append("--   AND 'W'       = NVL(BK.BL_TP_CD(+), 'N')" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--SURRENDER NOTICE" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */8 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'SN') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'SN' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML,    CNTC.CNTC_PSON_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ALL_FLG ELSE EML.FRT_ALL_FLG END,'N') FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CLT_FLG ELSE EML.FRT_CLT_FLG END,'N') FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_PPD_FLG ELSE EML.FRT_PPD_FLG END,'N') FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_CHG_FLG ELSE EML.FRT_CHG_FLG END,'N') FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_ARR_FLG ELSE EML.FRT_ARR_FLG END,'N') FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NVL(CASE WHEN FAX.SND_RQST_DT > EML.SND_RQST_DT THEN FAX.FRT_HDN_FLG ELSE EML.FRT_HDN_FLG END,'N') FRT_HDN_FLG" ).append("\n"); 
		query.append("        , NULL DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, '' REMARK" ).append("\n"); 
		query.append("		, DECODE(ISS.OBL_SRND_FLG, 'Y', 'Y', 'N') ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD       " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append("		, BKG_BL_ISS ISS" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = ISS.BKG_NO (+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'SN'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'SN'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC.BKG_CNTC_PSON_TP_CD = 'SI'   " ).append("\n"); 
		query.append("   AND 'Y'       = ISS.OBL_SRND_FLG(+)" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--Doc cut-off Reminder NOTICE" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */9 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'DR') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'DR' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC1.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(NVL(EML.NTC_EML,    CNTC1.CNTC_PSON_EML),CNTC2.CNTC_PSON_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NULL FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NULL FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NULL FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NULL FRT_HDN_FLG" ).append("\n"); 
		query.append("        , NULL DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, '' REMARK" ).append("\n"); 
		query.append("		, 'Y' ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD       " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC1" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC2" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND (BK.POR_CD like 'US%' " ).append("\n"); 
		query.append("   OR BK.POR_CD like  'CA%')" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'DR'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'DR'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC1.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC1.BKG_CNTC_PSON_TP_CD = 'SI' " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC2.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC2.BKG_CNTC_PSON_TP_CD = 'BK' " ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--AES/CAED Reminder NOTICE" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */10 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = 'UR') NTC_KND_NM" ).append("\n"); 
		query.append("        , 'UR' NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(FAX.NTC_FAX_NO, CNTC1.CNTC_PSON_FAX_NO) FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(NVL(EML.NTC_EML,    CNTC1.CNTC_PSON_EML),CNTC2.CNTC_PSON_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NULL FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NULL FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NULL FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NULL FRT_HDN_FLG" ).append("\n"); 
		query.append("        , NULL DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, '' REMARK" ).append("\n"); 
		query.append("		, 'Y' ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD       " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC1" ).append("\n"); 
		query.append("        , BKG_CNTC_PSON CNTC2" ).append("\n"); 
		query.append("        , BKG_NTC_HIS FAX" ).append("\n"); 
		query.append("        , BKG_NTC_HIS EML" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND (BK.POR_CD like 'US%' " ).append("\n"); 
		query.append("   OR BK.POR_CD like  'CA%')" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'F'       = FAX.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'UR'      = FAX.NTC_KND_CD(+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND 'M'       = EML.NTC_VIA_cD(+)" ).append("\n"); 
		query.append("   AND 'UR'      = EML.NTC_KND_CD(+)   " ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC1.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC1.BKG_CNTC_PSON_TP_CD = 'SI'" ).append("\n"); 
		query.append("   AND BK.BKG_NO = CNTC2.BKG_NO" ).append("\n"); 
		query.append("   AND CNTC2.BKG_CNTC_PSON_TP_CD = 'BK'" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append("UNION" ).append("\n"); 
		query.append("--C/H NOTICE" ).append("\n"); 
		query.append("SELECT /*+ INDEX_DESC(FAX XPKBKG_NTC_HIS) INDEX_DESC(EML XPKBKG_NTC_HIS) */11 ORD" ).append("\n"); 
		query.append("		, (SELECT INTG_CD_VAL_DP_DESC " ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL " ).append("\n"); 
		query.append("         WHERE INTG_CD_ID = 'CD01552'" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = DECODE((SELECT DECODE(USR_LOC.CONTI_CD, BK_LOC.CONTI_CD, 'O', 'I') IO_BND_CD" ).append("\n"); 
		query.append("										    FROM MDM_ORGANIZATION USR" ).append("\n"); 
		query.append("											   	, MDM_LOCATION USR_LOC" ).append("\n"); 
		query.append("											   	, BKG_BOOKING BK " ).append("\n"); 
		query.append("											   	, MDM_LOCATION BK_LOC	" ).append("\n"); 
		query.append("										   WHERE USR_LOC.LOC_CD= USR.LOC_CD" ).append("\n"); 
		query.append("											 AND USR.OFC_CD    = @[ofc_cd]" ).append("\n"); 
		query.append("										     AND BK.POL_CD     = BK_LOC.LOC_CD" ).append("\n"); 
		query.append("										     AND BK.BKG_NO     = @[bkg_no]), 'O', 'HO', 'HI')) NTC_KND_NM" ).append("\n"); 
		query.append("        , DECODE((SELECT DECODE(USR_LOC.CONTI_CD, BK_LOC.CONTI_CD, 'O', 'I') IO_BND_CD" ).append("\n"); 
		query.append("				    FROM MDM_ORGANIZATION USR" ).append("\n"); 
		query.append("					   	, MDM_LOCATION USR_LOC" ).append("\n"); 
		query.append("					   	, BKG_BOOKING BK " ).append("\n"); 
		query.append("					   	, MDM_LOCATION BK_LOC	" ).append("\n"); 
		query.append("				   WHERE USR_LOC.LOC_CD= USR.LOC_CD" ).append("\n"); 
		query.append("					 AND USR.OFC_CD    = @[ofc_cd]" ).append("\n"); 
		query.append("				     AND BK.POL_CD     = BK_LOC.LOC_CD" ).append("\n"); 
		query.append("				     AND BK.BKG_NO     = @[bkg_no]), 'O', 'HO', 'HI') NTC_KND_CD" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , FAX.NTC_FAX_NO FAX_NO" ).append("\n"); 
		query.append("        , FAX.SND_USR_ID FAX_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = FAX.SND_USR_ID) FAX_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT XPT_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          NVL ((SELECT UPD_DT FROM COM_FAX_SND_INFO WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("          FAX.SND_RQST_DT)) AS FAX_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                         WHERE FAX_SND_NO = FAX.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT FAX_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("                           WHERE FAX_SND_NO = FAX.SND_ID),1,2,2,2,3,2,4,2,5,3,6,4,1)," ).append("\n"); 
		query.append("                  NVL2(FAX.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(FAX.BKG_NTC_SND_RSLT_CD,4,2,5,3,6,4,1),1))) AS FAX_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT NVL(XPT_ERR_MSG, XPT_ERR_DTL_MSG)" ).append("\n"); 
		query.append("             FROM COM_FAX_SND_INFO" ).append("\n"); 
		query.append("            WHERE FAX_SND_NO = FAX.SND_ID) AS FAX_FAIL_REASON" ).append("\n"); 
		query.append("        --------------------------" ).append("\n"); 
		query.append("        , NVL(EML.NTC_EML,    TRO.CNTC_EML) EML" ).append("\n"); 
		query.append("        , EML.SND_USR_ID EML_SENDER" ).append("\n"); 
		query.append("        , (SELECT USR_NM FROM COM_USER USR WHERE USR.USR_ID = EML.SND_USR_ID) EML_SENDER_NM" ).append("\n"); 
		query.append("        , NVL ((SELECT EML_DT" ).append("\n"); 
		query.append("                  FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                 WHERE EML_SND_NO = EML.SND_ID),EML.SND_RQST_DT) AS EML_SEND_DT" ).append("\n"); 
		query.append("        , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("             FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("            WHERE 'CD02396' = INTG_CD_ID" ).append("\n"); 
		query.append("              AND INTG_CD_VAL_CTNT =" ).append("\n"); 
		query.append("                  NVL2((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                          FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                         WHERE EML_SND_NO = EML.SND_ID)," ).append("\n"); 
		query.append("                  DECODE((SELECT EML_PROC_STS_CD" ).append("\n"); 
		query.append("                            FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("                           WHERE EML_SND_NO = EML.SND_ID),1,2,2,2,3,3,4,4,1)," ).append("\n"); 
		query.append("                  NVL2(EML.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                  DECODE(EML.BKG_NTC_SND_RSLT_CD,3,3,4,4,1),1)) ) AS EML_SEND_RESULT" ).append("\n"); 
		query.append("        , (SELECT EML_ERR_MSG" ).append("\n"); 
		query.append("             FROM COM_EML_SND_INFO" ).append("\n"); 
		query.append("            WHERE EML_SND_NO = EML.SND_ID) AS EML_FAIL_REASON" ).append("\n"); 
		query.append("        , NULL FRT_ALL_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CLT_FLG" ).append("\n"); 
		query.append("        , NULL FRT_PPD_FLG" ).append("\n"); 
		query.append("        , NULL FRT_CHG_FLG" ).append("\n"); 
		query.append("        , NULL FRT_ARR_FLG" ).append("\n"); 
		query.append("        , NULL FRT_HDN_FLG" ).append("\n"); 
		query.append("        , NULL DISPLAY_HIDDEN" ).append("\n"); 
		query.append("		, '' REMARK" ).append("\n"); 
		query.append("		, DECODE(NVL(TRO.BKG_NO, 'N'), 'N', 'N', 'Y') ENABLE" ).append("\n"); 
		query.append("        , BK.BKG_NO" ).append("\n"); 
		query.append("        , BK.POR_CD" ).append("\n"); 
		query.append("        , BK.VSL_CD" ).append("\n"); 
		query.append("        , BK.SKD_VOY_NO" ).append("\n"); 
		query.append("        , BK.SKD_DIR_CD       " ).append("\n"); 
		query.append("  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("        , (SELECT BKG_NO, SND_RQST_DT, SND_USR_ID, NTC_FAX_NO, SND_ID, BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("             FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("            WHERE BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("              AND 'F'    = NTC_VIA_CD(+)" ).append("\n"); 
		query.append("              AND DECODE((SELECT DECODE(USR_LOC.CONTI_CD, BK_LOC.CONTI_CD, 'O', 'I') IO_BND_CD" ).append("\n"); 
		query.append("						    FROM MDM_ORGANIZATION USR" ).append("\n"); 
		query.append("							   	, MDM_LOCATION USR_LOC" ).append("\n"); 
		query.append("							   	, BKG_BOOKING BK " ).append("\n"); 
		query.append("							   	, MDM_LOCATION BK_LOC	" ).append("\n"); 
		query.append("						   WHERE USR_LOC.LOC_CD= USR.LOC_CD" ).append("\n"); 
		query.append("							 AND USR.OFC_CD    = @[ofc_cd]" ).append("\n"); 
		query.append("						     AND BK.POL_CD     = BK_LOC.LOC_CD" ).append("\n"); 
		query.append("						     AND BK.BKG_NO     = @[bkg_no]), 'O', 'HO', 'HI') = NTC_KND_CD) FAX" ).append("\n"); 
		query.append("        , (SELECT BKG_NO, SND_RQST_DT, SND_USR_ID, NTC_EML, SND_ID, BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("             FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("            WHERE BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("              AND 'M'    = NTC_VIA_CD(+)" ).append("\n"); 
		query.append("              AND DECODE((SELECT DECODE(USR_LOC.CONTI_CD, BK_LOC.CONTI_CD, 'O', 'I') IO_BND_CD" ).append("\n"); 
		query.append("						    FROM MDM_ORGANIZATION USR" ).append("\n"); 
		query.append("							   	, MDM_LOCATION USR_LOC" ).append("\n"); 
		query.append("							   	, BKG_BOOKING BK " ).append("\n"); 
		query.append("							   	, MDM_LOCATION BK_LOC	" ).append("\n"); 
		query.append("						   WHERE USR_LOC.LOC_CD= USR.LOC_CD" ).append("\n"); 
		query.append("							 AND USR.OFC_CD    = @[ofc_cd]" ).append("\n"); 
		query.append("						     AND BK.POL_CD     = BK_LOC.LOC_CD" ).append("\n"); 
		query.append("						     AND BK.BKG_NO     = @[bkg_no]), 'O', 'HO', 'HI') = NTC_KND_CD) EML" ).append("\n"); 
		query.append("        , (SELECT DISTINCT TRO.BKG_NO" ).append("\n"); 
		query.append("					, TRO.IO_BND_CD" ).append("\n"); 
		query.append("                    , DTL.CNTC_EML" ).append("\n"); 
		query.append("					, DECODE(TRO.IO_BND_CD, 'O', 'HO', 'HI') NTC_KND_CD" ).append("\n"); 
		query.append("             FROM BKG_EUR_TRO TRO" ).append("\n"); 
		query.append("                  	, BKG_EUR_TRO_DTL DTL" ).append("\n"); 
		query.append("					, (SELECT DECODE(USR_LOC.CONTI_CD, BK_LOC.CONTI_CD, 'O', 'I') IO_BND_CD" ).append("\n"); 
		query.append("									    FROM MDM_ORGANIZATION USR" ).append("\n"); 
		query.append("										   	, MDM_LOCATION USR_LOC" ).append("\n"); 
		query.append("										   	, BKG_BOOKING BK " ).append("\n"); 
		query.append("										   	, MDM_LOCATION BK_LOC	" ).append("\n"); 
		query.append("									   WHERE USR_LOC.LOC_CD= USR.LOC_CD" ).append("\n"); 
		query.append("										 AND USR.OFC_CD    = @[ofc_cd]" ).append("\n"); 
		query.append("									     AND BK.POL_CD     = BK_LOC.LOC_CD" ).append("\n"); 
		query.append("									     AND BK.BKG_NO     = @[bkg_no]) BOUND" ).append("\n"); 
		query.append("            WHERE TRO.BKG_NO    = @[bkg_no]" ).append("\n"); 
		query.append("              AND TRO.BKG_NO    = DTL.BKG_NO" ).append("\n"); 
		query.append("              AND TRO.IO_BND_CD = DTL.IO_BND_CD" ).append("\n"); 
		query.append("              AND TRO.TRO_SEQ   = DTL.TRO_SEQ              " ).append("\n"); 
		query.append("              AND 'Y'           = TRO.CFM_FLG" ).append("\n"); 
		query.append("              and BOUND.IO_BND_CD = TRO.IO_BND_CD(+) ) TRO" ).append("\n"); 
		query.append(" WHERE BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("   AND BK.BKG_NO = FAX.BKG_NO (+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = EML.BKG_NO (+)" ).append("\n"); 
		query.append("   AND BK.BKG_NO = TRO.BKG_NO(+)" ).append("\n"); 
		query.append("   AND ROWNUM    = 1" ).append("\n"); 
		query.append(" ORDER BY ORD" ).append("\n"); 

	}
}