/*=========================================================
*Copyright(c) 2018 CyberLogitec
*@FileName : GeneralBookingSearchDBDAOsearchEdiForNoticeRSQL.java
*@FileTitle : 
*Open Issues :
*Change history :
*@LastModifyDate : 2018.01.31
*@LastModifier : 
*@LastVersion : 1.0
* 2018.01.31 
* 1.0 Creation
=========================================================*/
package com.hanjin.apps.alps.esm.bkg.bookingconduct.generalbookingconduct.generalbookingsearch.integration;

import java.util.HashMap;
import org.apache.log4j.Logger;
import com.hanjin.framework.support.db.ISQLTemplate;

/**
 *
 * @author 
 * @see DAO 참조
 * @since J2EE 1.6
 */

public class GeneralBookingSearchDBDAOsearchEdiForNoticeRSQL implements ISQLTemplate{

	private StringBuffer query = new StringBuffer();
	
	Logger log =Logger.getLogger(this.getClass());
	
	/** Parameters definition in params/param elements */
	private HashMap<String,String[]> params = null;
	
	/**
	  * <pre>
	  * searchEdiForNotice
	  * </pre>
	  */
	public GeneralBookingSearchDBDAOsearchEdiForNoticeRSQL(){
		setQuery();
		params = new HashMap<String,String[]>();
		String tmp = null;
		String[] arrTmp = null;
		tmp = java.sql.Types.VARCHAR + ",N";
		arrTmp = tmp.split(",");
		if(arrTmp.length !=2){
			throw new IllegalArgumentException();
		}
		params.put("bkg_no",new String[]{arrTmp[0],arrTmp[1]});

		query.append("/*").append("\n"); 
		query.append("Path : com.hanjin.apps.alps.esm.bkg.bookingconduct.generalbookingconduct.generalbookingsearch.integration").append("\n"); 
		query.append("FileName : GeneralBookingSearchDBDAOsearchEdiForNoticeRSQL").append("\n"); 
		query.append("*/").append("\n"); 
	}
	
	public String getSQL(){
		return query.toString();
	}
	
	public HashMap<String,String[]> getParams() {
		return params;
	}

	/**
	 * Query 생성
	 */
	public void setQuery(){
		query.append("WITH EDI_ID AS" ).append("\n"); 
		query.append("     (SELECT GROUP_EDI_ID" ).append("\n"); 
		query.append("           , GROUP_NM" ).append("\n"); 
		query.append("           , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("           , BKG_CFM_FLG" ).append("\n"); 
		query.append("           , BL_DRFT_FLG" ).append("\n"); 
		query.append("           , CGO_TRAK_FLG" ).append("\n"); 
		query.append("           , CASE WHEN REF_TP_CD IN ('7SC','7RFA') THEN REF_CODE ELSE SUBSTR(REF_CODE,2) END AS REF_CODE" ).append("\n"); 
		query.append("           , SUBSTR(REF_TP_CD, 2) REF_TP_CD" ).append("\n"); 
		query.append("           , REF_TP_CD||'@'||CASE WHEN REF_TP_CD IN ('7SC','7RFA') THEN REF_CODE ELSE SUBSTR(REF_CODE,2) END AS REF_TMP" ).append("\n"); 
		query.append("        FROM (SELECT GRP.ESVC_GRP_CD      GROUP_EDI_ID" ).append("\n"); 
		query.append("                   , GRP.ESVC_GRP_NM      GROUP_NM" ).append("\n"); 
		query.append("                   , GRP.CUST_TRD_PRNR_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                   , GRP_CUST.BKG_CFM_FLG" ).append("\n"); 
		query.append("                   , GRP_Cust.BL_DRFT_FLG" ).append("\n"); 
		query.append("                   , GRP_Cust.CGO_TRAK_FLG" ).append("\n"); 
		query.append("                   , DECODE(CUST.BKG_CUST_TP_CD, 'S','1','C','2','N','3','F','4','A','5','6')" ).append("\n"); 
		query.append("                     ||CUST.CUST_CNT_CD||TRIM(TO_CHAR(CUST.CUST_SEQ,'000009')) REF_CODE" ).append("\n"); 
		query.append("                   , DECODE(CUST.BKG_CUST_TP_CD, 'S','1SH','C','2CN','N','3NF','F','4FF','A','5AN','6EX') REF_TP_CD" ).append("\n"); 
		query.append("                FROM BKG_EDI_GRP_CUST GRP_CUST" ).append("\n"); 
		query.append("                   , BKG_EDI_GRP GRP" ).append("\n"); 
		query.append("                   , BKG_CUSTOMER CUST" ).append("\n"); 
		query.append("               WHERE GRP.ESVC_GRP_CD       = GRP_CUST.ESVC_GRP_CD" ).append("\n"); 
		query.append("                 AND GRP.CO_CD             = GRP_CUST.CO_CD" ).append("\n"); 
		query.append("                 AND CUST.CUST_CNT_CD      = GRP_CUST.CNT_CD" ).append("\n"); 
		query.append("                 AND CUST.CUST_SEQ         = GRP_CUST.CUST_SEQ" ).append("\n"); 
		query.append("                 AND GRP.CO_CD             = 'H'" ).append("\n"); 
		query.append("                 AND GRP.ESVC_GRP_DELT_FLG = 'N'" ).append("\n"); 
		query.append("                 AND GRP_CUST.DELT_FLG     = 'N'" ).append("\n"); 
		query.append("                 AND CUST.CUST_CNT_CD      IS NOT NULL" ).append("\n"); 
		query.append("                 AND CUST.BKG_NO           = @[bkg_no]" ).append("\n"); 
		query.append("                 AND CUST.BKG_CUST_TP_CD IN (SELECT COLUMN_VALUE " ).append("\n"); 
		query.append("                                             FROM TABLE(BKG_SPLIT_FNC(DECODE(GRP_CUST.BKG_CUST_TP_DESC,'ALL',CUST.BKG_CUST_TP_CD,GRP_CUST.BKG_CUST_TP_DESC),',')))" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("               UNION" ).append("\n"); 
		query.append("              SELECT GRP.ESVC_GRP_CD      GROUP_EDI_ID" ).append("\n"); 
		query.append("                   , GRP.ESVC_GRP_NM      GROUP_NM" ).append("\n"); 
		query.append("                   , GRP.CUST_TRD_PRNR_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                   , GRP_CUST.BKG_CFM_FLG" ).append("\n"); 
		query.append("                   , GRP_CUST.BL_DRFT_FLG" ).append("\n"); 
		query.append("                   , GRP_CUST.CGO_TRAK_FLG" ).append("\n"); 
		query.append("                   , DECODE(GRP_CUST.BKG_CTRT_TP_CD, '1', BK.SC_NO, '2', BK.RFA_NO) REF_CODE" ).append("\n"); 
		query.append("                   , DECODE(GRP_CUST.BKG_CTRT_TP_CD, '1', '7SC', '2', '7RFA') REF_TP_CD" ).append("\n"); 
		query.append("                FROM BKG_EDI_GRP GRP" ).append("\n"); 
		query.append("                   , BKG_EDI_GRP_CUST GRP_CUST" ).append("\n"); 
		query.append("                   , BKG_BOOKING BK" ).append("\n"); 
		query.append("               WHERE GRP.ESVC_GRP_CD = GRP_CUST.ESVC_GRP_CD" ).append("\n"); 
		query.append("                 AND GRP.CO_CD       = GRP_CUST.CO_CD" ).append("\n"); 
		query.append("                 AND DECODE(GRP_CUST.BKG_CTRT_TP_CD, '1', BK.SC_NO, '2', BK.RFA_NO)        = GRP_CUST.SC_NO" ).append("\n"); 
		query.append("                 AND 'H'             = GRP.CO_CD" ).append("\n"); 
		query.append("                 AND 'N'             = GRP.ESVC_GRP_DELT_FLG" ).append("\n"); 
		query.append("                 AND ' '             < GRP_CUST.SC_NO" ).append("\n"); 
		query.append("                 AND 'N'             = GRP_CUST.DELT_FLG" ).append("\n"); 
		query.append("                 AND (BK.SC_NO        IS NOT NULL OR BK.RFA_NO IS NOT NULL)" ).append("\n"); 
		query.append("                 AND BK.BKG_NO       = @[bkg_no])" ).append("\n"); 
		query.append("	  WHERE 'Y' = CASE EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                    WHEN '6135830007' THEN                            " ).append("\n"); 
		query.append("                        (SELECT /*+ INDEX(MST XPKBKG_XTER_RQST_MST)*/" ).append("\n"); 
		query.append("                               DECODE(COUNT(1), 1, 'Y', 'N') AS TP_ID" ).append("\n"); 
		query.append("                           FROM BKG_XTER_RQST_MST MST" ).append("\n"); 
		query.append("                          WHERE XTER_SNDR_ID = '6135830007'" ).append("\n"); 
		query.append("                            AND BKG_NO = @[bkg_no] " ).append("\n"); 
		query.append("                            AND DOC_TP_CD = 'B'" ).append("\n"); 
		query.append("                            AND BKG_UPLD_STS_CD NOT IN ('D','R')" ).append("\n"); 
		query.append("                            AND EXISTS (SELECT 'X'" ).append("\n"); 
		query.append("                                          FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                                         WHERE BK.BKG_NO = MST.BKG_NO" ).append("\n"); 
		query.append("                                           AND XTER_BKG_RQST_CD = 'EDI')" ).append("\n"); 
		query.append("                            AND ROWNUM = 1)" ).append("\n"); 
		query.append("                    ELSE 'Y'" ).append("\n"); 
		query.append("                   END                  " ).append("\n"); 
		query.append("       ORDER BY REF_CODE, REF_TP_CD)" ).append("\n"); 
		query.append("SELECT NTC_KND_NM" ).append("\n"); 
		query.append("     , KIND.NTC_KND_CD" ).append("\n"); 
		query.append("     , REF_TP_CD" ).append("\n"); 
		query.append("     , REF_CODE" ).append("\n"); 
		query.append("     , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("     , GROUP_EDI_ID" ).append("\n"); 
		query.append("     , GROUP_NM" ).append("\n"); 
		query.append("     , SENDER" ).append("\n"); 
		query.append("     , SENDER_NM" ).append("\n"); 
		query.append("     , SEND_DT" ).append("\n"); 
		query.append("     , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("     , (SELECT INTG_CD_VAL_DP_DESC" ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("         WHERE DECODE(MST.NTC_KND_CD,'PS','CD01636','CD02396') = INTG_CD_ID" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT = " ).append("\n"); 
		query.append("               DECODE(MST.NTC_KND_CD,'PS'," ).append("\n"); 
		query.append("                   MST.BKG_NTC_SND_RSLT_CD," ).append("\n"); 
		query.append("                   DECODE(MST.BKG_NTC_SND_RSLT_CD,'A',3,'F',4,'N',4,NULL))" ).append("\n"); 
		query.append("       ) AS RESULT" ).append("\n"); 
		query.append("  FROM (SELECT DECODE(INTG_CD_VAL_DP_DESC,'Booking Receipt',                'Booking (Customer)'" ).append("\n"); 
		query.append("                                         ,'Booking Confirmation (Terminal)','Booking (Terminal)'" ).append("\n"); 
		query.append("                                         ,INTG_CD_VAL_DP_DESC) NTC_KND_NM" ).append("\n"); 
		query.append("             , INTG_CD_VAL_CTNT NTC_KND_CD" ).append("\n"); 
		query.append("             , DECODE(INTG_CD_VAL_CTNT,'BL',1,'BK',2,'BT',3,'CN',4,'FC',5,'CT',6,'EX',7,'IM',8,9) ORD" ).append("\n"); 
		query.append("          FROM COM_INTG_CD_DTL" ).append("\n"); 
		query.append("         WHERE 'CD01552' = INTG_CD_ID" ).append("\n"); 
		query.append("           AND INTG_CD_VAL_CTNT IN ('BK','BL','BT','CN'," ).append("\n"); 
		query.append("                                        DECODE((SELECT SUBSTR(POL_CD,1,2) FROM BKG_BOOKING" ).append("\n"); 
		query.append("                                                WHERE BKG_NO = @[bkg_no]),'US','FC',''),'EX','IM','VM')" ).append("\n"); 
		query.append("         UNION ALL " ).append("\n"); 
		query.append("        SELECT 'BOKCON', 'BO', 2.5 " ).append("\n"); 
		query.append("		  FROM BKG_BOOKING BK, BKG_XTER_RQST_MST MST" ).append("\n"); 
		query.append("		 WHERE BK.BKG_NO = MST.BKG_NO" ).append("\n"); 
		query.append("           AND BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append(" 		   AND MST.DOC_TP_CD = 'B'" ).append("\n"); 
		query.append("           AND MST.XTER_SNDR_ID IN ('FSELC'," ).append("\n"); 
		query.append("                   'C1T0M','C1T0P','C1T0S','C1T0W','C1S0'," ).append("\n"); 
		query.append("                   'T612','T613','T614','T615','T621'," ).append("\n"); 
		query.append("                   'T514','T515','T516','T517','T518')" ).append("\n"); 
		query.append("		   AND ROWNUM = 1" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("#if ('SGSIN'==${pol_cd})" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT 'PSA I/F', 'PS', 9 FROM DUAL" ).append("\n"); 
		query.append("#end" ).append("\n"); 
		query.append("       ) KIND" ).append("\n"); 
		query.append("     , (SELECT NTC_KND_CD" ).append("\n"); 
		query.append("             , REF_TP_CD" ).append("\n"); 
		query.append("             , REF_CODE" ).append("\n"); 
		query.append("             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , GROUP_EDI_ID" ).append("\n"); 
		query.append("             , GROUP_NM" ).append("\n"); 
		query.append("             , SENDER" ).append("\n"); 
		query.append("             , SENDER_NM" ).append("\n"); 
		query.append("             , SEND_DT" ).append("\n"); 
		query.append("             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM (SELECT 'BL' NTC_KND_CD" ).append("\n"); 
		query.append("                     , SUBSTRB(MIN(REF_TMP),2,INSTR(MIN(REF_TMP),'@')-2) AS REF_TP_CD" ).append("\n"); 
		query.append("                     , SUBSTRB(MIN(REF_TMP),INSTR(MIN(REF_TMP),'@')+1) AS REF_CODE" ).append("\n"); 
		query.append("                     , EDI_ID.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , EDI_ID.GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , EDI_ID.GROUP_NM" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,NTC.SND_USR_ID,NULL) AS SENDER" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,(SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID),NULL) AS SENDER_NM" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,TO_CHAR(NTC.SND_RQST_DT, 'YYYY-MM-DD HH24:MI'),NULL) AS SEND_DT" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,NTC.BKG_NTC_SND_RSLT_CD,NULL) AS BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                  FROM EDI_ID, BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("                 WHERE EDI_ID.EDI_RECEIVE_ID = NTC.EDI_ID(+)" ).append("\n"); 
		query.append("                   AND 'Y'  = EDI_ID.BL_DRFT_FLG" ).append("\n"); 
		query.append("                   AND 'E'  = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                   AND 'BL' = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                   AND @[bkg_no] = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND GROUP_EDI_ID = NTC.ESVC_GRP_CD(+)" ).append("\n"); 
		query.append("                   AND (EDI_ID.EDI_RECEIVE_ID NOT IN ('INTTRA', 'INTTRANG2')" ).append("\n"); 
		query.append("                       OR EXISTS (SELECT 'X' " ).append("\n"); 
		query.append("                                  FROM BKG_XTER_RQST_MST BXRM " ).append("\n"); 
		query.append("                                  WHERE BXRM.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                                  AND BXRM.DOC_TP_CD = 'S'" ).append("\n"); 
		query.append("                                  AND BXRM.BKG_UPLD_STS_CD = 'F'" ).append("\n"); 
		query.append("                                  AND BXRM.XTER_RQST_VIA_CD = 'INT')" ).append("\n"); 
		query.append("                       )" ).append("\n"); 
		query.append("                   AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                       NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                           FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                          WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                            AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                            AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                            AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                            AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                        ),1)" ).append("\n"); 
		query.append("                 GROUP BY EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , GROUP_NM" ).append("\n"); 
		query.append("                     , SND_USR_ID" ).append("\n"); 
		query.append("                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                     , NTC.ESVC_GRP_CD)" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("             , REF_TP_CD" ).append("\n"); 
		query.append("             , REF_CODE" ).append("\n"); 
		query.append("             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , GROUP_EDI_ID" ).append("\n"); 
		query.append("             , GROUP_NM" ).append("\n"); 
		query.append("             , SENDER" ).append("\n"); 
		query.append("             , SENDER_NM" ).append("\n"); 
		query.append("             , SEND_DT" ).append("\n"); 
		query.append("             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM (SELECT 'BK' NTC_KND_CD" ).append("\n"); 
		query.append("                     , SUBSTRB(MIN(REF_TMP),2,INSTR(MIN(REF_TMP),'@')-2) AS REF_TP_CD" ).append("\n"); 
		query.append("                     , SUBSTRB(MIN(REF_TMP),INSTR(MIN(REF_TMP),'@')+1) AS REF_CODE" ).append("\n"); 
		query.append("                     , EDI_ID.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , EDI_ID.GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , EDI_ID.GROUP_NM" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,NTC.SND_USR_ID,NULL) AS SENDER" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,(SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID),NULL) AS SENDER_NM" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,TO_CHAR(NTC.SND_RQST_DT, 'YYYY-MM-DD HH24:MI'),NULL) AS SEND_DT" ).append("\n"); 
		query.append("                     , DECODE(GROUP_EDI_ID,ESVC_GRP_CD,NTC.BKG_NTC_SND_RSLT_CD,NULL) AS BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                  FROM EDI_ID, BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("                 WHERE EDI_ID.EDI_RECEIVE_ID = NTC.EDI_ID(+)" ).append("\n"); 
		query.append("                   AND 'Y'  = EDI_ID.BKG_CFM_FLG" ).append("\n"); 
		query.append("                   AND 'E'  = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                   AND 'BK' = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                   AND @[bkg_no]  = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                   AND GROUP_EDI_ID = NTC.ESVC_GRP_CD(+)" ).append("\n"); 
		query.append("                   AND (EDI_ID.EDI_RECEIVE_ID NOT IN ('INTTRA', 'INTTRANG2')" ).append("\n"); 
		query.append("                       OR EXISTS (SELECT 'X' " ).append("\n"); 
		query.append("                                  FROM BKG_XTER_RQST_MST BXRM " ).append("\n"); 
		query.append("                                  WHERE BXRM.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                                  AND BXRM.DOC_TP_CD = 'B'" ).append("\n"); 
		query.append("                                  AND BXRM.BKG_UPLD_STS_CD = 'F'" ).append("\n"); 
		query.append("                                  AND BXRM.XTER_RQST_VIA_CD = 'INT')" ).append("\n"); 
		query.append("                       )" ).append("\n"); 
		query.append("                   AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                       NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                           FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                          WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                            AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                            AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                            AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                            AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                        ),1)" ).append("\n"); 
		query.append("                 GROUP BY EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , GROUP_NM" ).append("\n"); 
		query.append("                     , SND_USR_ID" ).append("\n"); 
		query.append("                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                     , NTC.ESVC_GRP_CD)" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("             , REF_TP_CD" ).append("\n"); 
		query.append("             , REF_CODE" ).append("\n"); 
		query.append("             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , GROUP_EDI_ID" ).append("\n"); 
		query.append("             , GROUP_NM" ).append("\n"); 
		query.append("             , SENDER" ).append("\n"); 
		query.append("             , SENDER_NM" ).append("\n"); 
		query.append("             , SEND_DT" ).append("\n"); 
		query.append("             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM (SELECT 'BO' NTC_KND_CD" ).append("\n"); 
		query.append("                     , '' REF_TP_CD" ).append("\n"); 
		query.append("                     , '' REF_CODE" ).append("\n"); 
		query.append("                     , NTC.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , '' GROUP_NM" ).append("\n"); 
		query.append("                     , NTC.SND_USR_ID SENDER" ).append("\n"); 
		query.append("                     , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("                     , TO_CHAR(NTC.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                     , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                             , NTC.SND_USR_ID, NTC.SND_RQST_DT, NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                             , MST.XTER_SNDR_ID EDI_ID" ).append("\n"); 
		query.append("                          FROM BKG_NTC_HIS NTC, BKG_BOOKING BK, BKG_XTER_RQST_MST MST" ).append("\n"); 
		query.append("                         WHERE 'E'       = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                           AND 'BO'      = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = MST.BKG_NO" ).append("\n"); 
		query.append("                           AND MST.DOC_TP_CD = 'B'" ).append("\n"); 
		query.append("                           AND MST.XTER_SNDR_ID IN ('FSELC'," ).append("\n"); 
		query.append("                                                    'C1T0M','C1T0P','C1T0S','C1T0W','C1S0'," ).append("\n"); 
		query.append("                                                    'T612','T613','T614','T615','T621'," ).append("\n"); 
		query.append("                                                    'T514','T515','T516','T517','T518')" ).append("\n"); 
		query.append("                           AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                               NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                                   FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                                  WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                                    AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                                    AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                                    AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                                    AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                                ),1)) NTC" ).append("\n"); 
		query.append("                 WHERE NTC.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("                 GROUP BY EDI_ID" ).append("\n"); 
		query.append("                     , SND_USR_ID" ).append("\n"); 
		query.append("                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD)" ).append("\n"); 
		query.append("" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("             , REF_TP_CD" ).append("\n"); 
		query.append("             , REF_CODE" ).append("\n"); 
		query.append("             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , GROUP_EDI_ID" ).append("\n"); 
		query.append("             , GROUP_NM" ).append("\n"); 
		query.append("             , SENDER" ).append("\n"); 
		query.append("             , SENDER_NM" ).append("\n"); 
		query.append("             , SEND_DT" ).append("\n"); 
		query.append("             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM (" ).append("\n"); 
		query.append("                SELECT NTC_KND_CD" ).append("\n"); 
		query.append("                     , REF_TP_CD" ).append("\n"); 
		query.append("                     , REF_CODE" ).append("\n"); 
		query.append("                     , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , GROUP_NM" ).append("\n"); 
		query.append("                     , SENDER" ).append("\n"); 
		query.append("                     , SENDER_NM" ).append("\n"); 
		query.append("                     , SEND_DT" ).append("\n"); 
		query.append("                     , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                     , RANK() OVER (PARTITION BY REF_CODE, EDI_RECEIVE_ID ORDER BY NTC_KND_CD, REF_CODE, EDI_RECEIVE_ID) AS RK" ).append("\n"); 
		query.append("                  FROM (" ).append("\n"); 
		query.append("                        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("                             , REF_TP_CD" ).append("\n"); 
		query.append("                             , REF_CODE" ).append("\n"); 
		query.append("                             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                             , GROUP_EDI_ID" ).append("\n"); 
		query.append("                             , GROUP_NM" ).append("\n"); 
		query.append("                             , SENDER" ).append("\n"); 
		query.append("                             , SENDER_NM" ).append("\n"); 
		query.append("                             , SEND_DT" ).append("\n"); 
		query.append("                             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                          FROM (SELECT 'CN' NTC_KND_CD" ).append("\n"); 
		query.append("                                     , '' REF_TP_CD" ).append("\n"); 
		query.append("                                     , NTC.YD_CD REF_CODE" ).append("\n"); 
		query.append("                                     , NTC.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                     , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("                                     , '' GROUP_NM" ).append("\n"); 
		query.append("                                     , NTC.SND_USR_ID SENDER" ).append("\n"); 
		query.append("                                     , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("                                     , TO_CHAR(NTC.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("                                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                                  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                                     , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                                             , NTC.SND_USR_ID" ).append("\n"); 
		query.append("                                             , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                                             , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                                             , EY.RCVR_TRD_PRNR_ID EDI_ID" ).append("\n"); 
		query.append("                                             , EY.PRNR_SUB_LNK_CD AS YD_CD" ).append("\n"); 
		query.append("                                          FROM BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("                                             , BKG_EDI_TRD_PRNR_SUB_LNK EY" ).append("\n"); 
		query.append("                                             , BKG_EDI_SUB_LNK_MSG MSG" ).append("\n"); 
		query.append("                                             , BKG_BOOKING BK" ).append("\n"); 
		query.append("                                         WHERE 'E'       = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                                           AND 'CN'      = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                                           AND BK.MTY_PKUP_YD_CD = EY.PRNR_SUB_LNK_CD(+)" ).append("\n"); 
		query.append("                                           AND 'Y'       = EY.EDI_SND_FLG(+)" ).append("\n"); 
		query.append("                                           AND BK.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                                           AND BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                                           AND EY.TRD_PRNR_SUB_LNK_SEQ = MSG.TRD_PRNR_SUB_LNK_SEQ" ).append("\n"); 
		query.append("                                           AND MSG.EDI_MSG_TP_ID = '301'" ).append("\n"); 
		query.append("                                           AND MSG.EDI_MSG_IND_CD = '5'" ).append("\n"); 
		query.append("                                           AND MSG.MSG_TP_DESC = '1'" ).append("\n"); 
		query.append("                                           AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                                               NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                                                   FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                                                  WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                                                    AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                                                    AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                                                    AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                                                    AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                                                ),1) ) NTC" ).append("\n"); 
		query.append("                                 WHERE NTC.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("                                 GROUP BY YD_CD" ).append("\n"); 
		query.append("                                     , EDI_ID" ).append("\n"); 
		query.append("                                     , SND_USR_ID" ).append("\n"); 
		query.append("                                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                                     , NTC.BKG_NTC_SND_RSLT_CD)" ).append("\n"); 
		query.append("                         UNION" ).append("\n"); 
		query.append("                        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("                             , REF_TP_CD" ).append("\n"); 
		query.append("                             , REF_CODE" ).append("\n"); 
		query.append("                             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                             , GROUP_EDI_ID" ).append("\n"); 
		query.append("                             , GROUP_NM" ).append("\n"); 
		query.append("                             , SENDER" ).append("\n"); 
		query.append("                             , SENDER_NM" ).append("\n"); 
		query.append("                             , SEND_DT" ).append("\n"); 
		query.append("                             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                          FROM (SELECT 'BT' NTC_KND_CD" ).append("\n"); 
		query.append("                                     , '' REF_TP_CD" ).append("\n"); 
		query.append("                                     , NTC.YD_CD REF_CODE" ).append("\n"); 
		query.append("                                     , NTC.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                     , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("                                     , '' GROUP_NM" ).append("\n"); 
		query.append("                                     , NTC.SND_USR_ID SENDER" ).append("\n"); 
		query.append("                                     , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("                                     , TO_CHAR(NTC.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("                                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                                  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                                     , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                                             , NTC.SND_USR_ID, NTC.SND_RQST_DT, NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                                             , EDI_YD.EDI_RCV_ID EDI_ID, EDI_YD.YD_CD" ).append("\n"); 
		query.append("                                          FROM BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("                                             , (SELECT DISTINCT EY.RCVR_TRD_PRNR_ID AS EDI_RCV_ID" ).append("\n"); 
		query.append("                                                     , EY.PRNR_PORT_CD AS PORT_CD" ).append("\n"); 
		query.append("                                                     , EY.PRNR_SUB_LNK_CD AS YD_CD" ).append("\n"); 
		query.append("                                                     , BK.BKG_NO" ).append("\n"); 
		query.append("                                                  FROM BKG_EDI_TRD_PRNR_SUB_LNK EY" ).append("\n"); 
		query.append("                                                     , BKG_EDI_SUB_LNK_MSG MSG" ).append("\n"); 
		query.append("                                                     , BKG_VVD VVD" ).append("\n"); 
		query.append("                                                     , BKG_BOOKING BK" ).append("\n"); 
		query.append("                                                 WHERE BK.BKG_NO   = @[bkg_no]" ).append("\n"); 
		query.append("                                                   AND BK.BKG_NO   = VVD.BKG_NO" ).append("\n"); 
		query.append("                                                   AND EY.TRD_PRNR_SUB_LNK_SEQ = MSG.TRD_PRNR_SUB_LNK_SEQ" ).append("\n"); 
		query.append("                                                   AND EY.PRNR_SUB_LNK_DIV_CD = '1'" ).append("\n"); 
		query.append("                                                   AND MSG.EDI_MSG_TP_ID      = '301'" ).append("\n"); 
		query.append("                                                   AND MSG.MSG_TP_DESC = '1'" ).append("\n"); 
		query.append("                                                   AND (   (EY.PRNR_SUB_LNK_CD = BK.POL_NOD_CD AND MSG.EDI_MSG_IND_CD IN ('1', '2')) " ).append("\n"); 
		query.append("                                                        OR (EY.PRNR_SUB_LNK_CD = VVD.POL_YD_CD AND VVD.VSL_PRE_PST_CD IN ('S','T') AND MSG.EDI_MSG_IND_CD = '6') " ).append("\n"); 
		query.append("                                                        OR (EY.PRNR_SUB_LNK_CD = VVD.POL_YD_CD AND VVD.VSL_PRE_PST_CD = 'U' AND MSG.EDI_MSG_IND_CD = '7')" ).append("\n"); 
		query.append("                                                       )" ).append("\n"); 
		query.append("                                                ) EDI_YD" ).append("\n"); 
		query.append("                                          WHERE 'E'  = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                                            AND 'BT' = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                                            AND EDI_YD.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                                            AND EDI_YD.EDI_RCV_ID = NTC.EDI_ID(+)" ).append("\n"); 
		query.append("                                            AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                                                NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                                                    FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                                                   WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                                                     AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                                                     AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                                                     AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                                                     AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                                                 ),1)) NTC" ).append("\n"); 
		query.append("                                 WHERE NTC.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("                                 GROUP BY YD_CD" ).append("\n"); 
		query.append("                                     , EDI_ID" ).append("\n"); 
		query.append("                                     , SND_USR_ID" ).append("\n"); 
		query.append("                                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                                     , NTC.BKG_NTC_SND_RSLT_CD)               " ).append("\n"); 
		query.append("                      )                      " ).append("\n"); 
		query.append("              )" ).append("\n"); 
		query.append("         WHERE RK = 1" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("             , REF_TP_CD" ).append("\n"); 
		query.append("             , REF_CODE" ).append("\n"); 
		query.append("             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , GROUP_EDI_ID" ).append("\n"); 
		query.append("             , GROUP_NM" ).append("\n"); 
		query.append("             , SENDER" ).append("\n"); 
		query.append("             , SENDER_NM" ).append("\n"); 
		query.append("             , SEND_DT" ).append("\n"); 
		query.append("             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM (SELECT 'FC' NTC_KND_CD" ).append("\n"); 
		query.append("                     , '' REF_TP_CD" ).append("\n"); 
		query.append("                     , NTC.YD_CD REF_CODE" ).append("\n"); 
		query.append("                     , NTC.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , '' GROUP_NM" ).append("\n"); 
		query.append("                     , NTC.SND_USR_ID SENDER" ).append("\n"); 
		query.append("                     , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("                     , TO_CHAR(NTC.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                     , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                             , NTC.SND_USR_ID" ).append("\n"); 
		query.append("                             , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                             , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                             , EY.RCVR_TRD_PRNR_ID EDI_ID" ).append("\n"); 
		query.append("                             , EY.PRNR_SUB_LNK_CD AS YD_CD" ).append("\n"); 
		query.append("                          FROM BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("                             , BKG_EDI_TRD_PRNR_SUB_LNK EY" ).append("\n"); 
		query.append("                             , BKG_EDI_SUB_LNK_MSG MSG" ).append("\n"); 
		query.append("                             , BKG_BOOKING BK" ).append("\n"); 
		query.append("                         WHERE 'E'       = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                           AND 'FC'      = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                           AND BK.FULL_RTN_YD_CD = EY.PRNR_SUB_LNK_CD(+)" ).append("\n"); 
		query.append("                           AND 'Y'       = EY.EDI_SND_FLG(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                           AND EY.TRD_PRNR_SUB_LNK_SEQ = MSG.TRD_PRNR_SUB_LNK_SEQ" ).append("\n"); 
		query.append("                           AND MSG.EDI_MSG_TP_ID = '301'" ).append("\n"); 
		query.append("                           AND MSG.EDI_MSG_IND_CD = '4'" ).append("\n"); 
		query.append("                           AND MSG.MSG_TP_DESC = '1'" ).append("\n"); 
		query.append("                           AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                               NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                                   FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                                  WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                                    AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                                    AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                                    AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                                    AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                                ),1) ) NTC" ).append("\n"); 
		query.append("                 WHERE NTC.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("                 GROUP BY YD_CD" ).append("\n"); 
		query.append("                     , EDI_ID" ).append("\n"); 
		query.append("                     , SND_USR_ID" ).append("\n"); 
		query.append("                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD)" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT 'CT' NTC_KND_CD" ).append("\n"); 
		query.append("             , '' REF_TP_CD" ).append("\n"); 
		query.append("             , '' REF_CODE" ).append("\n"); 
		query.append("             , EDI_ID.EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , EDI_ID.GROUP_EDI_ID" ).append("\n"); 
		query.append("             , EDI_ID.GROUP_NM" ).append("\n"); 
		query.append("             , '' SENDER" ).append("\n"); 
		query.append("             , '' SENDER_NM" ).append("\n"); 
		query.append("             , '' SEND_DT" ).append("\n"); 
		query.append("             , '' BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM EDI_ID" ).append("\n"); 
		query.append("         WHERE 'Y' = EDI_ID.CGO_TRAK_FLG" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("             , REF_TP_CD" ).append("\n"); 
		query.append("             , REF_CODE" ).append("\n"); 
		query.append("             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , GROUP_EDI_ID" ).append("\n"); 
		query.append("             , GROUP_NM" ).append("\n"); 
		query.append("             , SENDER" ).append("\n"); 
		query.append("             , SENDER_NM" ).append("\n"); 
		query.append("             , SEND_DT" ).append("\n"); 
		query.append("             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM (SELECT 'EX' NTC_KND_CD" ).append("\n"); 
		query.append("                     , '' REF_TP_CD" ).append("\n"); 
		query.append("                     , NTC.YD_CD REF_CODE" ).append("\n"); 
		query.append("                     , NTC.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , '' GROUP_NM" ).append("\n"); 
		query.append("                     , NTC.SND_USR_ID SENDER" ).append("\n"); 
		query.append("                     , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("                     , TO_CHAR(NTC.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                     , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                             , NTC.SND_USR_ID, NTC.SND_RQST_DT, NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                             , EDI_YD.RCVR_TRD_PRNR_ID EDI_ID" ).append("\n"); 
		query.append("							 , EDI_YD.PRNR_SUB_LNK_CD AS YD_CD" ).append("\n"); 
		query.append("                          FROM BKG_NTC_HIS NTC, BKG_BOOKING BK, BKG_VVD VVD" ).append("\n"); 
		query.append("                             , COM_SYS_AREA_GRP_ID AREA" ).append("\n"); 
		query.append("                             , BKG_EDI_TRD_PRNR_SUB_LNK EDI_YD" ).append("\n"); 
		query.append("                             , BKG_EDI_SUB_LNK_MSG MSG" ).append("\n"); 
		query.append("                         WHERE 'E'       = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                           AND 'EX'      = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = VVD.BKG_NO" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                           AND EDI_YD.TRD_PRNR_SUB_LNK_SEQ = MSG.TRD_PRNR_SUB_LNK_SEQ" ).append("\n"); 
		query.append("                           AND MSG.MSG_TP_DESC = '1'" ).append("\n"); 
		query.append("                           AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                               NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                                   FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                                  WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                                    AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                                    AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                                    AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                                    AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                                ),1)" ).append("\n"); 
		query.append("                           AND AREA.CNT_CD = SUBSTR(BK.POL_CD, 1, 2)" ).append("\n"); 
		query.append("                           AND VVD.POL_CD IN (CASE " ).append("\n"); 
		query.append("                                                   WHEN AREA.SYS_AREA_GRP_ID = 'EUR' THEN 'FRLEH' ELSE BK.POL_CD END" ).append("\n"); 
		query.append("                                             , VVD.POL_CD)" ).append("\n"); 
		query.append("                           AND VVD.POL_YD_CD LIKE SUBSTR(EDI_YD.PRNR_SUB_LNK_CD, 1, 5)||'%'" ).append("\n"); 
		query.append("                           AND EDI_YD.RCVR_TRD_PRNR_ID IN ('SOGET1','APPLUS')) NTC" ).append("\n"); 
		query.append("                 WHERE NTC.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("                 GROUP BY YD_CD" ).append("\n"); 
		query.append("                     , EDI_ID" ).append("\n"); 
		query.append("                     , SND_USR_ID" ).append("\n"); 
		query.append("                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD)" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT NTC_KND_CD" ).append("\n"); 
		query.append("             , REF_TP_CD" ).append("\n"); 
		query.append("             , REF_CODE" ).append("\n"); 
		query.append("             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , GROUP_EDI_ID" ).append("\n"); 
		query.append("             , GROUP_NM" ).append("\n"); 
		query.append("             , SENDER" ).append("\n"); 
		query.append("             , SENDER_NM" ).append("\n"); 
		query.append("             , SEND_DT" ).append("\n"); 
		query.append("             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM (SELECT 'IM' NTC_KND_CD" ).append("\n"); 
		query.append("                     , '' REF_TP_CD" ).append("\n"); 
		query.append("                     , NTC.YD_CD REF_CODE" ).append("\n"); 
		query.append("                     , NTC.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                     , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("                     , '' GROUP_NM" ).append("\n"); 
		query.append("                     , NTC.SND_USR_ID SENDER" ).append("\n"); 
		query.append("                     , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("                     , TO_CHAR(NTC.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                     , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                             , NTC.SND_USR_ID, NTC.SND_RQST_DT, NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                             , EDI_YD.RCVR_TRD_PRNR_ID EDI_ID" ).append("\n"); 
		query.append("							 , EDI_YD.PRNR_SUB_LNK_CD AS YD_CD" ).append("\n"); 
		query.append("                          FROM BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("							 , BKG_BOOKING BK" ).append("\n"); 
		query.append("                             , BKG_EDI_TRD_PRNR_SUB_LNK EDI_YD" ).append("\n"); 
		query.append("                             , BKG_EDI_SUB_LNK_MSG MSG" ).append("\n"); 
		query.append("                         WHERE 'E'       = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                           AND 'IM'      = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                           AND BK.POD_NOD_CD = EDI_YD.PRNR_SUB_LNK_CD(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                           AND BK.BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("                           AND EDI_YD.TRD_PRNR_SUB_LNK_SEQ = MSG.TRD_PRNR_SUB_LNK_SEQ" ).append("\n"); 
		query.append("                           AND MSG.MSG_TP_DESC = '1'" ).append("\n"); 
		query.append("                           AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                               NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                                   FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                                  WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                                    AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                                    AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                                    AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                                    AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                                ),1) ) NTC" ).append("\n"); 
		query.append("                 WHERE NTC.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("                 GROUP BY YD_CD" ).append("\n"); 
		query.append("                     , EDI_ID" ).append("\n"); 
		query.append("                     , SND_USR_ID" ).append("\n"); 
		query.append("                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                     , NTC.BKG_NTC_SND_RSLT_CD)" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("		SELECT NTC_KND_CD" ).append("\n"); 
		query.append("                             , REF_TP_CD" ).append("\n"); 
		query.append("                             , REF_CODE" ).append("\n"); 
		query.append("                             , EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                             , GROUP_EDI_ID" ).append("\n"); 
		query.append("                             , GROUP_NM" ).append("\n"); 
		query.append("                             , SENDER" ).append("\n"); 
		query.append("                             , SENDER_NM" ).append("\n"); 
		query.append("                             , SEND_DT" ).append("\n"); 
		query.append("                             , BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                          FROM (SELECT 'VM' NTC_KND_CD" ).append("\n"); 
		query.append("                                     , '' REF_TP_CD" ).append("\n"); 
		query.append("                                     , NTC.YD_CD REF_CODE" ).append("\n"); 
		query.append("                                     , NTC.EDI_ID EDI_RECEIVE_ID" ).append("\n"); 
		query.append("                                     , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("                                     , '' GROUP_NM" ).append("\n"); 
		query.append("                                     , NTC.SND_USR_ID SENDER" ).append("\n"); 
		query.append("                                     , (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NTC.SND_USR_ID) SENDER_NM" ).append("\n"); 
		query.append("                                     , TO_CHAR(NTC.SND_RQST_DT,'YYYY-MM-DD HH24:MI') SEND_DT" ).append("\n"); 
		query.append("                                     , NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                                  FROM BKG_BOOKING BK" ).append("\n"); 
		query.append("                                     , (SELECT NTC.BKG_NO" ).append("\n"); 
		query.append("                                             , NTC.SND_USR_ID, NTC.SND_RQST_DT, NTC.BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("                                             , EDI_YD.EDI_RCV_ID EDI_ID, EDI_YD.YD_CD" ).append("\n"); 
		query.append("                                          FROM BKG_NTC_HIS NTC" ).append("\n"); 
		query.append("                                             , (SELECT DISTINCT EY.RCVR_TRD_PRNR_ID AS EDI_RCV_ID" ).append("\n"); 
		query.append("                                                     , EY.PRNR_PORT_CD AS PORT_CD" ).append("\n"); 
		query.append("                                                     , EY.PRNR_SUB_LNK_CD AS YD_CD" ).append("\n"); 
		query.append("                                                     , BK.BKG_NO" ).append("\n"); 
		query.append("                                                  FROM BKG_EDI_TRD_PRNR_SUB_LNK EY" ).append("\n"); 
		query.append("                                                     , BKG_EDI_SUB_LNK_MSG MSG" ).append("\n"); 
		query.append("                                                     , BKG_VVD VVD" ).append("\n"); 
		query.append("                                                     , BKG_BOOKING BK" ).append("\n"); 
		query.append("                                                 WHERE BK.BKG_NO   = @[bkg_no]" ).append("\n"); 
		query.append("                                                   AND BK.BKG_NO   = VVD.BKG_NO" ).append("\n"); 
		query.append("                                                   AND EY.TRD_PRNR_SUB_LNK_SEQ = MSG.TRD_PRNR_SUB_LNK_SEQ" ).append("\n"); 
		query.append("                                                   AND EY.PRNR_SUB_LNK_DIV_CD = '1'" ).append("\n"); 
		query.append("                                                   AND MSG.EDI_MSG_TP_ID      = 'VERMAS'" ).append("\n"); 
		query.append("                                                   AND MSG.MSG_TP_DESC = '1'" ).append("\n"); 
		query.append("                                                   AND (   (EY.PRNR_SUB_LNK_CD = BK.POL_NOD_CD AND MSG.EDI_MSG_IND_CD IN ('13')) " ).append("\n"); 
		query.append("                                                        OR (EY.PRNR_SUB_LNK_CD <> BK.POL_NOD_CD AND EY.PRNR_SUB_LNK_CD = VVD.POL_YD_CD AND MSG.EDI_MSG_IND_CD IN ('14')) " ).append("\n"); 
		query.append("                                                       )" ).append("\n"); 
		query.append("                                                ) EDI_YD" ).append("\n"); 
		query.append("                                          WHERE 'E'  = NTC.NTC_VIA_CD(+)" ).append("\n"); 
		query.append("                                            AND 'VM' = NTC.NTC_KND_CD(+)" ).append("\n"); 
		query.append("                                            AND EDI_YD.BKG_NO = NTC.BKG_NO(+)" ).append("\n"); 
		query.append("                                            AND EDI_YD.EDI_RCV_ID = NTC.EDI_ID(+)" ).append("\n"); 
		query.append("                                            AND NVL(NTC.HIS_SEQ,1) =" ).append("\n"); 
		query.append("                                                NVL2(NTC.HIS_SEQ,(SELECT MAX(HIS_SEQ)" ).append("\n"); 
		query.append("                                                                    FROM BKG_NTC_HIS" ).append("\n"); 
		query.append("                                                                   WHERE BKG_NO     = NTC.BKG_NO" ).append("\n"); 
		query.append("                                                                     AND NTC_VIA_CD = NTC.NTC_VIA_CD" ).append("\n"); 
		query.append("                                                                     AND NTC_KND_CD = NTC.NTC_KND_CD" ).append("\n"); 
		query.append("                                                                     AND EDI_ID     = NTC.EDI_ID" ).append("\n"); 
		query.append("                                                                     AND NVL(ESVC_GRP_CD,1) = NVL(NTC.ESVC_GRP_CD,1)" ).append("\n"); 
		query.append("                                                                 ),1)) NTC" ).append("\n"); 
		query.append("                                 WHERE NTC.BKG_NO = BK.BKG_NO(+)" ).append("\n"); 
		query.append("                                 GROUP BY YD_CD" ).append("\n"); 
		query.append("                                     , EDI_ID" ).append("\n"); 
		query.append("                                     , SND_USR_ID" ).append("\n"); 
		query.append("                                     , NTC.SND_RQST_DT" ).append("\n"); 
		query.append("                                     , NTC.BKG_NTC_SND_RSLT_CD)   " ).append("\n"); 
		query.append("#if ('SGSIN'==${pol_cd})" ).append("\n"); 
		query.append("         UNION" ).append("\n"); 
		query.append("        SELECT 'PS' NTC_KND_CD" ).append("\n"); 
		query.append("             , '' REF_TP_CD" ).append("\n"); 
		query.append("             , '' REF_CODE" ).append("\n"); 
		query.append("             , 'PSACBI' EDI_RECEIVE_ID" ).append("\n"); 
		query.append("             , '' GROUP_EDI_ID" ).append("\n"); 
		query.append("             , '' GROUP_NM" ).append("\n"); 
		query.append("             , NVL(PSA.SND_USR_ID,PSA.UPD_USR_ID) AS SENDER" ).append("\n"); 
		query.append("             ,  (SELECT USR.USR_NM FROM COM_USER USR WHERE USR.USR_ID = NVL(PSA.SND_USR_ID,PSA.UPD_USR_ID)) AS SENDER_NM" ).append("\n"); 
		query.append("             , TO_CHAR(PSA.SND_DT,'YYYY-MM-DD HH24:MI') AS SEND_DT" ).append("\n"); 
		query.append("             , PSA.ACK_RCV_STS_CD AS BKG_NTC_SND_RSLT_CD" ).append("\n"); 
		query.append("          FROM BKG_CSTMS_PSA_BKG PSA" ).append("\n"); 
		query.append("         WHERE BKG_NO = @[bkg_no]" ).append("\n"); 
		query.append("           AND BKG_SEQ =" ).append("\n"); 
		query.append("               (SELECT MAX(BKG_SEQ)" ).append("\n"); 
		query.append("                  FROM BKG_CSTMS_PSA_BKG" ).append("\n"); 
		query.append("                 WHERE BKG_NO = PSA.BKG_NO)" ).append("\n"); 
		query.append("#end                    " ).append("\n"); 
		query.append("       ) MST" ).append("\n"); 
		query.append("       " ).append("\n"); 
		query.append(" WHERE KIND.NTC_KND_CD = MST.NTC_KND_CD(+)" ).append("\n"); 
		query.append(" ORDER BY ORD,DECODE(REF_TP_CD,'SH',1,'CN',2,'NF',3,'FF',4,'AN',5,'EX',6,7),EDI_RECEIVE_ID,GROUP_EDI_ID" ).append("\n"); 

	}
}